export const INDEXING_WAVE_5_TOOL_SLUGS = [
  // Home
  "air-conditioner-monthly-cost-calculator",
  "appliance-usage-cost-calculator",
  "flooring-cost-calculator",
  "garden-watering-cost-calculator",
  "home-annual-maintenance-cost-calculator",
  "home-appliance-annual-consumption-calculator",
  "home-appliance-monthly-energy-calculator",
  "home-cleaning-cost-calculator",
  "home-cleaning-cost-per-visit-calculator",
  "home-electricity-cost-calculator",
  "home-electricity-usage-per-person-calculator",
  "home-energy-savings-rate-calculator",
  "home-furniture-budget-per-room-calculator",
  "home-insulation-savings-calculator",
  "home-maintenance-budget-calculator",
  "home-monthly-utility-total-calculator",
  "home-moving-cost-per-room-calculator",
  "home-renovation-buffer-calculator",
  "home-renovation-cost-per-sqm-calculator",
  "home-storage-volume-calculator",

  // Photography
  "battery-shooting-time-calculator",
  "camera-depreciation-calculator",
  "client-gallery-storage-calculator",
  "crop-factor-focal-length-calculator",
  "editing-time-per-photo-calculator",
  "event-photos-per-hour-calculator",
  "image-aspect-ratio-height-calculator",
  "image-aspect-ratio-width-calculator",
  "photo-delivery-rate-calculator",
  "photo-file-size-per-megapixel-calculator",
  "photo-print-cost-calculator",
  "photo-print-markup-calculator",
  "photo-session-profit-calculator",
  "photo-storage-calculator",
  "photography-backup-storage-multiplier-calculator",
  "photography-booking-conversion-rate-calculator",
  "photography-cull-keep-rate-calculator",
  "photography-editing-cost-per-photo-calculator",
  "photography-gallery-download-rate-calculator",
  "photography-print-profit-per-copy-calculator",

  // Sustainability
  "appliance-annual-energy-cost-calculator",
  "carbon-intensity-per-revenue-calculator",
  "commute-carbon-emissions-calculator",
  "composting-rate-calculator",
  "electricity-carbon-emissions-calculator",
  "electricity-savings-rate-calculator",
  "energy-efficiency-improvement-calculator",
  "fleet-emissions-reduction-rate-calculator",
  "fuel-carbon-emissions-calculator",
  "landfill-cost-savings-calculator",
  "paper-reams-saved-calculator",
  "paper-reduction-rate-calculator",
  "recycling-rate-calculator",
  "reusable-packaging-savings-calculator",
  "solar-energy-savings-calculator",
  "solar-offset-rate-calculator",
  "sustainability-carbon-cost-calculator",
  "sustainability-emissions-per-unit-calculator",
  "sustainability-energy-use-per-sqm-calculator",
  "sustainability-landfill-savings-per-ton-calculator",

  // Retail
  "basket-size-calculator",
  "branch-sales-target-calculator",
  "gross-profit-per-transaction-calculator",
  "retail-average-discount-value-calculator",
  "retail-discount-impact-calculator",
  "retail-footfall-conversion-rate-calculator",
  "retail-full-price-sales-rate-calculator",
  "retail-gross-margin-calculator",
  "retail-gross-margin-return-inventory-calculator",
  "retail-gross-profit-per-visitor-calculator",
  "retail-inventory-cost-per-sqm-calculator",
  "retail-inventory-loss-rate-calculator",
  "retail-inventory-value-calculator",
  "retail-labor-cost-rate-calculator",
  "retail-labor-productivity-calculator",
  "retail-markdown-rate-calculator",
  "retail-marketing-cost-rate-calculator",
  "retail-profit-per-employee-calculator",
  "retail-profit-per-opening-hour-calculator",
  "retail-promotion-sales-lift-calculator",

  // SEO
  "average-position-improvement-calculator",
  "backlink-growth-rate-calculator",
  "cost-per-organic-lead-calculator",
  "crawl-budget-utilization-calculator",
  "indexed-pages-rate-calculator",
  "internal-link-density-calculator",
  "keyword-impression-click-rate-calculator",
  "keyword-ranking-growth-calculator",
  "nonbrand-organic-click-share-calculator",
  "organic-content-decay-rate-calculator",
  "organic-conversion-rate-calculator",
  "organic-ctr-calculator",
  "organic-impression-growth-calculator",
  "organic-revenue-per-session-calculator",
  "orphan-page-rate-calculator",
  "pages-per-crawl-request-calculator",
  "seo-click-share-calculator",
  "seo-clicks-per-page-calculator",
  "seo-content-roi-calculator",
  "seo-impressions-per-page-calculator",
] as const;
