export const INDEXING_WAVE_6_TOOL_SLUGS = [
  // Business
  "break-even-calculator",
  "business-customer-acquisition-cost-calculator",
  "business-markup-percentage-calculator",
  "capacity-utilization-calculator",
  "cash-conversion-cycle-calculator",
  "contribution-margin-per-unit",
  "contribution-margin-ratio-calculator",
  "customer-churn-rate-calculator",
  "customer-concentration-calculator",
  "customer-retention-rate-calculator",

  // Ecommerce
  "average-order-value-calculator",
  "break-even-orders-calculator",
  "cart-abandonment-rate-calculator",
  "checkout-completion-rate-calculator",
  "coupon-redemption-rate-calculator",
  "customer-acquisition-payback-orders-calculator",
  "customer-lifetime-value-basic-calculator",
  "customer-retention-rate-basic-calculator",
  "ecommerce-average-items-per-order-calculator",
  "ecommerce-cart-recovery-value-calculator",

  // Marketing
  "ad-frequency-calculator",
  "aov-calculator",
  "campaign-profit-calculator",
  "campaign-profit-margin-calculator",
  "campaign-revenue-per-lead-calculator",
  "conversion-rate-calculator",
  "cpa-calculator",
  "cpc-calculator",
  "cpm-calculator",
  "ctr-calculator",

  // Productivity
  "automation-time-saved-calculator",
  "backlog-clearance-days-calculator",
  "context-switching-time-cost-calculator",
  "deadline-buffer-calculator",
  "deep-work-percentage-calculator",
  "focus-ratio-calculator",
  "interruptions-per-hour-calculator",
  "meeting-cost-calculator",
  "planned-actual-time-variance-calculator",
  "pomodoro-session-calculator",

  // Web
  "api-error-rate-calculator",
  "api-throughput-per-minute-calculator",
  "average-payload-size-calculator",
  "average-response-time-calculator",
  "bandwidth-per-user-calculator",
  "bounce-rate-reduction-calculator",
  "cache-hit-rate-calculator",
  "cdn-offload-rate-calculator",
  "conversion-uplift-calculator",
  "data-transfer-cost-calculator",

  // Logistics
  "average-delivery-distance-calculator",
  "delivery-cost-per-order-calculator",
  "delivery-route-cost-calculator",
  "dock-to-stock-average-hours-calculator",
  "failed-delivery-rate-calculator",
  "first-attempt-delivery-rate-calculator",
  "freight-cost-per-kg-calculator",
  "fuel-cost-per-km-calculator",
  "inventory-carrying-cost-calculator",
  "logistics-cost-per-delivery-calculator",

  // Manufacturing
  "defect-cost-calculator",
  "first-time-through-rate-calculator",
  "machine-downtime-rate-calculator",
  "machine-utilization-rate-calculator",
  "manufacturing-bottleneck-loss-rate-calculator",
  "manufacturing-capacity-gap-calculator",
  "manufacturing-capacity-utilization-rate-calculator",
  "manufacturing-changeover-time-share-calculator",
  "manufacturing-cycle-time-calculator",
  "manufacturing-direct-material-yield-rate-calculator",

  // Restaurant
  "average-check-calculator",
  "average-table-revenue-calculator",
  "beverage-cost-percentage-calculator",
  "delivery-order-contribution-calculator",
  "delivery-platform-fee-calculator",
  "dish-contribution-margin-calculator",
  "food-cost-percentage-calculator",
  "food-wastage-rate-calculator",
  "ingredient-yield-rate-calculator",
  "kitchen-waste-cost-per-day-calculator",

  // Project management
  "cost-performance-index-calculator",
  "earned-cost-variance-calculator",
  "earned-schedule-variance-calculator",
  "earned-value-calculator",
  "estimate-at-completion-calculator",
  "estimate-to-complete-calculator",
  "milestone-on-time-rate-calculator",
  "planned-value-calculator",
  "project-budget-variance-calculator",
  "project-burn-rate-calculator",

  // Sales
  "average-deal-size-calculator",
  "average-sales-cycle-calculator",
  "contract-renewal-rate-calculator",
  "cost-per-qualified-lead-calculator",
  "cross-sell-revenue-calculator",
  "lead-response-time-calculator",
  "lead-to-opportunity-rate-calculator",
  "opportunity-to-close-rate-calculator",
  "pipeline-coverage-calculator",
  "proposal-acceptance-rate-calculator",
] as const;
