export const INDEXING_WAVE_13_TOOL_SLUGS = [
  // Agriculture
  "harvest-loss-calculator",
  "irrigation-cost-calculator",
  "irrigation-hours-calculator",
  "irrigation-water-calculator",
  "livestock-feed-conversion-ratio-calculator",
  "livestock-weight-gain-calculator",
  "planting-area-from-seed-calculator",
  "planting-density-calculator",
  "seed-requirement-calculator",

  // Automotive
  "tire-cost-per-km-calculator",
  "trip-average-speed-calculator",
  "vehicle-cost-per-km-calculator",
  "vehicle-depreciation-amount-calculator",
  "vehicle-depreciation-calculator",
  "vehicle-finance-total-cost-calculator",
  "vehicle-fuel-cost-calculator",
  "vehicle-maintenance-budget-calculator",
  "vehicle-ownership-monthly-cost-calculator",
  "vehicle-running-cost-calculator",

  // Bakery
  "bakery-production-yield-rate-calculator",
  "bakery-revenue-per-labor-hour-calculator",
  "bakery-waste-rate-calculator",
  "batch-cycle-time-calculator",
  "dough-yield-per-item-calculator",
  "flour-cost-per-loaf-calculator",
  "ingredient-cost-per-item-calculator",
  "ingredient-cost-rate-calculator",
  "oven-throughput-per-hour-calculator",
  "packaging-cost-rate-calculator",

  // Construction
  "material-waste-cost-calculator",
  "paint-material-cost-calculator",
  "plaster-cost-calculator",
  "project-contingency-calculator",
  "rebar-cost-calculator",
  "rebar-weight-estimator",
  "tile-quantity-calculator",
  "wall-area-calculator",

  // Creator
  "newsletter-revenue-per-subscriber-calculator",
  "production-hours-per-post-calculator",
  "social-engagement-rate-calculator",
  "sponsorship-cpm-calculator",
  "sponsorship-rate-calculator",
  "subscriber-conversion-rate-calculator",
  "thumbnail-click-through-rate-calculator",
  "video-production-cost-calculator",
  "video-watch-time-calculator",
  "youtube-cpm-revenue-calculator",

  // Customer service
  "refund-request-rate-calculator",
  "self-service-deflection-rate-calculator",
  "sla-compliance-rate-calculator",
  "support-agent-utilization-calculator",
  "support-cost-per-ticket-calculator",
  "support-tickets-per-hour-calculator",
  "support-training-hours-per-agent-calculator",
  "ticket-backlog-calculator",
  "ticket-reopen-rate-calculator",
  "tickets-per-agent-calculator",

  // Design
  "pixel-height-from-dpi-calculator",
  "pixel-width-from-dpi-calculator",
  "print-cost-per-copy-calculator",
  "print-resolution-dpi-calculator",
  "print-run-cost-calculator",
  "print-size-with-bleed-calculator",
  "render-time-estimator",
  "revision-cost-calculator",
  "revision-hours-calculator",
  "storage-per-design-project-calculator",

  // Employment
  "hourly-wage-calculator",
  "monthly-hours-worked-calculator",
  "net-salary-after-deductions",
  "overtime-pay-calculator",
  "retirement-years-remaining-calculator",
  "salary-deduction-rate-calculator",
  "salary-increase-calculator",
  "salary-per-working-day-calculator",
  "shift-premium-pay",
  "unpaid-leave-deduction",
  "vacation-pay-estimate",
  "weekly-wage-calculator",
  "work-hours-per-month-calculator",

  // Events
  "event-staff-ratio-calculator",
  "event-ticket-conversion-rate-calculator",
  "event-vendor-cost-per-attendee-calculator",
  "event-venue-cost-per-attendee-calculator",
  "session-attendance-rate-calculator",
  "sponsorship-coverage-calculator",
  "ticket-break-even-calculator",
  "ticket-sell-through-rate-calculator",
  "venue-cost-per-attendee-calculator",
  "venue-occupancy-rate-calculator",

  // Freelancer
  "freelancer-tax-reserve-calculator",
  "late-payment-fee-calculator",
  "monthly-client-revenue-average-calculator",
  "net-freelance-income-calculator",
  "proposal-cost-per-win-calculator",
  "proposal-win-rate-calculator",
  "recurring-revenue-share-calculator",
  "retainer-contract-value-calculator",
  "revision-hours-per-project-calculator",
  "unpaid-invoice-rate-calculator",
] as const;
