export const INDEXING_WAVE_8_TOOL_SLUGS = [
  // Franchise
  "average-unit-volume-calculator",
  "franchise-average-ticket-calculator",
  "franchise-break-even-months-calculator",
  "franchise-break-even-sales-calculator",
  "franchise-contribution-after-fees-calculator",
  "franchise-fee-recovery-period-calculator",
  "franchise-gross-margin-calculator",
  "franchise-labor-cost-rate-calculator",
  "franchise-marketing-cost-per-location-calculator",
  "franchise-marketing-fund-calculator",

  // Hospitality
  "average-daily-rate-calculator",
  "booking-channel-commission-rate-calculator",
  "breakfast-cost-per-guest-calculator",
  "direct-booking-rate-calculator",
  "guest-acquisition-cost-calculator",
  "guest-repeat-rate-calculator",
  "hospitality-booking-conversion-rate-calculator",
  "hospitality-booking-lead-time-calculator",
  "hospitality-direct-booking-share-calculator",
  "hospitality-guest-repeat-rate-calculator",

  // HR
  "applicants-per-vacancy-calculator",
  "benefits-cost-per-employee-calculator",
  "cost-per-hire-calculator",
  "employee-absence-rate-calculator",
  "employee-retention-rate-calculator",
  "employee-turnover-rate-calculator",
  "internal-promotion-rate-calculator",
  "interview-to-offer-rate-calculator",
  "manager-span-of-control-calculator",
  "new-hire-90-day-retention-calculator",

  // Maintenance
  "downtime-cost-calculator",
  "emergency-maintenance-rate-calculator",
  "equipment-availability-calculator",
  "maintenance-backlog-weeks-calculator",
  "maintenance-contract-cost-per-asset-calculator",
  "maintenance-cost-per-asset-calculator",
  "maintenance-cost-to-replacement-value-calculator",
  "maintenance-hours-per-asset-calculator",
  "maintenance-inspection-finding-rate-calculator",
  "maintenance-inspection-hours-per-asset-calculator",

  // Procurement
  "average-procurement-order-value-calculator",
  "catalog-adoption-rate-calculator",
  "contract-savings-rate-calculator",
  "cost-avoidance-calculator",
  "early-payment-discount-savings-calculator",
  "maverick-spend-rate-calculator",
  "procurement-contract-savings-calculator",
  "procurement-cost-per-order-calculator",
  "procurement-cost-per-supplier-calculator",
  "procurement-cycle-time-calculator",

  // Quality
  "audit-finding-closure-rate-calculator",
  "calibration-compliance-rate-calculator",
  "corrective-action-closure-days-calculator",
  "corrective-action-closure-rate-calculator",
  "cost-of-poor-quality-calculator",
  "customer-complaint-rate-calculator",
  "customer-defect-return-rate-calculator",
  "defect-cost-per-unit-calculator",
  "defect-rate-calculator",
  "defects-per-million-opportunities-calculator",

  // Rental business
  "average-rental-duration-calculator",
  "maintenance-cost-per-rental-calculator",
  "rental-add-on-revenue-share-calculator",
  "rental-asset-downtime-rate-calculator",
  "rental-asset-yield-calculator",
  "rental-average-rental-duration-calculator",
  "rental-booking-cancellation-rate-calculator",
  "rental-booking-conversion-calculator",
  "rental-cleaning-cost-per-booking-calculator",
  "rental-damage-rate-calculator",

  // SaaS
  "annual-recurring-revenue-calculator",
  "gross-revenue-retention-calculator",
  "monthly-recurring-revenue-calculator",
  "net-revenue-retention-calculator",
  "saas-activation-rate-calculator",
  "saas-annual-prepay-share-calculator",
  "saas-arpu-calculator",
  "saas-cac-calculator",
  "saas-cac-payback-calculator",
  "saas-customer-churn-rate-calculator",

  // Salon
  "salon-appointment-cancellation-rate-calculator",
  "salon-appointment-fill-rate-calculator",
  "salon-average-service-duration-calculator",
  "salon-average-service-time-calculator",
  "salon-average-ticket-calculator",
  "salon-break-even-appointments-calculator",
  "salon-cancellation-rate-calculator",
  "salon-chair-revenue-per-hour-calculator",
  "salon-chair-utilization-calculator",
  "salon-client-frequency-calculator",

  // Startup
  "founder-dilution-calculator",
  "founder-equity-value-calculator",
  "investor-equity-percentage-calculator",
  "post-money-valuation-calculator",
  "pre-money-valuation-from-post-money-calculator",
  "startup-break-even-customers-calculator",
  "startup-break-even-revenue-calculator",
  "startup-burn-multiple-calculator",
  "startup-capital-efficiency-calculator",
  "startup-cash-burn-per-employee-calculator",
] as const;
