export const INDEXING_WAVE_9_TOOL_SLUGS = [
  // Advertising
  "ad-budget-pacing-calculator",
  "ad-clicks-from-budget-calculator",
  "ad-impressions-from-budget-calculator",
  "ad-lead-to-sale-rate-calculator",
  "ad-request-rpm-calculator",
  "ad-rpm-calculator",
  "adsense-revenue-estimator",
  "advertising-cost-per-reached-user-calculator",
  "advertising-profit-calculator",
  "break-even-cpa-calculator",

  // Energy
  "annual-appliance-energy-cost-calculator",
  "annual-energy-savings-calculator",
  "appliance-running-cost-calculator",
  "battery-backup-hours-calculator",
  "battery-usable-capacity-calculator",
  "daily-energy-consumption-calculator",
  "demand-reduction-rate-calculator",
  "effective-electricity-cost-per-kwh-calculator",
  "electricity-demand-cost-calculator",
  "energy-cost-per-unit-calculator",

  // Home
  "home-rent-per-sqm-calculator",
  "home-rent-to-income-ratio-calculator",
  "home-water-usage-per-person-calculator",
  "lighting-monthly-cost-calculator",
  "moving-cost-calculator",
  "room-paint-cost-calculator",
  "room-volume-calculator",
  "solar-payback-period-calculator",
  "water-bill-estimator",
  "water-heater-monthly-cost-calculator",

  // Photography
  "photography-project-price-calculator",
  "photography-revenue-per-delivered-photo-calculator",
  "photography-session-revenue-per-hour-calculator",
  "photography-storage-cost-per-gb-calculator",
  "photography-travel-cost-per-session-calculator",
  "print-dpi-calculator",
  "shooting-day-cost-calculator",
  "timelapse-frame-count-calculator",
  "timelapse-output-duration-calculator",
  "video-storage-calculator",

  // Retail
  "retail-rent-cost-rate-calculator",
  "retail-reorder-quantity-gap-calculator",
  "retail-returned-units-rate-calculator",
  "retail-revenue-growth-rate-calculator",
  "retail-revenue-per-employee-calculator",
  "retail-revenue-per-opening-hour-calculator",
  "retail-revenue-per-transaction-calculator",
  "retail-sales-per-square-meter-calculator",
  "retail-sell-through-rate-calculator",
  "retail-shrinkage-rate-calculator",

  // SEO
  "seo-indexation-rate-calculator",
  "seo-lead-to-customer-rate-calculator",
  "seo-nonbrand-click-share-calculator",
  "seo-organic-lead-rate-calculator",
  "seo-organic-revenue-per-visit-calculator",
  "seo-pages-per-keyword-calculator",
  "seo-ranking-improvement-rate-calculator",
  "seo-traffic-growth-rate-calculator",
  "serp-click-share-calculator",
  "sitemap-indexation-rate-calculator",

  // Sustainability
  "sustainability-packaging-weight-reduction-rate-calculator",
  "sustainability-recycled-material-share-calculator",
  "sustainability-renewable-energy-cost-share-calculator",
  "sustainability-reuse-rate-calculator",
  "sustainability-waste-per-employee-calculator",
  "sustainability-water-saved-per-employee-calculator",
  "tree-offset-calculator",
  "waste-diversion-rate-calculator",
  "water-intensity-calculator",
  "water-savings-calculator",

  // Telecom
  "average-recharge-value-calculator",
  "bandwidth-utilization-rate-calculator",
  "call-setup-success-rate-calculator",
  "complaints-per-thousand-subscribers-calculator",
  "data-session-success-rate-calculator",
  "dropped-call-rate-calculator",
  "network-availability-hours-calculator",
  "prepaid-recharge-frequency-calculator",
  "subscriber-growth-rate-calculator",
  "telecom-arpu-calculator",

  // Travel
  "attraction-budget-per-day-calculator",
  "baggage-overweight-fee-calculator",
  "currency-exchange-fee-calculator",
  "flight-cost-per-traveler-calculator",
  "group-trip-share-calculator",
  "hotel-stay-total-calculator",
  "hotel-tax-total-calculator",
  "itinerary-hours-per-day-calculator",
  "local-transport-cost-per-day-calculator",
  "luggage-cost-per-traveler-calculator",

  // Web
  "latency-improvement-calculator",
  "monthly-bandwidth-calculator",
  "page-weight-calculator",
  "pageviews-per-session-calculator",
  "requests-per-second-calculator",
  "server-cost-per-request-calculator",
  "server-cost-per-user-calculator",
  "successful-request-rate-calculator",
  "uptime-percentage-calculator",
  "web-availability-minutes-calculator",
] as const;
