export const INDEXING_WAVE_4_TOOL_SLUGS = [
  // Franchise
  "franchise-average-revenue-per-employee-calculator",
  "franchise-fee-to-revenue-ratio-calculator",
  "franchise-location-profit-per-sqm-calculator",
  "franchise-marketing-fund-rate-calculator",
  "franchise-multi-unit-revenue-share-calculator",
  "franchise-new-unit-opening-rate-calculator",
  "franchise-owner-cash-return-rate-calculator",
  "franchise-royalty-revenue-share-calculator",
  "franchise-support-cost-rate-calculator",
  "franchise-training-cost-rate-calculator",

  // Hospitality
  "hospitality-amenity-revenue-per-guest-calculator",
  "hospitality-average-booking-value-calculator",
  "hospitality-booking-value-per-night-calculator",
  "hospitality-breakfast-attachment-rate-calculator",
  "hospitality-guest-service-cost-per-stay-calculator",
  "hospitality-late-checkout-revenue-calculator",
  "hospitality-laundry-revenue-per-guest-calculator",
  "hospitality-parking-attachment-rate-calculator",
  "hospitality-revenue-per-staff-hour-calculator",
  "hospitality-room-upgrade-rate-calculator",

  // HR
  "hr-absenteeism-days-per-employee-calculator",
  "hr-benefits-cost-per-employee-calculator",
  "hr-employee-referral-hire-rate-calculator",
  "hr-internal-fill-rate-calculator",
  "hr-internal-promotion-rate-calculator",
  "hr-probation-pass-rate-calculator",
  "hr-recruiting-funnel-conversion-calculator",
  "hr-span-of-control-calculator",
  "hr-training-completion-rate-calculator",
  "hr-voluntary-turnover-share-calculator",

  // Project management
  "project-average-task-duration-calculator",
  "project-budget-burn-rate-calculator",
  "project-cost-per-deliverable-calculator",
  "project-cost-variance-calculator",
  "project-defect-rework-rate-calculator",
  "project-estimate-accuracy-calculator",
  "project-milestone-hit-rate-calculator",
  "project-resource-utilization-calculator",
  "project-schedule-variance-calculator",
  "project-task-completion-rate-calculator",

  // Quality
  "quality-audit-findings-per-audit-calculator",
  "quality-complaint-resolution-time-calculator",
  "quality-corrective-action-cost-per-case-calculator",
  "quality-customer-return-cost-per-unit-calculator",
  "quality-defects-per-batch-calculator",
  "quality-first-article-pass-rate-calculator",
  "quality-inspection-hours-per-batch-calculator",
  "quality-sample-failure-rate-calculator",
  "quality-tolerance-utilization-rate-calculator",
  "quality-warranty-cost-rate-calculator",

  // Rental business
  "rental-asset-revenue-yield-rate-calculator",
  "rental-booking-lead-time-calculator",
  "rental-cancellation-loss-calculator",
  "rental-cleaning-cost-share-calculator",
  "rental-delivery-cost-share-calculator",
  "rental-extension-revenue-share-calculator",
  "rental-idle-cost-per-day-calculator",
  "rental-repair-cost-share-calculator",
  "rental-revenue-per-utilized-day-calculator",
  "rental-utilized-days-per-asset-calculator",

  // SaaS
  "saas-api-usage-per-customer-calculator",
  "saas-billing-recovery-rate-calculator",
  "saas-contraction-mrr-rate-calculator",
  "saas-downgrade-rate-calculator",
  "saas-expansion-revenue-per-customer-calculator",
  "saas-onboarding-cost-per-customer-calculator",
  "saas-reactivation-rate-calculator",
  "saas-storage-cost-per-customer-calculator",
  "saas-support-hours-per-customer-calculator",
  "saas-trial-to-paid-days-calculator",

  // Sales
  "sales-average-deal-size-calculator",
  "sales-cycle-days-calculator",
  "sales-followup-conversion-calculator",
  "sales-forecast-accuracy-calculator",
  "sales-lead-response-rate-calculator",
  "sales-pipeline-coverage-calculator",
  "sales-quota-attainment-calculator",
  "sales-revenue-per-rep-calculator",
  "sales-velocity-calculator",
  "sales-win-rate-calculator",

  // Salon
  "salon-appointment-lead-time-calculator",
  "salon-average-rebooking-days-calculator",
  "salon-chair-downtime-rate-calculator",
  "salon-consumables-cost-share-calculator",
  "salon-membership-churn-rate-calculator",
  "salon-overtime-cost-share-calculator",
  "salon-product-units-per-client-calculator",
  "salon-retail-units-per-appointment-calculator",
  "salon-revenue-per-square-meter-calculator",
  "salon-service-mix-share-calculator",

  // Startup
  "startup-cash-buffer-months-calculator",
  "startup-cash-efficiency-ratio-calculator",
  "startup-customer-acquisition-spend-share-calculator",
  "startup-funding-per-employee-calculator",
  "startup-monthly-net-cash-flow-calculator",
  "startup-operating-expense-rate-calculator",
  "startup-product-development-spend-share-calculator",
  "startup-revenue-per-founder-calculator",
  "startup-revenue-run-rate-calculator",
  "startup-sales-efficiency-ratio-calculator",
] as const;
