export const INDEXING_WAVE_12_TOOL_SLUGS = [
  // Business
  "expense-ratio-calculator",
  "fixed-cost-per-unit-calculator",
  "gross-margin-calculator",
  "inventory-days-calculator",
  "net-profit-margin-calculator",
  "operating-expense-per-customer-calculator",
  "operating-leverage-calculator",
  "operating-margin-calculator",
  "payable-days-calculator",
  "profit-per-employee-calculator",

  // Cybersecurity
  "alert-to-incident-conversion-rate-calculator",
  "backup-recovery-success-rate-calculator",
  "backup-success-rate-calculator",
  "critical-vulnerability-rate-calculator",
  "endpoint-coverage-rate-calculator",
  "incident-cost-per-event-calculator",
  "log-ingestion-per-day-calculator",
  "mean-time-to-detect-calculator",
  "mean-time-to-respond-calculator",
  "mfa-coverage-rate-calculator",
  "password-reset-rate-calculator",
  "patch-compliance-rate-calculator",
  "phishing-click-rate-calculator",
  "phishing-reporting-rate-calculator",
  "security-alert-to-incident-rate-calculator",
  "security-awareness-completion-rate-calculator",
  "security-backup-failure-rate-calculator",
  "security-cost-per-endpoint-calculator",
  "security-false-positive-rate-calculator",
  "security-incident-cost-per-user-calculator",

  // Date and time
  "minutes-to-hours-calculator",
  "minutes-to-seconds-calculator",
  "months-to-weeks-estimate",
  "months-to-years-estimator",
  "net-shift-hours-calculator",
  "overtime-hours-calculator",
  "production-time-per-unit",
  "shifts-to-hours-calculator",
  "task-throughput-per-hour",
  "time-budget-per-day-calculator",

  // Ecommerce
  "ecommerce-conversion-rate-calculator",
  "ecommerce-customer-churn-rate-calculator",
  "ecommerce-customer-order-frequency-calculator",
  "ecommerce-delivery-success-rate-calculator",
  "ecommerce-gross-margin-per-order-calculator",
  "ecommerce-net-order-value-calculator",
  "ecommerce-payment-fee-rate-calculator",
  "ecommerce-refund-adjusted-margin-calculator",
  "ecommerce-refund-rate-calculator",
  "ecommerce-return-loss-calculator",

  // Education
  "grade-improvement-rate",
  "grade-point-contribution-calculator",
  "points-needed-for-target",
  "practice-question-accuracy-calculator",
  "quiz-average-calculator",
  "reading-pages-per-day-calculator",
  "semester-credit-load-calculator",
  "study-hours-per-subject",
  "study-plan-hours-calculator",
  "study-session-efficiency-calculator",

  // Marketing
  "customer-acquisition-cost-calculator",
  "customer-lifetime-value-simple",
  "email-bounce-rate-calculator",
  "email-click-to-open-rate",
  "email-delivery-rate-calculator",
  "email-open-rate-calculator",
  "landing-page-bounce-rate",
  "landing-page-conversion-value-calculator",
  "lead-cost-calculator",
  "lead-to-sale-rate",

  // Online income
  "ad-revenue-share-calculator",
  "affiliate-commission-per-sale-calculator",
  "affiliate-conversion-rate-calculator",
  "affiliate-epc-calculator",
  "affiliate-revenue-per-click-calculator",
  "course-refund-rate-calculator",
  "course-revenue-per-enrollment-calculator",
  "creator-income-per-content-piece-calculator",
  "creator-rpm-calculator",
  "digital-download-conversion-rate-calculator",
  "digital-product-net-earnings-calculator",
  "digital-product-profit-margin-calculator",
  "income-goal-pageviews-calculator",
  "membership-annual-revenue-calculator",
  "membership-monthly-revenue-calculator",
  "newsletter-paid-conversion-rate-calculator",
  "online-income-effective-hourly-rate-calculator",
  "online-income-monthly-growth-rate-calculator",
  "online-income-revenue-per-transaction-calculator",
  "platform-fee-rate-calculator",

  // Productivity
  "productive-meeting-hours-ratio-calculator",
  "productivity-output-per-hour-calculator",
  "project-progress-calculator",
  "recurring-task-annual-hours-calculator",
  "schedule-adherence-rate-calculator",
  "task-completion-rate-calculator",
  "tasks-per-workday-calculator",
  "team-utilization-rate-calculator",
  "weekly-focus-hours-calculator",
  "weekly-work-capacity-calculator",
] as const;
