export const INDEXING_WAVE_7_TOOL_SLUGS = [
  // Agriculture
  "animal-feed-requirement-calculator",
  "crop-loss-rate-calculator",
  "crop-yield-per-hectare-calculator",
  "farm-profit-calculator",
  "farm-revenue-calculator",
  "feed-cost-per-animal-day-calculator",
  "fertilizer-cost-calculator",
  "fertilizer-requirement-calculator",
  "greenhouse-plant-capacity-calculator",
  "greenhouse-revenue-per-sqm-calculator",

  // Automotive
  "annual-fuel-cost-calculator",
  "car-payment-income-ratio-calculator",
  "fleet-fuel-budget-calculator",
  "fuel-consumption-liters-per-100km",
  "fuel-efficiency-km-per-liter-calculator",
  "insurance-monthly-equivalent-calculator",
  "lease-mileage-overage-calculator",
  "maintenance-cost-per-km-calculator",
  "ride-profit-calculator",
  "service-interval-remaining-calculator",

  // Bakery
  "bakery-batch-profit-calculator",
  "bakery-break-even-items-calculator",
  "bakery-cost-per-item-calculator",
  "bakery-daily-production-capacity-calculator",
  "bakery-daily-profit-calculator",
  "bakery-gross-margin-calculator",
  "bakery-ingredient-cost-per-batch-calculator",
  "bakery-labor-cost-per-batch-calculator",
  "bakery-oven-utilization-calculator",
  "bakery-packaging-cost-calculator",

  // Construction
  "brick-count-calculator",
  "cement-bags-calculator",
  "concrete-cost-calculator",
  "construction-completion-rate-calculator",
  "construction-labor-cost-calculator",
  "construction-productivity-calculator",
  "construction-tile-waste-cost-calculator",
  "excavation-volume-calculator",
  "floor-area-calculator",
  "flooring-material-cost-calculator",

  // Creator
  "affiliate-revenue-calculator",
  "brand-deal-hourly-rate-calculator",
  "content-cost-per-post-calculator",
  "content-publishing-frequency-calculator",
  "creator-profit-margin-calculator",
  "creator-revenue-per-thousand-views-calculator",
  "engagements-per-post-calculator",
  "follower-growth-rate-calculator",
  "newsletter-click-rate-calculator",
  "newsletter-open-rate-calculator",

  // Customer service
  "average-handle-time-calculator",
  "average-resolution-time-calculator",
  "complaint-rate-per-thousand-customers",
  "csat-score-calculator",
  "customer-effort-score-average-calculator",
  "escalation-rate-calculator",
  "first-contact-resolution-rate-calculator",
  "first-response-time-calculator",
  "nps-score-calculator",
  "queue-clearance-hours-calculator",

  // Design
  "aspect-ratio-height-calculator",
  "aspect-ratio-width-calculator",
  "asset-storage-calculator",
  "canvas-area-calculator",
  "design-cost-per-asset-calculator",
  "design-project-quote-calculator",
  "design-utilization-rate-calculator",
  "designer-revenue-per-hour-calculator",
  "font-license-cost-calculator",
  "image-megapixels-calculator",

  // Employment
  "annual-bonus-percentage-calculator",
  "annual-compensation-calculator",
  "annual-overtime-income-calculator",
  "benefits-percentage-calculator",
  "bonus-amount-calculator",
  "commission-plus-salary",
  "commission-share-of-income-calculator",
  "daily-wage-calculator",
  "effective-pay-per-hour-calculator",
  "employer-payroll-cost",

  // Events
  "booth-revenue-calculator",
  "event-catering-cost-calculator",
  "event-catering-waste-cost-calculator",
  "event-checkin-rate-calculator",
  "event-cost-per-attendee-calculator",
  "event-no-show-rate-calculator",
  "event-profit-calculator",
  "event-registration-conversion-rate-calculator",
  "event-roi-calculator",
  "event-sponsorship-revenue-share-calculator",

  // Freelancer
  "billable-utilization-rate-calculator",
  "client-concentration-rate-calculator",
  "effective-hourly-rate-calculator",
  "freelance-platform-fee-calculator",
  "freelance-project-price-calculator",
  "freelance-project-profit-margin-calculator",
  "freelancer-availability-hours-calculator",
  "freelancer-hourly-rate-calculator",
  "freelancer-project-capacity-calculator",
  "freelancer-revenue-per-client-calculator",
] as const;
