export const INDEXING_WAVE_1_TOOL_SLUGS = [
  // Business
  "business-monthly-profit-run-rate-calculator",
  "business-cash-conversion-rate-calculator",
  "business-variable-cost-share-calculator",
  "business-fixed-cost-share-calculator",
  "business-profit-per-employee-calculator",
  "business-revenue-per-employee-calculator",
  "business-overhead-rate-calculator",
  "business-operating-margin-calculator",
  "business-expense-growth-rate-calculator",
  "business-revenue-growth-rate-calculator",

  // Converters
  "hour-to-minute-converter",
  "minute-to-hour-converter",
  "square-meter-to-square-kilometer-converter",
  "square-kilometer-to-square-meter-converter",
  "milliliter-to-liter-converter",
  "liter-to-milliliter-converter",
  "kilogram-to-gram-converter",
  "gram-to-kilogram-converter",
  "kilometer-to-meter-converter",
  "meter-to-centimeter-converter",

  // Date and time
  "days-per-cycle-calculator",
  "work-hours-per-month-estimate-calculator",
  "weekly-workload-hours-calculator",
  "years-to-months-total-calculator",
  "months-to-weeks-estimate-calculator",
  "weeks-to-hours-calculator",
  "hours-to-days-decimal-converter",
  "days-to-hours-total-calculator",
  "hours-to-minutes-calculator",
  "minutes-to-hours-decimal-converter",

  // Ecommerce
  "ecommerce-net-profit-per-order-calculator",
  "ecommerce-shipping-cost-share-calculator",
  "ecommerce-marketing-cost-share-calculator",
  "ecommerce-units-per-customer-calculator",
  "ecommerce-orders-per-day-calculator",
  "ecommerce-revenue-per-customer-calculator",
  "ecommerce-refund-loss-per-order-calculator",
  "ecommerce-discount-cost-per-order-calculator",
  "ecommerce-fee-cost-per-order-calculator",
  "ecommerce-net-revenue-after-fees-calculator",

  // Education
  "study-goal-completion-rate-calculator",
  "study-break-ratio-calculator",
  "reading-time-per-page-calculator",
  "learning-cost-per-hour-calculator",
  "course-cost-per-credit-calculator",
  "remaining-course-progress-calculator",
  "exam-weighted-contribution-calculator",
  "questions-per-study-hour-calculator",
  "study-days-needed-calculator",
  "study-hours-per-credit-calculator",

  // General
  "rate-per-ten-thousand-calculator",
  "portion-of-total-calculator",
  "weighted-average-three-values-calculator",
  "target-gap-percentage-calculator",
  "remaining-amount-calculator",
  "average-per-item-calculator",
  "combined-total-calculator",
  "bulk-package-unit-cost-calculator",
  "percentage-to-ratio-calculator",
  "ratio-to-percentage-calculator",

  // Marketing
  "marketing-attributed-revenue-share-calculator",
  "marketing-budget-utilization-rate-calculator",
  "marketing-revenue-per-channel-calculator",
  "marketing-content-cost-per-lead-calculator",
  "marketing-campaign-efficiency-calculator",
  "marketing-opportunity-rate-calculator",
  "marketing-sql-rate-calculator",
  "marketing-mql-rate-calculator",
  "marketing-lead-share-calculator",
  "marketing-revenue-per-campaign-calculator",

  // Math
  "cube-volume-from-side-calculator",
  "square-area-from-side-calculator",
  "inverse-rate-calculator",
  "linear-rate-calculator",
  "proportional-allocation-calculator",
  "ratio-simplified-value-calculator",
  "relative-change-calculator",
  "percentage-point-difference-calculator",
  "average-of-three-numbers-calculator",
  "sum-of-three-numbers-calculator",

  // Productivity
  "productivity-weekly-capacity-calculator",
  "productivity-utilization-gap-calculator",
  "productivity-output-rate-per-hour-calculator",
  "productivity-time-saved-calculator",
  "productivity-planned-vs-completed-calculator",
  "productivity-meeting-load-rate-calculator",
  "productivity-interruption-rate-calculator",
  "productivity-task-throughput-calculator",
  "productivity-deep-work-hours-calculator",
  "productivity-focus-rate-calculator",

  // Web
  "web-response-time-reduction-rate-calculator",
  "web-monthly-transfer-per-user-calculator",
  "web-conversions-per-thousand-visitors-calculator",
  "web-error-free-session-rate-calculator",
  "cdn-bandwidth-savings-calculator",
  "page-weight-per-asset-calculator",
  "server-memory-per-user-calculator",
  "api-successful-requests-per-minute-calculator",
  "api-bandwidth-per-request-calculator",
  "api-cost-per-thousand-requests-calculator",
] as const;
