export const INDEXING_WAVE_2_TOOL_SLUGS = [
  // Advertising
  "advertising-cost-per-video-completion-calculator",
  "advertising-daily-remaining-budget-calculator",
  "advertising-remaining-budget-calculator",
  "advertising-budget-utilization-rate-calculator",
  "advertising-cost-per-engagement-calculator",
  "advertising-spend-per-impression-calculator",
  "advertising-profit-per-click-calculator",
  "advertising-revenue-per-click-calculator",
  "advertising-lead-cost-per-customer-calculator",
  "advertising-click-to-lead-rate-calculator",

  // Energy
  "energy-load-growth-rate-calculator",
  "energy-carbon-cost-calculator",
  "energy-renewable-share-calculator",
  "energy-peak-to-average-ratio-calculator",
  "energy-efficiency-savings-rate-calculator",
  "energy-generator-cost-per-kwh-calculator",
  "energy-battery-roundtrip-output-calculator",
  "energy-solar-self-consumption-rate-calculator",
  "energy-cost-per-kwh-effective-calculator",
  "energy-demand-savings-calculator",

  // Logistics
  "logistics-storage-cost-per-pallet-calculator",
  "logistics-return-cost-share-calculator",
  "logistics-delivery-hours-per-stop-calculator",
  "logistics-fuel-liters-per-100km-calculator",
  "logistics-picking-cost-per-item-calculator",
  "logistics-warehouse-cost-per-order-calculator",
  "logistics-driver-cost-per-km-calculator",
  "logistics-profit-per-shipment-calculator",
  "logistics-revenue-per-shipment-calculator",
  "logistics-cost-per-ton-km-calculator",

  // Maintenance
  "maintenance-service-contract-savings-calculator",
  "maintenance-spare-parts-cost-per-asset-calculator",
  "maintenance-labor-hours-per-work-order-calculator",
  "maintenance-repair-cost-per-failure-calculator",
  "maintenance-scheduled-hours-per-asset-calculator",
  "maintenance-work-order-age-average-calculator",
  "maintenance-parts-usage-per-work-order-calculator",
  "maintenance-unplanned-downtime-cost-calculator",
  "maintenance-preventive-hours-share-calculator",
  "maintenance-backlog-hours-per-technician-calculator",

  // Manufacturing
  "manufacturing-material-usage-per-good-unit-calculator",
  "manufacturing-capacity-per-shift-calculator",
  "manufacturing-operator-to-machine-ratio-calculator",
  "manufacturing-changeover-cost-calculator",
  "manufacturing-downtime-cost-per-hour-calculator",
  "manufacturing-production-hours-per-batch-calculator",
  "manufacturing-packaging-cost-per-unit-calculator",
  "manufacturing-overtime-cost-share-calculator",
  "manufacturing-scrap-cost-per-unit-calculator",
  "manufacturing-output-per-machine-calculator",

  // Procurement
  "procurement-negotiated-discount-value-calculator",
  "procurement-supplier-dependency-ratio-calculator",
  "procurement-urgent-spend-share-calculator",
  "procurement-invoice-match-rate-calculator",
  "procurement-sourcing-savings-per-event-calculator",
  "procurement-supplier-risk-share-calculator",
  "procurement-purchase-order-value-variance-calculator",
  "procurement-contract-utilization-rate-calculator",
  "procurement-average-bids-per-rfq-calculator",
  "procurement-supplier-bid-response-rate-calculator",

  // Real estate
  "real-estate-rent-growth-calculator",
  "real-estate-property-management-fee-calculator",
  "real-estate-maintenance-reserve-calculator",
  "real-estate-rental-yield-net-calculator",
  "real-estate-debt-service-coverage-calculator",
  "real-estate-cash-on-cash-return-calculator",
  "real-estate-vacancy-loss-calculator",
  "real-estate-rent-per-square-meter-calculator",
  "real-estate-expense-ratio-calculator",
  "real-estate-net-operating-income-calculator",

  // Restaurant
  "restaurant-tip-rate-calculator",
  "restaurant-reservation-conversion-rate-calculator",
  "restaurant-kitchen-output-per-hour-calculator",
  "restaurant-average-items-per-order-calculator",
  "restaurant-discount-rate-calculator",
  "restaurant-delivery-fee-cost-share-calculator",
  "restaurant-beverage-revenue-share-calculator",
  "restaurant-food-cost-per-cover-calculator",
  "restaurant-profit-per-cover-calculator",
  "restaurant-revenue-per-cover-calculator",

  // Telecom
  "telecom-subscriber-net-additions-calculator",
  "telecom-voice-revenue-share-calculator",
  "telecom-data-revenue-share-calculator",
  "telecom-tower-revenue-per-site-calculator",
  "telecom-recharge-revenue-per-user-calculator",
  "telecom-support-tickets-per-thousand-subscribers-calculator",
  "telecom-network-cost-per-subscriber-calculator",
  "telecom-call-minutes-per-subscriber-calculator",
  "telecom-data-usage-per-subscriber-calculator",
  "telecom-revenue-per-subscriber-calculator",

  // Travel
  "travel-roadtrip-fuel-cost-per-km-calculator",
  "travel-exchange-loss-amount-calculator",
  "travel-budget-remaining-calculator",
  "travel-savings-progress-rate-calculator",
  "travel-cost-per-traveler-day-calculator",
  "travel-attraction-cost-share-calculator",
  "travel-transport-cost-share-calculator",
  "travel-meal-cost-share-calculator",
  "travel-flight-cost-share-calculator",
  "travel-accommodation-cost-per-night-calculator",
] as const;
