export const INDEXING_WAVE_3_TOOL_SLUGS = [
  // Agriculture
  "crop-input-cost-share-calculator",
  "crop-revenue-per-hectare-calculator",
  "farm-labor-cost-per-hectare-calculator",
  "farm-operating-margin-calculator",
  "fertilizer-cost-per-hectare-calculator",
  "greenhouse-output-per-sqm-calculator",
  "harvest-value-per-ton-calculator",
  "irrigation-water-cost-per-hectare-calculator",
  "livestock-feed-cost-per-kg-gain-calculator",
  "seed-cost-per-hectare-calculator",

  // Automotive
  "car-loan-interest-cost-calculator",
  "commute-monthly-fuel-cost-calculator",
  "fleet-fuel-cost-calculator",
  "fleet-maintenance-cost-per-vehicle-calculator",
  "fuel-cost-per-100km-calculator",
  "ride-revenue-per-km-calculator",
  "service-cost-per-km-calculator",
  "vehicle-insurance-cost-per-month-calculator",
  "vehicle-registration-cost-per-month-calculator",
  "vehicle-resale-value-loss-calculator",

  // Bakery
  "bakery-average-basket-value-calculator",
  "bakery-revenue-per-item-calculator",
  "bakery-break-even-revenue-calculator",
  "bakery-contribution-margin-calculator",
  "bakery-daily-revenue-per-worker-calculator",
  "bakery-discounted-price-calculator",
  "bakery-output-per-labor-hour-calculator",
  "bakery-production-hours-calculator",
  "bakery-return-rate-calculator",
  "bakery-unsold-rate-calculator",

  // Construction
  "construction-change-order-cost-rate-calculator",
  "construction-cost-per-sqm-calculator",
  "construction-concrete-waste-rate-calculator",
  "construction-daily-site-cost-calculator",
  "construction-equipment-utilization-calculator",
  "construction-labor-productivity-calculator",
  "construction-material-cost-rate-calculator",
  "construction-project-overrun-rate-calculator",
  "construction-rebar-cost-calculator",
  "construction-scaffolding-cost-calculator",

  // Creator
  "creator-content-cost-per-post-calculator",
  "creator-content-roi-calculator",
  "creator-conversion-per-thousand-views-calculator",
  "creator-course-revenue-per-student-calculator",
  "creator-email-revenue-per-subscriber-calculator",
  "creator-membership-revenue-calculator",
  "creator-profit-per-post-calculator",
  "creator-revenue-per-post-calculator",
  "creator-revenue-per-thousand-followers-calculator",
  "creator-sponsorship-share-calculator",

  // Customer service
  "support-abandonment-rate-calculator",
  "support-backlog-per-agent-calculator",
  "support-escalation-cost-calculator",
  "support-first-contact-resolution-rate-calculator",
  "support-reopen-rate-calculator",
  "support-resolution-cost-calculator",
  "support-resolution-sla-rate-calculator",
  "support-response-sla-rate-calculator",
  "support-tickets-per-agent-calculator",
  "support-tickets-per-customer-calculator",

  // Design
  "design-asset-cost-per-file-calculator",
  "design-billable-rate-calculator",
  "design-cost-per-screen-calculator",
  "design-hours-per-screen-calculator",
  "design-print-cost-per-copy-calculator",
  "design-production-hours-calculator",
  "design-profit-margin-calculator",
  "design-project-profit-calculator",
  "design-revenue-per-project-calculator",
  "design-revision-rate-calculator",

  // Employment
  "employment-acceptance-rate-calculator",
  "employment-applicants-per-hire-calculator",
  "employment-cost-per-applicant-calculator",
  "employment-cost-per-interview-calculator",
  "employment-cost-per-offer-calculator",
  "employment-hire-rate-calculator",
  "employment-interview-rate-calculator",
  "employment-offer-rate-calculator",
  "employment-recruiter-productivity-calculator",
  "employment-time-per-hire-calculator",

  // Events
  "event-marketing-cost-per-registration-calculator",
  "event-merchandise-revenue-share-calculator",
  "event-paid-upgrade-rate-calculator",
  "event-revenue-per-attendee-calculator",
  "event-sponsor-revenue-per-attendee-calculator",
  "event-ticket-revenue-calculator",
  "event-profit-margin-calculator",
  "event-refund-rate-calculator",
  "event-sponsorship-per-attendee-calculator",
  "event-staff-cost-per-attendee-calculator",

  // Freelancer
  "freelancer-admin-time-rate-calculator",
  "freelancer-average-invoice-value-calculator",
  "freelancer-booking-rate-calculator",
  "freelancer-client-retention-rate-calculator",
  "freelancer-expense-ratio-calculator",
  "freelancer-lead-conversion-rate-calculator",
  "freelancer-monthly-income-variance-calculator",
  "freelancer-payment-delay-days-calculator",
  "freelancer-project-delivery-rate-calculator",
  "freelancer-scope-creep-rate-calculator",
] as const;
