export const INDEXING_WAVE_10_TOOL_SLUGS = [
  // Hospitality
  "hospitality-no-show-rate-calculator",
  "hospitality-refund-rate-calculator",
  "hospitality-revenue-per-guest-calculator",
  "hospitality-room-service-revenue-per-order-calculator",
  "hospitality-staff-cost-share-calculator",
  "hospitality-utility-cost-per-occupied-room-calculator",
  "hotel-cancellation-rate-calculator",
  "hotel-food-beverage-revenue-per-guest-calculator",
  "hotel-housekeeping-cost-per-room-calculator",
  "hotel-labor-cost-per-occupied-room-calculator",

  // Logistics
  "logistics-cost-per-km-calculator",
  "logistics-cost-per-shipment-calculator",
  "logistics-damage-rate-calculator",
  "logistics-delivery-attempt-success-rate-calculator",
  "logistics-empty-mile-rate-calculator",
  "logistics-fuel-cost-share-calculator",
  "logistics-load-utilization-calculator",
  "logistics-lost-shipment-rate-calculator",
  "logistics-on-time-delivery-rate-calculator",
  "logistics-return-shipment-rate-calculator",

  // Manufacturing
  "manufacturing-energy-cost-per-unit-calculator",
  "manufacturing-good-units-per-hour-calculator",
  "manufacturing-labor-cost-per-unit-calculator",
  "manufacturing-maintenance-cost-per-unit-calculator",
  "manufacturing-material-cost-per-unit-calculator",
  "manufacturing-order-completion-rate-calculator",
  "manufacturing-output-per-worker-calculator",
  "manufacturing-rework-cost-rate-calculator",
  "manufacturing-throughput-per-hour-calculator",
  "overall-equipment-effectiveness-calculator",

  // Procurement
  "procurement-expedited-order-rate-calculator",
  "procurement-lead-time-calculator",
  "procurement-order-frequency-calculator",
  "procurement-return-rate-calculator",
  "procurement-savings-rate-calculator",
  "procurement-spend-per-supplier-calculator",
  "purchase-order-accuracy-rate-calculator",
  "purchase-order-error-rate-calculator",
  "purchase-price-variance-calculator",
  "spend-under-management-calculator",

  // Quality
  "escape-defect-rate-calculator",
  "first-pass-yield-calculator",
  "inspection-cost-per-unit-calculator",
  "inspection-pass-rate-calculator",
  "nonconformance-cost-per-case-calculator",
  "nonconformance-rate-calculator",
  "process-conformance-rate-calculator",
  "quality-acceptance-rate-calculator",
  "quality-audit-pass-rate-calculator",
  "quality-cost-per-unit-calculator",

  // Rental business
  "rental-delivery-cost-per-booking-calculator",
  "rental-deposit-refund-rate-calculator",
  "rental-discount-rate-calculator",
  "rental-extension-rate-calculator",
  "rental-fleet-revenue-per-asset-calculator",
  "rental-idle-days-calculator",
  "rental-insurance-cost-per-day-calculator",
  "rental-late-fee-calculator",
  "rental-maintenance-cost-rate-calculator",
  "rental-net-margin-calculator",

  // Restaurant
  "menu-item-contribution-rate-calculator",
  "menu-price-from-food-cost-calculator",
  "recipe-cost-per-serving-calculator",
  "restaurant-average-check-calculator",
  "restaurant-break-even-covers-calculator",
  "restaurant-break-even-orders-calculator",
  "restaurant-delivery-order-share-calculator",
  "restaurant-food-cost-rate-calculator",
  "restaurant-labor-cost-per-cover-calculator",
  "restaurant-labor-cost-percentage-calculator",

  // SaaS
  "saas-discount-rate-calculator",
  "saas-expansion-mrr-rate-calculator",
  "saas-feature-adoption-rate-calculator",
  "saas-freemium-conversion-rate-calculator",
  "saas-gross-margin-calculator",
  "saas-infrastructure-cost-per-customer-calculator",
  "saas-ltv-cac-ratio-calculator",
  "saas-ltv-calculator",
  "saas-magic-number-calculator",
  "saas-monthly-logo-retention-calculator",

  // Salon
  "salon-consumables-cost-per-service-calculator",
  "salon-customer-retention-rate-calculator",
  "salon-daily-capacity-calculator",
  "salon-discount-rate-calculator",
  "salon-labor-cost-share-calculator",
  "salon-membership-revenue-share-calculator",
  "salon-new-client-conversion-calculator",
  "salon-no-show-rate-calculator",
  "salon-product-attachment-rate-calculator",
  "salon-product-revenue-share-calculator",

  // Startup
  "startup-cash-need-calculator",
  "startup-customer-growth-rate-calculator",
  "startup-equity-dilution-calculator",
  "startup-equity-value-per-percent-calculator",
  "startup-funding-gap-calculator",
  "startup-funding-runway-calculator",
  "startup-gross-burn-calculator",
  "startup-hiring-runway-impact-calculator",
  "startup-marketing-spend-share-calculator",
  "startup-monthly-cash-change-calculator",
] as const;
