import { createContext,useCallback,useContext,useEffect,useMemo,useState } from "react";
import { appStorage } from "@/lib/app-storage";
import { getBootstrap } from "@/lib/api";
import type { BootstrapResponse,Direction } from "@/types/api";
const LOCALE_KEY="web-empire-mobile-locale";
interface EmpireContextValue { bootstrap:BootstrapResponse|null; loading:boolean; error:string|null; locale:string; direction:Direction; refresh():Promise<void>; setLocale(locale:string):Promise<void>; t(key:string,fallback:string):string; }
const EmpireContext=createContext<EmpireContextValue|null>(null);
export function EmpireProvider({children}:{children:React.ReactNode}){const [bootstrap,setBootstrap]=useState<BootstrapResponse|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [requestedLocale,setRequestedLocale]=useState("auto");const load=useCallback(async(locale:string)=>{setLoading(true);setError(null);try{const data=await getBootstrap(locale);setBootstrap(data);setRequestedLocale(data.locale.code);await appStorage.setItem(LOCALE_KEY,data.locale.code);}catch(caught){setError(caught instanceof Error?caught.message:"BOOTSTRAP_FAILED");}finally{setLoading(false);}},[]);useEffect(()=>{appStorage.getItem(LOCALE_KEY).then(saved=>load(saved??"auto")).catch(()=>load("auto"));},[load]);const value=useMemo<EmpireContextValue>(()=>({bootstrap,loading,error,locale:bootstrap?.locale.code??requestedLocale,direction:bootstrap?.locale.direction??"ltr",refresh:()=>load(bootstrap?.locale.code??requestedLocale),async setLocale(locale){await load(locale)},t(key,fallback){return bootstrap?.messages[key]??fallback}}),[bootstrap,loading,error,requestedLocale,load]);return <EmpireContext.Provider value={value}>{children}</EmpireContext.Provider>}
export function useEmpire(){const value=useContext(EmpireContext);if(!value)throw new Error("useEmpire must be used inside EmpireProvider");return value;}
