import { createContext,useContext,useEffect,useMemo,useState } from "react";
import { useColorScheme } from "react-native";
import { EMPIRE_COLORS } from "@/brand/empire";
import { useEmpire } from "@/contexts/empire";
import { appStorage } from "@/lib/app-storage";
import type { ColorMode } from "@/types/api";
const MODE_KEY="web-empire-mobile-color-mode";
export interface EmpireColors{background:string;surface:string;text:string;muted:string;primary:string;accent:string;border:string;danger:string;success:string;}
interface ThemeContextValue{mode:ColorMode;resolvedMode:"light"|"dark";colors:EmpireColors;radius:number;setMode(mode:ColorMode):Promise<void>;}
const ThemeContext=createContext<ThemeContextValue|null>(null);
export function EmpireThemeProvider({children}:{children:React.ReactNode}){const systemMode=useColorScheme();const {bootstrap}=useEmpire();const [mode,setModeState]=useState<ColorMode>("system");useEffect(()=>{appStorage.getItem(MODE_KEY).then(value=>{if(value==="light"||value==="dark"||value==="system")setModeState(value);else if(bootstrap?.appearance.defaultColorMode)setModeState(bootstrap.appearance.defaultColorMode);});},[bootstrap?.appearance.defaultColorMode]);const value=useMemo<ThemeContextValue>(()=>{const appearance=bootstrap?.appearance;const resolvedMode=mode==="system"?(systemMode==="dark"?"dark":"light"):mode;const dark=resolvedMode==="dark";return{mode,resolvedMode,radius:appearance?.borderRadius??20,colors:{background:dark?appearance?.darkBackgroundColor??EMPIRE_COLORS.empireBlack:appearance?.backgroundColor??EMPIRE_COLORS.empireIvory,surface:dark?appearance?.darkSurfaceColor??EMPIRE_COLORS.darkSurface:appearance?.surfaceColor??EMPIRE_COLORS.lightSurface,text:dark?appearance?.darkInkColor??EMPIRE_COLORS.darkInk:appearance?.inkColor??EMPIRE_COLORS.lightInk,muted:dark?"#9FB0CA":"#667085",primary:appearance?.primaryColor??EMPIRE_COLORS.imperialViolet,accent:appearance?.accentColor??EMPIRE_COLORS.signalCyan,border:dark?"#1F2D44":"#DFE5EF",danger:EMPIRE_COLORS.danger,success:EMPIRE_COLORS.success},async setMode(nextMode){setModeState(nextMode);await appStorage.setItem(MODE_KEY,nextMode);}}},[bootstrap?.appearance,mode,systemMode]);return <ThemeContext.Provider value={value}>{children}</ThemeContext.Provider>}
export function useEmpireTheme(){const value=useContext(ThemeContext);if(!value)throw new Error("useEmpireTheme must be used inside EmpireThemeProvider");return value;}
