import { useMemo,useState } from "react";
import { Pressable,StyleSheet,TextInput,View } from "react-native";
import { ToolCard } from "@/components/tool-card";
import { AppScreen,AppText,ErrorState,MutedText,SectionTitle } from "@/components/ui";
import { useEmpire } from "@/contexts/empire";
import { useEmpireTheme } from "@/contexts/theme";
export default function ToolsScreen(){const {bootstrap,direction,error,refresh}=useEmpire();const {colors,radius}=useEmpireTheme();const [query,setQuery]=useState("");const [categoryId,setCategoryId]=useState<string|null>(null);const ar=direction==="rtl";const tools=useMemo(()=>{const normalized=query.trim().toLowerCase();return(bootstrap?.tools??[]).filter(tool=>{if(categoryId&&tool.categoryId!==categoryId)return false;return !normalized||`${tool.title} ${tool.description}`.toLowerCase().includes(normalized)})},[bootstrap?.tools,categoryId,query]);if(error||!bootstrap)return <AppScreen><ErrorState message={error??"BOOTSTRAP_MISSING"} onRetry={()=>void refresh()}/></AppScreen>;return <AppScreen><SectionTitle eyebrow="TOOLS" title={ar?"جميع الأدوات":"All tools"} description={ar?"ابحث وشغّل أدواتك مباشرة من الجوال.":"Find and run your tools directly from mobile."}/><TextInput value={query} onChangeText={setQuery} placeholder={ar?"ابحث عن أداة...":"Search tools..."} placeholderTextColor={colors.muted} style={[styles.search,{color:colors.text,backgroundColor:colors.surface,borderColor:colors.border,borderRadius:Math.min(radius,16),textAlign:ar?"right":"left"}]}/><View style={styles.chips}><CategoryChip label={ar?"الكل":"All"} active={!categoryId} onPress={()=>setCategoryId(null)}/>{bootstrap.categories.map(category=><CategoryChip key={category.id} label={category.name} active={categoryId===category.id} onPress={()=>setCategoryId(category.id)}/>)}</View><MutedText>{tools.length} {ar?"أداة":"tools"}</MutedText><View style={styles.list}>{tools.map(tool=><ToolCard key={tool.id} tool={tool}/>)}</View></AppScreen>}
function CategoryChip({label,active,onPress}:{label:string;active:boolean;onPress():void}){const {colors}=useEmpireTheme();return <Pressable onPress={onPress} style={[styles.chip,{backgroundColor:active?colors.primary:colors.surface,borderColor:active?colors.primary:colors.border}]}><AppText style={{color:active?"#fff":colors.text,fontSize:13,fontWeight:"800"}}>{label}</AppText></Pressable>}
const styles=StyleSheet.create({search:{borderWidth:1,minHeight:52,paddingHorizontal:16,fontSize:16},chips:{flexDirection:"row",flexWrap:"wrap",gap:8},chip:{borderWidth:1,borderRadius:999,paddingHorizontal:13,paddingVertical:8},list:{gap:14}});
