import { router,useFocusEffect } from "expo-router";
import { useCallback,useState } from "react";
import { RefreshControl,ScrollView,StyleSheet,View } from "react-native";
import { AppText,Card,ErrorState,LoadingState,MutedText,PrimaryButton,SectionTitle } from "@/components/ui";
import { useAuth } from "@/contexts/auth";
import { useEmpire } from "@/contexts/empire";
import { useEmpireTheme } from "@/contexts/theme";
import { getAccount } from "@/lib/api";
import type { AccountResponse } from "@/types/api";
export default function WalletScreen(){const {session}=useAuth();const {direction}=useEmpire();const {colors}=useEmpireTheme();const [account,setAccount]=useState<AccountResponse|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState<string|null>(null);const ar=direction==="rtl";const accessToken=session?.access_token;const load=useCallback(async()=>{if(!accessToken)return;setLoading(true);setError(null);try{setAccount(await getAccount(accessToken))}catch(caught){setError(caught instanceof Error?caught.message:"ACCOUNT_FAILED")}finally{setLoading(false)}},[accessToken]);useFocusEffect(useCallback(()=>{void load()},[load]));if(!session)return <View style={{flex:1,backgroundColor:colors.background}}><ScrollView contentContainerStyle={styles.guest}><Card><SectionTitle title={ar?"رصيدك في مكان واحد":"One credit balance"} description={ar?"سجل الدخول لمشاهدة الرصيد والخطة وسجل تشغيلات الموقع والتطبيق.":"Sign in to see the same balance, plan, and run history across web and mobile."}/><PrimaryButton label={ar?"تسجيل الدخول":"Sign in"} onPress={()=>router.push("/sign-in")}/></Card></ScrollView></View>;if(loading&&!account)return <View style={{flex:1,backgroundColor:colors.background}}><LoadingState/></View>;if(error&&!account)return <View style={{flex:1,backgroundColor:colors.background,padding:18}}><ErrorState message={error} onRetry={()=>void load()}/></View>;const planRelation=account?.subscription?.plans;const plan=Array.isArray(planRelation)?planRelation[0]:planRelation;return <ScrollView style={{flex:1,backgroundColor:colors.background}} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={()=>void load()} tintColor={colors.primary}/>}><SectionTitle eyebrow="CREDITS" title={ar?"رصيدي وخطتي":"Wallet & plan"} description={account?.user.email??""}/><View style={styles.metrics}><Card style={styles.metric}><MutedText>{ar?"الرصيد":"Balance"}</MutedText><AppText style={styles.metricValue}>{Number(account?.wallet.balance??0).toLocaleString()} pts</AppText></Card><Card style={styles.metric}><MutedText>{ar?"الخطة":"Plan"}</MutedText><AppText style={styles.metricValue}>{plan?(ar?plan.name_ar:plan.name_en):(ar?"مجاني":"Free")}</AppText></Card></View><PrimaryButton label={ar?"عرض الخطط":"View plans"} onPress={()=>router.push("/pricing")}/><SectionTitle title={ar?"آخر التشغيلات":"Recent runs"}/><View style={styles.runs}>{(account?.runs??[]).map(run=>{const relation=run.tools;const tool=Array.isArray(relation)?relation[0]:relation;return <Card key={run.id}><AppText style={styles.runTitle}>{tool?(ar?tool.title_ar:tool.title_en):"Tool"}</AppText><View style={styles.runMeta}><MutedText>{run.status}</MutedText><AppText style={{color:colors.primary,fontWeight:"900"}}>-{run.credits_charged} pts</AppText></View><MutedText style={styles.date}>{new Date(run.created_at).toLocaleString()}</MutedText></Card>})}</View></ScrollView>}
const styles=StyleSheet.create({guest:{flexGrow:1,justifyContent:"center",padding:18},content:{padding:18,gap:18,paddingBottom:40},metrics:{flexDirection:"row",gap:12},metric:{flex:1},metricValue:{fontSize:24,fontWeight:"900"},runs:{gap:12},runTitle:{fontWeight:"900",fontSize:17},runMeta:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},date:{fontSize:12}});
