import type { PropsWithChildren,ReactNode } from "react";
import { ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,type TextProps,View,type ViewStyle } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useEmpire } from "@/contexts/empire";
import { useEmpireTheme } from "@/contexts/theme";
export function AppScreen({children,scroll=true,contentStyle}:PropsWithChildren<{scroll?:boolean;contentStyle?:ViewStyle}>){const {colors}=useEmpireTheme();const content=<View style={[styles.screenContent,contentStyle]}>{children}</View>;return <SafeAreaView style={[styles.safeArea,{backgroundColor:colors.background}]} edges={["top","left","right"]}>{scroll?<ScrollView contentContainerStyle={styles.scrollContent} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>{content}</ScrollView>:content}</SafeAreaView>}
export function AppText({children,style,...props}:TextProps&{children?:ReactNode}){const {direction}=useEmpire();const {colors}=useEmpireTheme();return <Text {...props} style={[styles.text,{color:colors.text,textAlign:direction==="rtl"?"right":"left",writingDirection:direction},style]}>{children}</Text>}
export function MutedText(props:TextProps&{children?:ReactNode}){const {colors}=useEmpireTheme();return <AppText {...props} style={[{color:colors.muted},props.style]}/>}
export function Card({children,style}:PropsWithChildren<{style?:ViewStyle}>){const {colors,radius}=useEmpireTheme();return <View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border,borderRadius:Math.max(radius,18)},style]}>{children}</View>}
export function PrimaryButton({label,onPress,disabled,loading}:{label:string;onPress():void;disabled?:boolean;loading?:boolean}){const {colors,radius}=useEmpireTheme();return <Pressable accessibilityRole="button" disabled={disabled||loading} onPress={onPress} style={({pressed})=>[styles.button,{backgroundColor:colors.primary,borderRadius:Math.min(radius,16),opacity:disabled||loading?.55:pressed?.8:1}]}>{loading?<ActivityIndicator color="#fff"/>:<Text style={styles.buttonText}>{label}</Text>}</Pressable>}
export function SectionTitle({eyebrow,title,description}:{eyebrow?:string;title:string;description?:string}){const {colors}=useEmpireTheme();return <View style={styles.sectionTitle}>{eyebrow?<AppText style={[styles.eyebrow,{color:colors.primary}]}>{eyebrow}</AppText>:null}<AppText style={styles.heading}>{title}</AppText>{description?<MutedText style={styles.description}>{description}</MutedText>:null}</View>}
export function LoadingState({label="Loading..."}:{label?:string}){const {colors}=useEmpireTheme();return <View style={styles.loading}><ActivityIndicator color={colors.primary} size="large"/><MutedText>{label}</MutedText></View>}
export function ErrorState({message,onRetry}:{message:string;onRetry?:()=>void}){const {colors}=useEmpireTheme();return <Card><AppText style={[styles.errorTitle,{color:colors.danger}]}>حدث خطأ</AppText><MutedText>{message}</MutedText>{onRetry?<View style={styles.retry}><PrimaryButton label="إعادة المحاولة" onPress={onRetry}/></View>:null}</Card>}
const styles=StyleSheet.create({safeArea:{flex:1},scrollContent:{flexGrow:1},screenContent:{flex:1,padding:18,gap:18,paddingBottom:36},text:{fontSize:16,lineHeight:24},card:{borderWidth:1,padding:18,gap:10,shadowColor:"#000",shadowOpacity:0.12,shadowRadius:18,shadowOffset:{width:0,height:10},elevation:2},button:{minHeight:50,alignItems:"center",justifyContent:"center",paddingHorizontal:18},buttonText:{color:"#fff",fontWeight:"800",fontSize:16},sectionTitle:{gap:6},eyebrow:{fontWeight:"900",fontSize:12,letterSpacing:1},heading:{fontSize:30,lineHeight:38,fontWeight:"900"},description:{fontSize:15,lineHeight:24},loading:{flex:1,minHeight:280,alignItems:"center",justifyContent:"center",gap:12},errorTitle:{fontWeight:"900",fontSize:18},retry:{marginTop:8}});
