import * as WebBrowser from "expo-web-browser";
import { router } from "expo-router";
import { useState } from "react";
import { StyleSheet,View } from "react-native";
import { AppScreen,AppText,Card,MutedText,PrimaryButton,SectionTitle } from "@/components/ui";
import { useAuth } from "@/contexts/auth";
import { useEmpire } from "@/contexts/empire";
import { useEmpireTheme } from "@/contexts/theme";
import { createCheckout } from "@/lib/api";
export default function PricingScreen(){const {session}=useAuth();const {bootstrap,direction,locale}=useEmpire();const {colors}=useEmpireTheme();const [pendingPlan,setPendingPlan]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const ar=direction==="rtl";async function subscribe(planId:string){if(!session?.access_token){router.push("/sign-in");return}setPendingPlan(planId);setError(null);try{const checkout=await createCheckout(planId,locale,session.access_token);await WebBrowser.openBrowserAsync(checkout.url)}catch(caught){setError(caught instanceof Error?caught.message:"CHECKOUT_FAILED")}finally{setPendingPlan(null)}}return <AppScreen><SectionTitle eyebrow="CREDITS" title={ar?"النقاط والخطط":"Credits & plans"} description={ar?"اشترك من الجوال عبر صفحة الدفع الآمنة ثم حدّث رصيدك.":"Subscribe through secure hosted checkout, then refresh your wallet."}/>{error?<AppText style={{color:colors.danger}}>{error}</AppText>:null}<View style={styles.list}>{(bootstrap?.plans??[]).map(plan=><Card key={plan.id}><View style={styles.planHead}><AppText style={styles.planName}>{plan.name}</AppText><AppText style={[styles.price,{color:colors.primary}]}>{plan.priceSar} SAR</AppText></View><MutedText>{plan.description}</MutedText><AppText style={styles.credits}>{plan.monthlyCredits.toLocaleString()} pts</AppText>{plan.dailyAiRuns?<MutedText>{plan.dailyAiRuns} AI runs/day</MutedText>:null}{plan.maxOutputTokens?<MutedText>{plan.maxOutputTokens.toLocaleString()} max output tokens</MutedText>:null}{plan.priceSar>0?<PrimaryButton label={ar?"اشترك الآن":"Subscribe"} onPress={()=>void subscribe(plan.id)} loading={pendingPlan===plan.id}/>:null}</Card>)}</View></AppScreen>}
const styles=StyleSheet.create({list:{gap:14},planHead:{flexDirection:"row",justifyContent:"space-between",gap:12,alignItems:"center"},planName:{fontSize:22,fontWeight:"900"},price:{fontSize:20,fontWeight:"900"},credits:{fontSize:30,fontWeight:"900"}});
