import { router } from "expo-router";
import { useState } from "react";
import { StyleSheet,TextInput,View } from "react-native";
import { AppScreen,AppText,Card,MutedText,PrimaryButton,SectionTitle } from "@/components/ui";
import { useAuth } from "@/contexts/auth";
import { useEmpire } from "@/contexts/empire";
import { useEmpireTheme } from "@/contexts/theme";
export default function SignInScreen(){const {signIn,signUp}=useAuth();const {direction}=useEmpire();const {colors,radius}=useEmpireTheme();const [mode,setMode]=useState<"sign-in"|"sign-up">("sign-in");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [pending,setPending]=useState(false);const [error,setError]=useState<string|null>(null);const ar=direction==="rtl";async function submit(){setPending(true);setError(null);try{if(mode==="sign-in")await signIn(email.trim(),password);else await signUp(email.trim(),password);router.back()}catch(caught){setError(caught instanceof Error?caught.message:"AUTH_FAILED")}finally{setPending(false)}}const inputStyle=[styles.input,{color:colors.text,backgroundColor:colors.background,borderColor:colors.border,borderRadius:Math.min(radius,16),textAlign:ar?"right" as const:"left" as const}];return <AppScreen contentStyle={styles.container}><Card><SectionTitle eyebrow="WEB EMPIRE" title={mode==="sign-in"?(ar?"تسجيل الدخول":"Sign in"):(ar?"إنشاء حساب":"Create account")} description={ar?"نفس حساب webempire.site ونفس رصيد النقاط.":"The same webempire.site account and credit balance."}/><TextInput autoCapitalize="none" autoComplete="email" keyboardType="email-address" placeholder={ar?"البريد الإلكتروني":"Email"} placeholderTextColor={colors.muted} value={email} onChangeText={setEmail} style={inputStyle}/><TextInput autoCapitalize="none" autoComplete={mode==="sign-in"?"current-password":"new-password"} secureTextEntry placeholder={ar?"كلمة المرور":"Password"} placeholderTextColor={colors.muted} value={password} onChangeText={setPassword} style={inputStyle}/>{error?<AppText style={{color:colors.danger}}>{error}</AppText>:null}<PrimaryButton label={mode==="sign-in"?(ar?"دخول":"Sign in"):(ar?"إنشاء الحساب":"Create account")} onPress={()=>void submit()} loading={pending} disabled={!email.trim()||password.length<8}/><View style={styles.switchRow}><MutedText>{mode==="sign-in"?(ar?"ما عندك حساب؟":"No account?"):(ar?"عندك حساب؟":"Already registered?")}</MutedText><AppText onPress={()=>setMode(mode==="sign-in"?"sign-up":"sign-in")} style={{color:colors.primary,fontWeight:"900"}}>{mode==="sign-in"?(ar?"إنشاء حساب":"Create account"):(ar?"تسجيل الدخول":"Sign in")}</AppText></View></Card></AppScreen>}
const styles=StyleSheet.create({container:{justifyContent:"center"},input:{minHeight:52,borderWidth:1,paddingHorizontal:15,fontSize:16},switchRow:{flexDirection:"row",justifyContent:"center",gap:8,flexWrap:"wrap"}});
