-- Web Empire wave 14 — Photography + Sustainability (20 tools).
select public._wave14_upsert_formula_tools('photography-tools',$json$[
{"slug":"photography-revenue-per-delivered-photo-calculator","title_ar":"حاسبة إيراد التصوير لكل صورة مسلمة","title_en":"Photography Revenue per Delivered Photo Calculator","expression":"revenue / delivered_photos","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"delivered_photos","ar":"الصور المسلمة","en":"Delivered photos","min":0.000001}],"sort_order":33201},
{"slug":"photography-editing-cost-per-photo-calculator","title_ar":"حاسبة تكلفة تعديل كل صورة","title_en":"Photography Editing Cost per Photo Calculator","expression":"editing_cost / edited_photos","fields":[{"key":"editing_cost","ar":"تكلفة التعديل","en":"Editing cost","min":0},{"key":"edited_photos","ar":"الصور المعدلة","en":"Edited photos","min":0.000001}],"sort_order":33202},
{"slug":"photography-storage-cost-per-gb-calculator","title_ar":"حاسبة تكلفة تخزين الصور لكل جيجابايت","title_en":"Photography Storage Cost per GB Calculator","expression":"storage_cost / storage_gb","fields":[{"key":"storage_cost","ar":"تكلفة التخزين","en":"Storage cost","min":0},{"key":"storage_gb","ar":"التخزين GB","en":"Storage GB","min":0.000001}],"sort_order":33203},
{"slug":"photography-session-revenue-per-hour-calculator","title_ar":"حاسبة إيراد جلسة التصوير لكل ساعة","title_en":"Photography Session Revenue per Hour Calculator","expression":"session_revenue / session_hours","fields":[{"key":"session_revenue","ar":"إيراد الجلسة","en":"Session revenue","min":0},{"key":"session_hours","ar":"ساعات الجلسة","en":"Session hours","min":0.000001}],"sort_order":33204},
{"slug":"photography-booking-conversion-rate-calculator","title_ar":"حاسبة تحويل استفسارات التصوير إلى حجوزات","title_en":"Photography Booking Conversion Rate Calculator","expression":"bookings / inquiries * 100","fields":[{"key":"bookings","ar":"الحجوزات","en":"Bookings","min":0},{"key":"inquiries","ar":"الاستفسارات","en":"Inquiries","min":0.000001}],"sort_order":33205},
{"slug":"photography-cull-keep-rate-calculator","title_ar":"حاسبة نسبة الصور المختارة بعد الفرز","title_en":"Photography Cull Keep Rate Calculator","expression":"kept_photos / captured_photos * 100","fields":[{"key":"kept_photos","ar":"الصور المختارة","en":"Kept photos","min":0},{"key":"captured_photos","ar":"الصور الملتقطة","en":"Captured photos","min":0.000001}],"sort_order":33206},
{"slug":"photography-print-profit-per-copy-calculator","title_ar":"حاسبة ربح طباعة الصورة لكل نسخة","title_en":"Photography Print Profit per Copy Calculator","expression":"selling_price - print_cost","fields":[{"key":"selling_price","ar":"سعر البيع","en":"Selling price","min":0},{"key":"print_cost","ar":"تكلفة الطباعة","en":"Print cost","min":0}],"sort_order":33207},
{"slug":"photography-backup-storage-multiplier-calculator","title_ar":"حاسبة مضاعف تخزين النسخ الاحتياطية للصور","title_en":"Photography Backup Storage Multiplier Calculator","expression":"backup_storage_gb / source_storage_gb","fields":[{"key":"backup_storage_gb","ar":"تخزين النسخ الاحتياطية GB","en":"Backup storage GB","min":0},{"key":"source_storage_gb","ar":"التخزين الأصلي GB","en":"Source storage GB","min":0.000001}],"sort_order":33208},
{"slug":"photography-gallery-download-rate-calculator","title_ar":"حاسبة معدل تنزيل معرض الصور","title_en":"Photography Gallery Download Rate Calculator","expression":"downloads / gallery_views * 100","fields":[{"key":"downloads","ar":"التنزيلات","en":"Downloads","min":0},{"key":"gallery_views","ar":"مشاهدات المعرض","en":"Gallery views","min":0.000001}],"sort_order":33209},
{"slug":"photography-travel-cost-per-session-calculator","title_ar":"حاسبة تكلفة تنقل المصور لكل جلسة","title_en":"Photography Travel Cost per Session Calculator","expression":"travel_cost / sessions","fields":[{"key":"travel_cost","ar":"تكلفة التنقل","en":"Travel cost","min":0},{"key":"sessions","ar":"عدد الجلسات","en":"Sessions","min":0.000001}],"sort_order":33210}
]$json$::jsonb);

select public._wave14_upsert_formula_tools('sustainability-tools',$json$[
{"slug":"sustainability-waste-per-employee-calculator","title_ar":"حاسبة النفايات لكل موظف","title_en":"Sustainability Waste per Employee Calculator","expression":"waste_kg / employees","fields":[{"key":"waste_kg","ar":"النفايات كجم","en":"Waste kg","min":0},{"key":"employees","ar":"عدد الموظفين","en":"Employees","min":0.000001}],"sort_order":33301},
{"slug":"sustainability-water-saved-per-employee-calculator","title_ar":"حاسبة المياه الموفرة لكل موظف","title_en":"Sustainability Water Saved per Employee Calculator","expression":"water_saved_liters / employees","fields":[{"key":"water_saved_liters","ar":"المياه الموفرة باللتر","en":"Water saved liters","min":0},{"key":"employees","ar":"عدد الموظفين","en":"Employees","min":0.000001}],"sort_order":33302},
{"slug":"sustainability-energy-use-per-sqm-calculator","title_ar":"حاسبة استهلاك الطاقة لكل متر مربع","title_en":"Sustainability Energy Use per Square Meter Calculator","expression":"energy_kwh / area_sqm","fields":[{"key":"energy_kwh","ar":"الطاقة kWh","en":"Energy kWh","min":0},{"key":"area_sqm","ar":"المساحة م²","en":"Area m²","min":0.000001}],"sort_order":33303},
{"slug":"sustainability-recycled-material-share-calculator","title_ar":"حاسبة حصة المواد المعاد تدويرها","title_en":"Sustainability Recycled Material Share Calculator","expression":"recycled_material / total_material * 100","fields":[{"key":"recycled_material","ar":"المواد المعاد تدويرها","en":"Recycled material","min":0},{"key":"total_material","ar":"إجمالي المواد","en":"Total material","min":0.000001}],"sort_order":33304},
{"slug":"sustainability-reuse-rate-calculator","title_ar":"حاسبة معدل إعادة الاستخدام","title_en":"Sustainability Reuse Rate Calculator","expression":"reused_items / total_items * 100","fields":[{"key":"reused_items","ar":"العناصر المعاد استخدامها","en":"Reused items","min":0},{"key":"total_items","ar":"إجمالي العناصر","en":"Total items","min":0.000001}],"sort_order":33305},
{"slug":"sustainability-carbon-cost-calculator","title_ar":"حاسبة تكلفة الانبعاثات الكربونية","title_en":"Sustainability Carbon Cost Calculator","expression":"emissions_tons * carbon_price","fields":[{"key":"emissions_tons","ar":"الانبعاثات بالطن","en":"Emissions tons","min":0},{"key":"carbon_price","ar":"سعر الطن الكربوني","en":"Carbon price per ton","min":0}],"sort_order":33306},
{"slug":"sustainability-emissions-per-unit-calculator","title_ar":"حاسبة الانبعاثات لكل وحدة إنتاج","title_en":"Sustainability Emissions per Unit Calculator","expression":"emissions_kg / units","fields":[{"key":"emissions_kg","ar":"الانبعاثات كجم","en":"Emissions kg","min":0},{"key":"units","ar":"الوحدات المنتجة","en":"Units","min":0.000001}],"sort_order":33307},
{"slug":"sustainability-renewable-energy-cost-share-calculator","title_ar":"حاسبة حصة تكلفة الطاقة المتجددة","title_en":"Sustainability Renewable Energy Cost Share Calculator","expression":"renewable_energy_cost / total_energy_cost * 100","fields":[{"key":"renewable_energy_cost","ar":"تكلفة الطاقة المتجددة","en":"Renewable energy cost","min":0},{"key":"total_energy_cost","ar":"إجمالي تكلفة الطاقة","en":"Total energy cost","min":0.000001}],"sort_order":33308},
{"slug":"sustainability-landfill-savings-per-ton-calculator","title_ar":"حاسبة وفر المكب لكل طن","title_en":"Sustainability Landfill Savings per Ton Calculator","expression":"landfill_savings / diverted_tons","fields":[{"key":"landfill_savings","ar":"وفر تكلفة المكب","en":"Landfill savings","min":0},{"key":"diverted_tons","ar":"الأطنان المحولة","en":"Diverted tons","min":0.000001}],"sort_order":33309},
{"slug":"sustainability-packaging-weight-reduction-rate-calculator","title_ar":"حاسبة نسبة خفض وزن التغليف","title_en":"Sustainability Packaging Weight Reduction Rate Calculator","expression":"(old_weight - new_weight) / old_weight * 100","fields":[{"key":"old_weight","ar":"الوزن السابق","en":"Old weight","min":0.000001},{"key":"new_weight","ar":"الوزن الجديد","en":"New weight","min":0}],"sort_order":33310}
]$json$::jsonb);
