-- Web Empire — Non-AI catalog growth wave 4 (sales-tools)
-- GitHub staging only. 10 deterministic bilingual formula tools.
begin;
create temporary table w4_sales_tools(
 slug text primary key,title_ar text,title_en text,description_ar text,description_en text,
 runtime_config jsonb,schema_ar jsonb,schema_en jsonb,sort_order integer
) on commit drop;
insert into w4_sales_tools values
('lead-to-opportunity-rate-calculator','حاسبة تحويل العميل المحتمل إلى فرصة','Lead to Opportunity Rate Calculator','احسب نسبة العملاء المحتملين الذين تحولوا إلى فرص بيع.','Calculate the percentage of leads that became opportunities.','{"expression":"opportunities / leads * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"تحويل العميل المحتمل إلى فرصة","resultLabelEn":"Lead to Opportunity Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"opportunities","label":"الفرص","type":"number","required":true,"step":0.01,"min":0},{"key":"leads","label":"العملاء المحتملون","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"opportunities","label":"Opportunities","type":"number","required":true,"step":0.01,"min":0},{"key":"leads","label":"Leads","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10201),
('opportunity-win-rate-calculator','حاسبة فوز الفرص','Opportunity Win Rate Calculator','احسب نسبة فرص البيع التي أغلقت بنجاح.','Calculate the percentage of opportunities won.','{"expression":"won_deals / opportunities * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"فوز الفرص","resultLabelEn":"Opportunity Win Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"won_deals","label":"الصفقات الرابحة","type":"number","required":true,"step":0.01,"min":0},{"key":"opportunities","label":"الفرص","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"won_deals","label":"Won deals","type":"number","required":true,"step":0.01,"min":0},{"key":"opportunities","label":"Opportunities","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10202),
('sales-forecast-attainment-calculator','حاسبة تحقيق توقع المبيعات','Sales Forecast Attainment Calculator','قارن المبيعات الفعلية بتوقع المبيعات.','Compare actual sales with the sales forecast.','{"expression":"actual_sales / forecast_sales * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"تحقيق توقع المبيعات","resultLabelEn":"Sales Forecast Attainment","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"actual_sales","label":"المبيعات الفعلية","type":"number","required":true,"step":0.01,"min":0},{"key":"forecast_sales","label":"المبيعات المتوقعة","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"actual_sales","label":"Actual sales","type":"number","required":true,"step":0.01,"min":0},{"key":"forecast_sales","label":"Forecast sales","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10203),
('revenue-per-lead-calculator','حاسبة الإيراد لكل عميل محتمل','Revenue per Lead Calculator','احسب متوسط الإيراد الناتج عن كل عميل محتمل.','Calculate average revenue generated per lead.','{"expression":"revenue / leads","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"الإيراد لكل عميل محتمل","resultLabelEn":"Revenue per Lead","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"revenue","label":"الإيراد","type":"number","required":true,"step":0.01,"min":0},{"key":"leads","label":"العملاء المحتملون","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"revenue","label":"Revenue","type":"number","required":true,"step":0.01,"min":0},{"key":"leads","label":"Leads","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10204),
('revenue-per-sales-rep-calculator','حاسبة الإيراد لكل مندوب','Revenue per Sales Rep Calculator','احسب متوسط الإيراد لكل مندوب مبيعات.','Calculate average revenue per sales representative.','{"expression":"revenue / sales_reps","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"الإيراد لكل مندوب","resultLabelEn":"Revenue per Sales Rep","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"revenue","label":"الإيراد","type":"number","required":true,"step":0.01,"min":0},{"key":"sales_reps","label":"عدد مندوبي المبيعات","type":"number","required":true,"step":0.01,"min":1}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"revenue","label":"Revenue","type":"number","required":true,"step":0.01,"min":0},{"key":"sales_reps","label":"Sales reps","type":"number","required":true,"step":0.01,"min":1}],"submitLabel":"Calculate"}'::jsonb,10205),
('lost-revenue-rate-calculator','حاسبة نسبة الإيراد المفقود','Lost Revenue Rate Calculator','احسب نسبة الإيراد المفقود إلى إجمالي الإيراد المتاح.','Calculate lost revenue as a percentage of total potential revenue.','{"expression":"lost_revenue / potential_revenue * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة الإيراد المفقود","resultLabelEn":"Lost Revenue Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"lost_revenue","label":"الإيراد المفقود","type":"number","required":true,"step":0.01,"min":0},{"key":"potential_revenue","label":"الإيراد المحتمل","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"lost_revenue","label":"Lost revenue","type":"number","required":true,"step":0.01,"min":0},{"key":"potential_revenue","label":"Potential revenue","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10206),
('discount-to-list-price-rate-calculator','حاسبة نسبة الخصم من السعر','Discount to List Price Rate Calculator','احسب نسبة الخصومات الممنوحة من إجمالي السعر الأصلي.','Calculate total discounts as a percentage of list price value.','{"expression":"discount_amount / list_price_value * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة الخصم من السعر","resultLabelEn":"Discount to List Price Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"discount_amount","label":"قيمة الخصومات","type":"number","required":true,"step":0.01,"min":0},{"key":"list_price_value","label":"قيمة الأسعار الأصلية","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"discount_amount","label":"Discount amount","type":"number","required":true,"step":0.01,"min":0},{"key":"list_price_value","label":"List price value","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10207),
('customer-renewal-rate-calculator','حاسبة معدل التجديد','Customer Renewal Rate Calculator','احسب نسبة العملاء الذين جددوا من العملاء المستحقين للتجديد.','Calculate renewal rate among customers eligible to renew.','{"expression":"renewed_customers / eligible_customers * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"معدل التجديد","resultLabelEn":"Customer Renewal Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"renewed_customers","label":"العملاء المجددون","type":"number","required":true,"step":0.01,"min":0},{"key":"eligible_customers","label":"العملاء المستحقون","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"renewed_customers","label":"Renewed customers","type":"number","required":true,"step":0.01,"min":0},{"key":"eligible_customers","label":"Eligible customers","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10208),
('referral-conversion-rate-calculator','حاسبة تحويل الإحالات','Referral Conversion Rate Calculator','احسب نسبة الإحالات التي تحولت إلى عملاء.','Calculate the percentage of referrals converted to customers.','{"expression":"converted_referrals / referrals * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"تحويل الإحالات","resultLabelEn":"Referral Conversion Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"converted_referrals","label":"الإحالات المحولة","type":"number","required":true,"step":0.01,"min":0},{"key":"referrals","label":"إجمالي الإحالات","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"converted_referrals","label":"Converted referrals","type":"number","required":true,"step":0.01,"min":0},{"key":"referrals","label":"Referrals","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10209),
('quote-acceptance-rate-calculator','حاسبة قبول عروض الأسعار','Quote Acceptance Rate Calculator','احسب نسبة عروض الأسعار التي وافق عليها العملاء.','Calculate the percentage of quotes accepted by customers.','{"expression":"accepted_quotes / sent_quotes * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"قبول عروض الأسعار","resultLabelEn":"Quote Acceptance Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"accepted_quotes","label":"العروض المقبولة","type":"number","required":true,"step":0.01,"min":0},{"key":"sent_quotes","label":"العروض المرسلة","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"accepted_quotes","label":"Accepted quotes","type":"number","required":true,"step":0.01,"min":0},{"key":"sent_quotes","label":"Sent quotes","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10210);
insert into public.tools(slug,title_ar,title_en,short_description,category_id,engine_type,input_schema,output_schema,runtime_config,provider_strategy,model_alias,prompt_template,pricing_mode,fixed_points,minimum_points,cost_multiplier,requires_auth,is_featured,is_active,sort_order,seo_title,seo_description)
select s.slug,s.title_ar,s.title_en,s.description_ar,c.id,'formula'::public.tool_engine_type,s.schema_ar,'{}'::jsonb,s.runtime_config,'primary_with_fallback'::public.provider_strategy_type,null,null,'free'::public.pricing_mode_type,0,0,1,false,false,true,s.sort_order,s.title_ar,s.description_ar
from w4_sales_tools s join public.categories c on c.slug='sales-tools'
on conflict(slug) do update set title_ar=excluded.title_ar,title_en=excluded.title_en,short_description=excluded.short_description,category_id=excluded.category_id,engine_type=excluded.engine_type,input_schema=excluded.input_schema,output_schema=excluded.output_schema,runtime_config=excluded.runtime_config,model_alias=null,prompt_template=null,pricing_mode='free'::public.pricing_mode_type,fixed_points=0,minimum_points=0,cost_multiplier=1,requires_auth=false,is_featured=false,is_active=true,sort_order=excluded.sort_order,seo_title=excluded.seo_title,seo_description=excluded.seo_description,updated_at=now();
insert into public.tool_translations(tool_id,locale_id,title,short_description,seo_title,seo_description,prompt_template_override)
select t.id,l.id,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,null
from w4_sales_tools s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id) do update set title=excluded.title,short_description=excluded.short_description,seo_title=excluded.seo_title,seo_description=excluded.seo_description,prompt_template_override=null,updated_at=now();
insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,f->>'key',f->>'label',nullif(f->>'placeholder',''),nullif(f->>'helpText',''),f->'options'
from w4_sales_tools s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
cross join lateral jsonb_array_elements(case when l.code='ar' then s.schema_ar->'fields' else s.schema_en->'fields' end) f
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,placeholder=excluded.placeholder,help_text=excluded.help_text,options=excluded.options,updated_at=now();
insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,'__submit__',case when l.code='ar' then s.schema_ar->>'submitLabel' else s.schema_en->>'submitLabel' end,null,null,null
from w4_sales_tools s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,updated_at=now();
commit;
