-- Web Empire — Non-AI catalog growth wave 4 (project-management-tools)
-- GitHub staging only. 10 deterministic bilingual formula tools.
begin;
create temporary table w4_project_management_tools(
 slug text primary key,title_ar text,title_en text,description_ar text,description_en text,
 runtime_config jsonb,schema_ar jsonb,schema_en jsonb,sort_order integer
) on commit drop;
insert into w4_project_management_tools values
('milestone-completion-rate-calculator','حاسبة إنجاز المعالم','Milestone Completion Rate Calculator','احسب نسبة معالم المشروع المكتملة.','Calculate the percentage of project milestones completed.','{"expression":"completed_milestones / total_milestones * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"إنجاز المعالم","resultLabelEn":"Milestone Completion Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"completed_milestones","label":"المعالم المكتملة","type":"number","required":true,"step":0.01,"min":0},{"key":"total_milestones","label":"إجمالي المعالم","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"completed_milestones","label":"Completed milestones","type":"number","required":true,"step":0.01,"min":0},{"key":"total_milestones","label":"Total milestones","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10401),
('project-budget-used-rate-calculator','حاسبة استهلاك ميزانية المشروع','Project Budget Used Rate Calculator','احسب نسبة الميزانية المستهلكة حتى الآن.','Calculate the percentage of project budget used.','{"expression":"spent_amount / project_budget * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"استهلاك ميزانية المشروع","resultLabelEn":"Project Budget Used Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"spent_amount","label":"المبلغ المصروف","type":"number","required":true,"step":0.01,"min":0},{"key":"project_budget","label":"ميزانية المشروع","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"spent_amount","label":"Spent amount","type":"number","required":true,"step":0.01,"min":0},{"key":"project_budget","label":"Project budget","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10402),
('project-time-used-rate-calculator','حاسبة استهلاك وقت المشروع','Project Time Used Rate Calculator','احسب نسبة الوقت المستهلك من مدة المشروع.','Calculate the percentage of planned project time used.','{"expression":"elapsed_days / planned_days * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"استهلاك وقت المشروع","resultLabelEn":"Project Time Used Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"elapsed_days","label":"الأيام المنقضية","type":"number","required":true,"step":0.01,"min":0},{"key":"planned_days","label":"الأيام المخططة","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"elapsed_days","label":"Elapsed days","type":"number","required":true,"step":0.01,"min":0},{"key":"planned_days","label":"Planned days","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10403),
('project-defect-rate-calculator','حاسبة معدل العيوب بالمشروع','Project Defect Rate Calculator','احسب نسبة العناصر التي سجلت عليها عيوب.','Calculate defects as a percentage of delivered items.','{"expression":"defects / delivered_items * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"معدل العيوب بالمشروع","resultLabelEn":"Project Defect Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"defects","label":"العيوب","type":"number","required":true,"step":0.01,"min":0},{"key":"delivered_items","label":"العناصر المسلمة","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"defects","label":"Defects","type":"number","required":true,"step":0.01,"min":0},{"key":"delivered_items","label":"Delivered items","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10404),
('change-request-rate-calculator','حاسبة معدل طلبات التغيير','Change Request Rate Calculator','احسب نسبة طلبات التغيير إلى إجمالي عناصر النطاق.','Calculate change requests as a percentage of scope items.','{"expression":"change_requests / scope_items * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"معدل طلبات التغيير","resultLabelEn":"Change Request Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"change_requests","label":"طلبات التغيير","type":"number","required":true,"step":0.01,"min":0},{"key":"scope_items","label":"عناصر النطاق","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"change_requests","label":"Change requests","type":"number","required":true,"step":0.01,"min":0},{"key":"scope_items","label":"Scope items","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10405),
('blocked-task-rate-calculator','حاسبة معدل المهام المتوقفة','Blocked Task Rate Calculator','احسب نسبة المهام المتوقفة من إجمالي المهام المفتوحة.','Calculate blocked tasks as a percentage of open tasks.','{"expression":"blocked_tasks / open_tasks * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"معدل المهام المتوقفة","resultLabelEn":"Blocked Task Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"blocked_tasks","label":"المهام المتوقفة","type":"number","required":true,"step":0.01,"min":0},{"key":"open_tasks","label":"المهام المفتوحة","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"blocked_tasks","label":"Blocked tasks","type":"number","required":true,"step":0.01,"min":0},{"key":"open_tasks","label":"Open tasks","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10406),
('risk-closure-rate-calculator','حاسبة إغلاق المخاطر','Risk Closure Rate Calculator','احسب نسبة المخاطر التي تم إغلاقها أو معالجتها.','Calculate the percentage of risks closed or mitigated.','{"expression":"closed_risks / identified_risks * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"إغلاق المخاطر","resultLabelEn":"Risk Closure Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"closed_risks","label":"المخاطر المغلقة","type":"number","required":true,"step":0.01,"min":0},{"key":"identified_risks","label":"المخاطر المحددة","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"closed_risks","label":"Closed risks","type":"number","required":true,"step":0.01,"min":0},{"key":"identified_risks","label":"Identified risks","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10407),
('scope-completion-rate-calculator','حاسبة اكتمال نطاق المشروع','Scope Completion Rate Calculator','احسب نسبة عناصر النطاق المكتملة.','Calculate the percentage of scope items completed.','{"expression":"completed_scope_items / total_scope_items * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"اكتمال نطاق المشروع","resultLabelEn":"Scope Completion Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"completed_scope_items","label":"عناصر النطاق المكتملة","type":"number","required":true,"step":0.01,"min":0},{"key":"total_scope_items","label":"إجمالي عناصر النطاق","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"completed_scope_items","label":"Completed scope items","type":"number","required":true,"step":0.01,"min":0},{"key":"total_scope_items","label":"Total scope items","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10408),
('overdue-task-rate-calculator','حاسبة معدل المهام المتأخرة','Overdue Task Rate Calculator','احسب نسبة المهام المتأخرة من إجمالي المهام غير المكتملة.','Calculate overdue tasks as a percentage of unfinished tasks.','{"expression":"overdue_tasks / unfinished_tasks * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"معدل المهام المتأخرة","resultLabelEn":"Overdue Task Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"overdue_tasks","label":"المهام المتأخرة","type":"number","required":true,"step":0.01,"min":0},{"key":"unfinished_tasks","label":"المهام غير المكتملة","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"overdue_tasks","label":"Overdue tasks","type":"number","required":true,"step":0.01,"min":0},{"key":"unfinished_tasks","label":"Unfinished tasks","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10409),
('project-rework-rate-calculator','حاسبة نسبة إعادة العمل','Project Rework Rate Calculator','احسب نسبة ساعات إعادة العمل من إجمالي ساعات المشروع.','Calculate rework hours as a percentage of project hours.','{"expression":"rework_hours / total_hours * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة إعادة العمل","resultLabelEn":"Project Rework Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"rework_hours","label":"ساعات إعادة العمل","type":"number","required":true,"step":0.01,"min":0},{"key":"total_hours","label":"إجمالي الساعات","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"rework_hours","label":"Rework hours","type":"number","required":true,"step":0.01,"min":0},{"key":"total_hours","label":"Total hours","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10410);
insert into public.tools(slug,title_ar,title_en,short_description,category_id,engine_type,input_schema,output_schema,runtime_config,provider_strategy,model_alias,prompt_template,pricing_mode,fixed_points,minimum_points,cost_multiplier,requires_auth,is_featured,is_active,sort_order,seo_title,seo_description)
select s.slug,s.title_ar,s.title_en,s.description_ar,c.id,'formula'::public.tool_engine_type,s.schema_ar,'{}'::jsonb,s.runtime_config,'primary_with_fallback'::public.provider_strategy_type,null,null,'free'::public.pricing_mode_type,0,0,1,false,false,true,s.sort_order,s.title_ar,s.description_ar
from w4_project_management_tools s join public.categories c on c.slug='project-management-tools'
on conflict(slug) do update set title_ar=excluded.title_ar,title_en=excluded.title_en,short_description=excluded.short_description,category_id=excluded.category_id,engine_type=excluded.engine_type,input_schema=excluded.input_schema,output_schema=excluded.output_schema,runtime_config=excluded.runtime_config,model_alias=null,prompt_template=null,pricing_mode='free'::public.pricing_mode_type,fixed_points=0,minimum_points=0,cost_multiplier=1,requires_auth=false,is_featured=false,is_active=true,sort_order=excluded.sort_order,seo_title=excluded.seo_title,seo_description=excluded.seo_description,updated_at=now();
insert into public.tool_translations(tool_id,locale_id,title,short_description,seo_title,seo_description,prompt_template_override)
select t.id,l.id,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,null
from w4_project_management_tools s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id) do update set title=excluded.title,short_description=excluded.short_description,seo_title=excluded.seo_title,seo_description=excluded.seo_description,prompt_template_override=null,updated_at=now();
insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,f->>'key',f->>'label',nullif(f->>'placeholder',''),nullif(f->>'helpText',''),f->'options'
from w4_project_management_tools s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
cross join lateral jsonb_array_elements(case when l.code='ar' then s.schema_ar->'fields' else s.schema_en->'fields' end) f
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,placeholder=excluded.placeholder,help_text=excluded.help_text,options=excluded.options,updated_at=now();
insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,'__submit__',case when l.code='ar' then s.schema_ar->>'submitLabel' else s.schema_en->>'submitLabel' end,null,null,null
from w4_project_management_tools s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,updated_at=now();
commit;
