-- Web Empire — Non-AI catalog growth wave 3 (math-tools)
begin;
create temporary table w3_seed(
 slug text primary key,title_ar text,title_en text,description_ar text,description_en text,
 runtime_config jsonb,schema_ar jsonb,schema_en jsonb,sort_order integer
) on commit drop;
insert into w3_seed values
('rectangle-perimeter-calculator','حاسبة محيط المستطيل','Rectangle Perimeter Calculator','احسب محيط المستطيل من الطول والعرض.','Calculate a rectangle perimeter from length and width.','{"expression":"2 * (length + width)","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"محيط المستطيل","resultLabelEn":"Rectangle perimeter","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"length","type":"number","required":true,"min":0,"step":0.01,"label":"الطول"},{"key":"width","type":"number","required":true,"min":0,"step":0.01,"label":"العرض"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"length","type":"number","required":true,"min":0,"step":0.01,"label":"Length"},{"key":"width","type":"number","required":true,"min":0,"step":0.01,"label":"Width"}],"submitLabel":"Calculate"}'::jsonb,8101),
('triangle-area-basic-calculator','حاسبة مساحة المثلث','Triangle Area Calculator','احسب مساحة المثلث من القاعدة والارتفاع.','Calculate triangle area from base and height.','{"expression":"base * height / 2","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"مساحة المثلث","resultLabelEn":"Triangle area","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"base","type":"number","required":true,"min":0,"step":0.01,"label":"القاعدة"},{"key":"height","type":"number","required":true,"min":0,"step":0.01,"label":"الارتفاع"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"base","type":"number","required":true,"min":0,"step":0.01,"label":"Base"},{"key":"height","type":"number","required":true,"min":0,"step":0.01,"label":"Height"}],"submitLabel":"Calculate"}'::jsonb,8102),
('circle-area-calculator','حاسبة مساحة الدائرة','Circle Area Calculator','احسب مساحة الدائرة من نصف القطر.','Calculate circle area from radius.','{"expression":"3.141592653589793 * radius ^ 2","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"مساحة الدائرة","resultLabelEn":"Circle area","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"radius","type":"number","required":true,"min":0,"step":0.01,"label":"نصف القطر"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"radius","type":"number","required":true,"min":0,"step":0.01,"label":"Radius"}],"submitLabel":"Calculate"}'::jsonb,8103),
('cylinder-volume-calculator','حاسبة حجم الأسطوانة','Cylinder Volume Calculator','احسب حجم الأسطوانة من نصف القطر والارتفاع.','Calculate cylinder volume from radius and height.','{"expression":"3.141592653589793 * radius ^ 2 * height","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"حجم الأسطوانة","resultLabelEn":"Cylinder volume","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"radius","type":"number","required":true,"min":0,"step":0.01,"label":"نصف القطر"},{"key":"height","type":"number","required":true,"min":0,"step":0.01,"label":"الارتفاع"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"radius","type":"number","required":true,"min":0,"step":0.01,"label":"Radius"},{"key":"height","type":"number","required":true,"min":0,"step":0.01,"label":"Height"}],"submitLabel":"Calculate"}'::jsonb,8104),
('percentage-increase-calculator','حاسبة نسبة الزيادة','Percentage Increase Calculator','احسب نسبة الزيادة بين قيمة قديمة وقيمة جديدة.','Calculate percentage increase from an old value to a new value.','{"expression":"(new_value - old_value) / old_value * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة الزيادة","resultLabelEn":"Percentage increase","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"old_value","type":"number","required":true,"min":1e-06,"step":0.01,"label":"القيمة القديمة"},{"key":"new_value","type":"number","required":true,"min":0,"step":0.01,"label":"القيمة الجديدة"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"old_value","type":"number","required":true,"min":1e-06,"step":0.01,"label":"Old value"},{"key":"new_value","type":"number","required":true,"min":0,"step":0.01,"label":"New value"}],"submitLabel":"Calculate"}'::jsonb,8105),
('percentage-decrease-calculator','حاسبة نسبة الانخفاض','Percentage Decrease Calculator','احسب نسبة الانخفاض بين قيمة قديمة وقيمة جديدة.','Calculate percentage decrease from an old value to a new value.','{"expression":"(old_value - new_value) / old_value * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة الانخفاض","resultLabelEn":"Percentage decrease","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"old_value","type":"number","required":true,"min":1e-06,"step":0.01,"label":"القيمة القديمة"},{"key":"new_value","type":"number","required":true,"min":0,"step":0.01,"label":"القيمة الجديدة"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"old_value","type":"number","required":true,"min":1e-06,"step":0.01,"label":"Old value"},{"key":"new_value","type":"number","required":true,"min":0,"step":0.01,"label":"New value"}],"submitLabel":"Calculate"}'::jsonb,8106),
('three-value-average-calculator','حاسبة متوسط ثلاث قيم','Three-Value Average Calculator','احسب المتوسط الحسابي لثلاث قيم.','Calculate the arithmetic mean of three values.','{"expression":"(value_a + value_b + value_c) / 3","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"المتوسط","resultLabelEn":"Average","decimals":3,"showEquation":true}'::jsonb,'{"fields":[{"key":"value_a","type":"number","required":true,"step":0.01,"label":"القيمة الأولى"},{"key":"value_b","type":"number","required":true,"step":0.01,"label":"القيمة الثانية"},{"key":"value_c","type":"number","required":true,"step":0.01,"label":"القيمة الثالثة"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"value_a","type":"number","required":true,"step":0.01,"label":"First value"},{"key":"value_b","type":"number","required":true,"step":0.01,"label":"Second value"},{"key":"value_c","type":"number","required":true,"step":0.01,"label":"Third value"}],"submitLabel":"Calculate"}'::jsonb,8107),
('speed-from-distance-time-calculator','حاسبة السرعة من المسافة والزمن','Speed from Distance & Time','احسب السرعة المتوسطة بقسمة المسافة على الزمن.','Calculate average speed by dividing distance by time.','{"expression":"distance / time","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"السرعة","resultLabelEn":"Speed","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"distance","type":"number","required":true,"min":0,"step":0.01,"label":"المسافة"},{"key":"time","type":"number","required":true,"min":1e-06,"step":0.01,"label":"الزمن"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"distance","type":"number","required":true,"min":0,"step":0.01,"label":"Distance"},{"key":"time","type":"number","required":true,"min":1e-06,"step":0.01,"label":"Time"}],"submitLabel":"Calculate"}'::jsonb,8108),
('density-calculator','حاسبة الكثافة','Density Calculator','احسب الكثافة من الكتلة والحجم.','Calculate density from mass and volume.','{"expression":"mass / volume","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"الكثافة","resultLabelEn":"Density","decimals":3,"showEquation":true}'::jsonb,'{"fields":[{"key":"mass","type":"number","required":true,"min":0,"step":0.01,"label":"الكتلة"},{"key":"volume","type":"number","required":true,"min":1e-06,"step":0.01,"label":"الحجم"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"mass","type":"number","required":true,"min":0,"step":0.01,"label":"Mass"},{"key":"volume","type":"number","required":true,"min":1e-06,"step":0.01,"label":"Volume"}],"submitLabel":"Calculate"}'::jsonb,8109),
('math-cost-per-unit-calculator','حاسبة سعر الوحدة','Unit Price Calculator','احسب تكلفة الوحدة الواحدة من الإجمالي والكمية.','Calculate cost per unit from total cost and quantity.','{"expression":"total_cost / quantity","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"سعر الوحدة","resultLabelEn":"Unit price","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"total_cost","type":"number","required":true,"min":0,"step":0.01,"label":"التكلفة الإجمالية"},{"key":"quantity","type":"number","required":true,"min":1e-06,"step":0.01,"label":"الكمية"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"total_cost","type":"number","required":true,"min":0,"step":0.01,"label":"Total cost"},{"key":"quantity","type":"number","required":true,"min":1e-06,"step":0.01,"label":"Quantity"}],"submitLabel":"Calculate"}'::jsonb,8110);

insert into public.tools(slug,title_ar,title_en,short_description,category_id,engine_type,input_schema,output_schema,runtime_config,provider_strategy,model_alias,prompt_template,pricing_mode,fixed_points,minimum_points,cost_multiplier,requires_auth,is_featured,is_active,sort_order,seo_title,seo_description)
select s.slug,s.title_ar,s.title_en,s.description_ar,c.id,'formula'::public.tool_engine_type,s.schema_ar,'{}'::jsonb,s.runtime_config,'primary_with_fallback'::public.provider_strategy_type,null,null,'free'::public.pricing_mode_type,0,0,1,false,false,true,s.sort_order,s.title_ar,s.description_ar
from w3_seed s join public.categories c on c.slug='math-tools'
on conflict(slug) do update set title_ar=excluded.title_ar,title_en=excluded.title_en,short_description=excluded.short_description,category_id=excluded.category_id,engine_type=excluded.engine_type,input_schema=excluded.input_schema,output_schema=excluded.output_schema,runtime_config=excluded.runtime_config,model_alias=null,prompt_template=null,pricing_mode='free'::public.pricing_mode_type,fixed_points=0,minimum_points=0,cost_multiplier=1,requires_auth=false,is_featured=false,is_active=true,sort_order=excluded.sort_order,seo_title=excluded.seo_title,seo_description=excluded.seo_description,updated_at=now();

insert into public.tool_translations(tool_id,locale_id,title,short_description,seo_title,seo_description,prompt_template_override)
select t.id,l.id,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,null
from w3_seed s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id) do update set title=excluded.title,short_description=excluded.short_description,seo_title=excluded.seo_title,seo_description=excluded.seo_description,prompt_template_override=null,updated_at=now();

insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,f->>'key',f->>'label',nullif(f->>'placeholder',''),nullif(f->>'helpText',''),f->'options'
from w3_seed s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
cross join lateral jsonb_array_elements(case when l.code='ar' then s.schema_ar->'fields' else s.schema_en->'fields' end) f
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,placeholder=excluded.placeholder,help_text=excluded.help_text,options=excluded.options,updated_at=now();

insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,'__submit__',case when l.code='ar' then s.schema_ar->>'submitLabel' else s.schema_en->>'submitLabel' end,null,null,null
from w3_seed s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,updated_at=now();
commit;
