-- Web Empire — Non-AI catalog growth wave 4 (ecommerce-tools)
-- GitHub staging only. 10 deterministic bilingual formula tools.
begin;
create temporary table w4_ecommerce_tools(
 slug text primary key,title_ar text,title_en text,description_ar text,description_en text,
 runtime_config jsonb,schema_ar jsonb,schema_en jsonb,sort_order integer
) on commit drop;
insert into w4_ecommerce_tools values
('revenue-per-visitor-calculator','حاسبة الإيراد لكل زائر','Revenue per Visitor Calculator','احسب متوسط الإيراد الناتج عن كل زائر للمتجر.','Calculate average revenue generated per store visitor.','{"expression":"revenue / visitors","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"الإيراد لكل زائر","resultLabelEn":"Revenue per Visitor","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"revenue","label":"الإيراد","type":"number","required":true,"step":0.01,"min":0},{"key":"visitors","label":"الزوار","type":"number","required":true,"step":0.01,"min":1}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"revenue","label":"Revenue","type":"number","required":true,"step":0.01,"min":0},{"key":"visitors","label":"Visitors","type":"number","required":true,"step":0.01,"min":1}],"submitLabel":"Calculate"}'::jsonb,10001),
('net-profit-per-order-calculator','حاسبة صافي الربح لكل طلب','Net Profit per Order Calculator','احسب صافي الربح التقريبي لكل طلب بعد التكاليف المباشرة.','Estimate net profit per order after direct costs.','{"expression":"(revenue - product_cost - shipping_cost - fees) / orders","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"صافي الربح لكل طلب","resultLabelEn":"Net Profit per Order","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"revenue","label":"الإيراد","type":"number","required":true,"step":0.01,"min":0},{"key":"product_cost","label":"تكلفة المنتجات","type":"number","required":true,"step":0.01,"min":0},{"key":"shipping_cost","label":"تكلفة الشحن","type":"number","required":true,"step":0.01,"min":0},{"key":"fees","label":"الرسوم","type":"number","required":true,"step":0.01,"min":0},{"key":"orders","label":"الطلبات","type":"number","required":true,"step":0.01,"min":1}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"revenue","label":"Revenue","type":"number","required":true,"step":0.01,"min":0},{"key":"product_cost","label":"Product cost","type":"number","required":true,"step":0.01,"min":0},{"key":"shipping_cost","label":"Shipping cost","type":"number","required":true,"step":0.01,"min":0},{"key":"fees","label":"Fees","type":"number","required":true,"step":0.01,"min":0},{"key":"orders","label":"Orders","type":"number","required":true,"step":0.01,"min":1}],"submitLabel":"Calculate"}'::jsonb,10002),
('repeat-purchase-rate-calculator','حاسبة معدل تكرار الشراء','Repeat Purchase Rate Calculator','احسب نسبة العملاء الذين عادوا للشراء مرة أخرى.','Calculate the percentage of customers who purchased again.','{"expression":"repeat_customers / customers * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"معدل تكرار الشراء","resultLabelEn":"Repeat Purchase Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"repeat_customers","label":"العملاء المتكررون","type":"number","required":true,"step":0.01,"min":0},{"key":"customers","label":"إجمالي العملاء","type":"number","required":true,"step":0.01,"min":1}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"repeat_customers","label":"Repeat customers","type":"number","required":true,"step":0.01,"min":0},{"key":"customers","label":"Total customers","type":"number","required":true,"step":0.01,"min":1}],"submitLabel":"Calculate"}'::jsonb,10003),
('checkout-completion-rate-calculator','حاسبة إكمال الدفع','Checkout Completion Rate Calculator','احسب نسبة جلسات الدفع التي انتهت بطلب ناجح.','Calculate the percentage of checkout sessions that became orders.','{"expression":"orders / checkouts_started * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"إكمال الدفع","resultLabelEn":"Checkout Completion Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"orders","label":"الطلبات المكتملة","type":"number","required":true,"step":0.01,"min":0},{"key":"checkouts_started","label":"عمليات الدفع المبدوءة","type":"number","required":true,"step":0.01,"min":1}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"orders","label":"Completed orders","type":"number","required":true,"step":0.01,"min":0},{"key":"checkouts_started","label":"Checkouts started","type":"number","required":true,"step":0.01,"min":1}],"submitLabel":"Calculate"}'::jsonb,10004),
('coupon-usage-rate-calculator','حاسبة استخدام القسائم','Coupon Usage Rate Calculator','احسب نسبة الطلبات التي استخدمت قسيمة خصم.','Calculate the percentage of orders using a coupon.','{"expression":"coupon_orders / orders * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"استخدام القسائم","resultLabelEn":"Coupon Usage Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"coupon_orders","label":"طلبات القسائم","type":"number","required":true,"step":0.01,"min":0},{"key":"orders","label":"إجمالي الطلبات","type":"number","required":true,"step":0.01,"min":1}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"coupon_orders","label":"Coupon orders","type":"number","required":true,"step":0.01,"min":0},{"key":"orders","label":"Total orders","type":"number","required":true,"step":0.01,"min":1}],"submitLabel":"Calculate"}'::jsonb,10005),
('payment-failure-rate-calculator','حاسبة فشل الدفع','Payment Failure Rate Calculator','احسب نسبة محاولات الدفع غير الناجحة.','Calculate the percentage of failed payment attempts.','{"expression":"failed_payments / payment_attempts * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"فشل الدفع","resultLabelEn":"Payment Failure Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"failed_payments","label":"المدفوعات الفاشلة","type":"number","required":true,"step":0.01,"min":0},{"key":"payment_attempts","label":"محاولات الدفع","type":"number","required":true,"step":0.01,"min":1}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"failed_payments","label":"Failed payments","type":"number","required":true,"step":0.01,"min":0},{"key":"payment_attempts","label":"Payment attempts","type":"number","required":true,"step":0.01,"min":1}],"submitLabel":"Calculate"}'::jsonb,10006),
('net-revenue-after-refunds-calculator','حاسبة صافي الإيراد بعد الاستردادات','Net Revenue after Refunds Calculator','احسب الإيراد المتبقي بعد طرح مبالغ الاسترداد.','Calculate revenue remaining after refunds.','{"expression":"gross_revenue - refunds","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"صافي الإيراد بعد الاستردادات","resultLabelEn":"Net Revenue after Refunds","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"gross_revenue","label":"الإيراد الإجمالي","type":"number","required":true,"step":0.01,"min":0},{"key":"refunds","label":"الاستردادات","type":"number","required":true,"step":0.01,"min":0}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"gross_revenue","label":"Gross revenue","type":"number","required":true,"step":0.01,"min":0},{"key":"refunds","label":"Refunds","type":"number","required":true,"step":0.01,"min":0}],"submitLabel":"Calculate"}'::jsonb,10007),
('gross-profit-per-order-calculator','حاسبة إجمالي الربح لكل طلب','Gross Profit per Order Calculator','احسب إجمالي الربح لكل طلب قبل المصروفات التشغيلية.','Calculate gross profit per order before operating expenses.','{"expression":"(revenue - cost_of_goods) / orders","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"إجمالي الربح لكل طلب","resultLabelEn":"Gross Profit per Order","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"revenue","label":"الإيراد","type":"number","required":true,"step":0.01,"min":0},{"key":"cost_of_goods","label":"تكلفة البضاعة","type":"number","required":true,"step":0.01,"min":0},{"key":"orders","label":"الطلبات","type":"number","required":true,"step":0.01,"min":1}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"revenue","label":"Revenue","type":"number","required":true,"step":0.01,"min":0},{"key":"cost_of_goods","label":"Cost of goods","type":"number","required":true,"step":0.01,"min":0},{"key":"orders","label":"Orders","type":"number","required":true,"step":0.01,"min":1}],"submitLabel":"Calculate"}'::jsonb,10008),
('acquisition-payback-orders-calculator','حاسبة طلبات استرداد تكلفة الاستحواذ','Acquisition Payback Orders Calculator','قدّر عدد الطلبات اللازمة لاسترداد تكلفة اكتساب عميل.','Estimate how many orders are needed to recover customer acquisition cost.','{"expression":"acquisition_cost / gross_profit_per_order","outputUnitAr":" طلب","outputUnitEn":" orders","resultLabelAr":"طلبات استرداد تكلفة الاستحواذ","resultLabelEn":"Acquisition Payback Orders","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"acquisition_cost","label":"تكلفة اكتساب العميل","type":"number","required":true,"step":0.01,"min":0},{"key":"gross_profit_per_order","label":"إجمالي الربح لكل طلب","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"acquisition_cost","label":"Acquisition cost","type":"number","required":true,"step":0.01,"min":0},{"key":"gross_profit_per_order","label":"Gross profit per order","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10009),
('fulfillment-cost-rate-calculator','حاسبة نسبة تكلفة التجهيز','Fulfillment Cost Rate Calculator','احسب نسبة تكلفة تجهيز وتنفيذ الطلبات من الإيراد.','Calculate fulfillment cost as a percentage of revenue.','{"expression":"fulfillment_cost / revenue * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة تكلفة التجهيز","resultLabelEn":"Fulfillment Cost Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"fulfillment_cost","label":"تكلفة التجهيز","type":"number","required":true,"step":0.01,"min":0},{"key":"revenue","label":"الإيراد","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"fulfillment_cost","label":"Fulfillment cost","type":"number","required":true,"step":0.01,"min":0},{"key":"revenue","label":"Revenue","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10010);
insert into public.tools(slug,title_ar,title_en,short_description,category_id,engine_type,input_schema,output_schema,runtime_config,provider_strategy,model_alias,prompt_template,pricing_mode,fixed_points,minimum_points,cost_multiplier,requires_auth,is_featured,is_active,sort_order,seo_title,seo_description)
select s.slug,s.title_ar,s.title_en,s.description_ar,c.id,'formula'::public.tool_engine_type,s.schema_ar,'{}'::jsonb,s.runtime_config,'primary_with_fallback'::public.provider_strategy_type,null,null,'free'::public.pricing_mode_type,0,0,1,false,false,true,s.sort_order,s.title_ar,s.description_ar
from w4_ecommerce_tools s join public.categories c on c.slug='ecommerce-tools'
on conflict(slug) do update set title_ar=excluded.title_ar,title_en=excluded.title_en,short_description=excluded.short_description,category_id=excluded.category_id,engine_type=excluded.engine_type,input_schema=excluded.input_schema,output_schema=excluded.output_schema,runtime_config=excluded.runtime_config,model_alias=null,prompt_template=null,pricing_mode='free'::public.pricing_mode_type,fixed_points=0,minimum_points=0,cost_multiplier=1,requires_auth=false,is_featured=false,is_active=true,sort_order=excluded.sort_order,seo_title=excluded.seo_title,seo_description=excluded.seo_description,updated_at=now();
insert into public.tool_translations(tool_id,locale_id,title,short_description,seo_title,seo_description,prompt_template_override)
select t.id,l.id,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,null
from w4_ecommerce_tools s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id) do update set title=excluded.title,short_description=excluded.short_description,seo_title=excluded.seo_title,seo_description=excluded.seo_description,prompt_template_override=null,updated_at=now();
insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,f->>'key',f->>'label',nullif(f->>'placeholder',''),nullif(f->>'helpText',''),f->'options'
from w4_ecommerce_tools s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
cross join lateral jsonb_array_elements(case when l.code='ar' then s.schema_ar->'fields' else s.schema_en->'fields' end) f
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,placeholder=excluded.placeholder,help_text=excluded.help_text,options=excluded.options,updated_at=now();
insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,'__submit__',case when l.code='ar' then s.schema_ar->>'submitLabel' else s.schema_en->>'submitLabel' end,null,null,null
from w4_ecommerce_tools s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,updated_at=now();
commit;
