-- Web Empire wave 10 — 50 staged non-AI formula tools.
-- Cybersecurity, Design, Event, Procurement, Quality.

select public._wave10_upsert_formula_tools('cybersecurity-tools',$json$[
{"slug":"security-cost-per-endpoint-calculator","title_ar":"حاسبة تكلفة الأمن لكل جهاز طرفي","title_en":"Security Cost per Endpoint Calculator","expression":"security_cost / endpoints","fields":[{"key":"security_cost","ar":"تكلفة الأمن","en":"Security cost","min":0},{"key":"endpoints","ar":"عدد الأجهزة الطرفية","en":"Endpoints","min":0.000001}],"sort_order":30501},
{"slug":"security-incidents-per-thousand-users-calculator","title_ar":"حاسبة الحوادث الأمنية لكل ألف مستخدم","title_en":"Security Incidents per Thousand Users Calculator","expression":"incidents / users * 1000","fields":[{"key":"incidents","ar":"عدد الحوادث","en":"Incidents","min":0},{"key":"users","ar":"عدد المستخدمين","en":"Users","min":0.000001}],"sort_order":30502},
{"slug":"security-alert-to-incident-rate-calculator","title_ar":"حاسبة تحويل التنبيهات إلى حوادث","title_en":"Security Alert to Incident Rate Calculator","expression":"incidents / alerts * 100","fields":[{"key":"incidents","ar":"الحوادث المؤكدة","en":"Incidents","min":0},{"key":"alerts","ar":"إجمالي التنبيهات","en":"Alerts","min":0.000001}],"sort_order":30503},
{"slug":"security-patch-delay-rate-calculator","title_ar":"حاسبة نسبة تأخر التحديثات الأمنية","title_en":"Security Patch Delay Rate Calculator","expression":"overdue_patches / required_patches * 100","fields":[{"key":"overdue_patches","ar":"التحديثات المتأخرة","en":"Overdue patches","min":0},{"key":"required_patches","ar":"التحديثات المطلوبة","en":"Required patches","min":0.000001}],"sort_order":30504},
{"slug":"security-training-failure-rate-calculator","title_ar":"حاسبة نسبة الإخفاق في التدريب الأمني","title_en":"Security Training Failure Rate Calculator","expression":"failed_users / trained_users * 100","fields":[{"key":"failed_users","ar":"المستخدمون المخفقون","en":"Failed users","min":0},{"key":"trained_users","ar":"المستخدمون المدربون","en":"Trained users","min":0.000001}],"sort_order":30505},
{"slug":"security-risk-cost-per-asset-calculator","title_ar":"حاسبة تكلفة المخاطر الأمنية لكل أصل","title_en":"Security Risk Cost per Asset Calculator","expression":"risk_cost / assets","fields":[{"key":"risk_cost","ar":"تكلفة المخاطر","en":"Risk cost","min":0},{"key":"assets","ar":"عدد الأصول","en":"Assets","min":0.000001}],"sort_order":30506},
{"slug":"security-backup-failure-rate-calculator","title_ar":"حاسبة فشل النسخ الاحتياطي","title_en":"Security Backup Failure Rate Calculator","expression":"failed_backups / backup_jobs * 100","fields":[{"key":"failed_backups","ar":"النسخ الفاشلة","en":"Failed backups","min":0},{"key":"backup_jobs","ar":"إجمالي مهام النسخ","en":"Backup jobs","min":0.000001}],"sort_order":30507},
{"slug":"security-vulnerability-density-calculator","title_ar":"حاسبة كثافة الثغرات الأمنية","title_en":"Security Vulnerability Density Calculator","expression":"vulnerabilities / assets","fields":[{"key":"vulnerabilities","ar":"عدد الثغرات","en":"Vulnerabilities","min":0},{"key":"assets","ar":"عدد الأصول","en":"Assets","min":0.000001}],"sort_order":30508},
{"slug":"security-remediation-cost-per-vulnerability-calculator","title_ar":"حاسبة تكلفة معالجة كل ثغرة","title_en":"Security Remediation Cost per Vulnerability Calculator","expression":"remediation_cost / remediated_vulnerabilities","fields":[{"key":"remediation_cost","ar":"تكلفة المعالجة","en":"Remediation cost","min":0},{"key":"remediated_vulnerabilities","ar":"الثغرات المعالجة","en":"Remediated vulnerabilities","min":0.000001}],"sort_order":30509},
{"slug":"security-incident-cost-per-user-calculator","title_ar":"حاسبة تكلفة الحوادث الأمنية لكل مستخدم","title_en":"Security Incident Cost per User Calculator","expression":"incident_cost / users","fields":[{"key":"incident_cost","ar":"تكلفة الحوادث","en":"Incident cost","min":0},{"key":"users","ar":"عدد المستخدمين","en":"Users","min":0.000001}],"sort_order":30510}
]$json$::jsonb);

select public._wave10_upsert_formula_tools('design-tools',$json$[
{"slug":"design-cost-per-screen-calculator","title_ar":"حاسبة تكلفة التصميم لكل شاشة","title_en":"Design Cost per Screen Calculator","expression":"design_cost / screens","fields":[{"key":"design_cost","ar":"تكلفة التصميم","en":"Design cost","min":0},{"key":"screens","ar":"عدد الشاشات","en":"Screens","min":0.000001}],"sort_order":30601},
{"slug":"design-hours-per-screen-calculator","title_ar":"حاسبة ساعات التصميم لكل شاشة","title_en":"Design Hours per Screen Calculator","expression":"design_hours / screens","fields":[{"key":"design_hours","ar":"ساعات التصميم","en":"Design hours","min":0},{"key":"screens","ar":"عدد الشاشات","en":"Screens","min":0.000001}],"sort_order":30602},
{"slug":"design-revenue-per-project-calculator","title_ar":"حاسبة إيراد التصميم لكل مشروع","title_en":"Design Revenue per Project Calculator","expression":"revenue / projects","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"projects","ar":"عدد المشاريع","en":"Projects","min":0.000001}],"sort_order":30603},
{"slug":"design-profit-margin-calculator","title_ar":"حاسبة هامش ربح التصميم","title_en":"Design Profit Margin Calculator","expression":"(revenue - costs) / revenue * 100","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0.000001},{"key":"costs","ar":"التكاليف","en":"Costs","min":0}],"sort_order":30604},
{"slug":"design-revision-rate-calculator","title_ar":"حاسبة معدل جولات التعديل في التصميم","title_en":"Design Revision Rate Calculator","expression":"revision_rounds / projects","fields":[{"key":"revision_rounds","ar":"جولات التعديل","en":"Revision rounds","min":0},{"key":"projects","ar":"عدد المشاريع","en":"Projects","min":0.000001}],"sort_order":30605},
{"slug":"design-asset-cost-per-file-calculator","title_ar":"حاسبة تكلفة أصل التصميم لكل ملف","title_en":"Design Asset Cost per File Calculator","expression":"asset_cost / files","fields":[{"key":"asset_cost","ar":"تكلفة الأصول","en":"Asset cost","min":0},{"key":"files","ar":"عدد الملفات","en":"Files","min":0.000001}],"sort_order":30606},
{"slug":"design-print-cost-per-copy-calculator","title_ar":"حاسبة تكلفة الطباعة لكل نسخة","title_en":"Design Print Cost per Copy Calculator","expression":"print_cost / copies","fields":[{"key":"print_cost","ar":"تكلفة الطباعة","en":"Print cost","min":0},{"key":"copies","ar":"عدد النسخ","en":"Copies","min":0.000001}],"sort_order":30607},
{"slug":"design-production-hours-calculator","title_ar":"حاسبة ساعات إنتاج التصميم","title_en":"Design Production Hours Calculator","expression":"designs * hours_per_design","fields":[{"key":"designs","ar":"عدد التصاميم","en":"Designs","min":0},{"key":"hours_per_design","ar":"الساعات لكل تصميم","en":"Hours per design","min":0}],"sort_order":30608},
{"slug":"design-project-profit-calculator","title_ar":"حاسبة ربح مشروع التصميم","title_en":"Design Project Profit Calculator","expression":"project_revenue - project_cost","fields":[{"key":"project_revenue","ar":"إيراد المشروع","en":"Project revenue","min":0},{"key":"project_cost","ar":"تكلفة المشروع","en":"Project cost","min":0}],"sort_order":30609},
{"slug":"design-billable-rate-calculator","title_ar":"حاسبة نسبة ساعات التصميم القابلة للفوترة","title_en":"Design Billable Rate Calculator","expression":"billable_hours / total_hours * 100","fields":[{"key":"billable_hours","ar":"الساعات القابلة للفوترة","en":"Billable hours","min":0},{"key":"total_hours","ar":"إجمالي الساعات","en":"Total hours","min":0.000001}],"sort_order":30610}
]$json$::jsonb);

select public._wave10_upsert_formula_tools('event-tools',$json$[
{"slug":"event-ticket-revenue-calculator","title_ar":"حاسبة إيراد تذاكر الفعالية","title_en":"Event Ticket Revenue Calculator","expression":"tickets_sold * ticket_price","fields":[{"key":"tickets_sold","ar":"التذاكر المباعة","en":"Tickets sold","min":0},{"key":"ticket_price","ar":"سعر التذكرة","en":"Ticket price","min":0}],"sort_order":30701},
{"slug":"event-revenue-per-attendee-calculator","title_ar":"حاسبة إيراد الفعالية لكل حاضر","title_en":"Event Revenue per Attendee Calculator","expression":"total_revenue / attendees","fields":[{"key":"total_revenue","ar":"إجمالي الإيراد","en":"Total revenue","min":0},{"key":"attendees","ar":"عدد الحضور","en":"Attendees","min":0.000001}],"sort_order":30702},
{"slug":"event-sponsorship-per-attendee-calculator","title_ar":"حاسبة الرعاية لكل حاضر","title_en":"Event Sponsorship per Attendee Calculator","expression":"sponsorship_revenue / attendees","fields":[{"key":"sponsorship_revenue","ar":"إيراد الرعايات","en":"Sponsorship revenue","min":0},{"key":"attendees","ar":"عدد الحضور","en":"Attendees","min":0.000001}],"sort_order":30703},
{"slug":"event-profit-margin-calculator","title_ar":"حاسبة هامش ربح الفعالية","title_en":"Event Profit Margin Calculator","expression":"(revenue - costs) / revenue * 100","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0.000001},{"key":"costs","ar":"التكاليف","en":"Costs","min":0}],"sort_order":30704},
{"slug":"event-vendor-cost-per-attendee-calculator","title_ar":"حاسبة تكلفة الموردين لكل حاضر","title_en":"Event Vendor Cost per Attendee Calculator","expression":"vendor_cost / attendees","fields":[{"key":"vendor_cost","ar":"تكلفة الموردين","en":"Vendor cost","min":0},{"key":"attendees","ar":"عدد الحضور","en":"Attendees","min":0.000001}],"sort_order":30705},
{"slug":"event-marketing-cost-per-registration-calculator","title_ar":"حاسبة تكلفة تسويق الفعالية لكل تسجيل","title_en":"Event Marketing Cost per Registration Calculator","expression":"marketing_cost / registrations","fields":[{"key":"marketing_cost","ar":"تكلفة التسويق","en":"Marketing cost","min":0},{"key":"registrations","ar":"عدد التسجيلات","en":"Registrations","min":0.000001}],"sort_order":30706},
{"slug":"event-staff-cost-per-attendee-calculator","title_ar":"حاسبة تكلفة طاقم الفعالية لكل حاضر","title_en":"Event Staff Cost per Attendee Calculator","expression":"staff_cost / attendees","fields":[{"key":"staff_cost","ar":"تكلفة الطاقم","en":"Staff cost","min":0},{"key":"attendees","ar":"عدد الحضور","en":"Attendees","min":0.000001}],"sort_order":30707},
{"slug":"event-venue-cost-per-attendee-calculator","title_ar":"حاسبة تكلفة الموقع لكل حاضر","title_en":"Event Venue Cost per Attendee Calculator","expression":"venue_cost / attendees","fields":[{"key":"venue_cost","ar":"تكلفة الموقع","en":"Venue cost","min":0},{"key":"attendees","ar":"عدد الحضور","en":"Attendees","min":0.000001}],"sort_order":30708},
{"slug":"event-refund-rate-calculator","title_ar":"حاسبة نسبة استرداد تذاكر الفعالية","title_en":"Event Refund Rate Calculator","expression":"refunded_tickets / tickets_sold * 100","fields":[{"key":"refunded_tickets","ar":"التذاكر المستردة","en":"Refunded tickets","min":0},{"key":"tickets_sold","ar":"التذاكر المباعة","en":"Tickets sold","min":0.000001}],"sort_order":30709},
{"slug":"event-ticket-conversion-rate-calculator","title_ar":"حاسبة تحويل زوار صفحة الفعالية إلى مشترين","title_en":"Event Ticket Conversion Rate Calculator","expression":"tickets_sold / landing_page_visitors * 100","fields":[{"key":"tickets_sold","ar":"التذاكر المباعة","en":"Tickets sold","min":0},{"key":"landing_page_visitors","ar":"زوار صفحة الفعالية","en":"Landing page visitors","min":0.000001}],"sort_order":30710}
]$json$::jsonb);

select public._wave10_upsert_formula_tools('procurement-tools',$json$[
{"slug":"supplier-cost-reduction-rate-calculator","title_ar":"حاسبة نسبة خفض تكلفة المورد","title_en":"Supplier Cost Reduction Rate Calculator","expression":"(old_cost - new_cost) / old_cost * 100","fields":[{"key":"old_cost","ar":"التكلفة السابقة","en":"Old cost","min":0.000001},{"key":"new_cost","ar":"التكلفة الجديدة","en":"New cost","min":0}],"sort_order":30801},
{"slug":"procurement-cost-per-order-calculator","title_ar":"حاسبة تكلفة المشتريات لكل طلب","title_en":"Procurement Cost per Order Calculator","expression":"procurement_cost / orders","fields":[{"key":"procurement_cost","ar":"تكلفة عمليات الشراء","en":"Procurement cost","min":0},{"key":"orders","ar":"عدد أوامر الشراء","en":"Purchase orders","min":0.000001}],"sort_order":30802},
{"slug":"purchase-order-error-rate-calculator","title_ar":"حاسبة نسبة أخطاء أوامر الشراء","title_en":"Purchase Order Error Rate Calculator","expression":"erroneous_orders / purchase_orders * 100","fields":[{"key":"erroneous_orders","ar":"الأوامر التي بها أخطاء","en":"Erroneous orders","min":0},{"key":"purchase_orders","ar":"إجمالي أوامر الشراء","en":"Purchase orders","min":0.000001}],"sort_order":30803},
{"slug":"supplier-fill-rate-calculator","title_ar":"حاسبة نسبة تلبية المورد للطلب","title_en":"Supplier Fill Rate Calculator","expression":"fulfilled_units / ordered_units * 100","fields":[{"key":"fulfilled_units","ar":"الوحدات الملباة","en":"Fulfilled units","min":0},{"key":"ordered_units","ar":"الوحدات المطلوبة","en":"Ordered units","min":0.000001}],"sort_order":30804},
{"slug":"supplier-return-rate-calculator","title_ar":"حاسبة نسبة مرتجعات المورد","title_en":"Supplier Return Rate Calculator","expression":"returned_units / received_units * 100","fields":[{"key":"returned_units","ar":"الوحدات المرتجعة","en":"Returned units","min":0},{"key":"received_units","ar":"الوحدات المستلمة","en":"Received units","min":0.000001}],"sort_order":30805},
{"slug":"procurement-contract-savings-calculator","title_ar":"حاسبة وفر عقد المشتريات","title_en":"Procurement Contract Savings Calculator","expression":"baseline_cost - contract_cost","fields":[{"key":"baseline_cost","ar":"التكلفة المرجعية","en":"Baseline cost","min":0},{"key":"contract_cost","ar":"تكلفة العقد","en":"Contract cost","min":0}],"sort_order":30806},
{"slug":"procurement-spend-per-supplier-calculator","title_ar":"حاسبة إنفاق المشتريات لكل مورد","title_en":"Procurement Spend per Supplier Calculator","expression":"total_spend / suppliers","fields":[{"key":"total_spend","ar":"إجمالي الإنفاق","en":"Total spend","min":0},{"key":"suppliers","ar":"عدد الموردين","en":"Suppliers","min":0.000001}],"sort_order":30807},
{"slug":"supplier-lead-time-change-rate-calculator","title_ar":"حاسبة تغير مدة توريد المورد","title_en":"Supplier Lead Time Change Rate Calculator","expression":"(new_lead_time - old_lead_time) / old_lead_time * 100","fields":[{"key":"new_lead_time","ar":"مدة التوريد الجديدة","en":"New lead time","min":0},{"key":"old_lead_time","ar":"مدة التوريد السابقة","en":"Old lead time","min":0.000001}],"sort_order":30808},
{"slug":"procurement-order-frequency-calculator","title_ar":"حاسبة تكرار أوامر الشراء","title_en":"Procurement Order Frequency Calculator","expression":"purchase_orders / months","fields":[{"key":"purchase_orders","ar":"أوامر الشراء","en":"Purchase orders","min":0},{"key":"months","ar":"عدد الأشهر","en":"Months","min":0.000001}],"sort_order":30809},
{"slug":"procurement-expedited-order-rate-calculator","title_ar":"حاسبة نسبة أوامر الشراء العاجلة","title_en":"Expedited Procurement Order Rate Calculator","expression":"expedited_orders / purchase_orders * 100","fields":[{"key":"expedited_orders","ar":"الأوامر العاجلة","en":"Expedited orders","min":0},{"key":"purchase_orders","ar":"إجمالي أوامر الشراء","en":"Purchase orders","min":0.000001}],"sort_order":30810}
]$json$::jsonb);

select public._wave10_upsert_formula_tools('quality-tools',$json$[
{"slug":"quality-cost-per-unit-calculator","title_ar":"حاسبة تكلفة الجودة لكل وحدة","title_en":"Quality Cost per Unit Calculator","expression":"quality_cost / units","fields":[{"key":"quality_cost","ar":"تكلفة الجودة","en":"Quality cost","min":0},{"key":"units","ar":"عدد الوحدات","en":"Units","min":0.000001}],"sort_order":30901},
{"slug":"nonconformance-rate-calculator","title_ar":"حاسبة نسبة عدم المطابقة","title_en":"Nonconformance Rate Calculator","expression":"nonconforming_units / inspected_units * 100","fields":[{"key":"nonconforming_units","ar":"الوحدات غير المطابقة","en":"Nonconforming units","min":0},{"key":"inspected_units","ar":"الوحدات المفحوصة","en":"Inspected units","min":0.000001}],"sort_order":30902},
{"slug":"corrective-action-closure-rate-calculator","title_ar":"حاسبة نسبة إغلاق الإجراءات التصحيحية","title_en":"Corrective Action Closure Rate Calculator","expression":"closed_actions / total_actions * 100","fields":[{"key":"closed_actions","ar":"الإجراءات المغلقة","en":"Closed actions","min":0},{"key":"total_actions","ar":"إجمالي الإجراءات","en":"Total actions","min":0.000001}],"sort_order":30903},
{"slug":"inspection-cost-per-unit-calculator","title_ar":"حاسبة تكلفة الفحص لكل وحدة","title_en":"Inspection Cost per Unit Calculator","expression":"inspection_cost / inspected_units","fields":[{"key":"inspection_cost","ar":"تكلفة الفحص","en":"Inspection cost","min":0},{"key":"inspected_units","ar":"الوحدات المفحوصة","en":"Inspected units","min":0.000001}],"sort_order":30904},
{"slug":"supplier-quality-rate-calculator","title_ar":"حاسبة نسبة جودة المورد","title_en":"Supplier Quality Rate Calculator","expression":"accepted_supplier_units / received_supplier_units * 100","fields":[{"key":"accepted_supplier_units","ar":"الوحدات المقبولة من المورد","en":"Accepted supplier units","min":0},{"key":"received_supplier_units","ar":"الوحدات المستلمة من المورد","en":"Received supplier units","min":0.000001}],"sort_order":30905},
{"slug":"quality-rejection-rate-calculator","title_ar":"حاسبة نسبة رفض الجودة","title_en":"Quality Rejection Rate Calculator","expression":"rejected_units / inspected_units * 100","fields":[{"key":"rejected_units","ar":"الوحدات المرفوضة","en":"Rejected units","min":0},{"key":"inspected_units","ar":"الوحدات المفحوصة","en":"Inspected units","min":0.000001}],"sort_order":30906},
{"slug":"quality-acceptance-rate-calculator","title_ar":"حاسبة نسبة قبول الجودة","title_en":"Quality Acceptance Rate Calculator","expression":"accepted_units / inspected_units * 100","fields":[{"key":"accepted_units","ar":"الوحدات المقبولة","en":"Accepted units","min":0},{"key":"inspected_units","ar":"الوحدات المفحوصة","en":"Inspected units","min":0.000001}],"sort_order":30907},
{"slug":"quality-audit-pass-rate-calculator","title_ar":"حاسبة نسبة اجتياز تدقيق الجودة","title_en":"Quality Audit Pass Rate Calculator","expression":"passed_audits / total_audits * 100","fields":[{"key":"passed_audits","ar":"عمليات التدقيق المجتازة","en":"Passed audits","min":0},{"key":"total_audits","ar":"إجمالي عمليات التدقيق","en":"Total audits","min":0.000001}],"sort_order":30908},
{"slug":"rework-cost-per-unit-calculator","title_ar":"حاسبة تكلفة إعادة العمل لكل وحدة","title_en":"Rework Cost per Unit Calculator","expression":"rework_cost / reworked_units","fields":[{"key":"rework_cost","ar":"تكلفة إعادة العمل","en":"Rework cost","min":0},{"key":"reworked_units","ar":"الوحدات المعاد عملها","en":"Reworked units","min":0.000001}],"sort_order":30909},
{"slug":"customer-defect-return-rate-calculator","title_ar":"حاسبة نسبة مرتجعات العملاء بسبب العيوب","title_en":"Customer Defect Return Rate Calculator","expression":"defect_returns / units_sold * 100","fields":[{"key":"defect_returns","ar":"المرتجعات بسبب العيوب","en":"Defect returns","min":0},{"key":"units_sold","ar":"الوحدات المباعة","en":"Units sold","min":0.000001}],"sort_order":30910}
]$json$::jsonb);
