-- Web Empire — Non-AI catalog growth wave 3 (saudi-tools)
begin;
create temporary table w3_seed(
 slug text primary key,title_ar text,title_en text,description_ar text,description_en text,
 runtime_config jsonb,schema_ar jsonb,schema_en jsonb,sort_order integer
) on commit drop;
insert into w3_seed values
('saudi-vat-amount-calculator','حاسبة مبلغ ضريبة القيمة المضافة','Saudi VAT Amount Calculator','احسب مبلغ الضريبة من السعر قبل الضريبة ونسبة ضريبة تدخلها بنفسك.','Calculate VAT amount from pre-tax price and a VAT rate you provide.','{"expression":"subtotal * vat_rate / 100","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"مبلغ الضريبة","resultLabelEn":"VAT amount","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"subtotal","type":"number","required":true,"min":0,"step":0.01,"label":"المبلغ قبل الضريبة"},{"key":"vat_rate","type":"number","required":true,"min":0,"step":0.01,"defaultValue":15,"label":"نسبة الضريبة %"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"subtotal","type":"number","required":true,"min":0,"step":0.01,"label":"Amount before VAT"},{"key":"vat_rate","type":"number","required":true,"min":0,"step":0.01,"defaultValue":15,"label":"VAT rate %"}],"submitLabel":"Calculate"}'::jsonb,8401),
('saudi-price-with-vat-calculator','حاسبة السعر شامل الضريبة','Price Including VAT Calculator','احسب السعر شامل الضريبة باستخدام نسبة تدخلها بنفسك.','Calculate VAT-inclusive price using a rate you provide.','{"expression":"subtotal * (1 + vat_rate / 100)","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"السعر شامل الضريبة","resultLabelEn":"Price including VAT","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"subtotal","type":"number","required":true,"min":0,"step":0.01,"label":"السعر قبل الضريبة"},{"key":"vat_rate","type":"number","required":true,"min":0,"step":0.01,"defaultValue":15,"label":"نسبة الضريبة %"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"subtotal","type":"number","required":true,"min":0,"step":0.01,"label":"Price before VAT"},{"key":"vat_rate","type":"number","required":true,"min":0,"step":0.01,"defaultValue":15,"label":"VAT rate %"}],"submitLabel":"Calculate"}'::jsonb,8402),
('saudi-price-before-vat-calculator','حاسبة السعر قبل الضريبة','Price Before VAT Calculator','استخرج السعر قبل الضريبة من إجمالي شامل الضريبة باستخدام نسبة تدخلها بنفسك.','Extract pre-VAT price from a VAT-inclusive total using a rate you provide.','{"expression":"total_with_vat / (1 + vat_rate / 100)","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"السعر قبل الضريبة","resultLabelEn":"Price before VAT","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"total_with_vat","type":"number","required":true,"min":0,"step":0.01,"label":"الإجمالي شامل الضريبة"},{"key":"vat_rate","type":"number","required":true,"min":0,"step":0.01,"defaultValue":15,"label":"نسبة الضريبة %"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"total_with_vat","type":"number","required":true,"min":0,"step":0.01,"label":"Total including VAT"},{"key":"vat_rate","type":"number","required":true,"min":0,"step":0.01,"defaultValue":15,"label":"VAT rate %"}],"submitLabel":"Calculate"}'::jsonb,8403),
('saudi-hourly-salary-estimate','حاسبة أجر الساعة من الراتب','Hourly Salary Estimate','قدّر أجر الساعة من الراتب الشهري وعدد أيام وساعات العمل التي تدخلها.','Estimate hourly pay from monthly salary and the work schedule you provide.','{"expression":"monthly_salary / (working_days * hours_per_day)","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"أجر الساعة التقديري","resultLabelEn":"Estimated hourly pay","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"monthly_salary","type":"number","required":true,"min":0,"step":0.01,"label":"الراتب الشهري"},{"key":"working_days","type":"number","required":true,"min":1e-06,"step":1,"label":"أيام العمل في الشهر"},{"key":"hours_per_day","type":"number","required":true,"min":1e-06,"step":0.01,"label":"ساعات العمل يوميًا"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"monthly_salary","type":"number","required":true,"min":0,"step":0.01,"label":"Monthly salary"},{"key":"working_days","type":"number","required":true,"min":1e-06,"step":1,"label":"Working days per month"},{"key":"hours_per_day","type":"number","required":true,"min":1e-06,"step":0.01,"label":"Hours per day"}],"submitLabel":"Calculate"}'::jsonb,8404),
('saudi-annual-salary-calculator','حاسبة الراتب السنوي','Annual Salary Calculator','حوّل الراتب الشهري إلى إجمالي سنوي قبل أي استقطاعات أو بدلات إضافية.','Convert monthly salary to annual gross salary before extra deductions or allowances.','{"expression":"monthly_salary * 12","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"الراتب السنوي","resultLabelEn":"Annual salary","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"monthly_salary","type":"number","required":true,"min":0,"step":0.01,"label":"الراتب الشهري"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"monthly_salary","type":"number","required":true,"min":0,"step":0.01,"label":"Monthly salary"}],"submitLabel":"Calculate"}'::jsonb,8405),
('saudi-rent-installment-calculator','حاسبة دفعة الإيجار','Rent Installment Calculator','قسّم الإيجار السنوي على عدد الدفعات الذي تختاره.','Split annual rent by the number of installments you choose.','{"expression":"annual_rent / installments","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"قيمة الدفعة","resultLabelEn":"Installment amount","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"annual_rent","type":"number","required":true,"min":0,"step":0.01,"label":"الإيجار السنوي"},{"key":"installments","type":"number","required":true,"min":1e-06,"step":1,"label":"عدد الدفعات"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"annual_rent","type":"number","required":true,"min":0,"step":0.01,"label":"Annual rent"},{"key":"installments","type":"number","required":true,"min":1e-06,"step":1,"label":"Installments"}],"submitLabel":"Calculate"}'::jsonb,8406),
('saudi-trip-fuel-cost-calculator','حاسبة تكلفة وقود الرحلة','Trip Fuel Cost Calculator','قدّر تكلفة وقود الرحلة من المسافة وكفاءة السيارة وسعر الوقود الذي تدخله.','Estimate trip fuel cost from distance, vehicle efficiency, and fuel price you provide.','{"expression":"distance / km_per_liter * fuel_price","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"تكلفة الوقود التقديرية","resultLabelEn":"Estimated fuel cost","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"distance","type":"number","required":true,"min":0,"step":0.01,"label":"المسافة كم"},{"key":"km_per_liter","type":"number","required":true,"min":1e-06,"step":0.01,"label":"كفاءة السيارة كم/لتر"},{"key":"fuel_price","type":"number","required":true,"min":0,"step":0.001,"label":"سعر اللتر"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"distance","type":"number","required":true,"min":0,"step":0.01,"label":"Distance (km)"},{"key":"km_per_liter","type":"number","required":true,"min":1e-06,"step":0.01,"label":"Vehicle efficiency (km/L)"},{"key":"fuel_price","type":"number","required":true,"min":0,"step":0.001,"label":"Fuel price per liter"}],"submitLabel":"Calculate"}'::jsonb,8407),
('saudi-electricity-cost-estimate','حاسبة تكلفة استهلاك الكهرباء','Electricity Cost Estimate','قدّر تكلفة الاستهلاك بضرب الكيلوواط ساعة في التعرفة التي تدخلها.','Estimate electricity usage cost using a per-kWh tariff you provide.','{"expression":"kwh * tariff","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"تكلفة الاستهلاك التقديرية","resultLabelEn":"Estimated usage cost","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"kwh","type":"number","required":true,"min":0,"step":0.01,"label":"الاستهلاك ك.و.س"},{"key":"tariff","type":"number","required":true,"min":0,"step":0.0001,"label":"التعرفة لكل ك.و.س"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"kwh","type":"number","required":true,"min":0,"step":0.01,"label":"Consumption (kWh)"},{"key":"tariff","type":"number","required":true,"min":0,"step":0.0001,"label":"Tariff per kWh"}],"submitLabel":"Calculate"}'::jsonb,8408),
('saudi-sales-commission-calculator','حاسبة عمولة المبيعات','Sales Commission Calculator','احسب قيمة العمولة من قيمة البيع ونسبة العمولة التي تدخلها.','Calculate sales commission from sale value and a commission rate you provide.','{"expression":"sale_value * commission_rate / 100","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"قيمة العمولة","resultLabelEn":"Commission amount","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"sale_value","type":"number","required":true,"min":0,"step":0.01,"label":"قيمة البيع"},{"key":"commission_rate","type":"number","required":true,"min":0,"step":0.01,"label":"نسبة العمولة %"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"sale_value","type":"number","required":true,"min":0,"step":0.01,"label":"Sale value"},{"key":"commission_rate","type":"number","required":true,"min":0,"step":0.01,"label":"Commission rate %"}],"submitLabel":"Calculate"}'::jsonb,8409),
('saudi-delivery-cost-estimate','حاسبة تكلفة التوصيل التقديرية','Delivery Cost Estimate','قدّر تكلفة التوصيل من رسم أساسي ومسافة وسعر لكل كيلومتر تدخلها.','Estimate delivery cost from a base fee, distance, and per-kilometer rate you provide.','{"expression":"base_fee + distance * rate_per_km","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"تكلفة التوصيل التقديرية","resultLabelEn":"Estimated delivery cost","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"base_fee","type":"number","required":true,"min":0,"step":0.01,"label":"الرسم الأساسي"},{"key":"distance","type":"number","required":true,"min":0,"step":0.01,"label":"المسافة كم"},{"key":"rate_per_km","type":"number","required":true,"min":0,"step":0.01,"label":"السعر لكل كم"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"base_fee","type":"number","required":true,"min":0,"step":0.01,"label":"Base fee"},{"key":"distance","type":"number","required":true,"min":0,"step":0.01,"label":"Distance (km)"},{"key":"rate_per_km","type":"number","required":true,"min":0,"step":0.01,"label":"Rate per km"}],"submitLabel":"Calculate"}'::jsonb,8410);

insert into public.tools(slug,title_ar,title_en,short_description,category_id,engine_type,input_schema,output_schema,runtime_config,provider_strategy,model_alias,prompt_template,pricing_mode,fixed_points,minimum_points,cost_multiplier,requires_auth,is_featured,is_active,sort_order,seo_title,seo_description)
select s.slug,s.title_ar,s.title_en,s.description_ar,c.id,'formula'::public.tool_engine_type,s.schema_ar,'{}'::jsonb,s.runtime_config,'primary_with_fallback'::public.provider_strategy_type,null,null,'free'::public.pricing_mode_type,0,0,1,false,false,true,s.sort_order,s.title_ar,s.description_ar
from w3_seed s join public.categories c on c.slug='saudi-tools'
on conflict(slug) do update set title_ar=excluded.title_ar,title_en=excluded.title_en,short_description=excluded.short_description,category_id=excluded.category_id,engine_type=excluded.engine_type,input_schema=excluded.input_schema,output_schema=excluded.output_schema,runtime_config=excluded.runtime_config,model_alias=null,prompt_template=null,pricing_mode='free'::public.pricing_mode_type,fixed_points=0,minimum_points=0,cost_multiplier=1,requires_auth=false,is_featured=false,is_active=true,sort_order=excluded.sort_order,seo_title=excluded.seo_title,seo_description=excluded.seo_description,updated_at=now();

insert into public.tool_translations(tool_id,locale_id,title,short_description,seo_title,seo_description,prompt_template_override)
select t.id,l.id,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,null
from w3_seed s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id) do update set title=excluded.title,short_description=excluded.short_description,seo_title=excluded.seo_title,seo_description=excluded.seo_description,prompt_template_override=null,updated_at=now();

insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,f->>'key',f->>'label',nullif(f->>'placeholder',''),nullif(f->>'helpText',''),f->'options'
from w3_seed s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
cross join lateral jsonb_array_elements(case when l.code='ar' then s.schema_ar->'fields' else s.schema_en->'fields' end) f
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,placeholder=excluded.placeholder,help_text=excluded.help_text,options=excluded.options,updated_at=now();

insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,'__submit__',case when l.code='ar' then s.schema_ar->>'submitLabel' else s.schema_en->>'submitLabel' end,null,null,null
from w3_seed s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,updated_at=now();
commit;
