-- Web Empire wave 10 — 50 staged non-AI formula tools.
-- Agriculture, Automotive, Bakery, Creator, Customer Service.

select public._wave10_upsert_formula_tools('agriculture-tools',$json$[
{"slug":"crop-revenue-per-hectare-calculator","title_ar":"حاسبة إيراد المحصول لكل هكتار","title_en":"Crop Revenue per Hectare Calculator","expression":"revenue / area_hectares","fields":[{"key":"revenue","ar":"إجمالي الإيراد","en":"Total revenue","min":0},{"key":"area_hectares","ar":"المساحة بالهكتار","en":"Area (hectares)","min":0.000001}],"sort_order":30001},
{"slug":"farm-operating-margin-calculator","title_ar":"حاسبة هامش تشغيل المزرعة","title_en":"Farm Operating Margin Calculator","expression":"(revenue - operating_costs) / revenue * 100","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0.000001},{"key":"operating_costs","ar":"تكاليف التشغيل","en":"Operating costs","min":0}],"sort_order":30002},
{"slug":"irrigation-water-cost-per-hectare-calculator","title_ar":"حاسبة تكلفة مياه الري لكل هكتار","title_en":"Irrigation Water Cost per Hectare Calculator","expression":"water_cost / area_hectares","fields":[{"key":"water_cost","ar":"تكلفة المياه","en":"Water cost","min":0},{"key":"area_hectares","ar":"المساحة بالهكتار","en":"Area (hectares)","min":0.000001}],"sort_order":30003},
{"slug":"seed-cost-per-hectare-calculator","title_ar":"حاسبة تكلفة البذور لكل هكتار","title_en":"Seed Cost per Hectare Calculator","expression":"seed_cost / area_hectares","fields":[{"key":"seed_cost","ar":"تكلفة البذور","en":"Seed cost","min":0},{"key":"area_hectares","ar":"المساحة بالهكتار","en":"Area (hectares)","min":0.000001}],"sort_order":30004},
{"slug":"fertilizer-cost-per-hectare-calculator","title_ar":"حاسبة تكلفة السماد لكل هكتار","title_en":"Fertilizer Cost per Hectare Calculator","expression":"fertilizer_cost / area_hectares","fields":[{"key":"fertilizer_cost","ar":"تكلفة السماد","en":"Fertilizer cost","min":0},{"key":"area_hectares","ar":"المساحة بالهكتار","en":"Area (hectares)","min":0.000001}],"sort_order":30005},
{"slug":"harvest-value-per-ton-calculator","title_ar":"حاسبة قيمة الحصاد لكل طن","title_en":"Harvest Value per Ton Calculator","expression":"harvest_value / harvest_tons","fields":[{"key":"harvest_value","ar":"قيمة الحصاد","en":"Harvest value","min":0},{"key":"harvest_tons","ar":"كمية الحصاد بالطن","en":"Harvest tons","min":0.000001}],"sort_order":30006},
{"slug":"greenhouse-output-per-sqm-calculator","title_ar":"حاسبة إنتاج الصوبة لكل متر مربع","title_en":"Greenhouse Output per Square Meter Calculator","expression":"output_kg / greenhouse_area_sqm","fields":[{"key":"output_kg","ar":"الإنتاج بالكيلو","en":"Output (kg)","min":0},{"key":"greenhouse_area_sqm","ar":"مساحة الصوبة م²","en":"Greenhouse area (m²)","min":0.000001}],"sort_order":30007},
{"slug":"livestock-feed-cost-per-kg-gain-calculator","title_ar":"حاسبة تكلفة العلف لكل كجم زيادة وزن","title_en":"Livestock Feed Cost per Kg Gain Calculator","expression":"feed_cost / weight_gain_kg","fields":[{"key":"feed_cost","ar":"تكلفة العلف","en":"Feed cost","min":0},{"key":"weight_gain_kg","ar":"الزيادة في الوزن كجم","en":"Weight gain (kg)","min":0.000001}],"sort_order":30008},
{"slug":"farm-labor-cost-per-hectare-calculator","title_ar":"حاسبة تكلفة العمالة لكل هكتار","title_en":"Farm Labor Cost per Hectare Calculator","expression":"labor_cost / area_hectares","fields":[{"key":"labor_cost","ar":"تكلفة العمالة","en":"Labor cost","min":0},{"key":"area_hectares","ar":"المساحة بالهكتار","en":"Area (hectares)","min":0.000001}],"sort_order":30009},
{"slug":"crop-input-cost-share-calculator","title_ar":"حاسبة نسبة تكاليف مدخلات المحصول","title_en":"Crop Input Cost Share Calculator","expression":"input_cost / revenue * 100","fields":[{"key":"input_cost","ar":"تكلفة المدخلات","en":"Input cost","min":0},{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0.000001}],"sort_order":30010}
]$json$::jsonb);

select public._wave10_upsert_formula_tools('automotive-tools',$json$[
{"slug":"vehicle-insurance-cost-per-month-calculator","title_ar":"حاسبة تكلفة تأمين المركبة شهريًا","title_en":"Vehicle Insurance Cost per Month Calculator","expression":"annual_insurance / 12","fields":[{"key":"annual_insurance","ar":"التأمين السنوي","en":"Annual insurance","min":0}],"sort_order":30101},
{"slug":"vehicle-registration-cost-per-month-calculator","title_ar":"حاسبة تكلفة تسجيل المركبة شهريًا","title_en":"Vehicle Registration Cost per Month Calculator","expression":"annual_registration / 12","fields":[{"key":"annual_registration","ar":"تكلفة التسجيل السنوية","en":"Annual registration cost","min":0}],"sort_order":30102},
{"slug":"service-cost-per-km-calculator","title_ar":"حاسبة تكلفة الصيانة لكل كيلومتر","title_en":"Service Cost per Kilometer Calculator","expression":"service_cost / service_interval_km","fields":[{"key":"service_cost","ar":"تكلفة الصيانة","en":"Service cost","min":0},{"key":"service_interval_km","ar":"فاصل الصيانة كم","en":"Service interval (km)","min":0.000001}],"sort_order":30103},
{"slug":"fuel-cost-per-100km-calculator","title_ar":"حاسبة تكلفة الوقود لكل 100 كم","title_en":"Fuel Cost per 100km Calculator","expression":"fuel_price / fuel_efficiency_km_per_liter * 100","fields":[{"key":"fuel_price","ar":"سعر لتر الوقود","en":"Fuel price per liter","min":0},{"key":"fuel_efficiency_km_per_liter","ar":"الكفاءة كم/لتر","en":"Efficiency km/l","min":0.000001}],"sort_order":30104},
{"slug":"commute-monthly-fuel-cost-calculator","title_ar":"حاسبة وقود التنقل الشهري","title_en":"Monthly Commute Fuel Cost Calculator","expression":"daily_distance * work_days / fuel_efficiency * fuel_price","fields":[{"key":"daily_distance","ar":"المسافة اليومية كم","en":"Daily distance km","min":0},{"key":"work_days","ar":"أيام التنقل بالشهر","en":"Commute days per month","min":0},{"key":"fuel_efficiency","ar":"الكفاءة كم/لتر","en":"Fuel efficiency km/l","min":0.000001},{"key":"fuel_price","ar":"سعر اللتر","en":"Fuel price per liter","min":0}],"sort_order":30105},
{"slug":"vehicle-resale-value-loss-calculator","title_ar":"حاسبة خسارة قيمة إعادة بيع المركبة","title_en":"Vehicle Resale Value Loss Calculator","expression":"purchase_price - resale_value","fields":[{"key":"purchase_price","ar":"سعر الشراء","en":"Purchase price","min":0},{"key":"resale_value","ar":"قيمة إعادة البيع","en":"Resale value","min":0}],"sort_order":30106},
{"slug":"car-loan-interest-cost-calculator","title_ar":"حاسبة تكلفة فائدة تمويل السيارة","title_en":"Car Loan Interest Cost Calculator","expression":"total_payments - principal","fields":[{"key":"total_payments","ar":"إجمالي المدفوعات","en":"Total payments","min":0},{"key":"principal","ar":"أصل التمويل","en":"Principal","min":0}],"sort_order":30107},
{"slug":"fleet-fuel-cost-calculator","title_ar":"حاسبة تكلفة وقود الأسطول","title_en":"Fleet Fuel Cost Calculator","expression":"fleet_distance / fuel_efficiency * fuel_price","fields":[{"key":"fleet_distance","ar":"مسافة الأسطول كم","en":"Fleet distance km","min":0},{"key":"fuel_efficiency","ar":"الكفاءة كم/لتر","en":"Fuel efficiency km/l","min":0.000001},{"key":"fuel_price","ar":"سعر اللتر","en":"Fuel price per liter","min":0}],"sort_order":30108},
{"slug":"fleet-maintenance-cost-per-vehicle-calculator","title_ar":"حاسبة صيانة الأسطول لكل مركبة","title_en":"Fleet Maintenance Cost per Vehicle Calculator","expression":"maintenance_cost / vehicles","fields":[{"key":"maintenance_cost","ar":"تكلفة الصيانة","en":"Maintenance cost","min":0},{"key":"vehicles","ar":"عدد المركبات","en":"Vehicles","min":0.000001}],"sort_order":30109},
{"slug":"ride-revenue-per-km-calculator","title_ar":"حاسبة إيراد الرحلة لكل كيلومتر","title_en":"Ride Revenue per Kilometer Calculator","expression":"ride_revenue / distance_km","fields":[{"key":"ride_revenue","ar":"إيراد الرحلة","en":"Ride revenue","min":0},{"key":"distance_km","ar":"المسافة كم","en":"Distance km","min":0.000001}],"sort_order":30110}
]$json$::jsonb);

select public._wave10_upsert_formula_tools('bakery-tools',$json$[
{"slug":"ingredient-cost-per-item-calculator","title_ar":"حاسبة تكلفة المكونات لكل قطعة","title_en":"Ingredient Cost per Item Calculator","expression":"ingredient_cost / items","fields":[{"key":"ingredient_cost","ar":"تكلفة المكونات","en":"Ingredient cost","min":0},{"key":"items","ar":"عدد القطع","en":"Items","min":0.000001}],"sort_order":30201},
{"slug":"bakery-revenue-per-item-calculator","title_ar":"حاسبة إيراد المخبز لكل قطعة","title_en":"Bakery Revenue per Item Calculator","expression":"revenue / items_sold","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"items_sold","ar":"القطع المباعة","en":"Items sold","min":0.000001}],"sort_order":30202},
{"slug":"bakery-contribution-margin-calculator","title_ar":"حاسبة هامش مساهمة المخبز","title_en":"Bakery Contribution Margin Calculator","expression":"(selling_price - variable_cost) / selling_price * 100","fields":[{"key":"selling_price","ar":"سعر البيع","en":"Selling price","min":0.000001},{"key":"variable_cost","ar":"التكلفة المتغيرة","en":"Variable cost","min":0}],"sort_order":30203},
{"slug":"bakery-break-even-revenue-calculator","title_ar":"حاسبة إيراد التعادل للمخبز","title_en":"Bakery Break-even Revenue Calculator","expression":"fixed_costs / (1 - variable_cost_rate / 100)","fields":[{"key":"fixed_costs","ar":"التكاليف الثابتة","en":"Fixed costs","min":0},{"key":"variable_cost_rate","ar":"نسبة التكلفة المتغيرة %","en":"Variable cost rate %","min":0,"max":99.999}],"sort_order":30204},
{"slug":"bakery-production-hours-calculator","title_ar":"حاسبة ساعات إنتاج المخبز","title_en":"Bakery Production Hours Calculator","expression":"batches * hours_per_batch","fields":[{"key":"batches","ar":"عدد الدفعات","en":"Batches","min":0},{"key":"hours_per_batch","ar":"الساعات لكل دفعة","en":"Hours per batch","min":0}],"sort_order":30205},
{"slug":"bakery-output-per-labor-hour-calculator","title_ar":"حاسبة إنتاج المخبز لكل ساعة عمل","title_en":"Bakery Output per Labor Hour Calculator","expression":"items_produced / labor_hours","fields":[{"key":"items_produced","ar":"القطع المنتجة","en":"Items produced","min":0},{"key":"labor_hours","ar":"ساعات العمل","en":"Labor hours","min":0.000001}],"sort_order":30206},
{"slug":"bakery-discounted-price-calculator","title_ar":"حاسبة سعر المخبوز بعد الخصم","title_en":"Bakery Discounted Price Calculator","expression":"price * (1 - discount_rate / 100)","fields":[{"key":"price","ar":"السعر الأصلي","en":"Original price","min":0},{"key":"discount_rate","ar":"نسبة الخصم %","en":"Discount rate %","min":0,"max":100}],"sort_order":30207},
{"slug":"bakery-return-rate-calculator","title_ar":"حاسبة نسبة مرتجعات المخبز","title_en":"Bakery Return Rate Calculator","expression":"returned_items / sold_items * 100","fields":[{"key":"returned_items","ar":"القطع المرتجعة","en":"Returned items","min":0},{"key":"sold_items","ar":"القطع المباعة","en":"Sold items","min":0.000001}],"sort_order":30208},
{"slug":"bakery-unsold-rate-calculator","title_ar":"حاسبة نسبة غير المباع من المخبوزات","title_en":"Bakery Unsold Rate Calculator","expression":"unsold_items / produced_items * 100","fields":[{"key":"unsold_items","ar":"القطع غير المباعة","en":"Unsold items","min":0},{"key":"produced_items","ar":"القطع المنتجة","en":"Produced items","min":0.000001}],"sort_order":30209},
{"slug":"bakery-daily-revenue-per-worker-calculator","title_ar":"حاسبة إيراد المخبز اليومي لكل عامل","title_en":"Bakery Daily Revenue per Worker Calculator","expression":"daily_revenue / workers","fields":[{"key":"daily_revenue","ar":"الإيراد اليومي","en":"Daily revenue","min":0},{"key":"workers","ar":"عدد العمال","en":"Workers","min":0.000001}],"sort_order":30210}
]$json$::jsonb);

select public._wave10_upsert_formula_tools('creator-tools',$json$[
{"slug":"creator-revenue-per-post-calculator","title_ar":"حاسبة إيراد صانع المحتوى لكل منشور","title_en":"Creator Revenue per Post Calculator","expression":"revenue / posts","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"posts","ar":"عدد المنشورات","en":"Posts","min":0.000001}],"sort_order":30301},
{"slug":"creator-revenue-per-thousand-followers-calculator","title_ar":"حاسبة الإيراد لكل ألف متابع","title_en":"Creator Revenue per Thousand Followers Calculator","expression":"revenue / followers * 1000","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"followers","ar":"عدد المتابعين","en":"Followers","min":0.000001}],"sort_order":30302},
{"slug":"creator-sponsorship-share-calculator","title_ar":"حاسبة حصة الرعايات من دخل صانع المحتوى","title_en":"Creator Sponsorship Share Calculator","expression":"sponsorship_revenue / total_revenue * 100","fields":[{"key":"sponsorship_revenue","ar":"إيراد الرعايات","en":"Sponsorship revenue","min":0},{"key":"total_revenue","ar":"إجمالي الإيراد","en":"Total revenue","min":0.000001}],"sort_order":30303},
{"slug":"creator-content-cost-per-post-calculator","title_ar":"حاسبة تكلفة المحتوى لكل منشور","title_en":"Creator Content Cost per Post Calculator","expression":"content_cost / posts","fields":[{"key":"content_cost","ar":"تكلفة المحتوى","en":"Content cost","min":0},{"key":"posts","ar":"عدد المنشورات","en":"Posts","min":0.000001}],"sort_order":30304},
{"slug":"creator-profit-per-post-calculator","title_ar":"حاسبة ربح صانع المحتوى لكل منشور","title_en":"Creator Profit per Post Calculator","expression":"(revenue - content_cost) / posts","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"content_cost","ar":"تكلفة المحتوى","en":"Content cost","min":0},{"key":"posts","ar":"عدد المنشورات","en":"Posts","min":0.000001}],"sort_order":30305},
{"slug":"creator-email-revenue-per-subscriber-calculator","title_ar":"حاسبة إيراد البريد لكل مشترك","title_en":"Creator Email Revenue per Subscriber Calculator","expression":"email_revenue / subscribers","fields":[{"key":"email_revenue","ar":"إيراد البريد","en":"Email revenue","min":0},{"key":"subscribers","ar":"عدد المشتركين","en":"Subscribers","min":0.000001}],"sort_order":30306},
{"slug":"creator-course-revenue-per-student-calculator","title_ar":"حاسبة إيراد الدورة لكل طالب","title_en":"Creator Course Revenue per Student Calculator","expression":"course_revenue / students","fields":[{"key":"course_revenue","ar":"إيراد الدورة","en":"Course revenue","min":0},{"key":"students","ar":"عدد الطلاب","en":"Students","min":0.000001}],"sort_order":30307},
{"slug":"creator-membership-revenue-calculator","title_ar":"حاسبة إيراد عضويات صانع المحتوى","title_en":"Creator Membership Revenue Calculator","expression":"members * monthly_fee","fields":[{"key":"members","ar":"عدد الأعضاء","en":"Members","min":0},{"key":"monthly_fee","ar":"الرسوم الشهرية","en":"Monthly fee","min":0}],"sort_order":30308},
{"slug":"creator-conversion-per-thousand-views-calculator","title_ar":"حاسبة التحويلات لكل ألف مشاهدة","title_en":"Creator Conversions per Thousand Views Calculator","expression":"conversions / views * 1000","fields":[{"key":"conversions","ar":"عدد التحويلات","en":"Conversions","min":0},{"key":"views","ar":"المشاهدات","en":"Views","min":0.000001}],"sort_order":30309},
{"slug":"creator-content-roi-calculator","title_ar":"حاسبة عائد استثمار المحتوى","title_en":"Creator Content ROI Calculator","expression":"(revenue - content_cost) / content_cost * 100","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"content_cost","ar":"تكلفة المحتوى","en":"Content cost","min":0.000001}],"sort_order":30310}
]$json$::jsonb);

select public._wave10_upsert_formula_tools('customer-service-tools',$json$[
{"slug":"support-tickets-per-agent-calculator","title_ar":"حاسبة تذاكر الدعم لكل موظف","title_en":"Support Tickets per Agent Calculator","expression":"tickets / agents","fields":[{"key":"tickets","ar":"عدد التذاكر","en":"Tickets","min":0},{"key":"agents","ar":"عدد موظفي الدعم","en":"Agents","min":0.000001}],"sort_order":30401},
{"slug":"support-resolution-cost-calculator","title_ar":"حاسبة تكلفة حل تذكرة الدعم","title_en":"Support Resolution Cost Calculator","expression":"support_cost / resolved_tickets","fields":[{"key":"support_cost","ar":"تكلفة الدعم","en":"Support cost","min":0},{"key":"resolved_tickets","ar":"التذاكر المحلولة","en":"Resolved tickets","min":0.000001}],"sort_order":30402},
{"slug":"support-reopen-rate-calculator","title_ar":"حاسبة نسبة إعادة فتح التذاكر","title_en":"Support Reopen Rate Calculator","expression":"reopened_tickets / resolved_tickets * 100","fields":[{"key":"reopened_tickets","ar":"التذاكر المعاد فتحها","en":"Reopened tickets","min":0},{"key":"resolved_tickets","ar":"التذاكر المحلولة","en":"Resolved tickets","min":0.000001}],"sort_order":30403},
{"slug":"support-first-contact-resolution-rate-calculator","title_ar":"حاسبة الحل من أول تواصل","title_en":"First Contact Resolution Rate Calculator","expression":"first_contact_resolved / total_tickets * 100","fields":[{"key":"first_contact_resolved","ar":"تم حلها من أول تواصل","en":"Resolved on first contact","min":0},{"key":"total_tickets","ar":"إجمالي التذاكر","en":"Total tickets","min":0.000001}],"sort_order":30404},
{"slug":"support-abandonment-rate-calculator","title_ar":"حاسبة نسبة التخلي عن التواصل مع الدعم","title_en":"Support Abandonment Rate Calculator","expression":"abandoned_contacts / total_contacts * 100","fields":[{"key":"abandoned_contacts","ar":"التواصلات المتروكة","en":"Abandoned contacts","min":0},{"key":"total_contacts","ar":"إجمالي التواصلات","en":"Total contacts","min":0.000001}],"sort_order":30405},
{"slug":"support-escalation-cost-calculator","title_ar":"حاسبة تكلفة التصعيد في الدعم","title_en":"Support Escalation Cost Calculator","expression":"escalation_cost / escalated_tickets","fields":[{"key":"escalation_cost","ar":"تكلفة التصعيد","en":"Escalation cost","min":0},{"key":"escalated_tickets","ar":"التذاكر المصعّدة","en":"Escalated tickets","min":0.000001}],"sort_order":30406},
{"slug":"support-response-sla-rate-calculator","title_ar":"حاسبة الالتزام بزمن الاستجابة","title_en":"Support Response SLA Rate Calculator","expression":"responses_within_sla / total_tickets * 100","fields":[{"key":"responses_within_sla","ar":"الاستجابات ضمن SLA","en":"Responses within SLA","min":0},{"key":"total_tickets","ar":"إجمالي التذاكر","en":"Total tickets","min":0.000001}],"sort_order":30407},
{"slug":"support-resolution-sla-rate-calculator","title_ar":"حاسبة الالتزام بزمن الحل","title_en":"Support Resolution SLA Rate Calculator","expression":"resolutions_within_sla / resolved_tickets * 100","fields":[{"key":"resolutions_within_sla","ar":"الحلول ضمن SLA","en":"Resolutions within SLA","min":0},{"key":"resolved_tickets","ar":"التذاكر المحلولة","en":"Resolved tickets","min":0.000001}],"sort_order":30408},
{"slug":"support-tickets-per-customer-calculator","title_ar":"حاسبة تذاكر الدعم لكل عميل","title_en":"Support Tickets per Customer Calculator","expression":"tickets / customers","fields":[{"key":"tickets","ar":"عدد التذاكر","en":"Tickets","min":0},{"key":"customers","ar":"عدد العملاء","en":"Customers","min":0.000001}],"sort_order":30409},
{"slug":"support-backlog-per-agent-calculator","title_ar":"حاسبة التذاكر المتراكمة لكل موظف دعم","title_en":"Support Backlog per Agent Calculator","expression":"backlog_tickets / agents","fields":[{"key":"backlog_tickets","ar":"التذاكر المتراكمة","en":"Backlog tickets","min":0},{"key":"agents","ar":"عدد موظفي الدعم","en":"Agents","min":0.000001}],"sort_order":30410}
]$json$::jsonb);
