-- Web Empire wave 14 — Advertising + Home (20 tools).
select public._wave14_upsert_formula_tools('advertising-tools',$json$[
{"slug":"advertising-click-to-lead-rate-calculator","title_ar":"حاسبة تحويل نقرات الإعلان إلى عملاء محتملين","title_en":"Advertising Click-to-Lead Rate Calculator","expression":"leads / clicks * 100","fields":[{"key":"leads","ar":"العملاء المحتملون","en":"Leads","min":0},{"key":"clicks","ar":"النقرات","en":"Clicks","min":0.000001}],"sort_order":33001},
{"slug":"advertising-lead-cost-per-customer-calculator","title_ar":"حاسبة تكلفة الإعلان لكل عميل مكتسب","title_en":"Advertising Cost per Acquired Customer Calculator","expression":"spend / customers","fields":[{"key":"spend","ar":"الإنفاق الإعلاني","en":"Ad spend","min":0},{"key":"customers","ar":"العملاء المكتسبون","en":"Acquired customers","min":0.000001}],"sort_order":33002},
{"slug":"advertising-revenue-per-click-calculator","title_ar":"حاسبة إيراد الإعلان لكل نقرة","title_en":"Advertising Revenue per Click Calculator","expression":"revenue / clicks","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"clicks","ar":"النقرات","en":"Clicks","min":0.000001}],"sort_order":33003},
{"slug":"advertising-profit-per-click-calculator","title_ar":"حاسبة ربح الإعلان لكل نقرة","title_en":"Advertising Profit per Click Calculator","expression":"(revenue - spend) / clicks","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"spend","ar":"الإنفاق الإعلاني","en":"Ad spend","min":0},{"key":"clicks","ar":"النقرات","en":"Clicks","min":0.000001}],"sort_order":33004},
{"slug":"advertising-spend-per-impression-calculator","title_ar":"حاسبة الإنفاق الإعلاني لكل ظهور","title_en":"Advertising Spend per Impression Calculator","expression":"spend / impressions","fields":[{"key":"spend","ar":"الإنفاق الإعلاني","en":"Ad spend","min":0},{"key":"impressions","ar":"مرات الظهور","en":"Impressions","min":0.000001}],"sort_order":33005},
{"slug":"advertising-cost-per-engagement-calculator","title_ar":"حاسبة تكلفة الإعلان لكل تفاعل","title_en":"Advertising Cost per Engagement Calculator","expression":"spend / engagements","fields":[{"key":"spend","ar":"الإنفاق الإعلاني","en":"Ad spend","min":0},{"key":"engagements","ar":"التفاعلات","en":"Engagements","min":0.000001}],"sort_order":33006},
{"slug":"advertising-budget-utilization-rate-calculator","title_ar":"حاسبة نسبة استهلاك الميزانية الإعلانية","title_en":"Advertising Budget Utilization Rate Calculator","expression":"spent / budget * 100","fields":[{"key":"spent","ar":"المبلغ المصروف","en":"Amount spent","min":0},{"key":"budget","ar":"الميزانية","en":"Budget","min":0.000001}],"sort_order":33007},
{"slug":"advertising-remaining-budget-calculator","title_ar":"حاسبة الميزانية الإعلانية المتبقية","title_en":"Advertising Remaining Budget Calculator","expression":"budget - spent","fields":[{"key":"budget","ar":"الميزانية","en":"Budget","min":0},{"key":"spent","ar":"المبلغ المصروف","en":"Amount spent","min":0}],"sort_order":33008},
{"slug":"advertising-daily-remaining-budget-calculator","title_ar":"حاسبة الميزانية الإعلانية اليومية المتبقية","title_en":"Advertising Daily Remaining Budget Calculator","expression":"(budget - spent) / days_remaining","fields":[{"key":"budget","ar":"الميزانية","en":"Budget","min":0},{"key":"spent","ar":"المبلغ المصروف","en":"Amount spent","min":0},{"key":"days_remaining","ar":"الأيام المتبقية","en":"Days remaining","min":0.000001}],"sort_order":33009},
{"slug":"advertising-cost-per-video-completion-calculator","title_ar":"حاسبة تكلفة الإعلان لكل مشاهدة فيديو مكتملة","title_en":"Advertising Cost per Video Completion Calculator","expression":"spend / completed_views","fields":[{"key":"spend","ar":"الإنفاق الإعلاني","en":"Ad spend","min":0},{"key":"completed_views","ar":"المشاهدات المكتملة","en":"Completed views","min":0.000001}],"sort_order":33010}
]$json$::jsonb);

select public._wave14_upsert_formula_tools('home-tools',$json$[
{"slug":"home-monthly-utility-total-calculator","title_ar":"حاسبة إجمالي خدمات المنزل الشهرية","title_en":"Home Monthly Utility Total Calculator","expression":"electricity + water + gas + internet","fields":[{"key":"electricity","ar":"الكهرباء","en":"Electricity","min":0},{"key":"water","ar":"المياه","en":"Water","min":0},{"key":"gas","ar":"الغاز","en":"Gas","min":0},{"key":"internet","ar":"الإنترنت","en":"Internet","min":0}],"sort_order":33101},
{"slug":"home-annual-maintenance-cost-calculator","title_ar":"حاسبة تكلفة صيانة المنزل السنوية","title_en":"Home Annual Maintenance Cost Calculator","expression":"monthly_maintenance * 12","fields":[{"key":"monthly_maintenance","ar":"متوسط الصيانة الشهرية","en":"Average monthly maintenance","min":0}],"sort_order":33102},
{"slug":"home-renovation-cost-per-sqm-calculator","title_ar":"حاسبة تكلفة تجديد المنزل لكل متر مربع","title_en":"Home Renovation Cost per Square Meter Calculator","expression":"renovation_cost / area_sqm","fields":[{"key":"renovation_cost","ar":"تكلفة التجديد","en":"Renovation cost","min":0},{"key":"area_sqm","ar":"المساحة م²","en":"Area m²","min":0.000001}],"sort_order":33103},
{"slug":"home-cleaning-cost-per-visit-calculator","title_ar":"حاسبة تكلفة تنظيف المنزل لكل زيارة","title_en":"Home Cleaning Cost per Visit Calculator","expression":"total_cleaning_cost / visits","fields":[{"key":"total_cleaning_cost","ar":"إجمالي تكلفة التنظيف","en":"Total cleaning cost","min":0},{"key":"visits","ar":"عدد الزيارات","en":"Visits","min":0.000001}],"sort_order":33104},
{"slug":"home-appliance-monthly-energy-calculator","title_ar":"حاسبة استهلاك الجهاز المنزلي الشهري","title_en":"Home Appliance Monthly Energy Calculator","expression":"watts / 1000 * hours_per_day * days","fields":[{"key":"watts","ar":"قدرة الجهاز بالواط","en":"Appliance watts","min":0},{"key":"hours_per_day","ar":"ساعات التشغيل يوميًا","en":"Hours per day","min":0},{"key":"days","ar":"عدد الأيام","en":"Days","min":0}],"sort_order":33105},
{"slug":"home-water-usage-per-person-calculator","title_ar":"حاسبة استهلاك مياه المنزل لكل شخص","title_en":"Home Water Usage per Person Calculator","expression":"water_liters / people","fields":[{"key":"water_liters","ar":"استهلاك المياه باللتر","en":"Water liters","min":0},{"key":"people","ar":"عدد الأشخاص","en":"People","min":0.000001}],"sort_order":33106},
{"slug":"home-electricity-usage-per-person-calculator","title_ar":"حاسبة استهلاك كهرباء المنزل لكل شخص","title_en":"Home Electricity Usage per Person Calculator","expression":"electricity_kwh / people","fields":[{"key":"electricity_kwh","ar":"استهلاك الكهرباء kWh","en":"Electricity kWh","min":0},{"key":"people","ar":"عدد الأشخاص","en":"People","min":0.000001}],"sort_order":33107},
{"slug":"home-moving-cost-per-room-calculator","title_ar":"حاسبة تكلفة نقل المنزل لكل غرفة","title_en":"Home Moving Cost per Room Calculator","expression":"moving_cost / rooms","fields":[{"key":"moving_cost","ar":"إجمالي تكلفة النقل","en":"Moving cost","min":0},{"key":"rooms","ar":"عدد الغرف","en":"Rooms","min":0.000001}],"sort_order":33108},
{"slug":"home-furniture-budget-per-room-calculator","title_ar":"حاسبة ميزانية أثاث المنزل لكل غرفة","title_en":"Home Furniture Budget per Room Calculator","expression":"furniture_budget / rooms","fields":[{"key":"furniture_budget","ar":"ميزانية الأثاث","en":"Furniture budget","min":0},{"key":"rooms","ar":"عدد الغرف","en":"Rooms","min":0.000001}],"sort_order":33109},
{"slug":"home-rent-per-sqm-calculator","title_ar":"حاسبة إيجار المنزل لكل متر مربع","title_en":"Home Rent per Square Meter Calculator","expression":"monthly_rent / area_sqm","fields":[{"key":"monthly_rent","ar":"الإيجار الشهري","en":"Monthly rent","min":0},{"key":"area_sqm","ar":"المساحة م²","en":"Area m²","min":0.000001}],"sort_order":33110}
]$json$::jsonb);
