-- Web Empire — Non-AI catalog growth wave 4 (productivity-tools)
-- Adds 10 deterministic bilingual formula tools.
-- GitHub staging only until this migration is intentionally applied later.

begin;

create temporary table wave4_productivity_tools_seed (
  category_slug text not null,
  slug text primary key,
  title_ar text not null,
  title_en text not null,
  description_ar text not null,
  description_en text not null,
  expression text not null,
  input_fields jsonb not null,
  english_fields jsonb not null,
  submit_ar text not null,
  submit_en text not null,
  sort_order integer not null,
  is_featured boolean not null
) on commit drop;

insert into wave4_productivity_tools_seed(category_slug,slug,title_ar,title_en,description_ar,description_en,expression,input_fields,english_fields,submit_ar,submit_en,sort_order,is_featured)
values
('productivity-tools','deep-work-percentage-calculator','حاسبة نسبة العمل العميق','Deep Work Percentage Calculator','احسب نسبة ساعات العمل العميق من إجمالي ساعات العمل.','Calculate deep work hours as a percentage of total work hours.','deep_work_hours / total_work_hours * 100','[{"key":"deep_work_hours","label":"ساعات العمل العميق","type":"number","required":true,"step":0.01,"min":0},{"key":"total_work_hours","label":"إجمالي ساعات العمل","type":"number","required":true,"step":0.01,"min":0.01}]'::jsonb,'[{"key":"deep_work_hours","label":"Deep work hours","type":"number","required":true,"step":0.01,"min":0},{"key":"total_work_hours","label":"Total work hours","type":"number","required":true,"step":0.01,"min":0.01}]'::jsonb,'احسب','Calculate',8001,false),
('productivity-tools','interruptions-per-hour-calculator','حاسبة المقاطعات لكل ساعة','Interruptions per Hour Calculator','احسب متوسط عدد المقاطعات لكل ساعة عمل.','Calculate average interruptions per work hour.','interruptions / work_hours','[{"key":"interruptions","label":"عدد المقاطعات","type":"number","required":true,"step":1,"min":0},{"key":"work_hours","label":"ساعات العمل","type":"number","required":true,"step":0.01,"min":0.01}]'::jsonb,'[{"key":"interruptions","label":"Interruptions","type":"number","required":true,"step":1,"min":0},{"key":"work_hours","label":"Work hours","type":"number","required":true,"step":0.01,"min":0.01}]'::jsonb,'احسب','Calculate',8002,false),
('productivity-tools','tasks-per-workday-calculator','حاسبة المهام لكل يوم عمل','Tasks per Workday Calculator','احسب متوسط المهام المنجزة في يوم العمل.','Calculate average tasks completed per workday.','completed_tasks / workdays','[{"key":"completed_tasks","label":"المهام المنجزة","type":"number","required":true,"step":1,"min":0},{"key":"workdays","label":"أيام العمل","type":"number","required":true,"step":1,"min":1}]'::jsonb,'[{"key":"completed_tasks","label":"Completed tasks","type":"number","required":true,"step":1,"min":0},{"key":"workdays","label":"Workdays","type":"number","required":true,"step":1,"min":1}]'::jsonb,'احسب','Calculate',8003,false),
('productivity-tools','planned-actual-time-variance-calculator','حاسبة فرق الوقت المخطط والفعلي','Planned vs Actual Time Variance Calculator','احسب فرق الدقائق بين الوقت الفعلي والمخطط.','Calculate the difference between actual and planned minutes.','actual_minutes - planned_minutes','[{"key":"actual_minutes","label":"الدقائق الفعلية","type":"number","required":true,"step":0.01,"min":0},{"key":"planned_minutes","label":"الدقائق المخططة","type":"number","required":true,"step":0.01,"min":0}]'::jsonb,'[{"key":"actual_minutes","label":"Actual minutes","type":"number","required":true,"step":0.01,"min":0},{"key":"planned_minutes","label":"Planned minutes","type":"number","required":true,"step":0.01,"min":0}]'::jsonb,'احسب','Calculate',8004,false),
('productivity-tools','schedule-adherence-rate-calculator','حاسبة الالتزام بالجدول','Schedule Adherence Rate Calculator','احسب نسبة المهام المنجزة في وقتها من المهام المخططة.','Calculate on-time completed tasks as a percentage of planned tasks.','on_time_tasks / planned_tasks * 100','[{"key":"on_time_tasks","label":"المهام في وقتها","type":"number","required":true,"step":1,"min":0},{"key":"planned_tasks","label":"المهام المخططة","type":"number","required":true,"step":1,"min":1}]'::jsonb,'[{"key":"on_time_tasks","label":"On-time tasks","type":"number","required":true,"step":1,"min":0},{"key":"planned_tasks","label":"Planned tasks","type":"number","required":true,"step":1,"min":1}]'::jsonb,'احسب','Calculate',8005,false),
('productivity-tools','context-switching-time-cost-calculator','حاسبة تكلفة تبديل السياق','Context Switching Time Cost Calculator','احسب الساعات المهدرة بسبب تبديل السياق بين المهام.','Calculate hours lost to context switching.','switches * minutes_per_switch / 60','[{"key":"switches","label":"مرات تبديل السياق","type":"number","required":true,"step":1,"min":0},{"key":"minutes_per_switch","label":"دقائق لكل تبديل","type":"number","required":true,"step":0.01,"min":0}]'::jsonb,'[{"key":"switches","label":"Context switches","type":"number","required":true,"step":1,"min":0},{"key":"minutes_per_switch","label":"Minutes per switch","type":"number","required":true,"step":0.01,"min":0}]'::jsonb,'احسب','Calculate',8006,false),
('productivity-tools','weekly-focus-hours-calculator','حاسبة ساعات التركيز الأسبوعية','Weekly Focus Hours Calculator','حوّل دقائق التركيز اليومية إلى ساعات تركيز أسبوعية.','Convert daily focus minutes into weekly focus hours.','focus_minutes_per_day * days / 60','[{"key":"focus_minutes_per_day","label":"دقائق التركيز اليومية","type":"number","required":true,"step":0.01,"min":0},{"key":"days","label":"عدد الأيام","type":"number","required":true,"step":1,"min":0}]'::jsonb,'[{"key":"focus_minutes_per_day","label":"Focus minutes per day","type":"number","required":true,"step":0.01,"min":0},{"key":"days","label":"Days","type":"number","required":true,"step":1,"min":0}]'::jsonb,'احسب','Calculate',8007,false),
('productivity-tools','recurring-task-annual-hours-calculator','حاسبة ساعات المهام المتكررة سنويًا','Recurring Task Annual Hours Calculator','قدّر الساعات السنوية المستهلكة في مهمة متكررة.','Estimate annual hours spent on a recurring task.','minutes_per_task * occurrences_per_month * 12 / 60','[{"key":"minutes_per_task","label":"دقائق لكل مهمة","type":"number","required":true,"step":0.01,"min":0},{"key":"occurrences_per_month","label":"مرات التكرار شهريًا","type":"number","required":true,"step":1,"min":0}]'::jsonb,'[{"key":"minutes_per_task","label":"Minutes per task","type":"number","required":true,"step":0.01,"min":0},{"key":"occurrences_per_month","label":"Occurrences per month","type":"number","required":true,"step":1,"min":0}]'::jsonb,'احسب','Calculate',8008,false),
('productivity-tools','productive-meeting-hours-ratio-calculator','حاسبة نسبة العمل إلى الاجتماعات','Productive-to-Meeting Hours Ratio Calculator','احسب نسبة ساعات العمل المنتج إلى ساعات الاجتماعات.','Calculate productive hours relative to meeting hours.','productive_hours / meeting_hours','[{"key":"productive_hours","label":"ساعات العمل المنتج","type":"number","required":true,"step":0.01,"min":0},{"key":"meeting_hours","label":"ساعات الاجتماعات","type":"number","required":true,"step":0.01,"min":0.01}]'::jsonb,'[{"key":"productive_hours","label":"Productive hours","type":"number","required":true,"step":0.01,"min":0},{"key":"meeting_hours","label":"Meeting hours","type":"number","required":true,"step":0.01,"min":0.01}]'::jsonb,'احسب','Calculate',8009,false),
('productivity-tools','backlog-clearance-days-calculator','حاسبة أيام تصفية قائمة المهام','Backlog Clearance Days Calculator','قدّر الأيام اللازمة لإنهاء قائمة المهام الحالية.','Estimate days needed to clear the current backlog.','backlog_tasks / tasks_per_day','[{"key":"backlog_tasks","label":"المهام المتراكمة","type":"number","required":true,"step":1,"min":0},{"key":"tasks_per_day","label":"المهام المنجزة يوميًا","type":"number","required":true,"step":0.01,"min":0.01}]'::jsonb,'[{"key":"backlog_tasks","label":"Backlog tasks","type":"number","required":true,"step":1,"min":0},{"key":"tasks_per_day","label":"Tasks per day","type":"number","required":true,"step":0.01,"min":0.01}]'::jsonb,'احسب','Calculate',8010,false);

insert into public.tools(slug,title_ar,title_en,short_description,category_id,engine_type,input_schema,output_schema,runtime_config,pricing_mode,fixed_points,minimum_points,requires_auth,is_featured,is_active,sort_order,seo_title,seo_description)
select seed.slug,seed.title_ar,seed.title_en,seed.description_ar,category.id,'formula',jsonb_build_object('submitLabel',seed.submit_ar,'fields',seed.input_fields),jsonb_build_object('type','number','format','auto'),jsonb_build_object('expression',seed.expression),'free',0,0,false,seed.is_featured,true,seed.sort_order,seed.title_ar,seed.description_ar from wave4_productivity_tools_seed seed join public.categories category on category.slug=seed.category_slug
on conflict(slug) do update set title_ar=excluded.title_ar,title_en=excluded.title_en,short_description=excluded.short_description,category_id=excluded.category_id,engine_type=excluded.engine_type,input_schema=excluded.input_schema,output_schema=excluded.output_schema,runtime_config=excluded.runtime_config,pricing_mode=excluded.pricing_mode,fixed_points=excluded.fixed_points,minimum_points=excluded.minimum_points,requires_auth=excluded.requires_auth,is_featured=excluded.is_featured,is_active=excluded.is_active,sort_order=excluded.sort_order,seo_title=excluded.seo_title,seo_description=excluded.seo_description,updated_at=now();
insert into public.tool_translations(tool_id,locale_id,title,short_description,seo_title,seo_description,prompt_template_override)
select tool.id,locale.id,case when locale.code='ar' then seed.title_ar else seed.title_en end,case when locale.code='ar' then seed.description_ar else seed.description_en end,case when locale.code='ar' then seed.title_ar else seed.title_en end,case when locale.code='ar' then seed.description_ar else seed.description_en end,null from wave4_productivity_tools_seed seed join public.tools tool on tool.slug=seed.slug join public.locales locale on locale.code in('ar','en')
on conflict(tool_id,locale_id) do update set title=excluded.title,short_description=excluded.short_description,seo_title=excluded.seo_title,seo_description=excluded.seo_description,prompt_template_override=null,updated_at=now();
insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select tool.id,locale.id,field.value->>'key',field.value->>'label',nullif(field.value->>'placeholder',''),nullif(field.value->>'helpText',''),field.value->'options' from wave4_productivity_tools_seed seed join public.tools tool on tool.slug=seed.slug join public.locales locale on locale.code in('ar','en') cross join lateral jsonb_array_elements(case when locale.code='ar' then seed.input_fields else seed.english_fields end) field(value)
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,placeholder=excluded.placeholder,help_text=excluded.help_text,options=excluded.options,updated_at=now();
insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select tool.id,locale.id,'__submit__',case when locale.code='ar' then seed.submit_ar else seed.submit_en end,null,null,null from wave4_productivity_tools_seed seed join public.tools tool on tool.slug=seed.slug join public.locales locale on locale.code in('ar','en')
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,placeholder=null,help_text=null,options=null,updated_at=now();
commit;
