-- Wave 8: 50 staged non-AI formula tools.
select public._wave8_upsert_formula_tools('web-tools',$tools$
[
{"slug":"requests-per-second-calculator","title_ar":"حاسبة الطلبات في الثانية","title_en":"Requests per Second Calculator","expression":"requests / seconds","fields":[{"key":"requests","ar":"عدد الطلبات","en":"Requests","min":0},{"key":"seconds","ar":"الثواني","en":"Seconds","min":0.000001}],"sort_order":28001},
{"slug":"successful-request-rate-calculator","title_ar":"حاسبة معدل الطلبات الناجحة","title_en":"Successful Request Rate Calculator","expression":"successful_requests / total_requests * 100","fields":[{"key":"successful_requests","ar":"الطلبات الناجحة","en":"Successful requests","min":0},{"key":"total_requests","ar":"إجمالي الطلبات","en":"Total requests","min":0.000001}],"sort_order":28002},
{"slug":"api-throughput-per-minute-calculator","title_ar":"حاسبة إنتاجية API بالدقيقة","title_en":"API Throughput per Minute Calculator","expression":"requests / minutes","fields":[{"key":"requests","ar":"عدد الطلبات","en":"Requests","min":0},{"key":"minutes","ar":"الدقائق","en":"Minutes","min":0.000001}],"sort_order":28003},
{"slug":"bandwidth-per-user-calculator","title_ar":"حاسبة النطاق الترددي لكل مستخدم","title_en":"Bandwidth per User Calculator","expression":"bandwidth_gb / users","fields":[{"key":"bandwidth_gb","ar":"النطاق الترددي GB","en":"Bandwidth GB","min":0},{"key":"users","ar":"عدد المستخدمين","en":"Users","min":0.000001}],"sort_order":28004},
{"slug":"pageviews-per-session-calculator","title_ar":"حاسبة مشاهدات الصفحات لكل جلسة","title_en":"Pageviews per Session Calculator","expression":"pageviews / sessions","fields":[{"key":"pageviews","ar":"مشاهدات الصفحات","en":"Pageviews","min":0},{"key":"sessions","ar":"الجلسات","en":"Sessions","min":0.000001}],"sort_order":28005},
{"slug":"server-cost-per-request-calculator","title_ar":"حاسبة تكلفة الخادم لكل طلب","title_en":"Server Cost per Request Calculator","expression":"server_cost / requests","fields":[{"key":"server_cost","ar":"تكلفة الخادم","en":"Server cost","min":0},{"key":"requests","ar":"عدد الطلبات","en":"Requests","min":0.000001}],"sort_order":28006},
{"slug":"cdn-offload-rate-calculator","title_ar":"حاسبة نسبة تخفيف الحمل عبر CDN","title_en":"CDN Offload Rate Calculator","expression":"cdn_requests / total_requests * 100","fields":[{"key":"cdn_requests","ar":"طلبات CDN","en":"CDN requests","min":0},{"key":"total_requests","ar":"إجمالي الطلبات","en":"Total requests","min":0.000001}],"sort_order":28007},
{"slug":"average-payload-size-calculator","title_ar":"حاسبة متوسط حجم الاستجابة","title_en":"Average Payload Size Calculator","expression":"total_payload_mb / requests","fields":[{"key":"total_payload_mb","ar":"إجمالي البيانات MB","en":"Total payload MB","min":0},{"key":"requests","ar":"عدد الطلبات","en":"Requests","min":0.000001}],"sort_order":28008},
{"slug":"web-availability-minutes-calculator","title_ar":"حاسبة دقائق توفر الموقع","title_en":"Web Availability Minutes Calculator","expression":"total_minutes * availability_rate / 100","fields":[{"key":"total_minutes","ar":"إجمالي الدقائق","en":"Total minutes","min":0},{"key":"availability_rate","ar":"نسبة التوفر","en":"Availability rate","min":0,"max":100}],"sort_order":28009},
{"slug":"latency-improvement-calculator","title_ar":"حاسبة تحسن زمن الاستجابة","title_en":"Latency Improvement Calculator","expression":"(old_latency - new_latency) / old_latency * 100","fields":[{"key":"old_latency","ar":"زمن الاستجابة السابق","en":"Old latency","min":0.000001},{"key":"new_latency","ar":"زمن الاستجابة الجديد","en":"New latency","min":0}],"sort_order":28010}
]$tools$::jsonb);

select public._wave8_upsert_formula_tools('education-tools',$tools$
[
{"slug":"study-plan-hours-calculator","title_ar":"حاسبة ساعات خطة الدراسة","title_en":"Study Plan Hours Calculator","expression":"subjects * hours_per_subject","fields":[{"key":"subjects","ar":"عدد المواد","en":"Subjects","min":0},{"key":"hours_per_subject","ar":"الساعات لكل مادة","en":"Hours per subject","min":0}],"sort_order":28101},
{"slug":"quiz-average-calculator","title_ar":"حاسبة متوسط الاختبارات القصيرة","title_en":"Quiz Average Calculator","expression":"(quiz_1 + quiz_2 + quiz_3 + quiz_4) / 4","fields":[{"key":"quiz_1","ar":"الاختبار 1","en":"Quiz 1","min":0},{"key":"quiz_2","ar":"الاختبار 2","en":"Quiz 2","min":0},{"key":"quiz_3","ar":"الاختبار 3","en":"Quiz 3","min":0},{"key":"quiz_4","ar":"الاختبار 4","en":"Quiz 4","min":0}],"sort_order":28102},
{"slug":"weighted-assignment-score-calculator","title_ar":"حاسبة درجة الواجب الموزونة","title_en":"Weighted Assignment Score Calculator","expression":"score * weight / 100","fields":[{"key":"score","ar":"الدرجة","en":"Score","min":0},{"key":"weight","ar":"الوزن %","en":"Weight %","min":0,"max":100}],"sort_order":28103},
{"slug":"semester-credit-load-calculator","title_ar":"حاسبة العبء الدراسي للفصل","title_en":"Semester Credit Load Calculator","expression":"course_1 + course_2 + course_3 + course_4 + course_5","fields":[{"key":"course_1","ar":"ساعات المقرر 1","en":"Course 1 credits","min":0},{"key":"course_2","ar":"ساعات المقرر 2","en":"Course 2 credits","min":0},{"key":"course_3","ar":"ساعات المقرر 3","en":"Course 3 credits","min":0},{"key":"course_4","ar":"ساعات المقرر 4","en":"Course 4 credits","min":0},{"key":"course_5","ar":"ساعات المقرر 5","en":"Course 5 credits","min":0}],"sort_order":28104},
{"slug":"course-completion-rate-calculator","title_ar":"حاسبة نسبة إكمال المقرر","title_en":"Course Completion Rate Calculator","expression":"completed_units / total_units * 100","fields":[{"key":"completed_units","ar":"الوحدات المكتملة","en":"Completed units","min":0},{"key":"total_units","ar":"إجمالي الوحدات","en":"Total units","min":0.000001}],"sort_order":28105},
{"slug":"practice-question-accuracy-calculator","title_ar":"حاسبة دقة أسئلة التدريب","title_en":"Practice Question Accuracy Calculator","expression":"correct_answers / attempted_questions * 100","fields":[{"key":"correct_answers","ar":"الإجابات الصحيحة","en":"Correct answers","min":0},{"key":"attempted_questions","ar":"الأسئلة المحلولة","en":"Attempted questions","min":0.000001}],"sort_order":28106},
{"slug":"study-session-efficiency-calculator","title_ar":"حاسبة كفاءة جلسة الدراسة","title_en":"Study Session Efficiency Calculator","expression":"focused_minutes / study_minutes * 100","fields":[{"key":"focused_minutes","ar":"دقائق التركيز","en":"Focused minutes","min":0},{"key":"study_minutes","ar":"دقائق الدراسة","en":"Study minutes","min":0.000001}],"sort_order":28107},
{"slug":"reading-pages-per-day-calculator","title_ar":"حاسبة صفحات القراءة يوميًا","title_en":"Reading Pages per Day Calculator","expression":"pages / days","fields":[{"key":"pages","ar":"عدد الصفحات","en":"Pages","min":0},{"key":"days","ar":"الأيام","en":"Days","min":0.000001}],"sort_order":28108},
{"slug":"exam-score-gap-calculator","title_ar":"حاسبة الفارق عن درجة الاختبار المستهدفة","title_en":"Exam Score Gap Calculator","expression":"target_score - current_score","fields":[{"key":"target_score","ar":"الدرجة المستهدفة","en":"Target score","min":0},{"key":"current_score","ar":"الدرجة الحالية","en":"Current score","min":0}],"sort_order":28109},
{"slug":"grade-point-contribution-calculator","title_ar":"حاسبة مساهمة المقرر في النقاط","title_en":"Grade Point Contribution Calculator","expression":"grade_points * credit_hours","fields":[{"key":"grade_points","ar":"نقاط التقدير","en":"Grade points","min":0},{"key":"credit_hours","ar":"الساعات المعتمدة","en":"Credit hours","min":0}],"sort_order":28110}
]$tools$::jsonb);

select public._wave8_upsert_formula_tools('employment-tools',$tools$
[
{"slug":"annual-overtime-income-calculator","title_ar":"حاسبة دخل العمل الإضافي السنوي","title_en":"Annual Overtime Income Calculator","expression":"overtime_hours_per_month * overtime_rate * 12","fields":[{"key":"overtime_hours_per_month","ar":"ساعات الإضافي شهريًا","en":"Overtime hours per month","min":0},{"key":"overtime_rate","ar":"أجر ساعة الإضافي","en":"Overtime hourly rate","min":0}],"sort_order":28201},
{"slug":"weekly-wage-calculator","title_ar":"حاسبة الأجر الأسبوعي","title_en":"Weekly Wage Calculator","expression":"hourly_rate * hours_per_week","fields":[{"key":"hourly_rate","ar":"أجر الساعة","en":"Hourly rate","min":0},{"key":"hours_per_week","ar":"ساعات العمل أسبوعيًا","en":"Hours per week","min":0}],"sort_order":28202},
{"slug":"monthly-hours-worked-calculator","title_ar":"حاسبة ساعات العمل الشهرية","title_en":"Monthly Hours Worked Calculator","expression":"hours_per_day * work_days","fields":[{"key":"hours_per_day","ar":"ساعات العمل يوميًا","en":"Hours per day","min":0},{"key":"work_days","ar":"أيام العمل بالشهر","en":"Work days","min":0}],"sort_order":28203},
{"slug":"salary-per-working-day-calculator","title_ar":"حاسبة الراتب لكل يوم عمل","title_en":"Salary per Working Day Calculator","expression":"monthly_salary / work_days","fields":[{"key":"monthly_salary","ar":"الراتب الشهري","en":"Monthly salary","min":0},{"key":"work_days","ar":"أيام العمل","en":"Work days","min":0.000001}],"sort_order":28204},
{"slug":"benefits-percentage-calculator","title_ar":"حاسبة نسبة المزايا من الراتب","title_en":"Benefits Percentage Calculator","expression":"benefits_value / salary * 100","fields":[{"key":"benefits_value","ar":"قيمة المزايا","en":"Benefits value","min":0},{"key":"salary","ar":"الراتب","en":"Salary","min":0.000001}],"sort_order":28205},
{"slug":"commission-share-of-income-calculator","title_ar":"حاسبة نسبة العمولة من الدخل","title_en":"Commission Share of Income Calculator","expression":"commission_income / total_income * 100","fields":[{"key":"commission_income","ar":"دخل العمولة","en":"Commission income","min":0},{"key":"total_income","ar":"إجمالي الدخل","en":"Total income","min":0.000001}],"sort_order":28206},
{"slug":"salary-deduction-rate-calculator","title_ar":"حاسبة نسبة الاستقطاعات من الراتب","title_en":"Salary Deduction Rate Calculator","expression":"deductions / gross_salary * 100","fields":[{"key":"deductions","ar":"الاستقطاعات","en":"Deductions","min":0},{"key":"gross_salary","ar":"الراتب الإجمالي","en":"Gross salary","min":0.000001}],"sort_order":28207},
{"slug":"annual-bonus-percentage-calculator","title_ar":"حاسبة نسبة المكافأة السنوية","title_en":"Annual Bonus Percentage Calculator","expression":"annual_bonus / annual_salary * 100","fields":[{"key":"annual_bonus","ar":"المكافأة السنوية","en":"Annual bonus","min":0},{"key":"annual_salary","ar":"الراتب السنوي","en":"Annual salary","min":0.000001}],"sort_order":28208},
{"slug":"work-hours-per-month-calculator","title_ar":"حاسبة ساعات العمل في الشهر","title_en":"Work Hours per Month Calculator","expression":"weekly_hours * 52 / 12","fields":[{"key":"weekly_hours","ar":"ساعات العمل الأسبوعية","en":"Weekly hours","min":0}],"sort_order":28209},
{"slug":"effective-pay-per-hour-calculator","title_ar":"حاسبة الأجر الفعلي لكل ساعة","title_en":"Effective Pay per Hour Calculator","expression":"total_pay / total_hours","fields":[{"key":"total_pay","ar":"إجمالي الأجر","en":"Total pay","min":0},{"key":"total_hours","ar":"إجمالي الساعات","en":"Total hours","min":0.000001}],"sort_order":28210}
]$tools$::jsonb);

select public._wave8_upsert_formula_tools('general-tools',$tools$
[
{"slug":"percent-difference-calculator","title_ar":"حاسبة الفرق النسبي بين قيمتين","title_en":"Percent Difference Calculator","expression":"abs(first_value - second_value) / ((first_value + second_value) / 2) * 100","fields":[{"key":"first_value","ar":"القيمة الأولى","en":"First value","min":0},{"key":"second_value","ar":"القيمة الثانية","en":"Second value","min":0}],"sort_order":28301},
{"slug":"fraction-to-percentage-calculator","title_ar":"حاسبة تحويل الكسر إلى نسبة مئوية","title_en":"Fraction to Percentage Calculator","expression":"numerator / denominator * 100","fields":[{"key":"numerator","ar":"البسط","en":"Numerator"},{"key":"denominator","ar":"المقام","en":"Denominator","min":0.000001}],"sort_order":28302},
{"slug":"cross-multiplication-value-calculator","title_ar":"حاسبة القيمة بالتناسب المتقاطع","title_en":"Cross Multiplication Value Calculator","expression":"b * c / a","fields":[{"key":"a","ar":"القيمة A","en":"Value A","min":0.000001},{"key":"b","ar":"القيمة B","en":"Value B"},{"key":"c","ar":"القيمة C","en":"Value C"}],"sort_order":28303},
{"slug":"rate-per-thousand-calculator","title_ar":"حاسبة المعدل لكل ألف","title_en":"Rate per Thousand Calculator","expression":"events / population * 1000","fields":[{"key":"events","ar":"عدد الحالات","en":"Events","min":0},{"key":"population","ar":"الإجمالي","en":"Population","min":0.000001}],"sort_order":28304},
{"slug":"growth-multiplier-calculator","title_ar":"حاسبة معامل النمو","title_en":"Growth Multiplier Calculator","expression":"new_value / old_value","fields":[{"key":"new_value","ar":"القيمة الجديدة","en":"New value"},{"key":"old_value","ar":"القيمة السابقة","en":"Old value","min":0.000001}],"sort_order":28305},
{"slug":"average-rate-calculator","title_ar":"حاسبة متوسط المعدل","title_en":"Average Rate Calculator","expression":"total_amount / periods","fields":[{"key":"total_amount","ar":"الإجمالي","en":"Total amount"},{"key":"periods","ar":"عدد الفترات","en":"Periods","min":0.000001}],"sort_order":28306},
{"slug":"cost-per-person-calculator","title_ar":"حاسبة التكلفة لكل شخص","title_en":"Cost per Person Calculator","expression":"total_cost / people","fields":[{"key":"total_cost","ar":"التكلفة الإجمالية","en":"Total cost","min":0},{"key":"people","ar":"عدد الأشخاص","en":"People","min":0.000001}],"sort_order":28307},
{"slug":"time-per-unit-calculator","title_ar":"حاسبة الوقت لكل وحدة","title_en":"Time per Unit Calculator","expression":"total_time / units","fields":[{"key":"total_time","ar":"الوقت الإجمالي","en":"Total time","min":0},{"key":"units","ar":"عدد الوحدات","en":"Units","min":0.000001}],"sort_order":28308},
{"slug":"units-per-hour-calculator","title_ar":"حاسبة الوحدات في الساعة","title_en":"Units per Hour Calculator","expression":"units / hours","fields":[{"key":"units","ar":"عدد الوحدات","en":"Units","min":0},{"key":"hours","ar":"الساعات","en":"Hours","min":0.000001}],"sort_order":28309},
{"slug":"remaining-percentage-calculator","title_ar":"حاسبة النسبة المتبقية","title_en":"Remaining Percentage Calculator","expression":"remaining / total * 100","fields":[{"key":"remaining","ar":"المتبقي","en":"Remaining","min":0},{"key":"total","ar":"الإجمالي","en":"Total","min":0.000001}],"sort_order":28310}
]$tools$::jsonb);

select public._wave8_upsert_formula_tools('marketing-tools',$tools$
[
{"slug":"lead-cost-calculator","title_ar":"حاسبة تكلفة العميل المحتمل","title_en":"Lead Cost Calculator","expression":"marketing_spend / leads","fields":[{"key":"marketing_spend","ar":"الإنفاق التسويقي","en":"Marketing spend","min":0},{"key":"leads","ar":"العملاء المحتملون","en":"Leads","min":0.000001}],"sort_order":28401},
{"slug":"email-open-rate-calculator","title_ar":"حاسبة معدل فتح البريد","title_en":"Email Open Rate Calculator","expression":"opens / delivered * 100","fields":[{"key":"opens","ar":"مرات الفتح","en":"Opens","min":0},{"key":"delivered","ar":"الرسائل المسلمة","en":"Delivered emails","min":0.000001}],"sort_order":28402},
{"slug":"email-delivery-rate-calculator","title_ar":"حاسبة معدل تسليم البريد","title_en":"Email Delivery Rate Calculator","expression":"delivered / sent * 100","fields":[{"key":"delivered","ar":"الرسائل المسلمة","en":"Delivered emails","min":0},{"key":"sent","ar":"الرسائل المرسلة","en":"Sent emails","min":0.000001}],"sort_order":28403},
{"slug":"email-bounce-rate-calculator","title_ar":"حاسبة معدل ارتداد البريد","title_en":"Email Bounce Rate Calculator","expression":"bounced / sent * 100","fields":[{"key":"bounced","ar":"الرسائل المرتدة","en":"Bounced emails","min":0},{"key":"sent","ar":"الرسائل المرسلة","en":"Sent emails","min":0.000001}],"sort_order":28404},
{"slug":"campaign-revenue-per-lead-calculator","title_ar":"حاسبة إيراد الحملة لكل عميل محتمل","title_en":"Campaign Revenue per Lead Calculator","expression":"campaign_revenue / leads","fields":[{"key":"campaign_revenue","ar":"إيراد الحملة","en":"Campaign revenue","min":0},{"key":"leads","ar":"العملاء المحتملون","en":"Leads","min":0.000001}],"sort_order":28405},
{"slug":"cost-per-qualified-lead-calculator","title_ar":"حاسبة تكلفة العميل المحتمل المؤهل","title_en":"Cost per Qualified Lead Calculator","expression":"marketing_spend / qualified_leads","fields":[{"key":"marketing_spend","ar":"الإنفاق التسويقي","en":"Marketing spend","min":0},{"key":"qualified_leads","ar":"العملاء المحتملون المؤهلون","en":"Qualified leads","min":0.000001}],"sort_order":28406},
{"slug":"marketing-revenue-share-calculator","title_ar":"حاسبة نسبة الإيراد المنسوب للتسويق","title_en":"Marketing Revenue Share Calculator","expression":"marketing_revenue / total_revenue * 100","fields":[{"key":"marketing_revenue","ar":"الإيراد المنسوب للتسويق","en":"Marketing-attributed revenue","min":0},{"key":"total_revenue","ar":"إجمالي الإيراد","en":"Total revenue","min":0.000001}],"sort_order":28407},
{"slug":"campaign-profit-calculator","title_ar":"حاسبة ربح الحملة","title_en":"Campaign Profit Calculator","expression":"campaign_revenue - campaign_cost","fields":[{"key":"campaign_revenue","ar":"إيراد الحملة","en":"Campaign revenue","min":0},{"key":"campaign_cost","ar":"تكلفة الحملة","en":"Campaign cost","min":0}],"sort_order":28408},
{"slug":"campaign-profit-margin-calculator","title_ar":"حاسبة هامش ربح الحملة","title_en":"Campaign Profit Margin Calculator","expression":"(campaign_revenue - campaign_cost) / campaign_revenue * 100","fields":[{"key":"campaign_revenue","ar":"إيراد الحملة","en":"Campaign revenue","min":0.000001},{"key":"campaign_cost","ar":"تكلفة الحملة","en":"Campaign cost","min":0}],"sort_order":28409},
{"slug":"landing-page-conversion-value-calculator","title_ar":"حاسبة قيمة تحويل صفحة الهبوط","title_en":"Landing Page Conversion Value Calculator","expression":"conversions * value_per_conversion","fields":[{"key":"conversions","ar":"عدد التحويلات","en":"Conversions","min":0},{"key":"value_per_conversion","ar":"قيمة التحويل الواحد","en":"Value per conversion","min":0}],"sort_order":28410}
]$tools$::jsonb);
