-- Web Empire — Non-AI catalog growth wave 4 (productivity-tools)
-- GitHub staging only. 10 deterministic bilingual formula tools.
begin;
create temporary table w4_productivity_tools(
 slug text primary key,title_ar text,title_en text,description_ar text,description_en text,
 runtime_config jsonb,schema_ar jsonb,schema_en jsonb,sort_order integer
) on commit drop;
insert into w4_productivity_tools values
('interruption-rate-calculator','حاسبة معدل المقاطعات','Interruption Rate Calculator','احسب متوسط عدد المقاطعات لكل ساعة عمل.','Calculate average interruptions per work hour.','{"expression":"interruptions / work_hours","outputUnitAr":" مقاطعة/ساعة","outputUnitEn":" interruptions/hour","resultLabelAr":"معدل المقاطعات","resultLabelEn":"Interruption Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"interruptions","label":"عدد المقاطعات","type":"number","required":true,"step":0.01,"min":0},{"key":"work_hours","label":"ساعات العمل","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"interruptions","label":"Interruptions","type":"number","required":true,"step":0.01,"min":0},{"key":"work_hours","label":"Work hours","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10101),
('deep-work-share-calculator','حاسبة نسبة العمل العميق','Deep Work Share Calculator','احسب نسبة وقت العمل المخصص للتركيز العميق.','Calculate the share of work time spent in deep focus.','{"expression":"deep_work_hours / total_work_hours * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة العمل العميق","resultLabelEn":"Deep Work Share","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"deep_work_hours","label":"ساعات العمل العميق","type":"number","required":true,"step":0.01,"min":0},{"key":"total_work_hours","label":"إجمالي ساعات العمل","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"deep_work_hours","label":"Deep work hours","type":"number","required":true,"step":0.01,"min":0},{"key":"total_work_hours","label":"Total work hours","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10102),
('admin-time-share-calculator','حاسبة نسبة الوقت الإداري','Administrative Time Share Calculator','احسب نسبة وقت العمل المستهلك في المهام الإدارية.','Calculate the share of work time spent on administrative tasks.','{"expression":"admin_hours / total_work_hours * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة الوقت الإداري","resultLabelEn":"Administrative Time Share","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"admin_hours","label":"الساعات الإدارية","type":"number","required":true,"step":0.01,"min":0},{"key":"total_work_hours","label":"إجمالي ساعات العمل","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"admin_hours","label":"Admin hours","type":"number","required":true,"step":0.01,"min":0},{"key":"total_work_hours","label":"Total work hours","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10103),
('task-estimation-error-calculator','حاسبة خطأ تقدير المهمة','Task Estimation Error Calculator','قارن الوقت الفعلي للمهمة بالوقت المقدر كنسبة مئوية.','Compare actual task time with estimated time as a percentage.','{"expression":"(actual_hours - estimated_hours) / estimated_hours * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"خطأ تقدير المهمة","resultLabelEn":"Task Estimation Error","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"actual_hours","label":"الساعات الفعلية","type":"number","required":true,"step":0.01,"min":0},{"key":"estimated_hours","label":"الساعات المقدرة","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"actual_hours","label":"Actual hours","type":"number","required":true,"step":0.01,"min":0},{"key":"estimated_hours","label":"Estimated hours","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10104),
('planned-output-attainment-calculator','حاسبة تحقيق الإنتاج المخطط','Planned Output Attainment Calculator','احسب نسبة الإنجاز الفعلي مقارنة بالمخرجات المخططة.','Calculate actual output as a percentage of planned output.','{"expression":"actual_output / planned_output * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"تحقيق الإنتاج المخطط","resultLabelEn":"Planned Output Attainment","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"actual_output","label":"المخرجات الفعلية","type":"number","required":true,"step":0.01,"min":0},{"key":"planned_output","label":"المخرجات المخططة","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"actual_output","label":"Actual output","type":"number","required":true,"step":0.01,"min":0},{"key":"planned_output","label":"Planned output","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10105),
('backlog-burn-rate-calculator','حاسبة تصفية قائمة المهام','Backlog Burn Rate Calculator','احسب نسبة المهام التي تمت تصفيتها من القائمة المتراكمة.','Calculate the percentage of backlog items completed.','{"expression":"completed_items / backlog_items * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"تصفية قائمة المهام","resultLabelEn":"Backlog Burn Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"completed_items","label":"العناصر المنجزة","type":"number","required":true,"step":0.01,"min":0},{"key":"backlog_items","label":"عناصر القائمة","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"completed_items","label":"Completed items","type":"number","required":true,"step":0.01,"min":0},{"key":"backlog_items","label":"Backlog items","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10106),
('weekly-focus-hours-calculator','حاسبة ساعات التركيز الأسبوعية','Weekly Focus Hours Calculator','حوّل دقائق التركيز اليومية إلى إجمالي ساعات أسبوعية.','Convert daily focus minutes into weekly focus hours.','{"expression":"focus_minutes_per_day * days / 60","outputUnitAr":" ساعة","outputUnitEn":" hours","resultLabelAr":"ساعات التركيز الأسبوعية","resultLabelEn":"Weekly Focus Hours","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"focus_minutes_per_day","label":"دقائق التركيز يوميًا","type":"number","required":true,"step":0.01,"min":0},{"key":"days","label":"عدد الأيام","type":"number","required":true,"step":0.01,"min":0}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"focus_minutes_per_day","label":"Focus minutes per day","type":"number","required":true,"step":0.01,"min":0},{"key":"days","label":"Days","type":"number","required":true,"step":0.01,"min":0}],"submitLabel":"Calculate"}'::jsonb,10107),
('context-switch-cost-calculator','حاسبة تكلفة تبديل السياق','Context Switch Cost Calculator','قدّر الساعات المهدرة أسبوعيًا بسبب تبديل المهام.','Estimate hours lost to context switching.','{"expression":"switches * minutes_per_switch / 60","outputUnitAr":" ساعة","outputUnitEn":" hours","resultLabelAr":"تكلفة تبديل السياق","resultLabelEn":"Context Switch Cost","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"switches","label":"مرات تبديل المهام","type":"number","required":true,"step":0.01,"min":0},{"key":"minutes_per_switch","label":"الدقائق لكل تبديل","type":"number","required":true,"step":0.01,"min":0}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"switches","label":"Task switches","type":"number","required":true,"step":0.01,"min":0},{"key":"minutes_per_switch","label":"Minutes per switch","type":"number","required":true,"step":0.01,"min":0}],"submitLabel":"Calculate"}'::jsonb,10108),
('monthly-routine-time-saved-calculator','حاسبة الوقت الموفر شهريًا','Monthly Routine Time Saved Calculator','احسب الساعات الشهرية الموفرة من إجراء متكرر.','Calculate monthly hours saved by a repeated improvement.','{"expression":"monthly_runs * minutes_saved_per_run / 60","outputUnitAr":" ساعة","outputUnitEn":" hours","resultLabelAr":"الوقت الموفر شهريًا","resultLabelEn":"Monthly Routine Time Saved","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"monthly_runs","label":"مرات التنفيذ شهريًا","type":"number","required":true,"step":0.01,"min":0},{"key":"minutes_saved_per_run","label":"الدقائق الموفرة لكل مرة","type":"number","required":true,"step":0.01,"min":0}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"monthly_runs","label":"Monthly runs","type":"number","required":true,"step":0.01,"min":0},{"key":"minutes_saved_per_run","label":"Minutes saved per run","type":"number","required":true,"step":0.01,"min":0}],"submitLabel":"Calculate"}'::jsonb,10109),
('delegation-rate-calculator','حاسبة نسبة التفويض','Delegation Rate Calculator','احسب نسبة ساعات العمل التي تم تفويضها للآخرين.','Calculate the percentage of work hours delegated.','{"expression":"delegated_hours / total_hours * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة التفويض","resultLabelEn":"Delegation Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"delegated_hours","label":"الساعات المفوضة","type":"number","required":true,"step":0.01,"min":0},{"key":"total_hours","label":"إجمالي الساعات","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"delegated_hours","label":"Delegated hours","type":"number","required":true,"step":0.01,"min":0},{"key":"total_hours","label":"Total hours","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10110);
insert into public.tools(slug,title_ar,title_en,short_description,category_id,engine_type,input_schema,output_schema,runtime_config,provider_strategy,model_alias,prompt_template,pricing_mode,fixed_points,minimum_points,cost_multiplier,requires_auth,is_featured,is_active,sort_order,seo_title,seo_description)
select s.slug,s.title_ar,s.title_en,s.description_ar,c.id,'formula'::public.tool_engine_type,s.schema_ar,'{}'::jsonb,s.runtime_config,'primary_with_fallback'::public.provider_strategy_type,null,null,'free'::public.pricing_mode_type,0,0,1,false,false,true,s.sort_order,s.title_ar,s.description_ar
from w4_productivity_tools s join public.categories c on c.slug='productivity-tools'
on conflict(slug) do update set title_ar=excluded.title_ar,title_en=excluded.title_en,short_description=excluded.short_description,category_id=excluded.category_id,engine_type=excluded.engine_type,input_schema=excluded.input_schema,output_schema=excluded.output_schema,runtime_config=excluded.runtime_config,model_alias=null,prompt_template=null,pricing_mode='free'::public.pricing_mode_type,fixed_points=0,minimum_points=0,cost_multiplier=1,requires_auth=false,is_featured=false,is_active=true,sort_order=excluded.sort_order,seo_title=excluded.seo_title,seo_description=excluded.seo_description,updated_at=now();
insert into public.tool_translations(tool_id,locale_id,title,short_description,seo_title,seo_description,prompt_template_override)
select t.id,l.id,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,null
from w4_productivity_tools s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id) do update set title=excluded.title,short_description=excluded.short_description,seo_title=excluded.seo_title,seo_description=excluded.seo_description,prompt_template_override=null,updated_at=now();
insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,f->>'key',f->>'label',nullif(f->>'placeholder',''),nullif(f->>'helpText',''),f->'options'
from w4_productivity_tools s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
cross join lateral jsonb_array_elements(case when l.code='ar' then s.schema_ar->'fields' else s.schema_en->'fields' end) f
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,placeholder=excluded.placeholder,help_text=excluded.help_text,options=excluded.options,updated_at=now();
insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,'__submit__',case when l.code='ar' then s.schema_ar->>'submitLabel' else s.schema_en->>'submitLabel' end,null,null,null
from w4_productivity_tools s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,updated_at=now();
commit;
