-- Web Empire wave 14 — Ecommerce + Logistics (20 tools).
select public._wave14_upsert_formula_tools('ecommerce-tools',$json$[
{"slug":"ecommerce-net-revenue-after-fees-calculator","title_ar":"حاسبة صافي إيراد التجارة الإلكترونية بعد الرسوم","title_en":"Ecommerce Net Revenue after Fees Calculator","expression":"gross_revenue - platform_fees - payment_fees","fields":[{"key":"gross_revenue","ar":"الإيراد الإجمالي","en":"Gross revenue","min":0},{"key":"platform_fees","ar":"رسوم المنصة","en":"Platform fees","min":0},{"key":"payment_fees","ar":"رسوم الدفع","en":"Payment fees","min":0}],"sort_order":33601},
{"slug":"ecommerce-fee-cost-per-order-calculator","title_ar":"حاسبة رسوم المتجر لكل طلب","title_en":"Ecommerce Fee Cost per Order Calculator","expression":"total_fees / orders","fields":[{"key":"total_fees","ar":"إجمالي الرسوم","en":"Total fees","min":0},{"key":"orders","ar":"عدد الطلبات","en":"Orders","min":0.000001}],"sort_order":33602},
{"slug":"ecommerce-discount-cost-per-order-calculator","title_ar":"حاسبة تكلفة الخصومات لكل طلب","title_en":"Ecommerce Discount Cost per Order Calculator","expression":"discount_value / orders","fields":[{"key":"discount_value","ar":"قيمة الخصومات","en":"Discount value","min":0},{"key":"orders","ar":"عدد الطلبات","en":"Orders","min":0.000001}],"sort_order":33603},
{"slug":"ecommerce-refund-loss-per-order-calculator","title_ar":"حاسبة خسارة الاستردادات لكل طلب","title_en":"Ecommerce Refund Loss per Order Calculator","expression":"refund_loss / orders","fields":[{"key":"refund_loss","ar":"خسارة الاستردادات","en":"Refund loss","min":0},{"key":"orders","ar":"عدد الطلبات","en":"Orders","min":0.000001}],"sort_order":33604},
{"slug":"ecommerce-revenue-per-customer-calculator","title_ar":"حاسبة إيراد المتجر لكل عميل","title_en":"Ecommerce Revenue per Customer Calculator","expression":"revenue / customers","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"customers","ar":"عدد العملاء","en":"Customers","min":0.000001}],"sort_order":33605},
{"slug":"ecommerce-orders-per-day-calculator","title_ar":"حاسبة طلبات المتجر اليومية","title_en":"Ecommerce Orders per Day Calculator","expression":"orders / days","fields":[{"key":"orders","ar":"عدد الطلبات","en":"Orders","min":0},{"key":"days","ar":"عدد الأيام","en":"Days","min":0.000001}],"sort_order":33606},
{"slug":"ecommerce-units-per-customer-calculator","title_ar":"حاسبة الوحدات المباعة لكل عميل","title_en":"Ecommerce Units per Customer Calculator","expression":"units_sold / customers","fields":[{"key":"units_sold","ar":"الوحدات المباعة","en":"Units sold","min":0},{"key":"customers","ar":"عدد العملاء","en":"Customers","min":0.000001}],"sort_order":33607},
{"slug":"ecommerce-marketing-cost-share-calculator","title_ar":"حاسبة حصة التسويق من إيراد المتجر","title_en":"Ecommerce Marketing Cost Share Calculator","expression":"marketing_cost / revenue * 100","fields":[{"key":"marketing_cost","ar":"تكلفة التسويق","en":"Marketing cost","min":0},{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0.000001}],"sort_order":33608},
{"slug":"ecommerce-shipping-cost-share-calculator","title_ar":"حاسبة حصة الشحن من إيراد المتجر","title_en":"Ecommerce Shipping Cost Share Calculator","expression":"shipping_cost / revenue * 100","fields":[{"key":"shipping_cost","ar":"تكلفة الشحن","en":"Shipping cost","min":0},{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0.000001}],"sort_order":33609},
{"slug":"ecommerce-net-profit-per-order-calculator","title_ar":"حاسبة صافي ربح المتجر لكل طلب","title_en":"Ecommerce Net Profit per Order Calculator","expression":"net_profit / orders","fields":[{"key":"net_profit","ar":"صافي الربح","en":"Net profit","min":0},{"key":"orders","ar":"عدد الطلبات","en":"Orders","min":0.000001}],"sort_order":33610}
]$json$::jsonb);

select public._wave14_upsert_formula_tools('logistics-tools',$json$[
{"slug":"logistics-cost-per-ton-km-calculator","title_ar":"حاسبة تكلفة اللوجستيات لكل طن-كيلومتر","title_en":"Logistics Cost per Ton-Kilometer Calculator","expression":"total_cost / cargo_tons / distance_km","fields":[{"key":"total_cost","ar":"إجمالي التكلفة","en":"Total cost","min":0},{"key":"cargo_tons","ar":"وزن الحمولة بالطن","en":"Cargo tons","min":0.000001},{"key":"distance_km","ar":"المسافة كم","en":"Distance km","min":0.000001}],"sort_order":33701},
{"slug":"logistics-revenue-per-shipment-calculator","title_ar":"حاسبة إيراد اللوجستيات لكل شحنة","title_en":"Logistics Revenue per Shipment Calculator","expression":"revenue / shipments","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"shipments","ar":"عدد الشحنات","en":"Shipments","min":0.000001}],"sort_order":33702},
{"slug":"logistics-profit-per-shipment-calculator","title_ar":"حاسبة ربح اللوجستيات لكل شحنة","title_en":"Logistics Profit per Shipment Calculator","expression":"profit / shipments","fields":[{"key":"profit","ar":"الربح","en":"Profit","min":0},{"key":"shipments","ar":"عدد الشحنات","en":"Shipments","min":0.000001}],"sort_order":33703},
{"slug":"logistics-driver-cost-per-km-calculator","title_ar":"حاسبة تكلفة السائق لكل كيلومتر","title_en":"Logistics Driver Cost per Kilometer Calculator","expression":"driver_cost / distance_km","fields":[{"key":"driver_cost","ar":"تكلفة السائق","en":"Driver cost","min":0},{"key":"distance_km","ar":"المسافة كم","en":"Distance km","min":0.000001}],"sort_order":33704},
{"slug":"logistics-warehouse-cost-per-order-calculator","title_ar":"حاسبة تكلفة المستودع لكل طلب","title_en":"Logistics Warehouse Cost per Order Calculator","expression":"warehouse_cost / orders","fields":[{"key":"warehouse_cost","ar":"تكلفة المستودع","en":"Warehouse cost","min":0},{"key":"orders","ar":"عدد الطلبات","en":"Orders","min":0.000001}],"sort_order":33705},
{"slug":"logistics-picking-cost-per-item-calculator","title_ar":"حاسبة تكلفة التقاط المستودع لكل عنصر","title_en":"Logistics Picking Cost per Item Calculator","expression":"picking_cost / picked_items","fields":[{"key":"picking_cost","ar":"تكلفة الالتقاط","en":"Picking cost","min":0},{"key":"picked_items","ar":"العناصر الملتقطة","en":"Picked items","min":0.000001}],"sort_order":33706},
{"slug":"logistics-fuel-liters-per-100km-calculator","title_ar":"حاسبة استهلاك الوقود اللوجستي لكل 100 كم","title_en":"Logistics Fuel Liters per 100km Calculator","expression":"fuel_liters / distance_km * 100","fields":[{"key":"fuel_liters","ar":"الوقود باللتر","en":"Fuel liters","min":0},{"key":"distance_km","ar":"المسافة كم","en":"Distance km","min":0.000001}],"sort_order":33707},
{"slug":"logistics-delivery-hours-per-stop-calculator","title_ar":"حاسبة ساعات التوصيل لكل محطة","title_en":"Logistics Delivery Hours per Stop Calculator","expression":"delivery_hours / stops","fields":[{"key":"delivery_hours","ar":"ساعات التوصيل","en":"Delivery hours","min":0},{"key":"stops","ar":"عدد المحطات","en":"Stops","min":0.000001}],"sort_order":33708},
{"slug":"logistics-return-cost-share-calculator","title_ar":"حاسبة حصة تكلفة المرتجعات اللوجستية","title_en":"Logistics Return Cost Share Calculator","expression":"return_cost / total_logistics_cost * 100","fields":[{"key":"return_cost","ar":"تكلفة المرتجعات","en":"Return cost","min":0},{"key":"total_logistics_cost","ar":"إجمالي تكلفة اللوجستيات","en":"Total logistics cost","min":0.000001}],"sort_order":33709},
{"slug":"logistics-storage-cost-per-pallet-calculator","title_ar":"حاسبة تكلفة التخزين لكل منصة نقالة","title_en":"Logistics Storage Cost per Pallet Calculator","expression":"storage_cost / pallets","fields":[{"key":"storage_cost","ar":"تكلفة التخزين","en":"Storage cost","min":0},{"key":"pallets","ar":"عدد المنصات","en":"Pallets","min":0.000001}],"sort_order":33710}
]$json$::jsonb);
