-- Web Empire — Non-AI catalog growth wave 3 (date-time-tools)
begin;
create temporary table w3_seed(
 slug text primary key,title_ar text,title_en text,description_ar text,description_en text,
 runtime_config jsonb,schema_ar jsonb,schema_en jsonb,sort_order integer
) on commit drop;
insert into w3_seed values
('days-to-hours-calculator','تحويل الأيام إلى ساعات','Days to Hours Calculator','حوّل عدد الأيام إلى ساعات.','Convert days into hours.','{"expression":"days * 24","outputUnitAr":" ساعة","outputUnitEn":" hours","resultLabelAr":"الساعات","resultLabelEn":"Hours","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"days","type":"number","required":true,"min":0,"step":0.01,"label":"الأيام"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"days","type":"number","required":true,"min":0,"step":0.01,"label":"Days"}],"submitLabel":"Calculate"}'::jsonb,8201),
('hours-to-days-calculator','تحويل الساعات إلى أيام','Hours to Days Calculator','حوّل عدد الساعات إلى أيام.','Convert hours into days.','{"expression":"hours / 24","outputUnitAr":" يوم","outputUnitEn":" days","resultLabelAr":"الأيام","resultLabelEn":"Days","decimals":3,"showEquation":true}'::jsonb,'{"fields":[{"key":"hours","type":"number","required":true,"min":0,"step":0.01,"label":"الساعات"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"hours","type":"number","required":true,"min":0,"step":0.01,"label":"Hours"}],"submitLabel":"Calculate"}'::jsonb,8202),
('hours-to-seconds-calculator','تحويل الساعات إلى ثوانٍ','Hours to Seconds Calculator','حوّل الساعات إلى ثوانٍ.','Convert hours into seconds.','{"expression":"hours * 3600","outputUnitAr":" ثانية","outputUnitEn":" seconds","resultLabelAr":"الثواني","resultLabelEn":"Seconds","decimals":0,"showEquation":true}'::jsonb,'{"fields":[{"key":"hours","type":"number","required":true,"min":0,"step":0.01,"label":"الساعات"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"hours","type":"number","required":true,"min":0,"step":0.01,"label":"Hours"}],"submitLabel":"Calculate"}'::jsonb,8203),
('minutes-to-seconds-calculator','تحويل الدقائق إلى ثوانٍ','Minutes to Seconds Calculator','حوّل الدقائق إلى ثوانٍ.','Convert minutes into seconds.','{"expression":"minutes * 60","outputUnitAr":" ثانية","outputUnitEn":" seconds","resultLabelAr":"الثواني","resultLabelEn":"Seconds","decimals":0,"showEquation":true}'::jsonb,'{"fields":[{"key":"minutes","type":"number","required":true,"min":0,"step":0.01,"label":"الدقائق"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"minutes","type":"number","required":true,"min":0,"step":0.01,"label":"Minutes"}],"submitLabel":"Calculate"}'::jsonb,8204),
('weeks-to-days-calculator','تحويل الأسابيع إلى أيام','Weeks to Days Calculator','حوّل الأسابيع إلى أيام.','Convert weeks into days.','{"expression":"weeks * 7","outputUnitAr":" يوم","outputUnitEn":" days","resultLabelAr":"الأيام","resultLabelEn":"Days","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"weeks","type":"number","required":true,"min":0,"step":0.01,"label":"الأسابيع"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"weeks","type":"number","required":true,"min":0,"step":0.01,"label":"Weeks"}],"submitLabel":"Calculate"}'::jsonb,8205),
('months-to-weeks-estimate','تحويل الأشهر إلى أسابيع تقديريًا','Months to Weeks Estimate','حوّل الأشهر إلى أسابيع باستخدام متوسط 52 أسبوعًا في السنة.','Estimate weeks from months using 52 weeks per year.','{"expression":"months * 52 / 12","outputUnitAr":" أسبوع","outputUnitEn":" weeks","resultLabelAr":"الأسابيع التقديرية","resultLabelEn":"Estimated weeks","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"months","type":"number","required":true,"min":0,"step":0.01,"label":"الأشهر"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"months","type":"number","required":true,"min":0,"step":0.01,"label":"Months"}],"submitLabel":"Calculate"}'::jsonb,8206),
('annual-work-hours-calculator','حاسبة ساعات العمل السنوية','Annual Work Hours Calculator','قدّر ساعات العمل السنوية من الساعات الأسبوعية.','Estimate annual work hours from weekly hours.','{"expression":"weekly_hours * 52","outputUnitAr":" ساعة","outputUnitEn":" hours","resultLabelAr":"الساعات السنوية","resultLabelEn":"Annual hours","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"weekly_hours","type":"number","required":true,"min":0,"step":0.01,"label":"الساعات الأسبوعية"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"weekly_hours","type":"number","required":true,"min":0,"step":0.01,"label":"Weekly hours"}],"submitLabel":"Calculate"}'::jsonb,8207),
('net-shift-hours-calculator','حاسبة صافي ساعات الوردية','Net Shift Hours Calculator','احسب صافي ساعات الوردية بعد خصم وقت الاستراحة.','Calculate net shift hours after subtracting break time.','{"expression":"shift_hours - break_hours","outputUnitAr":" ساعة","outputUnitEn":" hours","resultLabelAr":"صافي ساعات الوردية","resultLabelEn":"Net shift hours","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"shift_hours","type":"number","required":true,"min":0,"step":0.01,"label":"مدة الوردية بالساعات"},{"key":"break_hours","type":"number","required":true,"min":0,"step":0.01,"label":"الاستراحة بالساعات"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"shift_hours","type":"number","required":true,"min":0,"step":0.01,"label":"Shift hours"},{"key":"break_hours","type":"number","required":true,"min":0,"step":0.01,"label":"Break hours"}],"submitLabel":"Calculate"}'::jsonb,8208),
('overtime-hours-calculator','حاسبة ساعات العمل الإضافي','Overtime Hours Calculator','احسب الساعات الإضافية بطرح الساعات القياسية من إجمالي الساعات.','Calculate overtime hours by subtracting standard hours from total hours.','{"expression":"total_hours - standard_hours","outputUnitAr":" ساعة","outputUnitEn":" hours","resultLabelAr":"الساعات الإضافية","resultLabelEn":"Overtime hours","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"total_hours","type":"number","required":true,"min":0,"step":0.01,"label":"إجمالي الساعات"},{"key":"standard_hours","type":"number","required":true,"min":0,"step":0.01,"label":"الساعات القياسية"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"total_hours","type":"number","required":true,"min":0,"step":0.01,"label":"Total hours"},{"key":"standard_hours","type":"number","required":true,"min":0,"step":0.01,"label":"Standard hours"}],"submitLabel":"Calculate"}'::jsonb,8209),
('time-utilization-calculator','حاسبة استغلال الوقت','Time Utilization Calculator','احسب نسبة الوقت المنتج من الوقت المتاح.','Calculate productive time as a percentage of available time.','{"expression":"productive_hours / available_hours * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة استغلال الوقت","resultLabelEn":"Time utilization","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"productive_hours","type":"number","required":true,"min":0,"step":0.01,"label":"الساعات المنتجة"},{"key":"available_hours","type":"number","required":true,"min":1e-06,"step":0.01,"label":"الساعات المتاحة"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"productive_hours","type":"number","required":true,"min":0,"step":0.01,"label":"Productive hours"},{"key":"available_hours","type":"number","required":true,"min":1e-06,"step":0.01,"label":"Available hours"}],"submitLabel":"Calculate"}'::jsonb,8210);

insert into public.tools(slug,title_ar,title_en,short_description,category_id,engine_type,input_schema,output_schema,runtime_config,provider_strategy,model_alias,prompt_template,pricing_mode,fixed_points,minimum_points,cost_multiplier,requires_auth,is_featured,is_active,sort_order,seo_title,seo_description)
select s.slug,s.title_ar,s.title_en,s.description_ar,c.id,'formula'::public.tool_engine_type,s.schema_ar,'{}'::jsonb,s.runtime_config,'primary_with_fallback'::public.provider_strategy_type,null,null,'free'::public.pricing_mode_type,0,0,1,false,false,true,s.sort_order,s.title_ar,s.description_ar
from w3_seed s join public.categories c on c.slug='date-time-tools'
on conflict(slug) do update set title_ar=excluded.title_ar,title_en=excluded.title_en,short_description=excluded.short_description,category_id=excluded.category_id,engine_type=excluded.engine_type,input_schema=excluded.input_schema,output_schema=excluded.output_schema,runtime_config=excluded.runtime_config,model_alias=null,prompt_template=null,pricing_mode='free'::public.pricing_mode_type,fixed_points=0,minimum_points=0,cost_multiplier=1,requires_auth=false,is_featured=false,is_active=true,sort_order=excluded.sort_order,seo_title=excluded.seo_title,seo_description=excluded.seo_description,updated_at=now();

insert into public.tool_translations(tool_id,locale_id,title,short_description,seo_title,seo_description,prompt_template_override)
select t.id,l.id,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,null
from w3_seed s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id) do update set title=excluded.title,short_description=excluded.short_description,seo_title=excluded.seo_title,seo_description=excluded.seo_description,prompt_template_override=null,updated_at=now();

insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,f->>'key',f->>'label',nullif(f->>'placeholder',''),nullif(f->>'helpText',''),f->'options'
from w3_seed s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
cross join lateral jsonb_array_elements(case when l.code='ar' then s.schema_ar->'fields' else s.schema_en->'fields' end) f
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,placeholder=excluded.placeholder,help_text=excluded.help_text,options=excluded.options,updated_at=now();

insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,'__submit__',case when l.code='ar' then s.schema_ar->>'submitLabel' else s.schema_en->>'submitLabel' end,null,null,null
from w3_seed s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,updated_at=now();
commit;
