-- Wave 8: second 50 staged non-AI formula tools.
select public._wave8_upsert_formula_tools('business-tools',$tools$
[
{"slug":"operating-margin-calculator","title_ar":"حاسبة هامش التشغيل","title_en":"Operating Margin Calculator","expression":"operating_income / revenue * 100","fields":[{"key":"operating_income","ar":"الدخل التشغيلي","en":"Operating income"},{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0.000001}],"sort_order":28501},
{"slug":"expense-ratio-calculator","title_ar":"حاسبة نسبة المصروفات","title_en":"Expense Ratio Calculator","expression":"expenses / revenue * 100","fields":[{"key":"expenses","ar":"المصروفات","en":"Expenses","min":0},{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0.000001}],"sort_order":28502},
{"slug":"revenue-growth-calculator","title_ar":"حاسبة نمو الإيرادات","title_en":"Revenue Growth Calculator","expression":"(current_revenue - previous_revenue) / previous_revenue * 100","fields":[{"key":"current_revenue","ar":"الإيراد الحالي","en":"Current revenue"},{"key":"previous_revenue","ar":"الإيراد السابق","en":"Previous revenue","min":0.000001}],"sort_order":28503},
{"slug":"operating-expense-per-customer-calculator","title_ar":"حاسبة المصروف التشغيلي لكل عميل","title_en":"Operating Expense per Customer Calculator","expression":"operating_expenses / customers","fields":[{"key":"operating_expenses","ar":"المصروفات التشغيلية","en":"Operating expenses","min":0},{"key":"customers","ar":"عدد العملاء","en":"Customers","min":0.000001}],"sort_order":28504},
{"slug":"profit-per-employee-calculator","title_ar":"حاسبة الربح لكل موظف","title_en":"Profit per Employee Calculator","expression":"net_profit / employees","fields":[{"key":"net_profit","ar":"صافي الربح","en":"Net profit"},{"key":"employees","ar":"عدد الموظفين","en":"Employees","min":0.000001}],"sort_order":28505},
{"slug":"fixed-cost-per-unit-calculator","title_ar":"حاسبة التكلفة الثابتة لكل وحدة","title_en":"Fixed Cost per Unit Calculator","expression":"fixed_costs / units","fields":[{"key":"fixed_costs","ar":"التكاليف الثابتة","en":"Fixed costs","min":0},{"key":"units","ar":"عدد الوحدات","en":"Units","min":0.000001}],"sort_order":28506},
{"slug":"variable-cost-ratio-calculator","title_ar":"حاسبة نسبة التكلفة المتغيرة","title_en":"Variable Cost Ratio Calculator","expression":"variable_costs / sales * 100","fields":[{"key":"variable_costs","ar":"التكاليف المتغيرة","en":"Variable costs","min":0},{"key":"sales","ar":"المبيعات","en":"Sales","min":0.000001}],"sort_order":28507},
{"slug":"working-capital-calculator","title_ar":"حاسبة رأس المال العامل","title_en":"Working Capital Calculator","expression":"current_assets - current_liabilities","fields":[{"key":"current_assets","ar":"الأصول المتداولة","en":"Current assets","min":0},{"key":"current_liabilities","ar":"الالتزامات المتداولة","en":"Current liabilities","min":0}],"sort_order":28508},
{"slug":"working-capital-ratio-calculator","title_ar":"حاسبة نسبة رأس المال العامل","title_en":"Working Capital Ratio Calculator","expression":"current_assets / current_liabilities","fields":[{"key":"current_assets","ar":"الأصول المتداولة","en":"Current assets","min":0},{"key":"current_liabilities","ar":"الالتزامات المتداولة","en":"Current liabilities","min":0.000001}],"sort_order":28509},
{"slug":"revenue-per-working-day-calculator","title_ar":"حاسبة الإيراد لكل يوم عمل","title_en":"Revenue per Working Day Calculator","expression":"revenue / working_days","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"working_days","ar":"أيام العمل","en":"Working days","min":0.000001}],"sort_order":28510}
]$tools$::jsonb);

select public._wave8_upsert_formula_tools('finance-tools',$tools$
[
{"slug":"monthly-interest-cost-calculator","title_ar":"حاسبة تكلفة الفائدة الشهرية","title_en":"Monthly Interest Cost Calculator","expression":"principal * annual_rate / 100 / 12","fields":[{"key":"principal","ar":"أصل المبلغ","en":"Principal","min":0},{"key":"annual_rate","ar":"النسبة السنوية %","en":"Annual rate %","min":0}],"sort_order":28601},
{"slug":"annual-interest-cost-calculator","title_ar":"حاسبة تكلفة الفائدة السنوية","title_en":"Annual Interest Cost Calculator","expression":"principal * annual_rate / 100","fields":[{"key":"principal","ar":"أصل المبلغ","en":"Principal","min":0},{"key":"annual_rate","ar":"النسبة السنوية %","en":"Annual rate %","min":0}],"sort_order":28602},
{"slug":"savings-growth-rate-calculator","title_ar":"حاسبة معدل نمو المدخرات","title_en":"Savings Growth Rate Calculator","expression":"(current_savings - previous_savings) / previous_savings * 100","fields":[{"key":"current_savings","ar":"المدخرات الحالية","en":"Current savings"},{"key":"previous_savings","ar":"المدخرات السابقة","en":"Previous savings","min":0.000001}],"sort_order":28603},
{"slug":"expense-to-income-ratio-calculator","title_ar":"حاسبة نسبة المصروفات إلى الدخل","title_en":"Expense to Income Ratio Calculator","expression":"monthly_expenses / monthly_income * 100","fields":[{"key":"monthly_expenses","ar":"المصروفات الشهرية","en":"Monthly expenses","min":0},{"key":"monthly_income","ar":"الدخل الشهري","en":"Monthly income","min":0.000001}],"sort_order":28604},
{"slug":"debt-payoff-months-calculator","title_ar":"حاسبة أشهر سداد الدين","title_en":"Debt Payoff Months Calculator","expression":"debt_balance / monthly_payment","fields":[{"key":"debt_balance","ar":"رصيد الدين","en":"Debt balance","min":0},{"key":"monthly_payment","ar":"الدفعة الشهرية","en":"Monthly payment","min":0.000001}],"sort_order":28605},
{"slug":"investment-gain-calculator","title_ar":"حاسبة ربح الاستثمار","title_en":"Investment Gain Calculator","expression":"ending_value - invested_amount","fields":[{"key":"ending_value","ar":"القيمة النهائية","en":"Ending value"},{"key":"invested_amount","ar":"المبلغ المستثمر","en":"Invested amount","min":0}],"sort_order":28606},
{"slug":"investment-return-per-year-calculator","title_ar":"حاسبة عائد الاستثمار السنوي البسيط","title_en":"Investment Return per Year Calculator","expression":"(ending_value - invested_amount) / invested_amount / years * 100","fields":[{"key":"ending_value","ar":"القيمة النهائية","en":"Ending value"},{"key":"invested_amount","ar":"المبلغ المستثمر","en":"Invested amount","min":0.000001},{"key":"years","ar":"عدد السنوات","en":"Years","min":0.000001}],"sort_order":28607},
{"slug":"monthly-investment-contribution-calculator","title_ar":"حاسبة المساهمة الاستثمارية الشهرية","title_en":"Monthly Investment Contribution Calculator","expression":"target_amount / months","fields":[{"key":"target_amount","ar":"المبلغ المستهدف","en":"Target amount","min":0},{"key":"months","ar":"عدد الأشهر","en":"Months","min":0.000001}],"sort_order":28608},
{"slug":"budget-allocation-percentage-calculator","title_ar":"حاسبة نسبة بند من الميزانية","title_en":"Budget Allocation Percentage Calculator","expression":"category_amount / total_budget * 100","fields":[{"key":"category_amount","ar":"قيمة البند","en":"Category amount","min":0},{"key":"total_budget","ar":"إجمالي الميزانية","en":"Total budget","min":0.000001}],"sort_order":28609},
{"slug":"monthly-cash-flow-calculator","title_ar":"حاسبة التدفق النقدي الشهري","title_en":"Monthly Cash Flow Calculator","expression":"monthly_income - monthly_expenses - debt_payments","fields":[{"key":"monthly_income","ar":"الدخل الشهري","en":"Monthly income"},{"key":"monthly_expenses","ar":"المصروفات الشهرية","en":"Monthly expenses","min":0},{"key":"debt_payments","ar":"دفعات الديون","en":"Debt payments","min":0}],"sort_order":28610}
]$tools$::jsonb);

select public._wave8_upsert_formula_tools('saudi-tools',$tools$
[
{"slug":"saudi-monthly-transport-allowance-calculator","title_ar":"حاسبة بدل النقل الشهري","title_en":"Saudi Monthly Transport Allowance Calculator","expression":"basic_salary * allowance_rate / 100","fields":[{"key":"basic_salary","ar":"الراتب الأساسي","en":"Basic salary","min":0},{"key":"allowance_rate","ar":"نسبة البدل %","en":"Allowance rate %","min":0}],"sort_order":28701},
{"slug":"saudi-annual-housing-allowance-calculator","title_ar":"حاسبة بدل السكن السنوي","title_en":"Saudi Annual Housing Allowance Calculator","expression":"monthly_housing_allowance * 12","fields":[{"key":"monthly_housing_allowance","ar":"بدل السكن الشهري","en":"Monthly housing allowance","min":0}],"sort_order":28702},
{"slug":"saudi-salary-plus-allowances-calculator","title_ar":"حاسبة الراتب مع البدلات","title_en":"Saudi Salary Plus Allowances Calculator","expression":"basic_salary + housing_allowance + transport_allowance + other_allowances","fields":[{"key":"basic_salary","ar":"الراتب الأساسي","en":"Basic salary","min":0},{"key":"housing_allowance","ar":"بدل السكن","en":"Housing allowance","min":0},{"key":"transport_allowance","ar":"بدل النقل","en":"Transport allowance","min":0},{"key":"other_allowances","ar":"بدلات أخرى","en":"Other allowances","min":0}],"sort_order":28703},
{"slug":"saudi-workday-hourly-rate-calculator","title_ar":"حاسبة أجر الساعة من يوم العمل","title_en":"Saudi Workday Hourly Rate Calculator","expression":"daily_wage / hours_per_day","fields":[{"key":"daily_wage","ar":"الأجر اليومي","en":"Daily wage","min":0},{"key":"hours_per_day","ar":"ساعات العمل يوميًا","en":"Hours per day","min":0.000001}],"sort_order":28704},
{"slug":"saudi-daily-commute-cost-calculator","title_ar":"حاسبة تكلفة التنقل اليومية","title_en":"Saudi Daily Commute Cost Calculator","expression":"distance_km / km_per_liter * fuel_price","fields":[{"key":"distance_km","ar":"المسافة اليومية كم","en":"Daily distance km","min":0},{"key":"km_per_liter","ar":"كم لكل لتر","en":"Km per liter","min":0.000001},{"key":"fuel_price","ar":"سعر الوقود لكل لتر","en":"Fuel price per liter","min":0}],"sort_order":28705},
{"slug":"saudi-monthly-commute-cost-calculator","title_ar":"حاسبة تكلفة التنقل الشهرية","title_en":"Saudi Monthly Commute Cost Calculator","expression":"daily_commute_cost * work_days","fields":[{"key":"daily_commute_cost","ar":"تكلفة التنقل اليومية","en":"Daily commute cost","min":0},{"key":"work_days","ar":"أيام العمل بالشهر","en":"Work days","min":0}],"sort_order":28706},
{"slug":"saudi-rent-per-square-meter-calculator","title_ar":"حاسبة الإيجار لكل متر مربع","title_en":"Saudi Rent per Square Meter Calculator","expression":"annual_rent / area_sqm","fields":[{"key":"annual_rent","ar":"الإيجار السنوي","en":"Annual rent","min":0},{"key":"area_sqm","ar":"المساحة م²","en":"Area sqm","min":0.000001}],"sort_order":28707},
{"slug":"saudi-utility-budget-share-calculator","title_ar":"حاسبة نسبة الخدمات من الميزانية","title_en":"Saudi Utility Budget Share Calculator","expression":"utility_cost / monthly_budget * 100","fields":[{"key":"utility_cost","ar":"تكلفة الخدمات","en":"Utility cost","min":0},{"key":"monthly_budget","ar":"الميزانية الشهرية","en":"Monthly budget","min":0.000001}],"sort_order":28708},
{"slug":"saudi-invoice-vat-total-calculator","title_ar":"حاسبة إجمالي الفاتورة مع الضريبة","title_en":"Saudi Invoice VAT Total Calculator","expression":"subtotal * (1 + vat_rate / 100)","fields":[{"key":"subtotal","ar":"المجموع قبل الضريبة","en":"Subtotal","min":0},{"key":"vat_rate","ar":"نسبة الضريبة %","en":"VAT rate %","min":0}],"sort_order":28709},
{"slug":"saudi-business-fee-annualized-calculator","title_ar":"حاسبة الرسوم التجارية السنوية","title_en":"Saudi Business Fee Annualized Calculator","expression":"monthly_fee * 12 + annual_fee","fields":[{"key":"monthly_fee","ar":"الرسوم الشهرية","en":"Monthly fee","min":0},{"key":"annual_fee","ar":"الرسوم السنوية الإضافية","en":"Additional annual fee","min":0}],"sort_order":28710}
]$tools$::jsonb);

select public._wave8_upsert_formula_tools('math-tools',$tools$
[
{"slug":"sum-of-five-numbers-calculator","title_ar":"حاسبة مجموع خمس قيم","title_en":"Sum of Five Numbers Calculator","expression":"a + b + c + d + e","fields":[{"key":"a","ar":"القيمة A","en":"Value A"},{"key":"b","ar":"القيمة B","en":"Value B"},{"key":"c","ar":"القيمة C","en":"Value C"},{"key":"d","ar":"القيمة D","en":"Value D"},{"key":"e","ar":"القيمة E","en":"Value E"}],"sort_order":28801},
{"slug":"geometric-mean-two-values-calculator","title_ar":"حاسبة المتوسط الهندسي لقيمتين","title_en":"Geometric Mean of Two Values Calculator","expression":"(a * b) ^ 0.5","fields":[{"key":"a","ar":"القيمة A","en":"Value A","min":0},{"key":"b","ar":"القيمة B","en":"Value B","min":0}],"sort_order":28802},
{"slug":"harmonic-mean-two-values-calculator","title_ar":"حاسبة المتوسط التوافقي لقيمتين","title_en":"Harmonic Mean of Two Values Calculator","expression":"2 * a * b / (a + b)","fields":[{"key":"a","ar":"القيمة A","en":"Value A","min":0.000001},{"key":"b","ar":"القيمة B","en":"Value B","min":0.000001}],"sort_order":28803},
{"slug":"percentage-point-change-calculator","title_ar":"حاسبة فرق النقاط المئوية","title_en":"Percentage Point Change Calculator","expression":"new_percentage - old_percentage","fields":[{"key":"new_percentage","ar":"النسبة الجديدة","en":"New percentage"},{"key":"old_percentage","ar":"النسبة السابقة","en":"Old percentage"}],"sort_order":28804},
{"slug":"weighted-average-two-values-calculator","title_ar":"حاسبة المتوسط الموزون لقيمتين","title_en":"Weighted Average of Two Values Calculator","expression":"(value_a * weight_a + value_b * weight_b) / (weight_a + weight_b)","fields":[{"key":"value_a","ar":"القيمة A","en":"Value A"},{"key":"weight_a","ar":"وزن A","en":"Weight A","min":0.000001},{"key":"value_b","ar":"القيمة B","en":"Value B"},{"key":"weight_b","ar":"وزن B","en":"Weight B","min":0.000001}],"sort_order":28805},
{"slug":"linear-interpolation-calculator","title_ar":"حاسبة الاستيفاء الخطي","title_en":"Linear Interpolation Calculator","expression":"y1 + (x - x1) * (y2 - y1) / (x2 - x1)","fields":[{"key":"x1","ar":"X1","en":"X1"},{"key":"y1","ar":"Y1","en":"Y1"},{"key":"x2","ar":"X2","en":"X2"},{"key":"y2","ar":"Y2","en":"Y2"},{"key":"x","ar":"X المطلوبة","en":"Target X"}],"sort_order":28806},
{"slug":"simple-proportion-calculator","title_ar":"حاسبة التناسب البسيط","title_en":"Simple Proportion Calculator","expression":"part / whole","fields":[{"key":"part","ar":"الجزء","en":"Part"},{"key":"whole","ar":"الكل","en":"Whole","min":0.000001}],"sort_order":28807},
{"slug":"circle-area-from-diameter-calculator","title_ar":"حاسبة مساحة الدائرة من القطر","title_en":"Circle Area from Diameter Calculator","expression":"3.141592653589793 * diameter * diameter / 4","fields":[{"key":"diameter","ar":"القطر","en":"Diameter","min":0}],"sort_order":28808},
{"slug":"rectangle-diagonal-calculator","title_ar":"حاسبة قطر المستطيل","title_en":"Rectangle Diagonal Calculator","expression":"(length * length + width * width) ^ 0.5","fields":[{"key":"length","ar":"الطول","en":"Length","min":0},{"key":"width","ar":"العرض","en":"Width","min":0}],"sort_order":28809},
{"slug":"triangle-area-base-height-calculator","title_ar":"حاسبة مساحة المثلث بالقاعدة والارتفاع","title_en":"Triangle Area from Base and Height Calculator","expression":"base * height / 2","fields":[{"key":"base","ar":"القاعدة","en":"Base","min":0},{"key":"height","ar":"الارتفاع","en":"Height","min":0}],"sort_order":28810}
]$tools$::jsonb);

select public._wave8_upsert_formula_tools('date-time-tools',$tools$
[
{"slug":"total-hours-to-decimal-days-calculator","title_ar":"حاسبة الساعات إلى أيام عشرية","title_en":"Total Hours to Decimal Days Calculator","expression":"hours / 24","fields":[{"key":"hours","ar":"الساعات","en":"Hours","min":0}],"sort_order":28901},
{"slug":"decimal-days-to-total-hours-calculator","title_ar":"حاسبة الأيام العشرية إلى ساعات","title_en":"Decimal Days to Total Hours Calculator","expression":"days * 24","fields":[{"key":"days","ar":"الأيام","en":"Days","min":0}],"sort_order":28902},
{"slug":"minutes-to-hours-calculator","title_ar":"حاسبة الدقائق إلى ساعات","title_en":"Minutes to Hours Calculator","expression":"minutes / 60","fields":[{"key":"minutes","ar":"الدقائق","en":"Minutes","min":0}],"sort_order":28903},
{"slug":"calendar-weeks-to-days-calculator","title_ar":"حاسبة الأسابيع إلى أيام","title_en":"Calendar Weeks to Days Calculator","expression":"weeks * 7","fields":[{"key":"weeks","ar":"الأسابيع","en":"Weeks","min":0}],"sort_order":28904},
{"slug":"days-to-weeks-calculator","title_ar":"حاسبة الأيام إلى أسابيع","title_en":"Days to Weeks Calculator","expression":"days / 7","fields":[{"key":"days","ar":"الأيام","en":"Days","min":0}],"sort_order":28905},
{"slug":"months-to-years-estimator","title_ar":"حاسبة الأشهر إلى سنوات","title_en":"Months to Years Estimator","expression":"months / 12","fields":[{"key":"months","ar":"الأشهر","en":"Months","min":0}],"sort_order":28906},
{"slug":"years-to-months-calculator","title_ar":"حاسبة السنوات إلى أشهر","title_en":"Years to Months Calculator","expression":"years * 12","fields":[{"key":"years","ar":"السنوات","en":"Years","min":0}],"sort_order":28907},
{"slug":"work-hours-per-week-calculator","title_ar":"حاسبة ساعات العمل الأسبوعية","title_en":"Work Hours per Week Calculator","expression":"hours_per_day * work_days","fields":[{"key":"hours_per_day","ar":"الساعات يوميًا","en":"Hours per day","min":0},{"key":"work_days","ar":"أيام العمل أسبوعيًا","en":"Work days per week","min":0}],"sort_order":28908},
{"slug":"work-hours-per-year-calculator","title_ar":"حاسبة ساعات العمل السنوية","title_en":"Work Hours per Year Calculator","expression":"hours_per_week * work_weeks","fields":[{"key":"hours_per_week","ar":"الساعات أسبوعيًا","en":"Hours per week","min":0},{"key":"work_weeks","ar":"أسابيع العمل سنويًا","en":"Work weeks per year","min":0}],"sort_order":28909},
{"slug":"time-budget-per-day-calculator","title_ar":"حاسبة الوقت المتاح يوميًا","title_en":"Time Budget per Day Calculator","expression":"total_hours / days","fields":[{"key":"total_hours","ar":"إجمالي الساعات","en":"Total hours","min":0},{"key":"days","ar":"عدد الأيام","en":"Days","min":0.000001}],"sort_order":28910}
]$tools$::jsonb);
