-- Web Empire Wave15 — Procurement + Quality (20 tools)
select public._wave15_upsert_formula_tools('procurement-tools',$json$[
{"slug":"procurement-supplier-bid-response-rate-calculator","title_ar":"حاسبة معدل استجابة الموردين للعروض","title_en":"Procurement Supplier Bid Response Rate Calculator","expression":"bids_received / suppliers_invited * 100","fields":[{"key":"bids_received","ar":"العروض المستلمة","en":"Bids received","min":0},{"key":"suppliers_invited","ar":"الموردون المدعوون","en":"Suppliers invited","min":0.000001}],"sort_order":33001},
{"slug":"procurement-average-bids-per-rfq-calculator","title_ar":"حاسبة متوسط العروض لكل طلب تسعير","title_en":"Procurement Average Bids per RFQ Calculator","expression":"bids_received / rfqs","fields":[{"key":"bids_received","ar":"العروض المستلمة","en":"Bids received","min":0},{"key":"rfqs","ar":"طلبات التسعير","en":"RFQs","min":0.000001}],"sort_order":33002},
{"slug":"procurement-contract-utilization-rate-calculator","title_ar":"حاسبة معدل استخدام العقود","title_en":"Procurement Contract Utilization Rate Calculator","expression":"contract_spend / addressable_spend * 100","fields":[{"key":"contract_spend","ar":"الإنفاق عبر العقود","en":"Contract spend","min":0},{"key":"addressable_spend","ar":"الإنفاق القابل للتغطية","en":"Addressable spend","min":0.000001}],"sort_order":33003},
{"slug":"procurement-purchase-order-value-variance-calculator","title_ar":"حاسبة انحراف قيمة أمر الشراء","title_en":"Procurement Purchase Order Value Variance Calculator","expression":"(actual_value - planned_value) / planned_value * 100","fields":[{"key":"actual_value","ar":"القيمة الفعلية","en":"Actual value","min":0},{"key":"planned_value","ar":"القيمة المخططة","en":"Planned value","min":0.000001}],"sort_order":33004},
{"slug":"procurement-supplier-risk-share-calculator","title_ar":"حاسبة حصة الإنفاق على الموردين مرتفعي المخاطر","title_en":"Procurement Supplier Risk Share Calculator","expression":"high_risk_spend / total_spend * 100","fields":[{"key":"high_risk_spend","ar":"إنفاق الموردين مرتفعي المخاطر","en":"High-risk supplier spend","min":0},{"key":"total_spend","ar":"إجمالي الإنفاق","en":"Total spend","min":0.000001}],"sort_order":33005},
{"slug":"procurement-sourcing-savings-per-event-calculator","title_ar":"حاسبة وفر التوريد لكل عملية","title_en":"Procurement Sourcing Savings per Event Calculator","expression":"total_savings / sourcing_events","fields":[{"key":"total_savings","ar":"إجمالي الوفر","en":"Total savings","min":0},{"key":"sourcing_events","ar":"عمليات التوريد","en":"Sourcing events","min":0.000001}],"sort_order":33006},
{"slug":"procurement-invoice-match-rate-calculator","title_ar":"حاسبة معدل مطابقة الفواتير","title_en":"Procurement Invoice Match Rate Calculator","expression":"matched_invoices / total_invoices * 100","fields":[{"key":"matched_invoices","ar":"الفواتير المطابقة","en":"Matched invoices","min":0},{"key":"total_invoices","ar":"إجمالي الفواتير","en":"Total invoices","min":0.000001}],"sort_order":33007},
{"slug":"procurement-urgent-spend-share-calculator","title_ar":"حاسبة حصة الإنفاق العاجل","title_en":"Procurement Urgent Spend Share Calculator","expression":"urgent_spend / total_spend * 100","fields":[{"key":"urgent_spend","ar":"الإنفاق العاجل","en":"Urgent spend","min":0},{"key":"total_spend","ar":"إجمالي الإنفاق","en":"Total spend","min":0.000001}],"sort_order":33008},
{"slug":"procurement-supplier-dependency-ratio-calculator","title_ar":"حاسبة الاعتماد على أكبر مورد","title_en":"Procurement Supplier Dependency Ratio Calculator","expression":"largest_supplier_spend / total_spend * 100","fields":[{"key":"largest_supplier_spend","ar":"إنفاق أكبر مورد","en":"Largest supplier spend","min":0},{"key":"total_spend","ar":"إجمالي الإنفاق","en":"Total spend","min":0.000001}],"sort_order":33009},
{"slug":"procurement-negotiated-discount-value-calculator","title_ar":"حاسبة قيمة الخصم المتفاوض عليه","title_en":"Procurement Negotiated Discount Value Calculator","expression":"list_price - negotiated_price","fields":[{"key":"list_price","ar":"السعر الأصلي","en":"List price","min":0},{"key":"negotiated_price","ar":"السعر المتفاوض عليه","en":"Negotiated price","min":0}],"sort_order":33010}
]$json$::jsonb);

select public._wave15_upsert_formula_tools('quality-tools',$json$[
{"slug":"quality-defects-per-batch-calculator","title_ar":"حاسبة العيوب لكل دفعة","title_en":"Quality Defects per Batch Calculator","expression":"defects / batches","fields":[{"key":"defects","ar":"عدد العيوب","en":"Defects","min":0},{"key":"batches","ar":"عدد الدفعات","en":"Batches","min":0.000001}],"sort_order":33101},
{"slug":"quality-inspection-hours-per-batch-calculator","title_ar":"حاسبة ساعات الفحص لكل دفعة","title_en":"Quality Inspection Hours per Batch Calculator","expression":"inspection_hours / batches","fields":[{"key":"inspection_hours","ar":"ساعات الفحص","en":"Inspection hours","min":0},{"key":"batches","ar":"عدد الدفعات","en":"Batches","min":0.000001}],"sort_order":33102},
{"slug":"quality-audit-findings-per-audit-calculator","title_ar":"حاسبة ملاحظات التدقيق لكل تدقيق","title_en":"Quality Audit Findings per Audit Calculator","expression":"findings / audits","fields":[{"key":"findings","ar":"ملاحظات التدقيق","en":"Audit findings","min":0},{"key":"audits","ar":"عدد عمليات التدقيق","en":"Audits","min":0.000001}],"sort_order":33103},
{"slug":"quality-corrective-action-cost-per-case-calculator","title_ar":"حاسبة تكلفة الإجراء التصحيحي لكل حالة","title_en":"Quality Corrective Action Cost per Case Calculator","expression":"corrective_action_cost / cases","fields":[{"key":"corrective_action_cost","ar":"تكلفة الإجراءات التصحيحية","en":"Corrective action cost","min":0},{"key":"cases","ar":"عدد الحالات","en":"Cases","min":0.000001}],"sort_order":33104},
{"slug":"quality-warranty-cost-rate-calculator","title_ar":"حاسبة نسبة تكلفة الضمان","title_en":"Quality Warranty Cost Rate Calculator","expression":"warranty_cost / revenue * 100","fields":[{"key":"warranty_cost","ar":"تكلفة الضمان","en":"Warranty cost","min":0},{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0.000001}],"sort_order":33105},
{"slug":"quality-sample-failure-rate-calculator","title_ar":"حاسبة معدل فشل العينات","title_en":"Quality Sample Failure Rate Calculator","expression":"failed_samples / tested_samples * 100","fields":[{"key":"failed_samples","ar":"العينات الفاشلة","en":"Failed samples","min":0},{"key":"tested_samples","ar":"العينات المختبرة","en":"Tested samples","min":0.000001}],"sort_order":33106},
{"slug":"quality-tolerance-utilization-rate-calculator","title_ar":"حاسبة نسبة استهلاك حدود السماحية","title_en":"Quality Tolerance Utilization Rate Calculator","expression":"actual_deviation / allowed_tolerance * 100","fields":[{"key":"actual_deviation","ar":"الانحراف الفعلي","en":"Actual deviation","min":0},{"key":"allowed_tolerance","ar":"السماحية المسموحة","en":"Allowed tolerance","min":0.000001}],"sort_order":33107},
{"slug":"quality-first-article-pass-rate-calculator","title_ar":"حاسبة معدل نجاح العينة الأولى","title_en":"Quality First Article Pass Rate Calculator","expression":"passed_first_articles / total_first_articles * 100","fields":[{"key":"passed_first_articles","ar":"العينات الأولى الناجحة","en":"Passed first articles","min":0},{"key":"total_first_articles","ar":"إجمالي العينات الأولى","en":"Total first articles","min":0.000001}],"sort_order":33108},
{"slug":"quality-customer-return-cost-per-unit-calculator","title_ar":"حاسبة تكلفة مرتجعات العملاء لكل وحدة","title_en":"Quality Customer Return Cost per Unit Calculator","expression":"return_cost / returned_units","fields":[{"key":"return_cost","ar":"تكلفة المرتجعات","en":"Return cost","min":0},{"key":"returned_units","ar":"الوحدات المرتجعة","en":"Returned units","min":0.000001}],"sort_order":33109},
{"slug":"quality-complaint-resolution-time-calculator","title_ar":"حاسبة متوسط وقت حل الشكاوى","title_en":"Quality Complaint Resolution Time Calculator","expression":"resolution_hours / complaints_closed","fields":[{"key":"resolution_hours","ar":"إجمالي ساعات الحل","en":"Resolution hours","min":0},{"key":"complaints_closed","ar":"الشكاوى المغلقة","en":"Complaints closed","min":0.000001}],"sort_order":33110}
]$json$::jsonb);
