-- Web Empire wave 14 — Telecom + Travel (20 tools).
select public._wave14_upsert_formula_tools('telecom-tools',$json$[
{"slug":"telecom-revenue-per-subscriber-calculator","title_ar":"حاسبة إيراد الاتصالات لكل مشترك","title_en":"Telecom Revenue per Subscriber Calculator","expression":"revenue / subscribers","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"subscribers","ar":"عدد المشتركين","en":"Subscribers","min":0.000001}],"sort_order":33401},
{"slug":"telecom-data-usage-per-subscriber-calculator","title_ar":"حاسبة استهلاك البيانات لكل مشترك","title_en":"Telecom Data Usage per Subscriber Calculator","expression":"data_gb / subscribers","fields":[{"key":"data_gb","ar":"استهلاك البيانات GB","en":"Data usage GB","min":0},{"key":"subscribers","ar":"عدد المشتركين","en":"Subscribers","min":0.000001}],"sort_order":33402},
{"slug":"telecom-call-minutes-per-subscriber-calculator","title_ar":"حاسبة دقائق المكالمات لكل مشترك","title_en":"Telecom Call Minutes per Subscriber Calculator","expression":"call_minutes / subscribers","fields":[{"key":"call_minutes","ar":"دقائق المكالمات","en":"Call minutes","min":0},{"key":"subscribers","ar":"عدد المشتركين","en":"Subscribers","min":0.000001}],"sort_order":33403},
{"slug":"telecom-network-cost-per-subscriber-calculator","title_ar":"حاسبة تكلفة الشبكة لكل مشترك","title_en":"Telecom Network Cost per Subscriber Calculator","expression":"network_cost / subscribers","fields":[{"key":"network_cost","ar":"تكلفة الشبكة","en":"Network cost","min":0},{"key":"subscribers","ar":"عدد المشتركين","en":"Subscribers","min":0.000001}],"sort_order":33404},
{"slug":"telecom-support-tickets-per-thousand-subscribers-calculator","title_ar":"حاسبة تذاكر الدعم لكل ألف مشترك","title_en":"Telecom Support Tickets per Thousand Subscribers Calculator","expression":"support_tickets / subscribers * 1000","fields":[{"key":"support_tickets","ar":"تذاكر الدعم","en":"Support tickets","min":0},{"key":"subscribers","ar":"عدد المشتركين","en":"Subscribers","min":0.000001}],"sort_order":33405},
{"slug":"telecom-recharge-revenue-per-user-calculator","title_ar":"حاسبة إيراد إعادة الشحن لكل مستخدم","title_en":"Telecom Recharge Revenue per User Calculator","expression":"recharge_revenue / recharge_users","fields":[{"key":"recharge_revenue","ar":"إيراد إعادة الشحن","en":"Recharge revenue","min":0},{"key":"recharge_users","ar":"مستخدمو إعادة الشحن","en":"Recharge users","min":0.000001}],"sort_order":33406},
{"slug":"telecom-tower-revenue-per-site-calculator","title_ar":"حاسبة إيراد أبراج الاتصالات لكل موقع","title_en":"Telecom Tower Revenue per Site Calculator","expression":"tower_revenue / sites","fields":[{"key":"tower_revenue","ar":"إيراد الأبراج","en":"Tower revenue","min":0},{"key":"sites","ar":"عدد المواقع","en":"Sites","min":0.000001}],"sort_order":33407},
{"slug":"telecom-data-revenue-share-calculator","title_ar":"حاسبة حصة إيرادات البيانات","title_en":"Telecom Data Revenue Share Calculator","expression":"data_revenue / total_revenue * 100","fields":[{"key":"data_revenue","ar":"إيراد البيانات","en":"Data revenue","min":0},{"key":"total_revenue","ar":"إجمالي الإيراد","en":"Total revenue","min":0.000001}],"sort_order":33408},
{"slug":"telecom-voice-revenue-share-calculator","title_ar":"حاسبة حصة إيرادات المكالمات","title_en":"Telecom Voice Revenue Share Calculator","expression":"voice_revenue / total_revenue * 100","fields":[{"key":"voice_revenue","ar":"إيراد المكالمات","en":"Voice revenue","min":0},{"key":"total_revenue","ar":"إجمالي الإيراد","en":"Total revenue","min":0.000001}],"sort_order":33409},
{"slug":"telecom-subscriber-net-additions-calculator","title_ar":"حاسبة صافي إضافات المشتركين","title_en":"Telecom Subscriber Net Additions Calculator","expression":"new_subscribers - lost_subscribers","fields":[{"key":"new_subscribers","ar":"المشتركون الجدد","en":"New subscribers","min":0},{"key":"lost_subscribers","ar":"المشتركون المفقودون","en":"Lost subscribers","min":0}],"sort_order":33410}
]$json$::jsonb);

select public._wave14_upsert_formula_tools('travel-tools',$json$[
{"slug":"travel-accommodation-cost-per-night-calculator","title_ar":"حاسبة تكلفة السكن لكل ليلة","title_en":"Travel Accommodation Cost per Night Calculator","expression":"accommodation_cost / nights","fields":[{"key":"accommodation_cost","ar":"تكلفة السكن","en":"Accommodation cost","min":0},{"key":"nights","ar":"عدد الليالي","en":"Nights","min":0.000001}],"sort_order":33501},
{"slug":"travel-flight-cost-share-calculator","title_ar":"حاسبة حصة تكلفة الطيران من الرحلة","title_en":"Travel Flight Cost Share Calculator","expression":"flight_cost / total_trip_cost * 100","fields":[{"key":"flight_cost","ar":"تكلفة الطيران","en":"Flight cost","min":0},{"key":"total_trip_cost","ar":"إجمالي تكلفة الرحلة","en":"Total trip cost","min":0.000001}],"sort_order":33502},
{"slug":"travel-meal-cost-share-calculator","title_ar":"حاسبة حصة تكلفة الوجبات من الرحلة","title_en":"Travel Meal Cost Share Calculator","expression":"meal_cost / total_trip_cost * 100","fields":[{"key":"meal_cost","ar":"تكلفة الوجبات","en":"Meal cost","min":0},{"key":"total_trip_cost","ar":"إجمالي تكلفة الرحلة","en":"Total trip cost","min":0.000001}],"sort_order":33503},
{"slug":"travel-transport-cost-share-calculator","title_ar":"حاسبة حصة النقل المحلي من تكلفة الرحلة","title_en":"Travel Transport Cost Share Calculator","expression":"transport_cost / total_trip_cost * 100","fields":[{"key":"transport_cost","ar":"تكلفة النقل","en":"Transport cost","min":0},{"key":"total_trip_cost","ar":"إجمالي تكلفة الرحلة","en":"Total trip cost","min":0.000001}],"sort_order":33504},
{"slug":"travel-attraction-cost-share-calculator","title_ar":"حاسبة حصة الأنشطة من تكلفة الرحلة","title_en":"Travel Attraction Cost Share Calculator","expression":"attraction_cost / total_trip_cost * 100","fields":[{"key":"attraction_cost","ar":"تكلفة الأنشطة","en":"Attraction cost","min":0},{"key":"total_trip_cost","ar":"إجمالي تكلفة الرحلة","en":"Total trip cost","min":0.000001}],"sort_order":33505},
{"slug":"travel-cost-per-traveler-day-calculator","title_ar":"حاسبة تكلفة الرحلة لكل مسافر في اليوم","title_en":"Travel Cost per Traveler-Day Calculator","expression":"total_trip_cost / travelers / days","fields":[{"key":"total_trip_cost","ar":"إجمالي تكلفة الرحلة","en":"Total trip cost","min":0},{"key":"travelers","ar":"عدد المسافرين","en":"Travelers","min":0.000001},{"key":"days","ar":"عدد الأيام","en":"Days","min":0.000001}],"sort_order":33506},
{"slug":"travel-savings-progress-rate-calculator","title_ar":"حاسبة نسبة التقدم في ادخار السفر","title_en":"Travel Savings Progress Rate Calculator","expression":"saved_amount / savings_goal * 100","fields":[{"key":"saved_amount","ar":"المبلغ المدخر","en":"Saved amount","min":0},{"key":"savings_goal","ar":"هدف الادخار","en":"Savings goal","min":0.000001}],"sort_order":33507},
{"slug":"travel-budget-remaining-calculator","title_ar":"حاسبة ميزانية السفر المتبقية","title_en":"Travel Remaining Budget Calculator","expression":"travel_budget - spent_amount","fields":[{"key":"travel_budget","ar":"ميزانية السفر","en":"Travel budget","min":0},{"key":"spent_amount","ar":"المبلغ المصروف","en":"Spent amount","min":0}],"sort_order":33508},
{"slug":"travel-exchange-loss-amount-calculator","title_ar":"حاسبة خسارة تحويل العملة في السفر","title_en":"Travel Exchange Loss Amount Calculator","expression":"amount_exchanged * fee_rate / 100","fields":[{"key":"amount_exchanged","ar":"المبلغ المحول","en":"Amount exchanged","min":0},{"key":"fee_rate","ar":"نسبة رسوم التحويل %","en":"Exchange fee rate %","min":0,"max":100}],"sort_order":33509},
{"slug":"travel-roadtrip-fuel-cost-per-km-calculator","title_ar":"حاسبة تكلفة وقود الرحلة البرية لكل كيلومتر","title_en":"Travel Road Trip Fuel Cost per Kilometer Calculator","expression":"fuel_cost / distance_km","fields":[{"key":"fuel_cost","ar":"تكلفة الوقود","en":"Fuel cost","min":0},{"key":"distance_km","ar":"المسافة كم","en":"Distance km","min":0.000001}],"sort_order":33510}
]$json$::jsonb);
