-- Web Empire Wave15 — Hospitality + Salon (20 tools)
select public._wave15_upsert_formula_tools('hospitality-tools',$json$[
{"slug":"hospitality-booking-value-per-night-calculator","title_ar":"حاسبة قيمة الحجز لكل ليلة","title_en":"Hospitality Booking Value per Night Calculator","expression":"booking_revenue / nights","fields":[{"key":"booking_revenue","ar":"إيراد الحجز","en":"Booking revenue","min":0},{"key":"nights","ar":"عدد الليالي","en":"Nights","min":0.000001}],"sort_order":33401},
{"slug":"hospitality-amenity-revenue-per-guest-calculator","title_ar":"حاسبة إيراد المرافق لكل نزيل","title_en":"Hospitality Amenity Revenue per Guest Calculator","expression":"amenity_revenue / guests","fields":[{"key":"amenity_revenue","ar":"إيراد المرافق","en":"Amenity revenue","min":0},{"key":"guests","ar":"عدد النزلاء","en":"Guests","min":0.000001}],"sort_order":33402},
{"slug":"hospitality-late-checkout-revenue-calculator","title_ar":"حاسبة إيراد المغادرة المتأخرة","title_en":"Hospitality Late Checkout Revenue Calculator","expression":"late_checkouts * late_checkout_fee","fields":[{"key":"late_checkouts","ar":"حالات المغادرة المتأخرة","en":"Late checkouts","min":0},{"key":"late_checkout_fee","ar":"رسوم المغادرة المتأخرة","en":"Late checkout fee","min":0}],"sort_order":33403},
{"slug":"hospitality-room-upgrade-rate-calculator","title_ar":"حاسبة معدل ترقية الغرف","title_en":"Hospitality Room Upgrade Rate Calculator","expression":"upgraded_bookings / eligible_bookings * 100","fields":[{"key":"upgraded_bookings","ar":"الحجوزات التي تمت ترقيتها","en":"Upgraded bookings","min":0},{"key":"eligible_bookings","ar":"الحجوزات المؤهلة","en":"Eligible bookings","min":0.000001}],"sort_order":33404},
{"slug":"hospitality-breakfast-attachment-rate-calculator","title_ar":"حاسبة معدل إضافة الإفطار","title_en":"Hospitality Breakfast Attachment Rate Calculator","expression":"breakfast_guests / room_guests * 100","fields":[{"key":"breakfast_guests","ar":"نزلاء الإفطار","en":"Breakfast guests","min":0},{"key":"room_guests","ar":"نزلاء الغرف","en":"Room guests","min":0.000001}],"sort_order":33405},
{"slug":"hospitality-parking-attachment-rate-calculator","title_ar":"حاسبة معدل إضافة مواقف السيارات","title_en":"Hospitality Parking Attachment Rate Calculator","expression":"parking_bookings / room_bookings * 100","fields":[{"key":"parking_bookings","ar":"حجوزات المواقف","en":"Parking bookings","min":0},{"key":"room_bookings","ar":"حجوزات الغرف","en":"Room bookings","min":0.000001}],"sort_order":33406},
{"slug":"hospitality-laundry-revenue-per-guest-calculator","title_ar":"حاسبة إيراد المغسلة لكل نزيل","title_en":"Hospitality Laundry Revenue per Guest Calculator","expression":"laundry_revenue / guests","fields":[{"key":"laundry_revenue","ar":"إيراد المغسلة","en":"Laundry revenue","min":0},{"key":"guests","ar":"عدد النزلاء","en":"Guests","min":0.000001}],"sort_order":33407},
{"slug":"hospitality-revenue-per-staff-hour-calculator","title_ar":"حاسبة الإيراد لكل ساعة عمل للموظفين","title_en":"Hospitality Revenue per Staff Hour Calculator","expression":"revenue / staff_hours","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"staff_hours","ar":"ساعات عمل الموظفين","en":"Staff hours","min":0.000001}],"sort_order":33408},
{"slug":"hospitality-guest-service-cost-per-stay-calculator","title_ar":"حاسبة تكلفة خدمة النزيل لكل إقامة","title_en":"Hospitality Guest Service Cost per Stay Calculator","expression":"guest_service_cost / stays","fields":[{"key":"guest_service_cost","ar":"تكلفة خدمة النزلاء","en":"Guest service cost","min":0},{"key":"stays","ar":"عدد الإقامات","en":"Stays","min":0.000001}],"sort_order":33409},
{"slug":"hospitality-average-booking-value-calculator","title_ar":"حاسبة متوسط قيمة الحجز","title_en":"Hospitality Average Booking Value Calculator","expression":"booking_revenue / bookings","fields":[{"key":"booking_revenue","ar":"إيراد الحجوزات","en":"Booking revenue","min":0},{"key":"bookings","ar":"عدد الحجوزات","en":"Bookings","min":0.000001}],"sort_order":33410}
]$json$::jsonb);

select public._wave15_upsert_formula_tools('salon-tools',$json$[
{"slug":"salon-service-mix-share-calculator","title_ar":"حاسبة حصة نوع خدمة من إيراد الخدمات","title_en":"Salon Service Mix Share Calculator","expression":"selected_service_revenue / service_revenue * 100","fields":[{"key":"selected_service_revenue","ar":"إيراد الخدمة المحددة","en":"Selected service revenue","min":0},{"key":"service_revenue","ar":"إجمالي إيراد الخدمات","en":"Service revenue","min":0.000001}],"sort_order":33501},
{"slug":"salon-product-units-per-client-calculator","title_ar":"حاسبة وحدات المنتجات لكل عميل","title_en":"Salon Product Units per Client Calculator","expression":"product_units / clients","fields":[{"key":"product_units","ar":"وحدات المنتجات","en":"Product units","min":0},{"key":"clients","ar":"عدد العملاء","en":"Clients","min":0.000001}],"sort_order":33502},
{"slug":"salon-appointment-lead-time-calculator","title_ar":"حاسبة متوسط مدة الحجز المسبق","title_en":"Salon Appointment Lead Time Calculator","expression":"advance_days / appointments","fields":[{"key":"advance_days","ar":"إجمالي أيام الحجز المسبق","en":"Advance booking days","min":0},{"key":"appointments","ar":"عدد المواعيد","en":"Appointments","min":0.000001}],"sort_order":33503},
{"slug":"salon-overtime-cost-share-calculator","title_ar":"حاسبة حصة تكلفة العمل الإضافي للصالون","title_en":"Salon Overtime Cost Share Calculator","expression":"overtime_cost / labor_cost * 100","fields":[{"key":"overtime_cost","ar":"تكلفة العمل الإضافي","en":"Overtime cost","min":0},{"key":"labor_cost","ar":"إجمالي تكلفة العمالة","en":"Labor cost","min":0.000001}],"sort_order":33504},
{"slug":"salon-consumables-cost-share-calculator","title_ar":"حاسبة حصة تكلفة المستهلكات","title_en":"Salon Consumables Cost Share Calculator","expression":"consumables_cost / service_revenue * 100","fields":[{"key":"consumables_cost","ar":"تكلفة المستهلكات","en":"Consumables cost","min":0},{"key":"service_revenue","ar":"إيراد الخدمات","en":"Service revenue","min":0.000001}],"sort_order":33505},
{"slug":"salon-membership-churn-rate-calculator","title_ar":"حاسبة معدل إلغاء العضويات","title_en":"Salon Membership Churn Rate Calculator","expression":"cancelled_memberships / starting_memberships * 100","fields":[{"key":"cancelled_memberships","ar":"العضويات الملغاة","en":"Cancelled memberships","min":0},{"key":"starting_memberships","ar":"العضويات في بداية الفترة","en":"Starting memberships","min":0.000001}],"sort_order":33506},
{"slug":"salon-chair-downtime-rate-calculator","title_ar":"حاسبة معدل وقت تعطل الكراسي","title_en":"Salon Chair Downtime Rate Calculator","expression":"idle_chair_hours / available_chair_hours * 100","fields":[{"key":"idle_chair_hours","ar":"ساعات الكراسي الخاملة","en":"Idle chair hours","min":0},{"key":"available_chair_hours","ar":"ساعات الكراسي المتاحة","en":"Available chair hours","min":0.000001}],"sort_order":33507},
{"slug":"salon-revenue-per-square-meter-calculator","title_ar":"حاسبة إيراد الصالون لكل متر مربع","title_en":"Salon Revenue per Square Meter Calculator","expression":"revenue / area_sqm","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"area_sqm","ar":"المساحة بالمتر المربع","en":"Area sqm","min":0.000001}],"sort_order":33508},
{"slug":"salon-retail-units-per-appointment-calculator","title_ar":"حاسبة وحدات التجزئة لكل موعد","title_en":"Salon Retail Units per Appointment Calculator","expression":"retail_units / appointments","fields":[{"key":"retail_units","ar":"وحدات التجزئة المباعة","en":"Retail units","min":0},{"key":"appointments","ar":"عدد المواعيد","en":"Appointments","min":0.000001}],"sort_order":33509},
{"slug":"salon-average-rebooking-days-calculator","title_ar":"حاسبة متوسط أيام إعادة الحجز","title_en":"Salon Average Rebooking Days Calculator","expression":"rebooking_days / rebookings","fields":[{"key":"rebooking_days","ar":"إجمالي أيام إعادة الحجز","en":"Rebooking days","min":0},{"key":"rebookings","ar":"عدد إعادات الحجز","en":"Rebookings","min":0.000001}],"sort_order":33510}
]$json$::jsonb);
