-- Web Empire Wave15 — Manufacturing + Maintenance (20 tools)
select public._wave15_upsert_formula_tools('manufacturing-tools',$json$[
{"slug":"manufacturing-output-per-machine-calculator","title_ar":"حاسبة الإنتاج لكل آلة","title_en":"Manufacturing Output per Machine Calculator","expression":"output_units / machines","fields":[{"key":"output_units","ar":"الوحدات المنتجة","en":"Output units","min":0},{"key":"machines","ar":"عدد الآلات","en":"Machines","min":0.000001}],"sort_order":33201},
{"slug":"manufacturing-scrap-cost-per-unit-calculator","title_ar":"حاسبة تكلفة الخردة لكل وحدة","title_en":"Manufacturing Scrap Cost per Unit Calculator","expression":"scrap_cost / scrap_units","fields":[{"key":"scrap_cost","ar":"تكلفة الخردة","en":"Scrap cost","min":0},{"key":"scrap_units","ar":"وحدات الخردة","en":"Scrap units","min":0.000001}],"sort_order":33202},
{"slug":"manufacturing-overtime-cost-share-calculator","title_ar":"حاسبة حصة تكلفة العمل الإضافي","title_en":"Manufacturing Overtime Cost Share Calculator","expression":"overtime_cost / labor_cost * 100","fields":[{"key":"overtime_cost","ar":"تكلفة العمل الإضافي","en":"Overtime cost","min":0},{"key":"labor_cost","ar":"إجمالي تكلفة العمالة","en":"Labor cost","min":0.000001}],"sort_order":33203},
{"slug":"manufacturing-packaging-cost-per-unit-calculator","title_ar":"حاسبة تكلفة التغليف لكل وحدة","title_en":"Manufacturing Packaging Cost per Unit Calculator","expression":"packaging_cost / units","fields":[{"key":"packaging_cost","ar":"تكلفة التغليف","en":"Packaging cost","min":0},{"key":"units","ar":"عدد الوحدات","en":"Units","min":0.000001}],"sort_order":33204},
{"slug":"manufacturing-production-hours-per-batch-calculator","title_ar":"حاسبة ساعات الإنتاج لكل دفعة","title_en":"Manufacturing Production Hours per Batch Calculator","expression":"production_hours / batches","fields":[{"key":"production_hours","ar":"ساعات الإنتاج","en":"Production hours","min":0},{"key":"batches","ar":"عدد الدفعات","en":"Batches","min":0.000001}],"sort_order":33205},
{"slug":"manufacturing-downtime-cost-per-hour-calculator","title_ar":"حاسبة تكلفة التوقف لكل ساعة","title_en":"Manufacturing Downtime Cost per Hour Calculator","expression":"downtime_cost / downtime_hours","fields":[{"key":"downtime_cost","ar":"تكلفة التوقف","en":"Downtime cost","min":0},{"key":"downtime_hours","ar":"ساعات التوقف","en":"Downtime hours","min":0.000001}],"sort_order":33206},
{"slug":"manufacturing-changeover-cost-calculator","title_ar":"حاسبة تكلفة تغيير خط الإنتاج","title_en":"Manufacturing Changeover Cost Calculator","expression":"changeover_hours * hourly_cost","fields":[{"key":"changeover_hours","ar":"ساعات التغيير","en":"Changeover hours","min":0},{"key":"hourly_cost","ar":"التكلفة لكل ساعة","en":"Hourly cost","min":0}],"sort_order":33207},
{"slug":"manufacturing-operator-to-machine-ratio-calculator","title_ar":"حاسبة نسبة المشغلين إلى الآلات","title_en":"Manufacturing Operator-to-Machine Ratio Calculator","expression":"operators / machines","fields":[{"key":"operators","ar":"عدد المشغلين","en":"Operators","min":0},{"key":"machines","ar":"عدد الآلات","en":"Machines","min":0.000001}],"sort_order":33208},
{"slug":"manufacturing-capacity-per-shift-calculator","title_ar":"حاسبة الطاقة الإنتاجية لكل وردية","title_en":"Manufacturing Capacity per Shift Calculator","expression":"total_capacity / shifts","fields":[{"key":"total_capacity","ar":"إجمالي الطاقة الإنتاجية","en":"Total capacity","min":0},{"key":"shifts","ar":"عدد الورديات","en":"Shifts","min":0.000001}],"sort_order":33209},
{"slug":"manufacturing-material-usage-per-good-unit-calculator","title_ar":"حاسبة استهلاك المواد لكل وحدة سليمة","title_en":"Manufacturing Material Usage per Good Unit Calculator","expression":"material_used / good_units","fields":[{"key":"material_used","ar":"المواد المستخدمة","en":"Material used","min":0},{"key":"good_units","ar":"الوحدات السليمة","en":"Good units","min":0.000001}],"sort_order":33210}
]$json$::jsonb);

select public._wave15_upsert_formula_tools('maintenance-tools',$json$[
{"slug":"maintenance-backlog-hours-per-technician-calculator","title_ar":"حاسبة ساعات الأعمال المتأخرة لكل فني","title_en":"Maintenance Backlog Hours per Technician Calculator","expression":"backlog_hours / technicians","fields":[{"key":"backlog_hours","ar":"ساعات الأعمال المتأخرة","en":"Backlog hours","min":0},{"key":"technicians","ar":"عدد الفنيين","en":"Technicians","min":0.000001}],"sort_order":33301},
{"slug":"maintenance-preventive-hours-share-calculator","title_ar":"حاسبة حصة ساعات الصيانة الوقائية","title_en":"Maintenance Preventive Hours Share Calculator","expression":"preventive_hours / maintenance_hours * 100","fields":[{"key":"preventive_hours","ar":"ساعات الصيانة الوقائية","en":"Preventive hours","min":0},{"key":"maintenance_hours","ar":"إجمالي ساعات الصيانة","en":"Maintenance hours","min":0.000001}],"sort_order":33302},
{"slug":"maintenance-unplanned-downtime-cost-calculator","title_ar":"حاسبة تكلفة التوقف غير المخطط","title_en":"Maintenance Unplanned Downtime Cost Calculator","expression":"downtime_hours * cost_per_hour","fields":[{"key":"downtime_hours","ar":"ساعات التوقف","en":"Downtime hours","min":0},{"key":"cost_per_hour","ar":"التكلفة لكل ساعة","en":"Cost per hour","min":0}],"sort_order":33303},
{"slug":"maintenance-parts-usage-per-work-order-calculator","title_ar":"حاسبة استهلاك القطع لكل أمر عمل","title_en":"Maintenance Parts Usage per Work Order Calculator","expression":"parts_used / work_orders","fields":[{"key":"parts_used","ar":"القطع المستخدمة","en":"Parts used","min":0},{"key":"work_orders","ar":"أوامر العمل","en":"Work orders","min":0.000001}],"sort_order":33304},
{"slug":"maintenance-work-order-age-average-calculator","title_ar":"حاسبة متوسط عمر أوامر العمل المفتوحة","title_en":"Maintenance Work Order Age Average Calculator","expression":"total_open_days / open_orders","fields":[{"key":"total_open_days","ar":"إجمالي أيام الأوامر المفتوحة","en":"Total open days","min":0},{"key":"open_orders","ar":"الأوامر المفتوحة","en":"Open orders","min":0.000001}],"sort_order":33305},
{"slug":"maintenance-scheduled-hours-per-asset-calculator","title_ar":"حاسبة ساعات الصيانة المجدولة لكل أصل","title_en":"Maintenance Scheduled Hours per Asset Calculator","expression":"scheduled_hours / assets","fields":[{"key":"scheduled_hours","ar":"الساعات المجدولة","en":"Scheduled hours","min":0},{"key":"assets","ar":"عدد الأصول","en":"Assets","min":0.000001}],"sort_order":33306},
{"slug":"maintenance-repair-cost-per-failure-calculator","title_ar":"حاسبة تكلفة الإصلاح لكل عطل","title_en":"Maintenance Repair Cost per Failure Calculator","expression":"repair_cost / failures","fields":[{"key":"repair_cost","ar":"تكلفة الإصلاح","en":"Repair cost","min":0},{"key":"failures","ar":"عدد الأعطال","en":"Failures","min":0.000001}],"sort_order":33307},
{"slug":"maintenance-labor-hours-per-work-order-calculator","title_ar":"حاسبة ساعات العمل لكل أمر صيانة","title_en":"Maintenance Labor Hours per Work Order Calculator","expression":"labor_hours / work_orders","fields":[{"key":"labor_hours","ar":"ساعات العمل","en":"Labor hours","min":0},{"key":"work_orders","ar":"أوامر العمل","en":"Work orders","min":0.000001}],"sort_order":33308},
{"slug":"maintenance-spare-parts-cost-per-asset-calculator","title_ar":"حاسبة تكلفة قطع الغيار لكل أصل","title_en":"Maintenance Spare Parts Cost per Asset Calculator","expression":"spare_parts_cost / assets","fields":[{"key":"spare_parts_cost","ar":"تكلفة قطع الغيار","en":"Spare parts cost","min":0},{"key":"assets","ar":"عدد الأصول","en":"Assets","min":0.000001}],"sort_order":33309},
{"slug":"maintenance-service-contract-savings-calculator","title_ar":"حاسبة وفر عقد الصيانة","title_en":"Maintenance Service Contract Savings Calculator","expression":"estimated_internal_cost - contract_cost","fields":[{"key":"estimated_internal_cost","ar":"التكلفة الداخلية المقدرة","en":"Estimated internal cost","min":0},{"key":"contract_cost","ar":"تكلفة العقد","en":"Contract cost","min":0}],"sort_order":33310}
]$json$::jsonb);
