-- Web Empire — Non-AI catalog growth wave 4 (sales-tools)
-- Adds 10 deterministic bilingual formula tools.
-- GitHub staging only until this migration is intentionally applied later.

begin;
create temporary table wave4_sales_tools_seed(category_slug text not null,slug text primary key,title_ar text not null,title_en text not null,description_ar text not null,description_en text not null,expression text not null,input_fields jsonb not null,english_fields jsonb not null,submit_ar text not null,submit_en text not null,sort_order integer not null,is_featured boolean not null) on commit drop;
insert into wave4_sales_tools_seed(category_slug,slug,title_ar,title_en,description_ar,description_en,expression,input_fields,english_fields,submit_ar,submit_en,sort_order,is_featured) values
('sales-tools','lead-to-opportunity-rate-calculator','حاسبة تحويل العميل المحتمل إلى فرصة','Lead-to-Opportunity Rate Calculator','احسب نسبة العملاء المحتملين الذين أصبحوا فرص بيع.','Calculate leads that become sales opportunities.','opportunities / leads * 100','[{"key":"opportunities","label":"فرص البيع","type":"number","required":true,"step":1,"min":0},{"key":"leads","label":"العملاء المحتملون","type":"number","required":true,"step":1,"min":1}]'::jsonb,'[{"key":"opportunities","label":"Opportunities","type":"number","required":true,"step":1,"min":0},{"key":"leads","label":"Leads","type":"number","required":true,"step":1,"min":1}]'::jsonb,'احسب','Calculate',8001,false),
('sales-tools','opportunity-to-close-rate-calculator','حاسبة إغلاق فرص البيع','Opportunity-to-Close Rate Calculator','احسب نسبة الفرص التي تحولت إلى صفقات مغلقة.','Calculate opportunities that become closed deals.','closed_deals / opportunities * 100','[{"key":"closed_deals","label":"الصفقات المغلقة","type":"number","required":true,"step":1,"min":0},{"key":"opportunities","label":"فرص البيع","type":"number","required":true,"step":1,"min":1}]'::jsonb,'[{"key":"closed_deals","label":"Closed deals","type":"number","required":true,"step":1,"min":0},{"key":"opportunities","label":"Opportunities","type":"number","required":true,"step":1,"min":1}]'::jsonb,'احسب','Calculate',8002,false),
('sales-tools','weighted-sales-pipeline-value-calculator','حاسبة قيمة خط المبيعات المرجحة','Weighted Sales Pipeline Value Calculator','قدّر قيمة خط المبيعات بعد ترجيح احتمال الفوز.','Estimate pipeline value weighted by win probability.','pipeline_value * win_probability / 100','[{"key":"pipeline_value","label":"قيمة خط المبيعات","type":"number","required":true,"step":0.01,"min":0},{"key":"win_probability","label":"احتمال الفوز %","type":"number","required":true,"step":0.01,"min":0}]'::jsonb,'[{"key":"pipeline_value","label":"Pipeline value","type":"number","required":true,"step":0.01,"min":0},{"key":"win_probability","label":"Win probability %","type":"number","required":true,"step":0.01,"min":0}]'::jsonb,'احسب','Calculate',8003,false),
('sales-tools','sales-forecast-attainment-calculator','حاسبة تحقيق توقعات المبيعات','Sales Forecast Attainment Calculator','احسب نسبة المبيعات الفعلية إلى التوقعات.','Calculate actual sales as a percentage of forecast sales.','actual_sales / forecast_sales * 100','[{"key":"actual_sales","label":"المبيعات الفعلية","type":"number","required":true,"step":0.01,"min":0},{"key":"forecast_sales","label":"المبيعات المتوقعة","type":"number","required":true,"step":0.01,"min":0.01}]'::jsonb,'[{"key":"actual_sales","label":"Actual sales","type":"number","required":true,"step":0.01,"min":0},{"key":"forecast_sales","label":"Forecast sales","type":"number","required":true,"step":0.01,"min":0.01}]'::jsonb,'احسب','Calculate',8004,false),
('sales-tools','revenue-per-lead-calculator','حاسبة الإيراد لكل عميل محتمل','Revenue per Lead Calculator','احسب متوسط الإيراد لكل عميل محتمل.','Calculate average revenue generated per lead.','revenue / leads','[{"key":"revenue","label":"الإيراد","type":"number","required":true,"step":0.01,"min":0},{"key":"leads","label":"العملاء المحتملون","type":"number","required":true,"step":1,"min":1}]'::jsonb,'[{"key":"revenue","label":"Revenue","type":"number","required":true,"step":0.01,"min":0},{"key":"leads","label":"Leads","type":"number","required":true,"step":1,"min":1}]'::jsonb,'احسب','Calculate',8005,false),
('sales-tools','cost-per-qualified-lead-calculator','حاسبة تكلفة العميل المحتمل المؤهل','Cost per Qualified Lead Calculator','احسب تكلفة الحصول على عميل محتمل مؤهل.','Calculate cost per qualified lead.','campaign_cost / qualified_leads','[{"key":"campaign_cost","label":"تكلفة الحملة","type":"number","required":true,"step":0.01,"min":0},{"key":"qualified_leads","label":"العملاء المحتملون المؤهلون","type":"number","required":true,"step":1,"min":1}]'::jsonb,'[{"key":"campaign_cost","label":"Campaign cost","type":"number","required":true,"step":0.01,"min":0},{"key":"qualified_leads","label":"Qualified leads","type":"number","required":true,"step":1,"min":1}]'::jsonb,'احسب','Calculate',8006,false),
('sales-tools','proposal-acceptance-rate-calculator','حاسبة قبول العروض','Proposal Acceptance Rate Calculator','احسب نسبة العروض المقبولة إلى العروض المقدمة.','Calculate accepted proposals as a percentage of proposals sent.','accepted_proposals / proposals_sent * 100','[{"key":"accepted_proposals","label":"العروض المقبولة","type":"number","required":true,"step":1,"min":0},{"key":"proposals_sent","label":"العروض المقدمة","type":"number","required":true,"step":1,"min":1}]'::jsonb,'[{"key":"accepted_proposals","label":"Accepted proposals","type":"number","required":true,"step":1,"min":0},{"key":"proposals_sent","label":"Proposals sent","type":"number","required":true,"step":1,"min":1}]'::jsonb,'احسب','Calculate',8007,false),
('sales-tools','contract-renewal-rate-calculator','حاسبة تجديد العقود','Contract Renewal Rate Calculator','احسب نسبة العقود التي تم تجديدها عند الاستحقاق.','Calculate contracts renewed as a percentage of contracts due.','renewed_contracts / contracts_due * 100','[{"key":"renewed_contracts","label":"العقود المجددة","type":"number","required":true,"step":1,"min":0},{"key":"contracts_due","label":"العقود المستحقة","type":"number","required":true,"step":1,"min":1}]'::jsonb,'[{"key":"renewed_contracts","label":"Renewed contracts","type":"number","required":true,"step":1,"min":0},{"key":"contracts_due","label":"Contracts due","type":"number","required":true,"step":1,"min":1}]'::jsonb,'احسب','Calculate',8008,false),
('sales-tools','sales-revenue-per-selling-day-calculator','حاسبة المبيعات لكل يوم بيع','Sales Revenue per Selling Day Calculator','احسب متوسط إيراد المبيعات لكل يوم بيع.','Calculate average sales revenue per selling day.','revenue / selling_days','[{"key":"revenue","label":"إيراد المبيعات","type":"number","required":true,"step":0.01,"min":0},{"key":"selling_days","label":"أيام البيع","type":"number","required":true,"step":1,"min":1}]'::jsonb,'[{"key":"revenue","label":"Sales revenue","type":"number","required":true,"step":0.01,"min":0},{"key":"selling_days","label":"Selling days","type":"number","required":true,"step":1,"min":1}]'::jsonb,'احسب','Calculate',8009,false),
('sales-tools','sales-discount-to-revenue-ratio-calculator','حاسبة نسبة الخصومات إلى الإيراد','Sales Discount-to-Revenue Ratio Calculator','احسب قيمة الخصومات كنسبة من الإيراد الإجمالي.','Calculate discounts as a percentage of gross revenue.','discount_amount / gross_revenue * 100','[{"key":"discount_amount","label":"قيمة الخصومات","type":"number","required":true,"step":0.01,"min":0},{"key":"gross_revenue","label":"الإيراد الإجمالي","type":"number","required":true,"step":0.01,"min":0.01}]'::jsonb,'[{"key":"discount_amount","label":"Discount amount","type":"number","required":true,"step":0.01,"min":0},{"key":"gross_revenue","label":"Gross revenue","type":"number","required":true,"step":0.01,"min":0.01}]'::jsonb,'احسب','Calculate',8010,false);
insert into public.tools(slug,title_ar,title_en,short_description,category_id,engine_type,input_schema,output_schema,runtime_config,pricing_mode,fixed_points,minimum_points,requires_auth,is_featured,is_active,sort_order,seo_title,seo_description) select seed.slug,seed.title_ar,seed.title_en,seed.description_ar,category.id,'formula',jsonb_build_object('submitLabel',seed.submit_ar,'fields',seed.input_fields),jsonb_build_object('type','number','format','auto'),jsonb_build_object('expression',seed.expression),'free',0,0,false,seed.is_featured,true,seed.sort_order,seed.title_ar,seed.description_ar from wave4_sales_tools_seed seed join public.categories category on category.slug=seed.category_slug on conflict(slug) do update set title_ar=excluded.title_ar,title_en=excluded.title_en,short_description=excluded.short_description,category_id=excluded.category_id,engine_type=excluded.engine_type,input_schema=excluded.input_schema,output_schema=excluded.output_schema,runtime_config=excluded.runtime_config,pricing_mode=excluded.pricing_mode,fixed_points=excluded.fixed_points,minimum_points=excluded.minimum_points,requires_auth=excluded.requires_auth,is_featured=excluded.is_featured,is_active=excluded.is_active,sort_order=excluded.sort_order,seo_title=excluded.seo_title,seo_description=excluded.seo_description,updated_at=now();
insert into public.tool_translations(tool_id,locale_id,title,short_description,seo_title,seo_description,prompt_template_override) select tool.id,locale.id,case when locale.code='ar' then seed.title_ar else seed.title_en end,case when locale.code='ar' then seed.description_ar else seed.description_en end,case when locale.code='ar' then seed.title_ar else seed.title_en end,case when locale.code='ar' then seed.description_ar else seed.description_en end,null from wave4_sales_tools_seed seed join public.tools tool on tool.slug=seed.slug join public.locales locale on locale.code in('ar','en') on conflict(tool_id,locale_id) do update set title=excluded.title,short_description=excluded.short_description,seo_title=excluded.seo_title,seo_description=excluded.seo_description,prompt_template_override=null,updated_at=now();
insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options) select tool.id,locale.id,field.value->>'key',field.value->>'label',nullif(field.value->>'placeholder',''),nullif(field.value->>'helpText',''),field.value->'options' from wave4_sales_tools_seed seed join public.tools tool on tool.slug=seed.slug join public.locales locale on locale.code in('ar','en') cross join lateral jsonb_array_elements(case when locale.code='ar' then seed.input_fields else seed.english_fields end) field(value) on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,placeholder=excluded.placeholder,help_text=excluded.help_text,options=excluded.options,updated_at=now();
insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options) select tool.id,locale.id,'__submit__',case when locale.code='ar' then seed.submit_ar else seed.submit_en end,null,null,null from wave4_sales_tools_seed seed join public.tools tool on tool.slug=seed.slug join public.locales locale on locale.code in('ar','en') on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,placeholder=null,help_text=null,options=null,updated_at=now();
commit;
