-- Web Empire — Non-AI catalog growth wave 3 (business-tools)
begin;
create temporary table w3_seed(
 slug text primary key,title_ar text,title_en text,description_ar text,description_en text,
 runtime_config jsonb,schema_ar jsonb,schema_en jsonb,sort_order integer
) on commit drop;
insert into w3_seed values
('gross-margin-calculator','حاسبة هامش الربح الإجمالي','Gross Margin Calculator','احسب هامش الربح الإجمالي من الإيراد وتكلفة البضاعة.','Calculate gross margin from revenue and cost of goods sold.','{"expression":"(revenue - cogs) / revenue * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"هامش الربح الإجمالي","resultLabelEn":"Gross margin","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"revenue","type":"number","required":true,"min":1e-06,"step":0.01,"label":"الإيراد"},{"key":"cogs","type":"number","required":true,"min":0,"step":0.01,"label":"تكلفة البضاعة"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"revenue","type":"number","required":true,"min":1e-06,"step":0.01,"label":"Revenue"},{"key":"cogs","type":"number","required":true,"min":0,"step":0.01,"label":"Cost of goods sold"}],"submitLabel":"Calculate"}'::jsonb,8301),
('business-markup-percentage-calculator','حاسبة نسبة الزيادة على التكلفة','Markup Calculator','احسب نسبة الزيادة على التكلفة من السعر والتكلفة.','Calculate markup percentage from selling price and cost.','{"expression":"(selling_price - cost) / cost * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة الزيادة على التكلفة","resultLabelEn":"Markup","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"selling_price","type":"number","required":true,"min":0,"step":0.01,"label":"سعر البيع"},{"key":"cost","type":"number","required":true,"min":1e-06,"step":0.01,"label":"التكلفة"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"selling_price","type":"number","required":true,"min":0,"step":0.01,"label":"Selling price"},{"key":"cost","type":"number","required":true,"min":1e-06,"step":0.01,"label":"Cost"}],"submitLabel":"Calculate"}'::jsonb,8302),
('net-profit-margin-calculator','حاسبة هامش صافي الربح','Net Profit Margin Calculator','احسب هامش صافي الربح من صافي الربح والإيراد.','Calculate net profit margin from net profit and revenue.','{"expression":"net_profit / revenue * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"هامش صافي الربح","resultLabelEn":"Net profit margin","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"net_profit","type":"number","required":true,"step":0.01,"label":"صافي الربح"},{"key":"revenue","type":"number","required":true,"min":1e-06,"step":0.01,"label":"الإيراد"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"net_profit","type":"number","required":true,"step":0.01,"label":"Net profit"},{"key":"revenue","type":"number","required":true,"min":1e-06,"step":0.01,"label":"Revenue"}],"submitLabel":"Calculate"}'::jsonb,8303),
('contribution-margin-per-unit','حاسبة هامش المساهمة للوحدة','Contribution Margin per Unit','احسب هامش المساهمة للوحدة من سعر البيع والتكلفة المتغيرة.','Calculate contribution margin per unit from selling price and variable cost.','{"expression":"unit_price - variable_cost","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"هامش المساهمة للوحدة","resultLabelEn":"Contribution margin per unit","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"unit_price","type":"number","required":true,"min":0,"step":0.01,"label":"سعر الوحدة"},{"key":"variable_cost","type":"number","required":true,"min":0,"step":0.01,"label":"التكلفة المتغيرة للوحدة"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"unit_price","type":"number","required":true,"min":0,"step":0.01,"label":"Unit price"},{"key":"variable_cost","type":"number","required":true,"min":0,"step":0.01,"label":"Variable cost per unit"}],"submitLabel":"Calculate"}'::jsonb,8304),
('contribution-margin-ratio-calculator','حاسبة نسبة هامش المساهمة','Contribution Margin Ratio','احسب نسبة هامش المساهمة من المبيعات والتكاليف المتغيرة.','Calculate contribution margin ratio from sales and variable costs.','{"expression":"(sales - variable_costs) / sales * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة هامش المساهمة","resultLabelEn":"Contribution margin ratio","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"sales","type":"number","required":true,"min":1e-06,"step":0.01,"label":"المبيعات"},{"key":"variable_costs","type":"number","required":true,"min":0,"step":0.01,"label":"التكاليف المتغيرة"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"sales","type":"number","required":true,"min":1e-06,"step":0.01,"label":"Sales"},{"key":"variable_costs","type":"number","required":true,"min":0,"step":0.01,"label":"Variable costs"}],"submitLabel":"Calculate"}'::jsonb,8305),
('business-customer-acquisition-cost-calculator','حاسبة تكلفة اكتساب العميل','Customer Acquisition Cost Calculator','احسب متوسط تكلفة اكتساب عميل جديد.','Calculate average customer acquisition cost.','{"expression":"marketing_spend / new_customers","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"تكلفة اكتساب العميل","resultLabelEn":"Customer acquisition cost","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"marketing_spend","type":"number","required":true,"min":0,"step":0.01,"label":"الإنفاق التسويقي"},{"key":"new_customers","type":"number","required":true,"min":1e-06,"step":1,"label":"العملاء الجدد"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"marketing_spend","type":"number","required":true,"min":0,"step":0.01,"label":"Marketing spend"},{"key":"new_customers","type":"number","required":true,"min":1e-06,"step":1,"label":"New customers"}],"submitLabel":"Calculate"}'::jsonb,8306),
('simple-customer-lifetime-value','حاسبة قيمة العميل التقديرية','Simple Customer Lifetime Value','قدّر قيمة العميل من متوسط الطلب وعدد الطلبات والسنوات وهامش الربح.','Estimate customer lifetime value from order value, purchase frequency, years, and margin.','{"expression":"average_order_value * orders_per_year * years * margin_rate / 100","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"قيمة العميل التقديرية","resultLabelEn":"Estimated customer lifetime value","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"average_order_value","type":"number","required":true,"min":0,"step":0.01,"label":"متوسط قيمة الطلب"},{"key":"orders_per_year","type":"number","required":true,"min":0,"step":0.01,"label":"عدد الطلبات سنويًا"},{"key":"years","type":"number","required":true,"min":0,"step":0.01,"label":"مدة العلاقة بالسنوات"},{"key":"margin_rate","type":"number","required":true,"min":0,"max":100,"step":0.01,"label":"هامش الربح %"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"average_order_value","type":"number","required":true,"min":0,"step":0.01,"label":"Average order value"},{"key":"orders_per_year","type":"number","required":true,"min":0,"step":0.01,"label":"Orders per year"},{"key":"years","type":"number","required":true,"min":0,"step":0.01,"label":"Relationship years"},{"key":"margin_rate","type":"number","required":true,"min":0,"max":100,"step":0.01,"label":"Margin %"}],"submitLabel":"Calculate"}'::jsonb,8307),
('customer-churn-rate-calculator','حاسبة معدل فقد العملاء','Customer Churn Rate Calculator','احسب نسبة العملاء المفقودين من قاعدة العملاء عند بداية الفترة.','Calculate customer churn as lost customers divided by starting customers.','{"expression":"lost_customers / starting_customers * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"معدل فقد العملاء","resultLabelEn":"Customer churn rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"lost_customers","type":"number","required":true,"min":0,"step":1,"label":"العملاء المفقودون"},{"key":"starting_customers","type":"number","required":true,"min":1e-06,"step":1,"label":"العملاء في بداية الفترة"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"lost_customers","type":"number","required":true,"min":0,"step":1,"label":"Lost customers"},{"key":"starting_customers","type":"number","required":true,"min":1e-06,"step":1,"label":"Starting customers"}],"submitLabel":"Calculate"}'::jsonb,8308),
('customer-retention-rate-calculator','حاسبة معدل الاحتفاظ بالعملاء','Customer Retention Rate Calculator','احسب نسبة العملاء المحتفظ بهم بعد استبعاد العملاء الجدد.','Calculate retention rate after excluding newly acquired customers.','{"expression":"(ending_customers - new_customers) / starting_customers * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"معدل الاحتفاظ","resultLabelEn":"Retention rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"ending_customers","type":"number","required":true,"min":0,"step":1,"label":"العملاء في نهاية الفترة"},{"key":"new_customers","type":"number","required":true,"min":0,"step":1,"label":"العملاء الجدد"},{"key":"starting_customers","type":"number","required":true,"min":1e-06,"step":1,"label":"العملاء في بداية الفترة"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"ending_customers","type":"number","required":true,"min":0,"step":1,"label":"Ending customers"},{"key":"new_customers","type":"number","required":true,"min":0,"step":1,"label":"New customers"},{"key":"starting_customers","type":"number","required":true,"min":1e-06,"step":1,"label":"Starting customers"}],"submitLabel":"Calculate"}'::jsonb,8309),
('capacity-utilization-calculator','حاسبة استغلال الطاقة التشغيلية','Capacity Utilization Calculator','احسب نسبة الإنتاج الفعلي إلى الطاقة القصوى.','Calculate actual output as a percentage of maximum capacity.','{"expression":"actual_output / max_capacity * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة استغلال الطاقة","resultLabelEn":"Capacity utilization","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"actual_output","type":"number","required":true,"min":0,"step":0.01,"label":"الإنتاج الفعلي"},{"key":"max_capacity","type":"number","required":true,"min":1e-06,"step":0.01,"label":"الطاقة القصوى"}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"actual_output","type":"number","required":true,"min":0,"step":0.01,"label":"Actual output"},{"key":"max_capacity","type":"number","required":true,"min":1e-06,"step":0.01,"label":"Maximum capacity"}],"submitLabel":"Calculate"}'::jsonb,8310);

insert into public.tools(slug,title_ar,title_en,short_description,category_id,engine_type,input_schema,output_schema,runtime_config,provider_strategy,model_alias,prompt_template,pricing_mode,fixed_points,minimum_points,cost_multiplier,requires_auth,is_featured,is_active,sort_order,seo_title,seo_description)
select s.slug,s.title_ar,s.title_en,s.description_ar,c.id,'formula'::public.tool_engine_type,s.schema_ar,'{}'::jsonb,s.runtime_config,'primary_with_fallback'::public.provider_strategy_type,null,null,'free'::public.pricing_mode_type,0,0,1,false,false,true,s.sort_order,s.title_ar,s.description_ar
from w3_seed s join public.categories c on c.slug='business-tools'
on conflict(slug) do update set title_ar=excluded.title_ar,title_en=excluded.title_en,short_description=excluded.short_description,category_id=excluded.category_id,engine_type=excluded.engine_type,input_schema=excluded.input_schema,output_schema=excluded.output_schema,runtime_config=excluded.runtime_config,model_alias=null,prompt_template=null,pricing_mode='free'::public.pricing_mode_type,fixed_points=0,minimum_points=0,cost_multiplier=1,requires_auth=false,is_featured=false,is_active=true,sort_order=excluded.sort_order,seo_title=excluded.seo_title,seo_description=excluded.seo_description,updated_at=now();

insert into public.tool_translations(tool_id,locale_id,title,short_description,seo_title,seo_description,prompt_template_override)
select t.id,l.id,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,null
from w3_seed s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id) do update set title=excluded.title,short_description=excluded.short_description,seo_title=excluded.seo_title,seo_description=excluded.seo_description,prompt_template_override=null,updated_at=now();

insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,f->>'key',f->>'label',nullif(f->>'placeholder',''),nullif(f->>'helpText',''),f->'options'
from w3_seed s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
cross join lateral jsonb_array_elements(case when l.code='ar' then s.schema_ar->'fields' else s.schema_en->'fields' end) f
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,placeholder=excluded.placeholder,help_text=excluded.help_text,options=excluded.options,updated_at=now();

insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,'__submit__',case when l.code='ar' then s.schema_ar->>'submitLabel' else s.schema_en->>'submitLabel' end,null,null,null
from w3_seed s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,updated_at=now();
commit;
