-- Web Empire Wave15 — Rental + Franchise (20 tools)
select public._wave15_upsert_formula_tools('rental-business-tools',$json$[
{"slug":"rental-asset-revenue-yield-rate-calculator","title_ar":"حاسبة عائد الإيراد على أصل التأجير","title_en":"Rental Asset Revenue Yield Rate Calculator","expression":"annual_rental_revenue / asset_value * 100","fields":[{"key":"annual_rental_revenue","ar":"إيراد التأجير السنوي","en":"Annual rental revenue","min":0},{"key":"asset_value","ar":"قيمة الأصل","en":"Asset value","min":0.000001}],"sort_order":33601},
{"slug":"rental-booking-lead-time-calculator","title_ar":"حاسبة متوسط مدة الحجز المسبق للتأجير","title_en":"Rental Booking Lead Time Calculator","expression":"advance_days / bookings","fields":[{"key":"advance_days","ar":"إجمالي أيام الحجز المسبق","en":"Advance booking days","min":0},{"key":"bookings","ar":"عدد الحجوزات","en":"Bookings","min":0.000001}],"sort_order":33602},
{"slug":"rental-cleaning-cost-share-calculator","title_ar":"حاسبة حصة تكلفة التنظيف من الإيراد","title_en":"Rental Cleaning Cost Share Calculator","expression":"cleaning_cost / rental_revenue * 100","fields":[{"key":"cleaning_cost","ar":"تكلفة التنظيف","en":"Cleaning cost","min":0},{"key":"rental_revenue","ar":"إيراد التأجير","en":"Rental revenue","min":0.000001}],"sort_order":33603},
{"slug":"rental-idle-cost-per-day-calculator","title_ar":"حاسبة تكلفة الخمول لكل يوم","title_en":"Rental Idle Cost per Day Calculator","expression":"idle_cost / idle_days","fields":[{"key":"idle_cost","ar":"تكلفة الخمول","en":"Idle cost","min":0},{"key":"idle_days","ar":"أيام الخمول","en":"Idle days","min":0.000001}],"sort_order":33604},
{"slug":"rental-repair-cost-share-calculator","title_ar":"حاسبة حصة تكلفة الإصلاح من الإيراد","title_en":"Rental Repair Cost Share Calculator","expression":"repair_cost / rental_revenue * 100","fields":[{"key":"repair_cost","ar":"تكلفة الإصلاح","en":"Repair cost","min":0},{"key":"rental_revenue","ar":"إيراد التأجير","en":"Rental revenue","min":0.000001}],"sort_order":33605},
{"slug":"rental-extension-revenue-share-calculator","title_ar":"حاسبة حصة إيراد تمديد التأجير","title_en":"Rental Extension Revenue Share Calculator","expression":"extension_revenue / rental_revenue * 100","fields":[{"key":"extension_revenue","ar":"إيراد التمديدات","en":"Extension revenue","min":0},{"key":"rental_revenue","ar":"إجمالي إيراد التأجير","en":"Rental revenue","min":0.000001}],"sort_order":33606},
{"slug":"rental-cancellation-loss-calculator","title_ar":"حاسبة خسارة إلغاءات التأجير","title_en":"Rental Cancellation Loss Calculator","expression":"cancelled_bookings * average_booking_value","fields":[{"key":"cancelled_bookings","ar":"الحجوزات الملغاة","en":"Cancelled bookings","min":0},{"key":"average_booking_value","ar":"متوسط قيمة الحجز","en":"Average booking value","min":0}],"sort_order":33607},
{"slug":"rental-utilized-days-per-asset-calculator","title_ar":"حاسبة الأيام المستخدمة لكل أصل","title_en":"Rental Utilized Days per Asset Calculator","expression":"utilized_days / assets","fields":[{"key":"utilized_days","ar":"إجمالي الأيام المستخدمة","en":"Utilized days","min":0},{"key":"assets","ar":"عدد الأصول","en":"Assets","min":0.000001}],"sort_order":33608},
{"slug":"rental-delivery-cost-share-calculator","title_ar":"حاسبة حصة تكلفة التسليم من الإيراد","title_en":"Rental Delivery Cost Share Calculator","expression":"delivery_cost / rental_revenue * 100","fields":[{"key":"delivery_cost","ar":"تكلفة التسليم","en":"Delivery cost","min":0},{"key":"rental_revenue","ar":"إيراد التأجير","en":"Rental revenue","min":0.000001}],"sort_order":33609},
{"slug":"rental-revenue-per-utilized-day-calculator","title_ar":"حاسبة إيراد التأجير لكل يوم مستخدم","title_en":"Rental Revenue per Utilized Day Calculator","expression":"rental_revenue / utilized_days","fields":[{"key":"rental_revenue","ar":"إيراد التأجير","en":"Rental revenue","min":0},{"key":"utilized_days","ar":"الأيام المستخدمة","en":"Utilized days","min":0.000001}],"sort_order":33610}
]$json$::jsonb);

select public._wave15_upsert_formula_tools('franchise-tools',$json$[
{"slug":"franchise-royalty-revenue-share-calculator","title_ar":"حاسبة حصة رسوم الامتياز من الإيراد","title_en":"Franchise Royalty Revenue Share Calculator","expression":"royalty_fees / revenue * 100","fields":[{"key":"royalty_fees","ar":"رسوم الامتياز","en":"Royalty fees","min":0},{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0.000001}],"sort_order":33701},
{"slug":"franchise-marketing-fund-rate-calculator","title_ar":"حاسبة نسبة صندوق التسويق من المبيعات","title_en":"Franchise Marketing Fund Rate Calculator","expression":"marketing_fund / sales * 100","fields":[{"key":"marketing_fund","ar":"مساهمة صندوق التسويق","en":"Marketing fund contribution","min":0},{"key":"sales","ar":"المبيعات","en":"Sales","min":0.000001}],"sort_order":33702},
{"slug":"franchise-support-cost-rate-calculator","title_ar":"حاسبة نسبة تكلفة دعم الامتياز","title_en":"Franchise Support Cost Rate Calculator","expression":"support_cost / revenue * 100","fields":[{"key":"support_cost","ar":"تكلفة الدعم","en":"Support cost","min":0},{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0.000001}],"sort_order":33703},
{"slug":"franchise-training-cost-rate-calculator","title_ar":"حاسبة نسبة تكلفة التدريب للامتياز","title_en":"Franchise Training Cost Rate Calculator","expression":"training_cost / revenue * 100","fields":[{"key":"training_cost","ar":"تكلفة التدريب","en":"Training cost","min":0},{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0.000001}],"sort_order":33704},
{"slug":"franchise-location-profit-per-sqm-calculator","title_ar":"حاسبة ربح موقع الامتياز لكل متر مربع","title_en":"Franchise Location Profit per Square Meter Calculator","expression":"location_profit / area_sqm","fields":[{"key":"location_profit","ar":"ربح الموقع","en":"Location profit","min":0},{"key":"area_sqm","ar":"المساحة بالمتر المربع","en":"Area sqm","min":0.000001}],"sort_order":33705},
{"slug":"franchise-average-revenue-per-employee-calculator","title_ar":"حاسبة متوسط إيراد الامتياز لكل موظف","title_en":"Franchise Average Revenue per Employee Calculator","expression":"revenue / employees","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"employees","ar":"عدد الموظفين","en":"Employees","min":0.000001}],"sort_order":33706},
{"slug":"franchise-new-unit-opening-rate-calculator","title_ar":"حاسبة معدل افتتاح وحدات امتياز جديدة","title_en":"Franchise New Unit Opening Rate Calculator","expression":"new_units / starting_units * 100","fields":[{"key":"new_units","ar":"الوحدات الجديدة","en":"New units","min":0},{"key":"starting_units","ar":"الوحدات في بداية الفترة","en":"Starting units","min":0.000001}],"sort_order":33707},
{"slug":"franchise-fee-to-revenue-ratio-calculator","title_ar":"حاسبة نسبة رسوم الامتياز إلى الإيراد","title_en":"Franchise Fee-to-Revenue Ratio Calculator","expression":"franchise_fees / revenue * 100","fields":[{"key":"franchise_fees","ar":"رسوم الامتياز","en":"Franchise fees","min":0},{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0.000001}],"sort_order":33708},
{"slug":"franchise-owner-cash-return-rate-calculator","title_ar":"حاسبة عائد النقد لمالك الامتياز","title_en":"Franchise Owner Cash Return Rate Calculator","expression":"owner_cash_flow / owner_investment * 100","fields":[{"key":"owner_cash_flow","ar":"التدفق النقدي للمالك","en":"Owner cash flow","min":0},{"key":"owner_investment","ar":"استثمار المالك","en":"Owner investment","min":0.000001}],"sort_order":33709},
{"slug":"franchise-multi-unit-revenue-share-calculator","title_ar":"حاسبة حصة إيراد الوحدات المتعددة","title_en":"Franchise Multi-Unit Revenue Share Calculator","expression":"multi_unit_revenue / total_revenue * 100","fields":[{"key":"multi_unit_revenue","ar":"إيراد الوحدات المتعددة","en":"Multi-unit revenue","min":0},{"key":"total_revenue","ar":"إجمالي الإيراد","en":"Total revenue","min":0.000001}],"sort_order":33710}
]$json$::jsonb);
