-- Web Empire Wave 12 — Social Media, WhatsApp, Text (30 deterministic text tools)

select public._wave12_upsert_text_tools('social-media-tools',$json$[
{"slug":"social-mention-prefixer","title_ar":"مضيف @ لقائمة المنشن","title_en":"Social Mention Prefixer","description_ar":"أضف علامة @ قبل كل اسم مستخدم في قائمة.","description_en":"Add @ before every username in a list.","operations":[{"type":"line_prefix","value":"@"}],"input_fields":[{"key":"text","label":"أسماء المستخدمين","type":"textarea","required":true,"maxLength":20000}],"english_fields":[{"key":"text","label":"Usernames","type":"textarea","required":true,"maxLength":20000}],"submit_ar":"أضف @","submit_en":"Add @","sort_order":33301},
{"slug":"social-mention-deduplicator","title_ar":"حذف تكرار قائمة المنشن","title_en":"Social Mention Deduplicator","description_ar":"احذف أسماء المستخدمين المكررة من قائمة المنشن.","description_en":"Remove duplicate usernames from a mention list.","operations":[{"type":"unique_lines"}],"input_fields":[{"key":"text","label":"قائمة المنشن","type":"textarea","required":true,"maxLength":20000}],"english_fields":[{"key":"text","label":"Mention list","type":"textarea","required":true,"maxLength":20000}],"submit_ar":"احذف التكرار","submit_en":"Remove duplicates","sort_order":33302},
{"slug":"social-mention-sorter","title_ar":"مرتب قائمة المنشن","title_en":"Social Mention Sorter","description_ar":"احذف التكرار ورتب أسماء المستخدمين أبجديًا.","description_en":"Deduplicate and sort usernames alphabetically.","operations":[{"type":"unique_lines"},{"type":"sort_lines","direction":"asc"}],"input_fields":[{"key":"text","label":"قائمة المنشن","type":"textarea","required":true,"maxLength":20000}],"english_fields":[{"key":"text","label":"Mention list","type":"textarea","required":true,"maxLength":20000}],"submit_ar":"رتب القائمة","submit_en":"Sort list","sort_order":33303},
{"slug":"social-link-list-deduplicator","title_ar":"حذف تكرار روابط السوشال","title_en":"Social Link List Deduplicator","description_ar":"احذف الروابط المكررة من قائمة روابط الحسابات والمنشورات.","description_en":"Remove duplicate social profile or post links.","operations":[{"type":"unique_lines"}],"input_fields":[{"key":"text","label":"الروابط","type":"textarea","required":true,"maxLength":30000}],"english_fields":[{"key":"text","label":"Links","type":"textarea","required":true,"maxLength":30000}],"submit_ar":"احذف التكرار","submit_en":"Deduplicate","sort_order":33304},
{"slug":"social-link-list-sorter","title_ar":"مرتب روابط السوشال","title_en":"Social Link List Sorter","description_ar":"نظّف روابط السوشال ورتبها أبجديًا.","description_en":"Deduplicate and sort social links alphabetically.","operations":[{"type":"unique_lines"},{"type":"sort_lines","direction":"asc"}],"input_fields":[{"key":"text","label":"الروابط","type":"textarea","required":true,"maxLength":30000}],"english_fields":[{"key":"text","label":"Links","type":"textarea","required":true,"maxLength":30000}],"submit_ar":"نظّف ورتب","submit_en":"Clean and sort","sort_order":33305},
{"slug":"caption-line-collapser","title_ar":"ضاغط أسطر الكابشن","title_en":"Caption Line Collapser","description_ar":"قلل فواصل الأسطر الزائدة في الكابشن مع الحفاظ على النص.","description_en":"Collapse excessive line breaks in a caption.","operations":[{"type":"collapse_lines"}],"input_fields":[{"key":"text","label":"الكابشن","type":"textarea","required":true,"maxLength":20000}],"english_fields":[{"key":"text","label":"Caption","type":"textarea","required":true,"maxLength":20000}],"submit_ar":"اضغط الأسطر","submit_en":"Collapse lines","sort_order":33306},
{"slug":"caption-punctuation-cleaner","title_ar":"منظف علامات الترقيم من الكابشن","title_en":"Caption Punctuation Cleaner","description_ar":"احذف علامات الترقيم من الكابشن ونظّف المسافات الناتجة.","description_en":"Remove punctuation from a caption and clean spacing.","operations":[{"type":"remove_punctuation"},{"type":"collapse_whitespace"}],"input_fields":[{"key":"text","label":"الكابشن","type":"textarea","required":true,"maxLength":20000}],"english_fields":[{"key":"text","label":"Caption","type":"textarea","required":true,"maxLength":20000}],"submit_ar":"نظّف الكابشن","submit_en":"Clean caption","sort_order":33307},
{"slug":"arabic-caption-diacritics-remover","title_ar":"حذف تشكيل الكابشن العربي","title_en":"Arabic Caption Diacritics Remover","description_ar":"احذف التشكيل والحركات من الكابشن العربي.","description_en":"Remove Arabic diacritics from captions.","operations":[{"type":"remove_diacritics"}],"input_fields":[{"key":"text","label":"الكابشن العربي","type":"textarea","required":true,"maxLength":20000}],"english_fields":[{"key":"text","label":"Arabic caption","type":"textarea","required":true,"maxLength":20000}],"submit_ar":"احذف التشكيل","submit_en":"Remove diacritics","sort_order":33308},
{"slug":"social-caption-line-prefixer","title_ar":"مضيف بادئة لأسطر الكابشن","title_en":"Caption Line Prefixer","description_ar":"أضف رمزًا أو كلمة مخصصة قبل كل سطر من الكابشن.","description_en":"Add a custom prefix before each caption line.","operations":[{"type":"line_prefix","value_key":"prefix"}],"input_fields":[{"key":"text","label":"الكابشن","type":"textarea","required":true,"maxLength":20000},{"key":"prefix","label":"البادئة","type":"text","required":true,"maxLength":50,"defaultValue":"• "}],"english_fields":[{"key":"text","label":"Caption","type":"textarea","required":true,"maxLength":20000},{"key":"prefix","label":"Prefix","type":"text","required":true,"maxLength":50,"defaultValue":"• "}],"submit_ar":"أضف البادئة","submit_en":"Add prefix","sort_order":33309},
{"slug":"social-caption-line-suffixer","title_ar":"مضيف لاحقة لأسطر الكابشن","title_en":"Caption Line Suffixer","description_ar":"أضف رمزًا أو نصًا مخصصًا بعد كل سطر من الكابشن.","description_en":"Add a custom suffix after each caption line.","operations":[{"type":"line_suffix","value_key":"suffix"}],"input_fields":[{"key":"text","label":"الكابشن","type":"textarea","required":true,"maxLength":20000},{"key":"suffix","label":"اللاحقة","type":"text","required":true,"maxLength":50,"defaultValue":" ✨"}],"english_fields":[{"key":"text","label":"Caption","type":"textarea","required":true,"maxLength":20000},{"key":"suffix","label":"Suffix","type":"text","required":true,"maxLength":50,"defaultValue":" ✨"}],"submit_ar":"أضف اللاحقة","submit_en":"Add suffix","sort_order":33310}
]$json$::jsonb);

select public._wave12_upsert_text_tools('whatsapp-tools',$json$[
{"slug":"whatsapp-bullet-list-formatter","title_ar":"منسق قائمة واتساب بالنقاط","title_en":"WhatsApp Bullet List Formatter","description_ar":"حوّل الأسطر إلى قائمة واتساب واضحة باستخدام النقاط.","description_en":"Format lines as a clean WhatsApp bullet list.","operations":[{"type":"line_prefix","value":"• "}],"input_fields":[{"key":"text","label":"عناصر القائمة","type":"textarea","required":true,"maxLength":20000}],"english_fields":[{"key":"text","label":"List items","type":"textarea","required":true,"maxLength":20000}],"submit_ar":"نسّق القائمة","submit_en":"Format list","sort_order":33401},
{"slug":"whatsapp-arrow-list-formatter","title_ar":"منسق قائمة واتساب بالأسهم","title_en":"WhatsApp Arrow List Formatter","description_ar":"أضف سهمًا قبل كل عنصر في قائمة واتساب.","description_en":"Add an arrow before each WhatsApp list item.","operations":[{"type":"line_prefix","value":"➤ "}],"input_fields":[{"key":"text","label":"عناصر القائمة","type":"textarea","required":true,"maxLength":20000}],"english_fields":[{"key":"text","label":"List items","type":"textarea","required":true,"maxLength":20000}],"submit_ar":"أضف الأسهم","submit_en":"Add arrows","sort_order":33402},
{"slug":"whatsapp-checklist-formatter","title_ar":"منسق قائمة تحقق واتساب","title_en":"WhatsApp Checklist Formatter","description_ar":"أضف علامة تحقق قبل كل بند لإرساله في واتساب.","description_en":"Add a check mark before each item for WhatsApp.","operations":[{"type":"line_prefix","value":"✓ "}],"input_fields":[{"key":"text","label":"البنود","type":"textarea","required":true,"maxLength":20000}],"english_fields":[{"key":"text","label":"Items","type":"textarea","required":true,"maxLength":20000}],"submit_ar":"أنشئ قائمة تحقق","submit_en":"Create checklist","sort_order":33403},
{"slug":"whatsapp-contact-deduplicator","title_ar":"حذف تكرار قائمة جهات واتساب","title_en":"WhatsApp Contact Deduplicator","description_ar":"احذف الأسطر المكررة من قائمة جهات اتصال أو أرقام واتساب.","description_en":"Remove duplicate lines from a WhatsApp contact or number list.","operations":[{"type":"unique_lines"}],"input_fields":[{"key":"text","label":"قائمة الجهات أو الأرقام","type":"textarea","required":true,"maxLength":30000}],"english_fields":[{"key":"text","label":"Contacts or numbers","type":"textarea","required":true,"maxLength":30000}],"submit_ar":"احذف التكرار","submit_en":"Remove duplicates","sort_order":33404},
{"slug":"whatsapp-contact-sorter","title_ar":"مرتب قائمة جهات واتساب","title_en":"WhatsApp Contact Sorter","description_ar":"احذف التكرار ورتب قائمة جهات واتساب تصاعديًا.","description_en":"Deduplicate and sort a WhatsApp contact list.","operations":[{"type":"unique_lines"},{"type":"sort_lines","direction":"asc"}],"input_fields":[{"key":"text","label":"قائمة الجهات أو الأرقام","type":"textarea","required":true,"maxLength":30000}],"english_fields":[{"key":"text","label":"Contacts or numbers","type":"textarea","required":true,"maxLength":30000}],"submit_ar":"نظّف ورتب","submit_en":"Clean and sort","sort_order":33405},
{"slug":"whatsapp-template-line-prefixer","title_ar":"مضيف بادئة لأسطر قالب واتساب","title_en":"WhatsApp Template Line Prefixer","description_ar":"أضف رمزًا أو كلمة قبل كل سطر في قالب رسالة واتساب.","description_en":"Add a custom prefix before each line of a WhatsApp template.","operations":[{"type":"line_prefix","value_key":"prefix"}],"input_fields":[{"key":"text","label":"قالب الرسالة","type":"textarea","required":true,"maxLength":20000},{"key":"prefix","label":"البادئة","type":"text","required":true,"maxLength":100,"defaultValue":"• "}],"english_fields":[{"key":"text","label":"Message template","type":"textarea","required":true,"maxLength":20000},{"key":"prefix","label":"Prefix","type":"text","required":true,"maxLength":100,"defaultValue":"• "}],"submit_ar":"أضف البادئة","submit_en":"Add prefix","sort_order":33406},
{"slug":"whatsapp-template-line-suffixer","title_ar":"مضيف لاحقة لأسطر قالب واتساب","title_en":"WhatsApp Template Line Suffixer","description_ar":"أضف نصًا أو رمزًا بعد كل سطر في قالب واتساب.","description_en":"Add a custom suffix after each WhatsApp template line.","operations":[{"type":"line_suffix","value_key":"suffix"}],"input_fields":[{"key":"text","label":"قالب الرسالة","type":"textarea","required":true,"maxLength":20000},{"key":"suffix","label":"اللاحقة","type":"text","required":true,"maxLength":100,"defaultValue":" ✓"}],"english_fields":[{"key":"text","label":"Message template","type":"textarea","required":true,"maxLength":20000},{"key":"suffix","label":"Suffix","type":"text","required":true,"maxLength":100,"defaultValue":" ✓"}],"submit_ar":"أضف اللاحقة","submit_en":"Add suffix","sort_order":33407},
{"slug":"whatsapp-broadcast-clean-sort","title_ar":"منظف ومرتب قائمة بث واتساب","title_en":"WhatsApp Broadcast Clean Sort","description_ar":"احذف التكرار ورتب قائمة البث لتسهيل المراجعة اليدوية.","description_en":"Deduplicate and sort a broadcast list for easier review.","operations":[{"type":"unique_lines"},{"type":"sort_lines","direction":"asc"}],"input_fields":[{"key":"text","label":"قائمة البث","type":"textarea","required":true,"maxLength":30000}],"english_fields":[{"key":"text","label":"Broadcast list","type":"textarea","required":true,"maxLength":30000}],"submit_ar":"نظّف ورتب","submit_en":"Clean and sort","sort_order":33408},
{"slug":"whatsapp-message-line-collapser","title_ar":"ضاغط فواصل رسالة واتساب","title_en":"WhatsApp Message Line Collapser","description_ar":"قلل فواصل الأسطر الزائدة في رسالة واتساب.","description_en":"Collapse excessive line breaks in a WhatsApp message.","operations":[{"type":"collapse_lines"}],"input_fields":[{"key":"text","label":"الرسالة","type":"textarea","required":true,"maxLength":20000}],"english_fields":[{"key":"text","label":"Message","type":"textarea","required":true,"maxLength":20000}],"submit_ar":"اضغط الأسطر","submit_en":"Collapse lines","sort_order":33409},
{"slug":"whatsapp-message-punctuation-cleaner","title_ar":"منظف ترقيم رسالة واتساب","title_en":"WhatsApp Message Punctuation Cleaner","description_ar":"احذف علامات الترقيم ونظف المسافات في رسالة واتساب.","description_en":"Remove punctuation and clean spacing in a WhatsApp message.","operations":[{"type":"remove_punctuation"},{"type":"collapse_whitespace"}],"input_fields":[{"key":"text","label":"الرسالة","type":"textarea","required":true,"maxLength":20000}],"english_fields":[{"key":"text","label":"Message","type":"textarea","required":true,"maxLength":20000}],"submit_ar":"نظّف الرسالة","submit_en":"Clean message","sort_order":33410}
]$json$::jsonb);

select public._wave12_upsert_text_tools('text-tools',$json$[
{"slug":"line-suffix-adder","title_ar":"مضيف لاحقة لكل سطر","title_en":"Line Suffix Adder","description_ar":"أضف نصًا مخصصًا بعد كل سطر.","description_en":"Add custom text after every line.","operations":[{"type":"line_suffix","value_key":"suffix"}],"input_fields":[{"key":"text","label":"النص","type":"textarea","required":true,"maxLength":20000},{"key":"suffix","label":"اللاحقة","type":"text","required":true,"maxLength":200}],"english_fields":[{"key":"text","label":"Text","type":"textarea","required":true,"maxLength":20000},{"key":"suffix","label":"Suffix","type":"text","required":true,"maxLength":200}],"submit_ar":"أضف اللاحقة","submit_en":"Add suffix","sort_order":33501},
{"slug":"line-descending-sorter","title_ar":"مرتب الأسطر تنازليًا","title_en":"Descending Line Sorter","description_ar":"رتب أسطر النص ترتيبًا تنازليًا.","description_en":"Sort text lines in descending order.","operations":[{"type":"sort_lines","direction":"desc"}],"input_fields":[{"key":"text","label":"الأسطر","type":"textarea","required":true,"maxLength":20000}],"english_fields":[{"key":"text","label":"Lines","type":"textarea","required":true,"maxLength":20000}],"submit_ar":"رتب تنازليًا","submit_en":"Sort descending","sort_order":33502},
{"slug":"line-clean-sorter","title_ar":"منظف ومرتب الأسطر","title_en":"Clean Line Sorter","description_ar":"احذف الأسطر المكررة ثم رتبها تصاعديًا.","description_en":"Remove duplicate lines and sort ascending.","operations":[{"type":"unique_lines"},{"type":"sort_lines","direction":"asc"}],"input_fields":[{"key":"text","label":"الأسطر","type":"textarea","required":true,"maxLength":20000}],"english_fields":[{"key":"text","label":"Lines","type":"textarea","required":true,"maxLength":20000}],"submit_ar":"نظّف ورتب","submit_en":"Clean and sort","sort_order":33503},
{"slug":"html-strip-to-text","title_ar":"محول HTML إلى نص نظيف","title_en":"HTML Strip to Text","description_ar":"احذف وسوم HTML ونظف المسافات لإنتاج نص مقروء.","description_en":"Strip HTML tags and clean whitespace into readable text.","operations":[{"type":"strip_html"},{"type":"collapse_whitespace"}],"input_fields":[{"key":"text","label":"HTML أو النص","type":"textarea","required":true,"maxLength":30000}],"english_fields":[{"key":"text","label":"HTML or text","type":"textarea","required":true,"maxLength":30000}],"submit_ar":"حوّل إلى نص","submit_en":"Convert to text","sort_order":33504},
{"slug":"arabic-clean-text","title_ar":"منظف النص العربي الشامل","title_en":"Arabic Clean Text","description_ar":"وحّد الحروف العربية واحذف التشكيل ونظف المسافات.","description_en":"Normalize Arabic, remove diacritics, and clean whitespace.","operations":[{"type":"normalize_arabic"},{"type":"remove_diacritics"},{"type":"collapse_whitespace"}],"input_fields":[{"key":"text","label":"النص العربي","type":"textarea","required":true,"maxLength":30000}],"english_fields":[{"key":"text","label":"Arabic text","type":"textarea","required":true,"maxLength":30000}],"submit_ar":"نظّف النص","submit_en":"Clean text","sort_order":33505},
{"slug":"compact-line-breaks","title_ar":"مضغوط فواصل الأسطر","title_en":"Compact Line Breaks","description_ar":"قلل فواصل الأسطر المتكررة في النصوص الطويلة.","description_en":"Collapse repeated line breaks in long text.","operations":[{"type":"collapse_lines"}],"input_fields":[{"key":"text","label":"النص","type":"textarea","required":true,"maxLength":30000}],"english_fields":[{"key":"text","label":"Text","type":"textarea","required":true,"maxLength":30000}],"submit_ar":"اضغط الفواصل","submit_en":"Compact breaks","sort_order":33506},
{"slug":"text-whitespace-remover","title_ar":"حذف جميع المسافات من النص","title_en":"Text Whitespace Remover","description_ar":"احذف جميع المسافات البيضاء من النص عند الحاجة لصيغة مضغوطة.","description_en":"Remove all whitespace from text for a compact representation.","operations":[{"type":"remove_whitespace"}],"input_fields":[{"key":"text","label":"النص","type":"textarea","required":true,"maxLength":30000}],"english_fields":[{"key":"text","label":"Text","type":"textarea","required":true,"maxLength":30000}],"submit_ar":"احذف المسافات","submit_en":"Remove whitespace","sort_order":33507},
{"slug":"text-line-wrapper","title_ar":"مغلف كل سطر ببادئة ولاحقة","title_en":"Text Line Wrapper","description_ar":"أضف بادئة ولاحقة مخصصتين لكل سطر في النص.","description_en":"Wrap every line with custom prefix and suffix text.","operations":[{"type":"line_prefix","value_key":"prefix"},{"type":"line_suffix","value_key":"suffix"}],"input_fields":[{"key":"text","label":"النص","type":"textarea","required":true,"maxLength":30000},{"key":"prefix","label":"البادئة","type":"text","required":false,"maxLength":100},{"key":"suffix","label":"اللاحقة","type":"text","required":false,"maxLength":100}],"english_fields":[{"key":"text","label":"Text","type":"textarea","required":true,"maxLength":30000},{"key":"prefix","label":"Prefix","type":"text","required":false,"maxLength":100},{"key":"suffix","label":"Suffix","type":"text","required":false,"maxLength":100}],"submit_ar":"غلّف الأسطر","submit_en":"Wrap lines","sort_order":33508},
{"slug":"text-unique-bullet-list","title_ar":"قائمة نقاط بدون تكرار","title_en":"Unique Bullet List","description_ar":"احذف الأسطر المكررة وحول الباقي إلى قائمة نقاط.","description_en":"Deduplicate lines and format them as a bullet list.","operations":[{"type":"unique_lines"},{"type":"line_prefix","value":"• "}],"input_fields":[{"key":"text","label":"العناصر","type":"textarea","required":true,"maxLength":30000}],"english_fields":[{"key":"text","label":"Items","type":"textarea","required":true,"maxLength":30000}],"submit_ar":"أنشئ القائمة","submit_en":"Create list","sort_order":33509},
{"slug":"text-sorted-bullet-list","title_ar":"قائمة نقاط مرتبة بدون تكرار","title_en":"Sorted Unique Bullet List","description_ar":"احذف التكرار ورتب العناصر ثم نسقها كنقاط.","description_en":"Deduplicate, sort, and format items as bullets.","operations":[{"type":"unique_lines"},{"type":"sort_lines","direction":"asc"},{"type":"line_prefix","value":"• "}],"input_fields":[{"key":"text","label":"العناصر","type":"textarea","required":true,"maxLength":30000}],"english_fields":[{"key":"text","label":"Items","type":"textarea","required":true,"maxLength":30000}],"submit_ar":"رتب وأنشئ القائمة","submit_en":"Sort and format","sort_order":33510}
]$json$::jsonb);
