-- Web Empire — Non-AI catalog growth wave 2 (whatsapp-tools)
begin;
create temporary table whatsapp_tools_w2 (slug text primary key,title_ar text not null,title_en text not null,description_ar text not null,description_en text not null,operations jsonb not null,schema_kind text not null check (schema_kind in ('one','aux','case','style')),input_ar text not null,input_en text not null,submit_ar text not null,submit_en text not null,max_length integer not null,aux_key text,aux_ar text,aux_en text,aux_ph_ar text,aux_ph_en text,sort_order integer not null) on commit drop;
insert into whatsapp_tools_w2 values
('whatsapp-message-stats','إحصاءات رسالة واتساب','WhatsApp Message Stats','احسب الكلمات والأحرف والأسطر في رسالة واتساب.','Count words, characters, and lines in a WhatsApp message.','[{"type":"stats"}]'::jsonb,'one','الرسالة','Message','احسب الإحصاءات','Calculate stats',10000,null,null,null,null,null,7401),
('whatsapp-status-decorator','زخرفة حالة واتساب','WhatsApp Status Decorator','زخرف نص حالة واتساب بأنماط بسيطة قابلة للنسخ.','Decorate WhatsApp status text with simple copy-ready styles.','[{"type":"trim"},{"type":"decorate","style_key":"style"}]'::jsonb,'style','نص الحالة','Status text','زخرف الحالة','Decorate status',10000,null,null,null,null,null,7402),
('whatsapp-arabic-diacritics-remover','إزالة التشكيل من رسالة واتساب','WhatsApp Diacritics Remover','احذف التشكيل العربي من رسالة مع الحفاظ على الحروف.','Remove Arabic diacritics from a message while keeping the letters.','[{"type":"remove_diacritics"}]'::jsonb,'one','الرسالة العربية','Arabic message','أزل التشكيل','Remove diacritics',10000,null,null,null,null,null,7403),
('whatsapp-arabic-normalizer','تطبيع العربية لواتساب','WhatsApp Arabic Normalizer','وحّد أشكال الحروف العربية ونظف المسافات في الرسالة.','Normalize Arabic letter forms and spacing in a message.','[{"type":"normalize_arabic"}]'::jsonb,'one','الرسالة العربية','Arabic message','طبّع الرسالة','Normalize message',10000,null,null,null,null,null,7404),
('whatsapp-phone-link-generator','مولد رابط واتساب من رقم','WhatsApp Phone Link Generator','حوّل رقم الهاتف إلى رابط wa.me مباشر بعد حذف الرموز والمسافات.','Turn a phone number into a direct wa.me link after removing symbols and spaces.','[{"type":"remove_punctuation"},{"type":"remove_whitespace"},{"type":"prefix","value":"https://wa.me/"}]'::jsonb,'one','رقم الهاتف مع رمز الدولة','Phone number with country code','أنشئ الرابط','Generate link',100,null,null,null,null,null,7405),
('whatsapp-broadcast-sorter','ترتيب قائمة بث واتساب','WhatsApp Broadcast Sorter','رتب قائمة أسماء أو أرقام البث أبجديًا.','Sort a WhatsApp broadcast list alphabetically.','[{"type":"sort_lines","direction":"asc"}]'::jsonb,'one','قائمة البث','Broadcast list','رتب القائمة','Sort list',10000,null,null,null,null,null,7406),
('whatsapp-broadcast-counter','عداد قائمة بث واتساب','WhatsApp Broadcast Counter','احسب عدد الأسطر والعناصر النصية في قائمة البث.','Count lines and text items in a broadcast list.','[{"type":"stats"}]'::jsonb,'one','قائمة البث','Broadcast list','احسب','Count',10000,null,null,null,null,null,7407),
('whatsapp-italic-text','تنسيق مائل لواتساب','WhatsApp Italic Formatter','ضع الشرطة السفلية حول النص لتنسيقه كمائل في واتساب.','Wrap text with underscores for WhatsApp italic formatting.','[{"type":"prefix","value":"_"},{"type":"suffix","value":"_"}]'::jsonb,'one','النص','Text','نسق كمائل','Format italic',10000,null,null,null,null,null,7408),
('whatsapp-strikethrough-text','تنسيق مشطوب لواتساب','WhatsApp Strikethrough Formatter','ضع علامة ~ حول النص لتنسيقه كمشطوب في واتساب.','Wrap text with ~ for WhatsApp strikethrough formatting.','[{"type":"prefix","value":"~"},{"type":"suffix","value":"~"}]'::jsonb,'one','النص','Text','نسق كمشطوب','Format strikethrough',10000,null,null,null,null,null,7409),
('whatsapp-code-text','تنسيق كود لواتساب','WhatsApp Code Formatter','ضع ثلاث علامات اقتباس خلفية حول النص لعرضه ككتلة كود.','Wrap text in triple backticks for WhatsApp code formatting.','[{"type":"prefix","value":"```"},{"type":"suffix","value":"```"}]'::jsonb,'one','النص أو الكود','Text or code','نسق ككود','Format as code',10000,null,null,null,null,null,7410);
create temporary table whatsapp_tools_w2_ready as select seed.*,
jsonb_build_object('fields',case seed.schema_kind when 'one' then jsonb_build_array(jsonb_build_object('key','text','label',seed.input_ar,'type','textarea','required',true,'placeholder','أدخل النص هنا...','maxLength',seed.max_length)) else jsonb_build_array(jsonb_build_object('key','text','label',seed.input_ar,'type','textarea','required',true,'placeholder','أدخل النص هنا...','maxLength',seed.max_length),jsonb_build_object('key','style','label','النمط','type','select','required',true,'defaultValue','sparkles','options','[{"value":"stars","label":"نجوم"},{"value":"sparkles","label":"لمعان"},{"value":"hearts","label":"قلوب"},{"value":"brackets","label":"أقواس"},{"value":"quotes","label":"اقتباس"},{"value":"arrows","label":"أسهم"}]'::jsonb)) end,'submitLabel',seed.submit_ar) schema_ar,
jsonb_build_object('fields',case seed.schema_kind when 'one' then jsonb_build_array(jsonb_build_object('key','text','label',seed.input_en,'type','textarea','required',true,'placeholder','Enter text here...','maxLength',seed.max_length)) else jsonb_build_array(jsonb_build_object('key','text','label',seed.input_en,'type','textarea','required',true,'placeholder','Enter text here...','maxLength',seed.max_length),jsonb_build_object('key','style','label','Style','type','select','required',true,'defaultValue','sparkles','options','[{"value":"stars","label":"Stars"},{"value":"sparkles","label":"Sparkles"},{"value":"hearts","label":"Hearts"},{"value":"brackets","label":"Brackets"},{"value":"quotes","label":"Quotes"},{"value":"arrows","label":"Arrows"}]'::jsonb)) end,'submitLabel',seed.submit_en) schema_en from whatsapp_tools_w2 seed;
insert into public.tools(slug,title_ar,title_en,short_description,category_id,engine_type,input_schema,output_schema,runtime_config,provider_strategy,model_alias,prompt_template,pricing_mode,fixed_points,minimum_points,cost_multiplier,requires_auth,is_featured,is_active,sort_order,seo_title,seo_description)
select s.slug,s.title_ar,s.title_en,s.description_ar,c.id,'text_transform'::public.tool_engine_type,s.schema_ar,'{}'::jsonb,jsonb_build_object('input_key','text','operations',s.operations),'primary_with_fallback'::public.provider_strategy_type,null,null,'free'::public.pricing_mode_type,0,0,1,false,false,true,s.sort_order,s.title_ar,s.description_ar from whatsapp_tools_w2_ready s join public.categories c on c.slug='whatsapp-tools'
on conflict(slug) do update set title_ar=excluded.title_ar,title_en=excluded.title_en,short_description=excluded.short_description,category_id=excluded.category_id,engine_type=excluded.engine_type,input_schema=excluded.input_schema,output_schema=excluded.output_schema,runtime_config=excluded.runtime_config,model_alias=null,prompt_template=null,pricing_mode='free'::public.pricing_mode_type,fixed_points=0,minimum_points=0,cost_multiplier=1,requires_auth=false,is_featured=false,is_active=true,sort_order=excluded.sort_order,seo_title=excluded.seo_title,seo_description=excluded.seo_description,updated_at=now();
insert into public.tool_translations(tool_id,locale_id,title,short_description,seo_title,seo_description,prompt_template_override) select t.id,l.id,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,null from whatsapp_tools_w2_ready s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en') on conflict(tool_id,locale_id) do update set title=excluded.title,short_description=excluded.short_description,seo_title=excluded.seo_title,seo_description=excluded.seo_description,prompt_template_override=null,updated_at=now();
insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options) select t.id,l.id,f->>'key',f->>'label',nullif(f->>'placeholder',''),nullif(f->>'helpText',''),f->'options' from whatsapp_tools_w2_ready s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en') cross join lateral jsonb_array_elements(case when l.code='ar' then s.schema_ar->'fields' else s.schema_en->'fields' end) f on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,placeholder=excluded.placeholder,help_text=excluded.help_text,options=excluded.options,updated_at=now();
insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options) select t.id,l.id,'__submit__',case when l.code='ar' then s.submit_ar else s.submit_en end,null,null,null from whatsapp_tools_w2_ready s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en') on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,updated_at=now();
commit;