-- Web Empire wave 14 — Restaurant + Retail (20 tools).
select public._wave14_upsert_formula_tools('restaurant-tools',$json$[
{"slug":"restaurant-revenue-per-cover-calculator","title_ar":"حاسبة إيراد المطعم لكل ضيف","title_en":"Restaurant Revenue per Cover Calculator","expression":"revenue / covers","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"covers","ar":"عدد الضيوف","en":"Covers","min":0.000001}],"sort_order":33801},
{"slug":"restaurant-profit-per-cover-calculator","title_ar":"حاسبة ربح المطعم لكل ضيف","title_en":"Restaurant Profit per Cover Calculator","expression":"profit / covers","fields":[{"key":"profit","ar":"الربح","en":"Profit"},{"key":"covers","ar":"عدد الضيوف","en":"Covers","min":0.000001}],"sort_order":33802},
{"slug":"restaurant-food-cost-per-cover-calculator","title_ar":"حاسبة تكلفة الطعام لكل ضيف","title_en":"Restaurant Food Cost per Cover Calculator","expression":"food_cost / covers","fields":[{"key":"food_cost","ar":"تكلفة الطعام","en":"Food cost","min":0},{"key":"covers","ar":"عدد الضيوف","en":"Covers","min":0.000001}],"sort_order":33803},
{"slug":"restaurant-beverage-revenue-share-calculator","title_ar":"حاسبة حصة إيرادات المشروبات","title_en":"Restaurant Beverage Revenue Share Calculator","expression":"beverage_revenue / total_revenue * 100","fields":[{"key":"beverage_revenue","ar":"إيراد المشروبات","en":"Beverage revenue","min":0},{"key":"total_revenue","ar":"إجمالي الإيراد","en":"Total revenue","min":0.000001}],"sort_order":33804},
{"slug":"restaurant-delivery-fee-cost-share-calculator","title_ar":"حاسبة حصة رسوم منصات التوصيل","title_en":"Restaurant Delivery Fee Cost Share Calculator","expression":"delivery_fees / delivery_revenue * 100","fields":[{"key":"delivery_fees","ar":"رسوم التوصيل والمنصات","en":"Delivery fees","min":0},{"key":"delivery_revenue","ar":"إيراد التوصيل","en":"Delivery revenue","min":0.000001}],"sort_order":33805},
{"slug":"restaurant-discount-rate-calculator","title_ar":"حاسبة معدل خصومات المطعم","title_en":"Restaurant Discount Rate Calculator","expression":"discount_value / gross_sales * 100","fields":[{"key":"discount_value","ar":"قيمة الخصومات","en":"Discount value","min":0},{"key":"gross_sales","ar":"إجمالي المبيعات","en":"Gross sales","min":0.000001}],"sort_order":33806},
{"slug":"restaurant-average-items-per-order-calculator","title_ar":"حاسبة متوسط الأصناف لكل طلب","title_en":"Restaurant Average Items per Order Calculator","expression":"items_sold / orders","fields":[{"key":"items_sold","ar":"الأصناف المباعة","en":"Items sold","min":0},{"key":"orders","ar":"عدد الطلبات","en":"Orders","min":0.000001}],"sort_order":33807},
{"slug":"restaurant-kitchen-output-per-hour-calculator","title_ar":"حاسبة إنتاج المطبخ لكل ساعة","title_en":"Restaurant Kitchen Output per Hour Calculator","expression":"dishes_completed / kitchen_hours","fields":[{"key":"dishes_completed","ar":"الأطباق المكتملة","en":"Dishes completed","min":0},{"key":"kitchen_hours","ar":"ساعات تشغيل المطبخ","en":"Kitchen hours","min":0.000001}],"sort_order":33808},
{"slug":"restaurant-reservation-conversion-rate-calculator","title_ar":"حاسبة تحويل استفسارات المطعم إلى حجوزات","title_en":"Restaurant Reservation Conversion Rate Calculator","expression":"reservations / inquiries * 100","fields":[{"key":"reservations","ar":"الحجوزات","en":"Reservations","min":0},{"key":"inquiries","ar":"استفسارات الحجز","en":"Reservation inquiries","min":0.000001}],"sort_order":33809},
{"slug":"restaurant-tip-rate-calculator","title_ar":"حاسبة نسبة الإكرامية","title_en":"Restaurant Tip Rate Calculator","expression":"tips / bill_total * 100","fields":[{"key":"tips","ar":"الإكرامية","en":"Tips","min":0},{"key":"bill_total","ar":"إجمالي الفاتورة","en":"Bill total","min":0.000001}],"sort_order":33810}
]$json$::jsonb);

select public._wave14_upsert_formula_tools('retail-tools',$json$[
{"slug":"retail-revenue-per-employee-calculator","title_ar":"حاسبة إيراد التجزئة لكل موظف","title_en":"Retail Revenue per Employee Calculator","expression":"revenue / employees","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"employees","ar":"عدد الموظفين","en":"Employees","min":0.000001}],"sort_order":33901},
{"slug":"retail-profit-per-employee-calculator","title_ar":"حاسبة ربح التجزئة لكل موظف","title_en":"Retail Profit per Employee Calculator","expression":"profit / employees","fields":[{"key":"profit","ar":"الربح","en":"Profit"},{"key":"employees","ar":"عدد الموظفين","en":"Employees","min":0.000001}],"sort_order":33902},
{"slug":"retail-rent-cost-rate-calculator","title_ar":"حاسبة نسبة تكلفة الإيجار في التجزئة","title_en":"Retail Rent Cost Rate Calculator","expression":"rent_cost / sales * 100","fields":[{"key":"rent_cost","ar":"تكلفة الإيجار","en":"Rent cost","min":0},{"key":"sales","ar":"المبيعات","en":"Sales","min":0.000001}],"sort_order":33903},
{"slug":"retail-utilities-cost-rate-calculator","title_ar":"حاسبة نسبة تكلفة الخدمات في التجزئة","title_en":"Retail Utilities Cost Rate Calculator","expression":"utilities_cost / sales * 100","fields":[{"key":"utilities_cost","ar":"تكلفة الخدمات","en":"Utilities cost","min":0},{"key":"sales","ar":"المبيعات","en":"Sales","min":0.000001}],"sort_order":33904},
{"slug":"retail-marketing-cost-rate-calculator","title_ar":"حاسبة نسبة تكلفة التسويق في التجزئة","title_en":"Retail Marketing Cost Rate Calculator","expression":"marketing_cost / sales * 100","fields":[{"key":"marketing_cost","ar":"تكلفة التسويق","en":"Marketing cost","min":0},{"key":"sales","ar":"المبيعات","en":"Sales","min":0.000001}],"sort_order":33905},
{"slug":"retail-average-discount-value-calculator","title_ar":"حاسبة متوسط قيمة الخصم في التجزئة","title_en":"Retail Average Discount Value Calculator","expression":"discount_value / discounted_transactions","fields":[{"key":"discount_value","ar":"إجمالي قيمة الخصومات","en":"Total discount value","min":0},{"key":"discounted_transactions","ar":"المعاملات المخفضة","en":"Discounted transactions","min":0.000001}],"sort_order":33906},
{"slug":"retail-inventory-cost-per-sqm-calculator","title_ar":"حاسبة تكلفة المخزون لكل متر مربع","title_en":"Retail Inventory Cost per Square Meter Calculator","expression":"inventory_cost / floor_area_sqm","fields":[{"key":"inventory_cost","ar":"تكلفة المخزون","en":"Inventory cost","min":0},{"key":"floor_area_sqm","ar":"مساحة المتجر م²","en":"Floor area m²","min":0.000001}],"sort_order":33907},
{"slug":"retail-transactions-per-opening-hour-calculator","title_ar":"حاسبة معاملات التجزئة لكل ساعة عمل","title_en":"Retail Transactions per Opening Hour Calculator","expression":"transactions / opening_hours","fields":[{"key":"transactions","ar":"عدد المعاملات","en":"Transactions","min":0},{"key":"opening_hours","ar":"ساعات العمل","en":"Opening hours","min":0.000001}],"sort_order":33908},
{"slug":"retail-revenue-per-transaction-calculator","title_ar":"حاسبة إيراد التجزئة لكل معاملة","title_en":"Retail Revenue per Transaction Calculator","expression":"revenue / transactions","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"transactions","ar":"عدد المعاملات","en":"Transactions","min":0.000001}],"sort_order":33909},
{"slug":"retail-profit-per-opening-hour-calculator","title_ar":"حاسبة ربح التجزئة لكل ساعة عمل","title_en":"Retail Profit per Opening Hour Calculator","expression":"profit / opening_hours","fields":[{"key":"profit","ar":"الربح","en":"Profit"},{"key":"opening_hours","ar":"ساعات العمل","en":"Opening hours","min":0.000001}],"sort_order":33910}
]$json$::jsonb);
