-- Web Empire — Non-AI catalog growth wave 4 (ecommerce-tools)
-- Adds 10 deterministic bilingual formula tools.
-- GitHub staging only until this migration is intentionally applied later.

begin;

create temporary table wave4_ecommerce_tools_seed (
  category_slug text not null,
  slug text primary key,
  title_ar text not null,
  title_en text not null,
  description_ar text not null,
  description_en text not null,
  expression text not null,
  input_fields jsonb not null,
  english_fields jsonb not null,
  submit_ar text not null,
  submit_en text not null,
  sort_order integer not null,
  is_featured boolean not null
) on commit drop;

insert into wave4_ecommerce_tools_seed(
  category_slug, slug, title_ar, title_en, description_ar, description_en,
  expression, input_fields, english_fields, submit_ar, submit_en, sort_order, is_featured
)
values
  ('ecommerce-tools', 'gross-merchandise-value-calculator', 'حاسبة إجمالي قيمة البضائع', 'Gross Merchandise Value Calculator', 'احسب إجمالي قيمة البضائع من عدد الطلبات ومتوسط قيمة الطلب.', 'Calculate gross merchandise value from order count and average order value.', 'orders * average_order_value', '[{"key":"orders","label":"عدد الطلبات","type":"number","required":true,"step":1,"min":0},{"key":"average_order_value","label":"متوسط قيمة الطلب","type":"number","required":true,"step":0.01,"min":0}]'::jsonb, '[{"key":"orders","label":"Orders","type":"number","required":true,"step":1,"min":0},{"key":"average_order_value","label":"Average order value","type":"number","required":true,"step":0.01,"min":0}]'::jsonb, 'احسب', 'Calculate', 8001, false),
  ('ecommerce-tools', 'repeat-purchase-rate-calculator', 'حاسبة معدل تكرار الشراء', 'Repeat Purchase Rate Calculator', 'احسب نسبة العملاء الذين اشتروا أكثر من مرة.', 'Calculate the percentage of customers who purchased more than once.', 'repeat_customers / total_customers * 100', '[{"key":"repeat_customers","label":"العملاء المتكررون","type":"number","required":true,"step":1,"min":0},{"key":"total_customers","label":"إجمالي العملاء","type":"number","required":true,"step":1,"min":1}]'::jsonb, '[{"key":"repeat_customers","label":"Repeat customers","type":"number","required":true,"step":1,"min":0},{"key":"total_customers","label":"Total customers","type":"number","required":true,"step":1,"min":1}]'::jsonb, 'احسب', 'Calculate', 8002, false),
  ('ecommerce-tools', 'customer-retention-rate-basic-calculator', 'حاسبة معدل الاحتفاظ بالعملاء', 'Customer Retention Rate Calculator', 'احسب نسبة العملاء المحتفظ بهم من بداية الفترة.', 'Calculate retained customers as a share of starting customers.', 'retained_customers / starting_customers * 100', '[{"key":"retained_customers","label":"العملاء المحتفظ بهم","type":"number","required":true,"step":1,"min":0},{"key":"starting_customers","label":"عملاء بداية الفترة","type":"number","required":true,"step":1,"min":1}]'::jsonb, '[{"key":"retained_customers","label":"Retained customers","type":"number","required":true,"step":1,"min":0},{"key":"starting_customers","label":"Starting customers","type":"number","required":true,"step":1,"min":1}]'::jsonb, 'احسب', 'Calculate', 8003, false),
  ('ecommerce-tools', 'ecommerce-customer-churn-rate-calculator', 'حاسبة تسرب عملاء المتجر', 'E-commerce Customer Churn Rate Calculator', 'احسب نسبة العملاء المفقودين خلال الفترة.', 'Calculate the share of starting customers lost during the period.', 'lost_customers / starting_customers * 100', '[{"key":"lost_customers","label":"العملاء المفقودون","type":"number","required":true,"step":1,"min":0},{"key":"starting_customers","label":"عملاء بداية الفترة","type":"number","required":true,"step":1,"min":1}]'::jsonb, '[{"key":"lost_customers","label":"Lost customers","type":"number","required":true,"step":1,"min":0},{"key":"starting_customers","label":"Starting customers","type":"number","required":true,"step":1,"min":1}]'::jsonb, 'احسب', 'Calculate', 8004, false),
  ('ecommerce-tools', 'product-page-conversion-rate-calculator', 'حاسبة تحويل صفحة المنتج', 'Product Page Conversion Rate Calculator', 'احسب نسبة المشتريات إلى مشاهدات صفحة المنتج.', 'Calculate purchases as a percentage of product page views.', 'purchases / product_page_views * 100', '[{"key":"purchases","label":"المشتريات","type":"number","required":true,"step":1,"min":0},{"key":"product_page_views","label":"مشاهدات صفحة المنتج","type":"number","required":true,"step":1,"min":1}]'::jsonb, '[{"key":"purchases","label":"Purchases","type":"number","required":true,"step":1,"min":0},{"key":"product_page_views","label":"Product page views","type":"number","required":true,"step":1,"min":1}]'::jsonb, 'احسب', 'Calculate', 8005, false),
  ('ecommerce-tools', 'checkout-completion-rate-calculator', 'حاسبة إكمال الدفع', 'Checkout Completion Rate Calculator', 'احسب نسبة عمليات الدفع المكتملة إلى عمليات الدفع التي بدأت.', 'Calculate completed checkouts as a percentage of started checkouts.', 'completed_orders / checkouts_started * 100', '[{"key":"completed_orders","label":"الطلبات المكتملة","type":"number","required":true,"step":1,"min":0},{"key":"checkouts_started","label":"عمليات الدفع التي بدأت","type":"number","required":true,"step":1,"min":1}]'::jsonb, '[{"key":"completed_orders","label":"Completed orders","type":"number","required":true,"step":1,"min":0},{"key":"checkouts_started","label":"Checkouts started","type":"number","required":true,"step":1,"min":1}]'::jsonb, 'احسب', 'Calculate', 8006, false),
  ('ecommerce-tools', 'coupon-redemption-rate-calculator', 'حاسبة استخدام القسائم', 'Coupon Redemption Rate Calculator', 'احسب نسبة القسائم المستخدمة إلى القسائم الموزعة.', 'Calculate redeemed coupons as a percentage of issued coupons.', 'redeemed_coupons / issued_coupons * 100', '[{"key":"redeemed_coupons","label":"القسائم المستخدمة","type":"number","required":true,"step":1,"min":0},{"key":"issued_coupons","label":"القسائم الموزعة","type":"number","required":true,"step":1,"min":1}]'::jsonb, '[{"key":"redeemed_coupons","label":"Redeemed coupons","type":"number","required":true,"step":1,"min":0},{"key":"issued_coupons","label":"Issued coupons","type":"number","required":true,"step":1,"min":1}]'::jsonb, 'احسب', 'Calculate', 8007, false),
  ('ecommerce-tools', 'free-shipping-threshold-contribution-calculator', 'حاسبة مساهمة حد الشحن المجاني', 'Free Shipping Threshold Contribution Calculator', 'قدّر المبلغ المتبقي من حد الشحن المجاني بعد تكلفة المنتج والشحن.', 'Estimate contribution left from a free-shipping threshold after product and shipping costs.', 'threshold - product_cost - shipping_cost', '[{"key":"threshold","label":"حد الشحن المجاني","type":"number","required":true,"step":0.01,"min":0},{"key":"product_cost","label":"تكلفة المنتجات","type":"number","required":true,"step":0.01,"min":0},{"key":"shipping_cost","label":"تكلفة الشحن","type":"number","required":true,"step":0.01,"min":0}]'::jsonb, '[{"key":"threshold","label":"Free shipping threshold","type":"number","required":true,"step":0.01,"min":0},{"key":"product_cost","label":"Product cost","type":"number","required":true,"step":0.01,"min":0},{"key":"shipping_cost","label":"Shipping cost","type":"number","required":true,"step":0.01,"min":0}]'::jsonb, 'احسب', 'Calculate', 8008, false),
  ('ecommerce-tools', 'ecommerce-gross-margin-per-order-calculator', 'حاسبة هامش الطلب للمتجر', 'E-commerce Order Margin Calculator', 'احسب هامش الطلب بعد تكلفة المنتج والتنفيذ.', 'Calculate order margin after product and fulfillment costs.', '(order_revenue - product_cost - fulfillment_cost) / order_revenue * 100', '[{"key":"order_revenue","label":"إيراد الطلب","type":"number","required":true,"step":0.01,"min":0.01},{"key":"product_cost","label":"تكلفة المنتج","type":"number","required":true,"step":0.01,"min":0},{"key":"fulfillment_cost","label":"تكلفة التنفيذ","type":"number","required":true,"step":0.01,"min":0}]'::jsonb, '[{"key":"order_revenue","label":"Order revenue","type":"number","required":true,"step":0.01,"min":0.01},{"key":"product_cost","label":"Product cost","type":"number","required":true,"step":0.01,"min":0},{"key":"fulfillment_cost","label":"Fulfillment cost","type":"number","required":true,"step":0.01,"min":0}]'::jsonb, 'احسب', 'Calculate', 8009, false),
  ('ecommerce-tools', 'customer-acquisition-payback-orders-calculator', 'حاسبة طلبات استرداد تكلفة اكتساب العميل', 'Customer Acquisition Payback Orders Calculator', 'احسب عدد الطلبات اللازمة لتغطية تكلفة اكتساب العميل.', 'Calculate how many orders are needed to recover customer acquisition cost.', 'acquisition_cost / contribution_per_order', '[{"key":"acquisition_cost","label":"تكلفة اكتساب العميل","type":"number","required":true,"step":0.01,"min":0},{"key":"contribution_per_order","label":"المساهمة لكل طلب","type":"number","required":true,"step":0.01,"min":0.01}]'::jsonb, '[{"key":"acquisition_cost","label":"Acquisition cost","type":"number","required":true,"step":0.01,"min":0},{"key":"contribution_per_order","label":"Contribution per order","type":"number","required":true,"step":0.01,"min":0.01}]'::jsonb, 'احسب', 'Calculate', 8010, false);

insert into public.tools(slug,title_ar,title_en,short_description,category_id,engine_type,input_schema,output_schema,runtime_config,pricing_mode,fixed_points,minimum_points,requires_auth,is_featured,is_active,sort_order,seo_title,seo_description)
select seed.slug,seed.title_ar,seed.title_en,seed.description_ar,category.id,'formula',jsonb_build_object('submitLabel',seed.submit_ar,'fields',seed.input_fields),jsonb_build_object('type','number','format','auto'),jsonb_build_object('expression',seed.expression),'free',0,0,false,seed.is_featured,true,seed.sort_order,seed.title_ar,seed.description_ar from wave4_ecommerce_tools_seed seed join public.categories category on category.slug=seed.category_slug
on conflict(slug) do update set title_ar=excluded.title_ar,title_en=excluded.title_en,short_description=excluded.short_description,category_id=excluded.category_id,engine_type=excluded.engine_type,input_schema=excluded.input_schema,output_schema=excluded.output_schema,runtime_config=excluded.runtime_config,pricing_mode=excluded.pricing_mode,fixed_points=excluded.fixed_points,minimum_points=excluded.minimum_points,requires_auth=excluded.requires_auth,is_featured=excluded.is_featured,is_active=excluded.is_active,sort_order=excluded.sort_order,seo_title=excluded.seo_title,seo_description=excluded.seo_description,updated_at=now();

insert into public.tool_translations(tool_id,locale_id,title,short_description,seo_title,seo_description,prompt_template_override)
select tool.id,locale.id,case when locale.code='ar' then seed.title_ar else seed.title_en end,case when locale.code='ar' then seed.description_ar else seed.description_en end,case when locale.code='ar' then seed.title_ar else seed.title_en end,case when locale.code='ar' then seed.description_ar else seed.description_en end,null from wave4_ecommerce_tools_seed seed join public.tools tool on tool.slug=seed.slug join public.locales locale on locale.code in('ar','en')
on conflict(tool_id,locale_id) do update set title=excluded.title,short_description=excluded.short_description,seo_title=excluded.seo_title,seo_description=excluded.seo_description,prompt_template_override=null,updated_at=now();

insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select tool.id,locale.id,field.value->>'key',field.value->>'label',nullif(field.value->>'placeholder',''),nullif(field.value->>'helpText',''),field.value->'options' from wave4_ecommerce_tools_seed seed join public.tools tool on tool.slug=seed.slug join public.locales locale on locale.code in('ar','en') cross join lateral jsonb_array_elements(case when locale.code='ar' then seed.input_fields else seed.english_fields end) field(value)
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,placeholder=excluded.placeholder,help_text=excluded.help_text,options=excluded.options,updated_at=now();

insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select tool.id,locale.id,'__submit__',case when locale.code='ar' then seed.submit_ar else seed.submit_en end,null,null,null from wave4_ecommerce_tools_seed seed join public.tools tool on tool.slug=seed.slug join public.locales locale on locale.code in('ar','en')
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,placeholder=null,help_text=null,options=null,updated_at=now();

commit;
