-- Web Empire wave 11: Freelancer, HR, Manufacturing, Maintenance, Hospitality (50 tools).
-- GitHub staging only; not applied to Supabase.

select public._wave11_upsert_formula_tools('freelancer-tools',$json$[
{"slug":"freelancer-booking-rate-calculator","title_ar":"حاسبة معدل حجز وقت المستقل","title_en":"Freelancer Booking Rate Calculator","expression":"booked_hours / available_hours * 100","fields":[{"key":"booked_hours","ar":"الساعات المحجوزة","en":"Booked hours","min":0},{"key":"available_hours","ar":"الساعات المتاحة","en":"Available hours","min":0.000001}],"sort_order":31101},
{"slug":"freelancer-scope-creep-rate-calculator","title_ar":"حاسبة نسبة تمدد نطاق المشروع","title_en":"Freelancer Scope Creep Rate Calculator","expression":"extra_hours / planned_hours * 100","fields":[{"key":"extra_hours","ar":"الساعات الإضافية","en":"Extra hours","min":0},{"key":"planned_hours","ar":"الساعات المخططة","en":"Planned hours","min":0.000001}],"sort_order":31102},
{"slug":"freelancer-average-invoice-value-calculator","title_ar":"حاسبة متوسط قيمة فاتورة المستقل","title_en":"Freelancer Average Invoice Value Calculator","expression":"invoiced_amount / invoices","fields":[{"key":"invoiced_amount","ar":"إجمالي قيمة الفواتير","en":"Total invoiced amount","min":0},{"key":"invoices","ar":"عدد الفواتير","en":"Invoices","min":1}],"sort_order":31103},
{"slug":"freelancer-payment-delay-days-calculator","title_ar":"حاسبة متوسط تأخر مدفوعات المستقل","title_en":"Freelancer Payment Delay Calculator","expression":"total_delay_days / paid_invoices","fields":[{"key":"total_delay_days","ar":"إجمالي أيام التأخير","en":"Total delay days","min":0},{"key":"paid_invoices","ar":"الفواتير المدفوعة","en":"Paid invoices","min":1}],"sort_order":31104},
{"slug":"freelancer-client-retention-rate-calculator","title_ar":"حاسبة احتفاظ عملاء المستقل","title_en":"Freelancer Client Retention Rate Calculator","expression":"returning_clients / starting_clients * 100","fields":[{"key":"returning_clients","ar":"العملاء العائدون","en":"Returning clients","min":0},{"key":"starting_clients","ar":"عملاء بداية الفترة","en":"Starting clients","min":0.000001}],"sort_order":31105},
{"slug":"freelancer-project-delivery-rate-calculator","title_ar":"حاسبة تسليم مشاريع المستقل في الموعد","title_en":"Freelancer On-time Delivery Rate Calculator","expression":"on_time_projects / completed_projects * 100","fields":[{"key":"on_time_projects","ar":"المشاريع المسلمة في الموعد","en":"On-time projects","min":0},{"key":"completed_projects","ar":"المشاريع المكتملة","en":"Completed projects","min":0.000001}],"sort_order":31106},
{"slug":"freelancer-admin-time-rate-calculator","title_ar":"حاسبة نسبة الوقت الإداري للمستقل","title_en":"Freelancer Admin Time Rate Calculator","expression":"admin_hours / total_hours * 100","fields":[{"key":"admin_hours","ar":"الساعات الإدارية","en":"Admin hours","min":0},{"key":"total_hours","ar":"إجمالي الساعات","en":"Total hours","min":0.000001}],"sort_order":31107},
{"slug":"freelancer-monthly-income-variance-calculator","title_ar":"حاسبة انحراف دخل المستقل الشهري","title_en":"Freelancer Monthly Income Variance Calculator","expression":"(actual_income - target_income) / target_income * 100","fields":[{"key":"actual_income","ar":"الدخل الفعلي","en":"Actual income","min":0},{"key":"target_income","ar":"الدخل المستهدف","en":"Target income","min":0.000001}],"sort_order":31108},
{"slug":"freelancer-expense-ratio-calculator","title_ar":"حاسبة نسبة مصروفات المستقل","title_en":"Freelancer Expense Ratio Calculator","expression":"business_expenses / gross_revenue * 100","fields":[{"key":"business_expenses","ar":"مصروفات العمل","en":"Business expenses","min":0},{"key":"gross_revenue","ar":"إجمالي الإيراد","en":"Gross revenue","min":0.000001}],"sort_order":31109},
{"slug":"freelancer-lead-conversion-rate-calculator","title_ar":"حاسبة تحويل العملاء المحتملين للمستقل","title_en":"Freelancer Lead Conversion Rate Calculator","expression":"new_clients / leads * 100","fields":[{"key":"new_clients","ar":"العملاء الجدد","en":"New clients","min":0},{"key":"leads","ar":"العملاء المحتملون","en":"Leads","min":0.000001}],"sort_order":31110}
]$json$::jsonb);

select public._wave11_upsert_formula_tools('hr-tools',$json$[
{"slug":"hr-internal-promotion-rate-calculator","title_ar":"حاسبة معدل الترقيات الداخلية","title_en":"HR Internal Promotion Rate Calculator","expression":"promotions / eligible_employees * 100","fields":[{"key":"promotions","ar":"عدد الترقيات","en":"Promotions","min":0},{"key":"eligible_employees","ar":"الموظفون المؤهلون","en":"Eligible employees","min":0.000001}],"sort_order":31201},
{"slug":"hr-probation-pass-rate-calculator","title_ar":"حاسبة اجتياز فترة التجربة","title_en":"HR Probation Pass Rate Calculator","expression":"passed_probation / completed_probation * 100","fields":[{"key":"passed_probation","ar":"مجتازو فترة التجربة","en":"Passed probation","min":0},{"key":"completed_probation","ar":"مكملو فترة التجربة","en":"Completed probation","min":0.000001}],"sort_order":31202},
{"slug":"hr-training-completion-rate-calculator","title_ar":"حاسبة إكمال تدريب الموظفين","title_en":"HR Training Completion Rate Calculator","expression":"completed_training / assigned_training * 100","fields":[{"key":"completed_training","ar":"برامج التدريب المكتملة","en":"Completed training","min":0},{"key":"assigned_training","ar":"برامج التدريب المسندة","en":"Assigned training","min":0.000001}],"sort_order":31203},
{"slug":"hr-employee-referral-hire-rate-calculator","title_ar":"حاسبة التوظيف عبر إحالات الموظفين","title_en":"Employee Referral Hire Rate Calculator","expression":"referral_hires / total_hires * 100","fields":[{"key":"referral_hires","ar":"التعيينات عبر الإحالات","en":"Referral hires","min":0},{"key":"total_hires","ar":"إجمالي التعيينات","en":"Total hires","min":0.000001}],"sort_order":31204},
{"slug":"hr-benefits-cost-per-employee-calculator","title_ar":"حاسبة تكلفة المزايا لكل موظف","title_en":"HR Benefits Cost per Employee Calculator","expression":"total_benefits_cost / employees","fields":[{"key":"total_benefits_cost","ar":"إجمالي تكلفة المزايا","en":"Total benefits cost","min":0},{"key":"employees","ar":"عدد الموظفين","en":"Employees","min":1}],"sort_order":31205},
{"slug":"hr-span-of-control-calculator","title_ar":"حاسبة نطاق الإشراف الإداري","title_en":"HR Span of Control Calculator","expression":"employees / managers","fields":[{"key":"employees","ar":"عدد الموظفين","en":"Employees","min":0},{"key":"managers","ar":"عدد المديرين","en":"Managers","min":0.000001}],"sort_order":31206},
{"slug":"hr-absenteeism-days-per-employee-calculator","title_ar":"حاسبة أيام الغياب لكل موظف","title_en":"Absence Days per Employee Calculator","expression":"absence_days / employees","fields":[{"key":"absence_days","ar":"إجمالي أيام الغياب","en":"Absence days","min":0},{"key":"employees","ar":"عدد الموظفين","en":"Employees","min":1}],"sort_order":31207},
{"slug":"hr-internal-fill-rate-calculator","title_ar":"حاسبة شغل الوظائف داخليًا","title_en":"HR Internal Fill Rate Calculator","expression":"internal_hires / filled_positions * 100","fields":[{"key":"internal_hires","ar":"التعيينات الداخلية","en":"Internal hires","min":0},{"key":"filled_positions","ar":"الوظائف المشغولة","en":"Filled positions","min":0.000001}],"sort_order":31208},
{"slug":"hr-recruiting-funnel-conversion-calculator","title_ar":"حاسبة تحويل قمع التوظيف","title_en":"HR Recruiting Funnel Conversion Calculator","expression":"hires / applicants * 100","fields":[{"key":"hires","ar":"التعيينات","en":"Hires","min":0},{"key":"applicants","ar":"المتقدمون","en":"Applicants","min":0.000001}],"sort_order":31209},
{"slug":"hr-voluntary-turnover-share-calculator","title_ar":"حاسبة حصة الاستقالات الطوعية","title_en":"Voluntary Turnover Share Calculator","expression":"voluntary_departures / total_departures * 100","fields":[{"key":"voluntary_departures","ar":"الاستقالات الطوعية","en":"Voluntary departures","min":0},{"key":"total_departures","ar":"إجمالي حالات المغادرة","en":"Total departures","min":0.000001}],"sort_order":31210}
]$json$::jsonb);

select public._wave11_upsert_formula_tools('manufacturing-tools',$json$[
{"slug":"manufacturing-order-completion-rate-calculator","title_ar":"حاسبة إكمال أوامر التصنيع","title_en":"Manufacturing Order Completion Rate Calculator","expression":"completed_orders / planned_orders * 100","fields":[{"key":"completed_orders","ar":"الأوامر المكتملة","en":"Completed orders","min":0},{"key":"planned_orders","ar":"الأوامر المخططة","en":"Planned orders","min":0.000001}],"sort_order":31301},
{"slug":"manufacturing-maintenance-cost-per-unit-calculator","title_ar":"حاسبة تكلفة صيانة المصنع لكل وحدة","title_en":"Manufacturing Maintenance Cost per Unit Calculator","expression":"maintenance_cost / units_produced","fields":[{"key":"maintenance_cost","ar":"تكلفة الصيانة","en":"Maintenance cost","min":0},{"key":"units_produced","ar":"الوحدات المنتجة","en":"Units produced","min":0.000001}],"sort_order":31302},
{"slug":"manufacturing-material-cost-per-unit-calculator","title_ar":"حاسبة تكلفة المواد لكل وحدة","title_en":"Manufacturing Material Cost per Unit Calculator","expression":"material_cost / units_produced","fields":[{"key":"material_cost","ar":"تكلفة المواد","en":"Material cost","min":0},{"key":"units_produced","ar":"الوحدات المنتجة","en":"Units produced","min":0.000001}],"sort_order":31303},
{"slug":"manufacturing-changeover-time-share-calculator","title_ar":"حاسبة نسبة وقت تغيير خط الإنتاج","title_en":"Manufacturing Changeover Time Share Calculator","expression":"changeover_minutes / scheduled_minutes * 100","fields":[{"key":"changeover_minutes","ar":"دقائق تغيير الخط","en":"Changeover minutes","min":0},{"key":"scheduled_minutes","ar":"الدقائق المجدولة","en":"Scheduled minutes","min":0.000001}],"sort_order":31304},
{"slug":"manufacturing-rework-cost-rate-calculator","title_ar":"حاسبة نسبة تكلفة إعادة العمل","title_en":"Manufacturing Rework Cost Rate Calculator","expression":"rework_cost / production_cost * 100","fields":[{"key":"rework_cost","ar":"تكلفة إعادة العمل","en":"Rework cost","min":0},{"key":"production_cost","ar":"تكلفة الإنتاج","en":"Production cost","min":0.000001}],"sort_order":31305},
{"slug":"manufacturing-good-units-per-hour-calculator","title_ar":"حاسبة الوحدات الجيدة في الساعة","title_en":"Good Units per Hour Calculator","expression":"good_units / production_hours","fields":[{"key":"good_units","ar":"الوحدات الجيدة","en":"Good units","min":0},{"key":"production_hours","ar":"ساعات الإنتاج","en":"Production hours","min":0.000001}],"sort_order":31306},
{"slug":"manufacturing-capacity-gap-calculator","title_ar":"حاسبة فجوة الطاقة الإنتاجية","title_en":"Manufacturing Capacity Gap Calculator","expression":"max_output - actual_output","fields":[{"key":"max_output","ar":"الإنتاج الأقصى","en":"Maximum output","min":0},{"key":"actual_output","ar":"الإنتاج الفعلي","en":"Actual output","min":0}],"sort_order":31307},
{"slug":"manufacturing-bottleneck-loss-rate-calculator","title_ar":"حاسبة خسارة وقت الاختناق الإنتاجي","title_en":"Manufacturing Bottleneck Loss Rate Calculator","expression":"bottleneck_lost_minutes / scheduled_minutes * 100","fields":[{"key":"bottleneck_lost_minutes","ar":"دقائق الفاقد بسبب الاختناق","en":"Bottleneck lost minutes","min":0},{"key":"scheduled_minutes","ar":"الدقائق المجدولة","en":"Scheduled minutes","min":0.000001}],"sort_order":31308},
{"slug":"manufacturing-direct-material-yield-rate-calculator","title_ar":"حاسبة مردود المواد المباشرة","title_en":"Direct Material Yield Rate Calculator","expression":"material_in_product / material_input * 100","fields":[{"key":"material_in_product","ar":"المواد داخل المنتج النهائي","en":"Material in finished product","min":0},{"key":"material_input","ar":"إجمالي المواد المدخلة","en":"Material input","min":0.000001}],"sort_order":31309},
{"slug":"manufacturing-output-per-worker-calculator","title_ar":"حاسبة الإنتاج لكل عامل","title_en":"Manufacturing Output per Worker Calculator","expression":"units_produced / workers","fields":[{"key":"units_produced","ar":"الوحدات المنتجة","en":"Units produced","min":0},{"key":"workers","ar":"عدد العمال","en":"Workers","min":0.000001}],"sort_order":31310}
]$json$::jsonb);

select public._wave11_upsert_formula_tools('maintenance-tools',$json$[
{"slug":"maintenance-labor-cost-share-calculator","title_ar":"حاسبة حصة العمالة من تكلفة الصيانة","title_en":"Maintenance Labor Cost Share Calculator","expression":"labor_cost / total_maintenance_cost * 100","fields":[{"key":"labor_cost","ar":"تكلفة العمالة","en":"Labor cost","min":0},{"key":"total_maintenance_cost","ar":"إجمالي تكلفة الصيانة","en":"Total maintenance cost","min":0.000001}],"sort_order":31401},
{"slug":"maintenance-parts-cost-share-calculator","title_ar":"حاسبة حصة قطع الغيار من تكلفة الصيانة","title_en":"Maintenance Parts Cost Share Calculator","expression":"parts_cost / total_maintenance_cost * 100","fields":[{"key":"parts_cost","ar":"تكلفة قطع الغيار","en":"Parts cost","min":0},{"key":"total_maintenance_cost","ar":"إجمالي تكلفة الصيانة","en":"Total maintenance cost","min":0.000001}],"sort_order":31402},
{"slug":"maintenance-work-order-completion-rate-calculator","title_ar":"حاسبة إكمال أوامر الصيانة","title_en":"Maintenance Work Order Completion Rate Calculator","expression":"completed_orders / opened_orders * 100","fields":[{"key":"completed_orders","ar":"الأوامر المكتملة","en":"Completed orders","min":0},{"key":"opened_orders","ar":"الأوامر المفتوحة","en":"Opened orders","min":0.000001}],"sort_order":31403},
{"slug":"maintenance-inspection-finding-rate-calculator","title_ar":"حاسبة معدل ملاحظات الفحص","title_en":"Maintenance Inspection Finding Rate Calculator","expression":"findings / inspections * 100","fields":[{"key":"findings","ar":"عدد الملاحظات","en":"Findings","min":0},{"key":"inspections","ar":"عدد الفحوصات","en":"Inspections","min":0.000001}],"sort_order":31404},
{"slug":"maintenance-outsourced-cost-share-calculator","title_ar":"حاسبة حصة الصيانة الخارجية من التكلفة","title_en":"Outsourced Maintenance Cost Share Calculator","expression":"outsourced_cost / total_maintenance_cost * 100","fields":[{"key":"outsourced_cost","ar":"تكلفة الصيانة الخارجية","en":"Outsourced cost","min":0},{"key":"total_maintenance_cost","ar":"إجمالي تكلفة الصيانة","en":"Total maintenance cost","min":0.000001}],"sort_order":31405},
{"slug":"maintenance-inspection-hours-per-asset-calculator","title_ar":"حاسبة ساعات الفحص لكل أصل","title_en":"Inspection Hours per Asset Calculator","expression":"inspection_hours / assets","fields":[{"key":"inspection_hours","ar":"ساعات الفحص","en":"Inspection hours","min":0},{"key":"assets","ar":"عدد الأصول","en":"Assets","min":0.000001}],"sort_order":31406},
{"slug":"maintenance-open-work-orders-per-asset-calculator","title_ar":"حاسبة أوامر الصيانة المفتوحة لكل أصل","title_en":"Open Work Orders per Asset Calculator","expression":"open_work_orders / assets","fields":[{"key":"open_work_orders","ar":"أوامر الصيانة المفتوحة","en":"Open work orders","min":0},{"key":"assets","ar":"عدد الأصول","en":"Assets","min":0.000001}],"sort_order":31407},
{"slug":"maintenance-technician-productivity-calculator","title_ar":"حاسبة إنتاجية فني الصيانة","title_en":"Maintenance Technician Productivity Calculator","expression":"completed_jobs / technician_hours","fields":[{"key":"completed_jobs","ar":"المهام المكتملة","en":"Completed jobs","min":0},{"key":"technician_hours","ar":"ساعات الفنيين","en":"Technician hours","min":0.000001}],"sort_order":31408},
{"slug":"maintenance-contract-cost-per-asset-calculator","title_ar":"حاسبة تكلفة عقد الصيانة لكل أصل","title_en":"Maintenance Contract Cost per Asset Calculator","expression":"contract_cost / assets","fields":[{"key":"contract_cost","ar":"تكلفة عقد الصيانة","en":"Contract cost","min":0},{"key":"assets","ar":"عدد الأصول","en":"Assets","min":0.000001}],"sort_order":31409},
{"slug":"maintenance-service-level-rate-calculator","title_ar":"حاسبة الالتزام بمستوى خدمة الصيانة","title_en":"Maintenance SLA Compliance Calculator","expression":"completed_within_sla / closed_orders * 100","fields":[{"key":"completed_within_sla","ar":"المكتمل ضمن مستوى الخدمة","en":"Completed within SLA","min":0},{"key":"closed_orders","ar":"الأوامر المغلقة","en":"Closed orders","min":0.000001}],"sort_order":31410}
]$json$::jsonb);

select public._wave11_upsert_formula_tools('hospitality-tools',$json$[
{"slug":"hospitality-revenue-per-guest-calculator","title_ar":"حاسبة الإيراد لكل نزيل","title_en":"Hospitality Revenue per Guest Calculator","expression":"total_revenue / guests","fields":[{"key":"total_revenue","ar":"إجمالي الإيراد","en":"Total revenue","min":0},{"key":"guests","ar":"عدد النزلاء","en":"Guests","min":0.000001}],"sort_order":31501},
{"slug":"hospitality-booking-lead-time-calculator","title_ar":"حاسبة متوسط مدة الحجز قبل الوصول","title_en":"Hospitality Booking Lead Time Calculator","expression":"total_days_before_arrival / bookings","fields":[{"key":"total_days_before_arrival","ar":"إجمالي الأيام قبل الوصول","en":"Total days before arrival","min":0},{"key":"bookings","ar":"عدد الحجوزات","en":"Bookings","min":0.000001}],"sort_order":31502},
{"slug":"hospitality-booking-conversion-rate-calculator","title_ar":"حاسبة تحويل حجوزات الضيافة","title_en":"Hospitality Booking Conversion Rate Calculator","expression":"bookings / booking_visitors * 100","fields":[{"key":"bookings","ar":"الحجوزات","en":"Bookings","min":0},{"key":"booking_visitors","ar":"زوار صفحة الحجز","en":"Booking visitors","min":0.000001}],"sort_order":31503},
{"slug":"hospitality-direct-booking-share-calculator","title_ar":"حاسبة حصة الحجوزات المباشرة","title_en":"Direct Booking Share Calculator","expression":"direct_bookings / total_bookings * 100","fields":[{"key":"direct_bookings","ar":"الحجوزات المباشرة","en":"Direct bookings","min":0},{"key":"total_bookings","ar":"إجمالي الحجوزات","en":"Total bookings","min":0.000001}],"sort_order":31504},
{"slug":"hospitality-refund-rate-calculator","title_ar":"حاسبة معدل المبالغ المستردة للضيافة","title_en":"Hospitality Refund Rate Calculator","expression":"refund_amount / booking_revenue * 100","fields":[{"key":"refund_amount","ar":"المبالغ المستردة","en":"Refund amount","min":0},{"key":"booking_revenue","ar":"إيراد الحجوزات","en":"Booking revenue","min":0.000001}],"sort_order":31505},
{"slug":"hospitality-no-show-rate-calculator","title_ar":"حاسبة عدم الحضور للضيافة","title_en":"Hospitality No-show Rate Calculator","expression":"no_shows / confirmed_bookings * 100","fields":[{"key":"no_shows","ar":"حالات عدم الحضور","en":"No-shows","min":0},{"key":"confirmed_bookings","ar":"الحجوزات المؤكدة","en":"Confirmed bookings","min":0.000001}],"sort_order":31506},
{"slug":"hospitality-room-service-revenue-per-order-calculator","title_ar":"حاسبة إيراد خدمة الغرف لكل طلب","title_en":"Room Service Revenue per Order Calculator","expression":"room_service_revenue / room_service_orders","fields":[{"key":"room_service_revenue","ar":"إيراد خدمة الغرف","en":"Room service revenue","min":0},{"key":"room_service_orders","ar":"طلبات خدمة الغرف","en":"Room service orders","min":0.000001}],"sort_order":31507},
{"slug":"hospitality-utility-cost-per-occupied-room-calculator","title_ar":"حاسبة تكلفة المرافق لكل غرفة مشغولة","title_en":"Utility Cost per Occupied Room Calculator","expression":"utility_cost / occupied_rooms","fields":[{"key":"utility_cost","ar":"تكلفة المرافق","en":"Utility cost","min":0},{"key":"occupied_rooms","ar":"الغرف المشغولة","en":"Occupied rooms","min":0.000001}],"sort_order":31508},
{"slug":"hospitality-staff-cost-share-calculator","title_ar":"حاسبة حصة تكلفة الموظفين في الضيافة","title_en":"Hospitality Staff Cost Share Calculator","expression":"staff_cost / total_revenue * 100","fields":[{"key":"staff_cost","ar":"تكلفة الموظفين","en":"Staff cost","min":0},{"key":"total_revenue","ar":"إجمالي الإيراد","en":"Total revenue","min":0.000001}],"sort_order":31509},
{"slug":"hospitality-guest-repeat-rate-calculator","title_ar":"حاسبة عودة النزلاء","title_en":"Hospitality Repeat Guest Rate Calculator","expression":"repeat_guests / total_guests * 100","fields":[{"key":"repeat_guests","ar":"النزلاء العائدون","en":"Repeat guests","min":0},{"key":"total_guests","ar":"إجمالي النزلاء","en":"Total guests","min":0.000001}],"sort_order":31510}
]$json$::jsonb);
