-- Web Empire 800 Tools Program — Initial Production Wave
-- Adds 88 deterministic, bilingual, production-ready formula tools.
-- Distribution: 8 tools across each of 11 categories.
-- Safe idempotent upserts. No destructive deletes.

begin;

insert into public.categories(
  slug, name_ar, name_en, description, icon, style_key, sort_order, is_active
)
values
  ('business-tools', 'أدوات الأعمال', 'Business Tools', 'أدوات القياس والتخطيط وتحسين أداء الأعمال.', 'briefcase', 'gold', 10, true),
  ('math-tools', 'أدوات حسابية', 'Math Tools', 'أدوات رياضية وحسابات هندسية ونسب ومتوسطات.', 'calculator', 'violet', 15, true),
  ('marketing-tools', 'أدوات التسويق', 'Marketing Tools', 'أدوات قياس كفاءة الحملات والعملاء والقنوات.', 'chart', 'cyan', 20, true),
  ('finance-tools', 'أدوات المال', 'Finance Tools', 'أدوات الميزانية والادخار والسيولة والالتزامات.', 'wallet', 'violet', 30, true),
  ('general-tools', 'أدوات عامة', 'General Tools', 'أدوات يومية للإنتاجية والتكاليف والمقارنات.', 'calculator', 'violet', 40, true),
  ('converter-tools', 'أدوات التحويل', 'Converter Tools', 'محولات وحدات دقيقة وسريعة.', 'convert', 'cyan', 50, true),
  ('date-time-tools', 'أدوات التاريخ والوقت', 'Date & Time Tools', 'أدوات الساعات والمدد والإنتاجية الزمنية.', 'calendar', 'gold', 60, true),
  ('health-tools', 'أدوات الصحة', 'Health Tools', 'حاسبات صحية تقديرية للاستخدام العام.', 'heart', 'violet', 130, true),
  ('education-tools', 'أدوات الطلاب', 'Education Tools', 'أدوات الدرجات والحضور والتخطيط الدراسي.', 'graduation-cap', 'cyan', 140, true),
  ('employment-tools', 'أدوات الرواتب والموظفين', 'Employment Tools', 'أدوات الرواتب والتعويضات والبدلات.', 'users', 'gold', 150, true),
  ('saudi-tools', 'أدوات السعودية', 'Saudi Tools', 'أدوات تقديرية شائعة للسوق السعودي.', 'landmark', 'gold', 190, true)
on conflict (slug) do update set
  name_ar = excluded.name_ar,
  name_en = excluded.name_en,
  description = excluded.description,
  icon = excluded.icon,
  style_key = excluded.style_key,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;

insert into public.category_translations(
  category_id, locale_id, name, description
)
select category.id, locale.id, seed.name, seed.description
from (
  values
    ('business-tools', 'ar', 'أدوات الأعمال', 'أدوات القياس والتخطيط وتحسين أداء الأعمال.'),
    ('business-tools', 'en', 'Business Tools', 'Business planning and performance tools.'),
    ('math-tools', 'ar', 'أدوات حسابية', 'أدوات رياضية وحسابات هندسية ونسب ومتوسطات.'),
    ('math-tools', 'en', 'Math Tools', 'Math, geometry, ratio, and average calculators.'),
    ('marketing-tools', 'ar', 'أدوات التسويق', 'أدوات قياس كفاءة الحملات والعملاء والقنوات.'),
    ('marketing-tools', 'en', 'Marketing Tools', 'Marketing campaign, customer, and channel metrics.'),
    ('finance-tools', 'ar', 'أدوات المال', 'أدوات الميزانية والادخار والسيولة والالتزامات.'),
    ('finance-tools', 'en', 'Finance Tools', 'Budgeting, savings, liquidity, and debt tools.'),
    ('general-tools', 'ar', 'أدوات عامة', 'أدوات يومية للإنتاجية والتكاليف والمقارنات.'),
    ('general-tools', 'en', 'General Tools', 'Everyday productivity, cost, and comparison tools.'),
    ('converter-tools', 'ar', 'أدوات التحويل', 'محولات وحدات دقيقة وسريعة.'),
    ('converter-tools', 'en', 'Converter Tools', 'Fast and accurate unit converters.'),
    ('date-time-tools', 'ar', 'أدوات التاريخ والوقت', 'أدوات الساعات والمدد والإنتاجية الزمنية.'),
    ('date-time-tools', 'en', 'Date & Time Tools', 'Hours, duration, and time-productivity tools.'),
    ('health-tools', 'ar', 'أدوات الصحة', 'حاسبات صحية تقديرية للاستخدام العام.'),
    ('health-tools', 'en', 'Health Tools', 'General health estimation calculators.'),
    ('education-tools', 'ar', 'أدوات الطلاب', 'أدوات الدرجات والحضور والتخطيط الدراسي.'),
    ('education-tools', 'en', 'Education Tools', 'Grades, attendance, and study planning tools.'),
    ('employment-tools', 'ar', 'أدوات الرواتب والموظفين', 'أدوات الرواتب والتعويضات والبدلات.'),
    ('employment-tools', 'en', 'Employment Tools', 'Salary, compensation, and allowance tools.'),
    ('saudi-tools', 'ar', 'أدوات السعودية', 'أدوات تقديرية شائعة للسوق السعودي.'),
    ('saudi-tools', 'en', 'Saudi Tools', 'Estimation tools for common Saudi use cases.')
) as seed(category_slug, locale_code, name, description)
join public.categories category on category.slug = seed.category_slug
join public.locales locale on locale.code = seed.locale_code
on conflict (category_id, locale_id) do update set
  name = excluded.name,
  description = excluded.description,
  updated_at = now();

create temporary table initial_800_tool_seed (
  category_slug text not null,
  slug text not null,
  title_ar text not null,
  title_en text not null,
  description_ar text not null,
  description_en text not null,
  runtime_config jsonb not null,
  input_fields jsonb not null,
  english_fields jsonb not null,
  submit_ar text not null,
  submit_en text not null,
  sort_order integer not null,
  is_featured boolean not null
) on commit drop;

insert into initial_800_tool_seed(
  category_slug, slug, title_ar, title_en, description_ar, description_en,
  runtime_config, input_fields, english_fields, submit_ar, submit_en,
  sort_order, is_featured
)
values
  ('business-tools', 'operating-leverage-calculator', 'حاسبة الرافعة التشغيلية', 'Operating Leverage Calculator', 'احسب درجة الرافعة التشغيلية من هامش المساهمة والربح التشغيلي.', 'Calculate operating leverage from contribution margin and operating income.', '{"expression":"contribution_margin / operating_income","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"درجة الرافعة التشغيلية","resultLabelEn":"Operating leverage","decimals":3,"showEquation":true}'::jsonb, '[{"key":"contribution_margin","label":"هامش المساهمة","type":"number","required":true,"min":0,"step":0.01},{"key":"operating_income","label":"الربح التشغيلي","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, '[{"key":"contribution_margin","label":"Contribution margin","type":"number","required":true,"min":0,"step":0.01},{"key":"operating_income","label":"Operating income","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, 'احسب الرافعة', 'Calculate leverage', 1000, true),
  ('business-tools', 'sales-per-employee-calculator', 'حاسبة المبيعات لكل موظف', 'Sales per Employee Calculator', 'احسب متوسط المبيعات التي يحققها كل موظف.', 'Calculate average sales generated per employee.', '{"expression":"annual_sales / employees","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"المبيعات لكل موظف","resultLabelEn":"Sales per employee","decimals":2,"showEquation":true}'::jsonb, '[{"key":"annual_sales","label":"المبيعات السنوية","type":"number","required":true,"min":0,"step":0.01},{"key":"employees","label":"عدد الموظفين","type":"number","required":true,"min":1,"step":1}]'::jsonb, '[{"key":"annual_sales","label":"Annual sales","type":"number","required":true,"min":0,"step":0.01},{"key":"employees","label":"Employees","type":"number","required":true,"min":1,"step":1}]'::jsonb, 'احسب المتوسط', 'Calculate average', 1001, false),
  ('business-tools', 'revenue-per-customer-calculator', 'حاسبة الإيراد لكل عميل', 'Revenue per Customer Calculator', 'احسب متوسط الإيراد الناتج من كل عميل.', 'Calculate average revenue generated per customer.', '{"expression":"revenue / customers","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"الإيراد لكل عميل","resultLabelEn":"Revenue per customer","decimals":2,"showEquation":true}'::jsonb, '[{"key":"revenue","label":"إجمالي الإيراد","type":"number","required":true,"min":0,"step":0.01},{"key":"customers","label":"عدد العملاء","type":"number","required":true,"min":1,"step":1}]'::jsonb, '[{"key":"revenue","label":"Total revenue","type":"number","required":true,"min":0,"step":0.01},{"key":"customers","label":"Customers","type":"number","required":true,"min":1,"step":1}]'::jsonb, 'احسب الإيراد', 'Calculate revenue', 1002, false),
  ('business-tools', 'inventory-days-calculator', 'حاسبة أيام المخزون', 'Inventory Days Calculator', 'قدّر متوسط عدد الأيام التي يبقى فيها المخزون قبل بيعه.', 'Estimate how many days inventory remains before being sold.', '{"expression":"average_inventory / cost_of_sales * 365","outputUnitAr":" يوم","outputUnitEn":" days","resultLabelAr":"أيام المخزون","resultLabelEn":"Inventory days","decimals":2,"showEquation":true}'::jsonb, '[{"key":"average_inventory","label":"متوسط المخزون","type":"number","required":true,"min":0,"step":0.01},{"key":"cost_of_sales","label":"تكلفة المبيعات السنوية","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, '[{"key":"average_inventory","label":"Average inventory","type":"number","required":true,"min":0,"step":0.01},{"key":"cost_of_sales","label":"Annual cost of sales","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, 'احسب أيام المخزون', 'Calculate inventory days', 1003, false),
  ('business-tools', 'receivable-days-calculator', 'حاسبة أيام التحصيل', 'Receivable Days Calculator', 'قدّر متوسط أيام تحصيل المبيعات الآجلة.', 'Estimate average collection days for credit sales.', '{"expression":"average_receivables / credit_sales * 365","outputUnitAr":" يوم","outputUnitEn":" days","resultLabelAr":"أيام التحصيل","resultLabelEn":"Receivable days","decimals":2,"showEquation":true}'::jsonb, '[{"key":"average_receivables","label":"متوسط الذمم المدينة","type":"number","required":true,"min":0,"step":0.01},{"key":"credit_sales","label":"المبيعات الآجلة السنوية","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, '[{"key":"average_receivables","label":"Average receivables","type":"number","required":true,"min":0,"step":0.01},{"key":"credit_sales","label":"Annual credit sales","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, 'احسب أيام التحصيل', 'Calculate collection days', 1004, false),
  ('business-tools', 'payable-days-calculator', 'حاسبة أيام السداد', 'Payable Days Calculator', 'قدّر متوسط الأيام التي تستغرقها المنشأة لسداد الموردين.', 'Estimate average days taken to pay suppliers.', '{"expression":"average_payables / purchases * 365","outputUnitAr":" يوم","outputUnitEn":" days","resultLabelAr":"أيام السداد","resultLabelEn":"Payable days","decimals":2,"showEquation":true}'::jsonb, '[{"key":"average_payables","label":"متوسط الذمم الدائنة","type":"number","required":true,"min":0,"step":0.01},{"key":"purchases","label":"المشتريات السنوية","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, '[{"key":"average_payables","label":"Average payables","type":"number","required":true,"min":0,"step":0.01},{"key":"purchases","label":"Annual purchases","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, 'احسب أيام السداد', 'Calculate payable days', 1005, false),
  ('business-tools', 'cash-conversion-cycle-calculator', 'حاسبة دورة التحويل النقدي', 'Cash Conversion Cycle Calculator', 'احسب مدة دورة التحويل النقدي من أيام المخزون والتحصيل والسداد.', 'Calculate cash conversion cycle from inventory, receivable, and payable days.', '{"expression":"inventory_days + receivable_days - payable_days","outputUnitAr":" يوم","outputUnitEn":" days","resultLabelAr":"دورة التحويل النقدي","resultLabelEn":"Cash conversion cycle","decimals":2,"showEquation":true}'::jsonb, '[{"key":"inventory_days","label":"أيام المخزون","type":"number","required":true,"min":0,"step":0.1},{"key":"receivable_days","label":"أيام التحصيل","type":"number","required":true,"min":0,"step":0.1},{"key":"payable_days","label":"أيام السداد","type":"number","required":true,"min":0,"step":0.1}]'::jsonb, '[{"key":"inventory_days","label":"Inventory days","type":"number","required":true,"min":0,"step":0.1},{"key":"receivable_days","label":"Receivable days","type":"number","required":true,"min":0,"step":0.1},{"key":"payable_days","label":"Payable days","type":"number","required":true,"min":0,"step":0.1}]'::jsonb, 'احسب الدورة', 'Calculate cycle', 1006, true),
  ('business-tools', 'customer-concentration-calculator', 'حاسبة تركّز العملاء', 'Customer Concentration Calculator', 'احسب نسبة الإيراد القادم من أكبر عميل إلى إجمالي الإيراد.', 'Calculate the share of total revenue generated by the largest customer.', '{"expression":"largest_customer_revenue / total_revenue * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة تركّز العملاء","resultLabelEn":"Customer concentration","decimals":2,"showEquation":true}'::jsonb, '[{"key":"largest_customer_revenue","label":"إيراد أكبر عميل","type":"number","required":true,"min":0,"step":0.01},{"key":"total_revenue","label":"إجمالي الإيراد","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, '[{"key":"largest_customer_revenue","label":"Largest customer revenue","type":"number","required":true,"min":0,"step":0.01},{"key":"total_revenue","label":"Total revenue","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, 'احسب التركّز', 'Calculate concentration', 1007, false),
  ('math-tools', 'weighted-mean-calculator', 'حاسبة المتوسط المرجّح', 'Weighted Mean Calculator', 'احسب المتوسط المرجّح لقيمتين حسب الوزن.', 'Calculate the weighted mean of two values.', '{"expression":"(value_a * weight_a + value_b * weight_b) / (weight_a + weight_b)","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"المتوسط المرجّح","resultLabelEn":"Weighted mean","decimals":2,"showEquation":true}'::jsonb, '[{"key":"value_a","label":"القيمة الأولى","type":"number","required":true,"step":0.01},{"key":"weight_a","label":"وزن القيمة الأولى","type":"number","required":true,"min":0,"step":0.01},{"key":"value_b","label":"القيمة الثانية","type":"number","required":true,"step":0.01},{"key":"weight_b","label":"وزن القيمة الثانية","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"value_a","label":"First value","type":"number","required":true,"step":0.01},{"key":"weight_a","label":"First weight","type":"number","required":true,"min":0,"step":0.01},{"key":"value_b","label":"Second value","type":"number","required":true,"step":0.01},{"key":"weight_b","label":"Second weight","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'احسب المتوسط', 'Calculate mean', 1100, true),
  ('math-tools', 'proportion-value-calculator', 'حاسبة التناسب', 'Proportion Value Calculator', 'أوجد القيمة المجهولة في معادلة تناسب بسيطة.', 'Find the unknown value in a simple proportion.', '{"expression":"b * c / a","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"القيمة المجهولة","resultLabelEn":"Unknown value","decimals":2,"showEquation":true}'::jsonb, '[{"key":"a","label":"A","type":"number","required":true,"min":1e-06,"step":0.01},{"key":"b","label":"B","type":"number","required":true,"step":0.01},{"key":"c","label":"C","type":"number","required":true,"step":0.01}]'::jsonb, '[{"key":"a","label":"A","type":"number","required":true,"min":1e-06,"step":0.01},{"key":"b","label":"B","type":"number","required":true,"step":0.01},{"key":"c","label":"C","type":"number","required":true,"step":0.01}]'::jsonb, 'احسب القيمة', 'Calculate value', 1101, false),
  ('math-tools', 'geometric-mean-two-values', 'حاسبة المتوسط الهندسي', 'Geometric Mean Calculator', 'احسب المتوسط الهندسي لقيمتين موجبتين.', 'Calculate the geometric mean of two positive values.', '{"expression":"(value_a * value_b) ^ 0.5","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"المتوسط الهندسي","resultLabelEn":"Geometric mean","decimals":2,"showEquation":true}'::jsonb, '[{"key":"value_a","label":"القيمة الأولى","type":"number","required":true,"min":0,"step":0.01},{"key":"value_b","label":"القيمة الثانية","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"value_a","label":"First value","type":"number","required":true,"min":0,"step":0.01},{"key":"value_b","label":"Second value","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'احسب المتوسط', 'Calculate mean', 1102, false),
  ('math-tools', 'harmonic-mean-two-values', 'حاسبة المتوسط التوافقي', 'Harmonic Mean Calculator', 'احسب المتوسط التوافقي لقيمتين موجبتين.', 'Calculate the harmonic mean of two positive values.', '{"expression":"2 * value_a * value_b / (value_a + value_b)","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"المتوسط التوافقي","resultLabelEn":"Harmonic mean","decimals":2,"showEquation":true}'::jsonb, '[{"key":"value_a","label":"القيمة الأولى","type":"number","required":true,"min":1e-06,"step":0.01},{"key":"value_b","label":"القيمة الثانية","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, '[{"key":"value_a","label":"First value","type":"number","required":true,"min":1e-06,"step":0.01},{"key":"value_b","label":"Second value","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, 'احسب المتوسط', 'Calculate mean', 1103, false),
  ('math-tools', 'square-diagonal-calculator', 'حاسبة قطر المربع', 'Square Diagonal Calculator', 'احسب طول قطر المربع من طول الضلع.', 'Calculate a square diagonal from side length.', '{"expression":"side * (2 ^ 0.5)","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"قطر المربع","resultLabelEn":"Square diagonal","decimals":2,"showEquation":true}'::jsonb, '[{"key":"side","label":"طول الضلع","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"side","label":"Side length","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'احسب القطر', 'Calculate diagonal', 1104, false),
  ('math-tools', 'circle-circumference-calculator', 'حاسبة محيط الدائرة', 'Circle Circumference Calculator', 'احسب محيط الدائرة من نصف القطر.', 'Calculate circle circumference from radius.', '{"expression":"2 * 3.141592653589793 * radius","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"محيط الدائرة","resultLabelEn":"Circle circumference","decimals":2,"showEquation":true}'::jsonb, '[{"key":"radius","label":"نصف القطر","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"radius","label":"Radius","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'احسب المحيط', 'Calculate circumference', 1105, false),
  ('math-tools', 'trapezoid-area-calculator', 'حاسبة مساحة شبه المنحرف', 'Trapezoid Area Calculator', 'احسب مساحة شبه المنحرف من القاعدتين والارتفاع.', 'Calculate trapezoid area from two bases and height.', '{"expression":"(base_a + base_b) * height / 2","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"مساحة شبه المنحرف","resultLabelEn":"Trapezoid area","decimals":2,"showEquation":true}'::jsonb, '[{"key":"base_a","label":"القاعدة الأولى","type":"number","required":true,"min":0,"step":0.01},{"key":"base_b","label":"القاعدة الثانية","type":"number","required":true,"min":0,"step":0.01},{"key":"height","label":"الارتفاع","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"base_a","label":"First base","type":"number","required":true,"min":0,"step":0.01},{"key":"base_b","label":"Second base","type":"number","required":true,"min":0,"step":0.01},{"key":"height","label":"Height","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'احسب المساحة', 'Calculate area', 1106, false),
  ('math-tools', 'regular-polygon-angle-calculator', 'حاسبة زاوية المضلع المنتظم', 'Regular Polygon Angle Calculator', 'احسب قياس الزاوية الداخلية للمضلع المنتظم.', 'Calculate the interior angle of a regular polygon.', '{"expression":"(sides - 2) * 180 / sides","outputUnitAr":"°","outputUnitEn":"°","resultLabelAr":"الزاوية الداخلية","resultLabelEn":"Interior angle","decimals":2,"showEquation":true}'::jsonb, '[{"key":"sides","label":"عدد الأضلاع","type":"number","required":true,"min":3,"step":1}]'::jsonb, '[{"key":"sides","label":"Number of sides","type":"number","required":true,"min":3,"step":1}]'::jsonb, 'احسب الزاوية', 'Calculate angle', 1107, false),
  ('date-time-tools', 'minutes-to-decimal-hours', 'محول الدقائق إلى ساعات عشرية', 'Minutes to Decimal Hours', 'حوّل عدد الدقائق إلى ساعات بصيغة عشرية.', 'Convert minutes to decimal hours.', '{"expression":"minutes / 60","outputUnitAr":" ساعة","outputUnitEn":" hours","resultLabelAr":"الساعات العشرية","resultLabelEn":"Decimal hours","decimals":2,"showEquation":true}'::jsonb, '[{"key":"minutes","label":"الدقائق","type":"number","required":true,"min":0,"step":1}]'::jsonb, '[{"key":"minutes","label":"Minutes","type":"number","required":true,"min":0,"step":1}]'::jsonb, 'حوّل إلى ساعات', 'Convert to hours', 1200, true),
  ('date-time-tools', 'decimal-hours-to-minutes', 'محول الساعات العشرية إلى دقائق', 'Decimal Hours to Minutes', 'حوّل الساعات العشرية إلى دقائق.', 'Convert decimal hours to minutes.', '{"expression":"hours * 60","outputUnitAr":" دقيقة","outputUnitEn":" minutes","resultLabelAr":"إجمالي الدقائق","resultLabelEn":"Total minutes","decimals":2,"showEquation":true}'::jsonb, '[{"key":"hours","label":"الساعات العشرية","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"hours","label":"Decimal hours","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'حوّل إلى دقائق', 'Convert to minutes', 1201, false),
  ('date-time-tools', 'workdays-to-hours-calculator', 'حاسبة ساعات أيام العمل', 'Workdays to Hours Calculator', 'احسب إجمالي ساعات العمل من عدد الأيام وساعات اليوم.', 'Calculate total work hours from days and hours per day.', '{"expression":"days * hours_per_day","outputUnitAr":" ساعة","outputUnitEn":" hours","resultLabelAr":"إجمالي ساعات العمل","resultLabelEn":"Total work hours","decimals":2,"showEquation":true}'::jsonb, '[{"key":"days","label":"أيام العمل","type":"number","required":true,"min":0,"step":1},{"key":"hours_per_day","label":"ساعات العمل يوميًا","type":"number","required":true,"min":0,"step":0.25,"defaultValue":8}]'::jsonb, '[{"key":"days","label":"Workdays","type":"number","required":true,"min":0,"step":1},{"key":"hours_per_day","label":"Hours per day","type":"number","required":true,"min":0,"step":0.25,"defaultValue":8}]'::jsonb, 'احسب الساعات', 'Calculate hours', 1202, false),
  ('date-time-tools', 'shifts-to-hours-calculator', 'حاسبة ساعات الورديات', 'Shifts to Hours Calculator', 'احسب إجمالي ساعات مجموعة من الورديات.', 'Calculate total hours across multiple shifts.', '{"expression":"shifts * hours_per_shift","outputUnitAr":" ساعة","outputUnitEn":" hours","resultLabelAr":"إجمالي ساعات الورديات","resultLabelEn":"Total shift hours","decimals":2,"showEquation":true}'::jsonb, '[{"key":"shifts","label":"عدد الورديات","type":"number","required":true,"min":0,"step":1},{"key":"hours_per_shift","label":"ساعات الوردية","type":"number","required":true,"min":0,"step":0.25,"defaultValue":8}]'::jsonb, '[{"key":"shifts","label":"Shifts","type":"number","required":true,"min":0,"step":1},{"key":"hours_per_shift","label":"Hours per shift","type":"number","required":true,"min":0,"step":0.25,"defaultValue":8}]'::jsonb, 'احسب الساعات', 'Calculate hours', 1203, false),
  ('date-time-tools', 'weekly-hours-to-monthly-hours', 'محول الساعات الأسبوعية إلى شهرية', 'Weekly to Monthly Hours', 'قدّر الساعات الشهرية من متوسط الساعات الأسبوعية.', 'Estimate monthly hours from weekly hours.', '{"expression":"weekly_hours * 52 / 12","outputUnitAr":" ساعة/شهر","outputUnitEn":" hours/month","resultLabelAr":"الساعات الشهرية التقديرية","resultLabelEn":"Estimated monthly hours","decimals":2,"showEquation":true}'::jsonb, '[{"key":"weekly_hours","label":"الساعات الأسبوعية","type":"number","required":true,"min":0,"step":0.25}]'::jsonb, '[{"key":"weekly_hours","label":"Weekly hours","type":"number","required":true,"min":0,"step":0.25}]'::jsonb, 'احسب الساعات الشهرية', 'Calculate monthly hours', 1204, false),
  ('date-time-tools', 'meeting-person-hours-calculator', 'حاسبة ساعات العمل في الاجتماع', 'Meeting Person-Hours Calculator', 'احسب إجمالي ساعات الأشخاص المستهلكة في اجتماع.', 'Calculate total person-hours consumed by a meeting.', '{"expression":"attendees * duration_hours","outputUnitAr":" ساعة-شخص","outputUnitEn":" person-hours","resultLabelAr":"إجمالي ساعات الأشخاص","resultLabelEn":"Total person-hours","decimals":2,"showEquation":true}'::jsonb, '[{"key":"attendees","label":"عدد الحضور","type":"number","required":true,"min":1,"step":1},{"key":"duration_hours","label":"مدة الاجتماع بالساعات","type":"number","required":true,"min":0,"step":0.25}]'::jsonb, '[{"key":"attendees","label":"Attendees","type":"number","required":true,"min":1,"step":1},{"key":"duration_hours","label":"Meeting duration in hours","type":"number","required":true,"min":0,"step":0.25}]'::jsonb, 'احسب ساعات الأشخاص', 'Calculate person-hours', 1205, false),
  ('date-time-tools', 'production-time-per-unit', 'حاسبة وقت الإنتاج للوحدة', 'Production Time per Unit', 'احسب متوسط الوقت المستغرق لإنتاج وحدة واحدة.', 'Calculate average time required to produce one unit.', '{"expression":"total_minutes / units","outputUnitAr":" دقيقة/وحدة","outputUnitEn":" min/unit","resultLabelAr":"وقت الإنتاج لكل وحدة","resultLabelEn":"Production time per unit","decimals":2,"showEquation":true}'::jsonb, '[{"key":"total_minutes","label":"إجمالي الوقت بالدقائق","type":"number","required":true,"min":0,"step":1},{"key":"units","label":"عدد الوحدات","type":"number","required":true,"min":1,"step":1}]'::jsonb, '[{"key":"total_minutes","label":"Total time in minutes","type":"number","required":true,"min":0,"step":1},{"key":"units","label":"Units produced","type":"number","required":true,"min":1,"step":1}]'::jsonb, 'احسب وقت الوحدة', 'Calculate unit time', 1206, false),
  ('date-time-tools', 'task-throughput-per-hour', 'حاسبة معدل إنجاز المهام', 'Task Throughput per Hour', 'احسب عدد المهام المنجزة في الساعة.', 'Calculate completed tasks per hour.', '{"expression":"tasks / hours","outputUnitAr":" مهمة/ساعة","outputUnitEn":" tasks/hour","resultLabelAr":"معدل الإنجاز","resultLabelEn":"Task throughput","decimals":2,"showEquation":true}'::jsonb, '[{"key":"tasks","label":"عدد المهام المنجزة","type":"number","required":true,"min":0,"step":1},{"key":"hours","label":"الساعات المستغرقة","type":"number","required":true,"min":1e-06,"step":0.25}]'::jsonb, '[{"key":"tasks","label":"Completed tasks","type":"number","required":true,"min":0,"step":1},{"key":"hours","label":"Hours spent","type":"number","required":true,"min":1e-06,"step":0.25}]'::jsonb, 'احسب المعدل', 'Calculate rate', 1207, false),
  ('health-tools', 'target-weight-by-bmi', 'حاسبة الوزن المستهدف حسب BMI', 'Target Weight by BMI', 'قدّر الوزن الموافق لمؤشر كتلة مستهدف وطول محدد.', 'Estimate weight matching a target BMI and height.', '{"expression":"target_bmi * ((height_cm / 100) ^ 2)","outputUnitAr":" كجم","outputUnitEn":" kg","resultLabelAr":"الوزن التقديري","resultLabelEn":"Estimated weight","decimals":2,"showEquation":true,"noteAr":"النتيجة تقديرية عامة ولا تغني عن استشارة مختص صحي.","noteEn":"This is a general estimate and not a substitute for professional medical advice."}'::jsonb, '[{"key":"target_bmi","label":"مؤشر BMI المستهدف","type":"number","required":true,"min":1,"step":0.1,"defaultValue":22},{"key":"height_cm","label":"الطول بالسنتيمتر","type":"number","required":true,"min":1,"step":0.1}]'::jsonb, '[{"key":"target_bmi","label":"Target BMI","type":"number","required":true,"min":1,"step":0.1,"defaultValue":22},{"key":"height_cm","label":"Height in cm","type":"number","required":true,"min":1,"step":0.1}]'::jsonb, 'احسب الوزن', 'Calculate weight', 1300, true),
  ('health-tools', 'walking-pace-calculator', 'حاسبة وتيرة المشي', 'Walking Pace Calculator', 'احسب عدد الدقائق لكل كيلومتر أثناء المشي.', 'Calculate walking pace in minutes per kilometer.', '{"expression":"minutes / distance_km","outputUnitAr":" دقيقة/كم","outputUnitEn":" min/km","resultLabelAr":"وتيرة المشي","resultLabelEn":"Walking pace","decimals":2,"showEquation":true,"noteAr":"النتيجة تقديرية عامة ولا تغني عن استشارة مختص صحي.","noteEn":"This is a general estimate and not a substitute for professional medical advice."}'::jsonb, '[{"key":"minutes","label":"المدة بالدقائق","type":"number","required":true,"min":0,"step":0.1},{"key":"distance_km","label":"المسافة بالكيلومتر","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, '[{"key":"minutes","label":"Duration in minutes","type":"number","required":true,"min":0,"step":0.1},{"key":"distance_km","label":"Distance in km","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, 'احسب الوتيرة', 'Calculate pace', 1301, false),
  ('health-tools', 'running-speed-calculator', 'حاسبة سرعة الجري', 'Running Speed Calculator', 'احسب متوسط سرعة الجري بالكيلومتر في الساعة.', 'Calculate average running speed in kilometers per hour.', '{"expression":"distance_km / (minutes / 60)","outputUnitAr":" كم/س","outputUnitEn":" km/h","resultLabelAr":"متوسط السرعة","resultLabelEn":"Average speed","decimals":2,"showEquation":true,"noteAr":"النتيجة تقديرية عامة ولا تغني عن استشارة مختص صحي.","noteEn":"This is a general estimate and not a substitute for professional medical advice."}'::jsonb, '[{"key":"distance_km","label":"المسافة بالكيلومتر","type":"number","required":true,"min":0,"step":0.01},{"key":"minutes","label":"المدة بالدقائق","type":"number","required":true,"min":1e-06,"step":0.1}]'::jsonb, '[{"key":"distance_km","label":"Distance in km","type":"number","required":true,"min":0,"step":0.01},{"key":"minutes","label":"Duration in minutes","type":"number","required":true,"min":1e-06,"step":0.1}]'::jsonb, 'احسب السرعة', 'Calculate speed', 1302, false),
  ('health-tools', 'protein-target-calculator', 'حاسبة الاحتياج التقديري للبروتين', 'Protein Target Calculator', 'قدّر كمية البروتين اليومية من الوزن ومعامل الجرام لكل كيلوجرام.', 'Estimate daily protein from weight and grams per kilogram.', '{"expression":"weight * grams_per_kg","outputUnitAr":" جم/يوم","outputUnitEn":" g/day","resultLabelAr":"كمية البروتين التقديرية","resultLabelEn":"Estimated protein","decimals":2,"showEquation":true,"noteAr":"النتيجة تقديرية عامة ولا تغني عن استشارة مختص صحي.","noteEn":"This is a general estimate and not a substitute for professional medical advice."}'::jsonb, '[{"key":"weight","label":"الوزن بالكيلوجرام","type":"number","required":true,"min":1,"step":0.1},{"key":"grams_per_kg","label":"جرام لكل كيلوجرام","type":"number","required":true,"min":0,"step":0.1,"defaultValue":1.2}]'::jsonb, '[{"key":"weight","label":"Weight in kg","type":"number","required":true,"min":1,"step":0.1},{"key":"grams_per_kg","label":"Grams per kg","type":"number","required":true,"min":0,"step":0.1,"defaultValue":1.2}]'::jsonb, 'احسب البروتين', 'Calculate protein', 1303, false),
  ('health-tools', 'body-fat-mass-calculator', 'حاسبة كتلة الدهون', 'Body Fat Mass Calculator', 'احسب كتلة الدهون التقديرية من الوزن ونسبة الدهون.', 'Calculate estimated fat mass from weight and body-fat percentage.', '{"expression":"weight * body_fat_percentage / 100","outputUnitAr":" كجم","outputUnitEn":" kg","resultLabelAr":"كتلة الدهون التقديرية","resultLabelEn":"Estimated fat mass","decimals":2,"showEquation":true,"noteAr":"النتيجة تقديرية عامة ولا تغني عن استشارة مختص صحي.","noteEn":"This is a general estimate and not a substitute for professional medical advice."}'::jsonb, '[{"key":"weight","label":"الوزن بالكيلوجرام","type":"number","required":true,"min":1,"step":0.1},{"key":"body_fat_percentage","label":"نسبة الدهون","type":"number","required":true,"min":0,"max":100,"step":0.1}]'::jsonb, '[{"key":"weight","label":"Weight in kg","type":"number","required":true,"min":1,"step":0.1},{"key":"body_fat_percentage","label":"Body-fat percentage","type":"number","required":true,"min":0,"max":100,"step":0.1}]'::jsonb, 'احسب كتلة الدهون', 'Calculate fat mass', 1304, false),
  ('health-tools', 'lean-body-mass-calculator', 'حاسبة الكتلة الخالية من الدهون', 'Lean Body Mass Calculator', 'احسب الكتلة الخالية من الدهون من الوزن ونسبة الدهون.', 'Calculate lean body mass from weight and body-fat percentage.', '{"expression":"weight * (1 - body_fat_percentage / 100)","outputUnitAr":" كجم","outputUnitEn":" kg","resultLabelAr":"الكتلة الخالية من الدهون","resultLabelEn":"Lean body mass","decimals":2,"showEquation":true,"noteAr":"النتيجة تقديرية عامة ولا تغني عن استشارة مختص صحي.","noteEn":"This is a general estimate and not a substitute for professional medical advice."}'::jsonb, '[{"key":"weight","label":"الوزن بالكيلوجرام","type":"number","required":true,"min":1,"step":0.1},{"key":"body_fat_percentage","label":"نسبة الدهون","type":"number","required":true,"min":0,"max":100,"step":0.1}]'::jsonb, '[{"key":"weight","label":"Weight in kg","type":"number","required":true,"min":1,"step":0.1},{"key":"body_fat_percentage","label":"Body-fat percentage","type":"number","required":true,"min":0,"max":100,"step":0.1}]'::jsonb, 'احسب الكتلة', 'Calculate lean mass', 1305, false),
  ('health-tools', 'waist-height-ratio-calculator', 'حاسبة نسبة الخصر إلى الطول', 'Waist-to-Height Ratio Calculator', 'احسب نسبة محيط الخصر إلى الطول كنسبة مئوية.', 'Calculate waist-to-height ratio as a percentage.', '{"expression":"waist_cm / height_cm * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة الخصر إلى الطول","resultLabelEn":"Waist-to-height ratio","decimals":2,"showEquation":true,"noteAr":"النتيجة تقديرية عامة ولا تغني عن استشارة مختص صحي.","noteEn":"This is a general estimate and not a substitute for professional medical advice."}'::jsonb, '[{"key":"waist_cm","label":"محيط الخصر بالسنتيمتر","type":"number","required":true,"min":1,"step":0.1},{"key":"height_cm","label":"الطول بالسنتيمتر","type":"number","required":true,"min":1,"step":0.1}]'::jsonb, '[{"key":"waist_cm","label":"Waist in cm","type":"number","required":true,"min":1,"step":0.1},{"key":"height_cm","label":"Height in cm","type":"number","required":true,"min":1,"step":0.1}]'::jsonb, 'احسب النسبة', 'Calculate ratio', 1306, false),
  ('health-tools', 'calorie-deficit-duration-calculator', 'حاسبة مدة عجز السعرات', 'Calorie Deficit Duration Calculator', 'قدّر عدد الأيام اللازمة لعجز طاقة محدد لكل كيلوجرام مستهدف.', 'Estimate days required for a calorie deficit target.', '{"expression":"target_kg * 7700 / daily_deficit","outputUnitAr":" يوم","outputUnitEn":" days","resultLabelAr":"المدة التقديرية","resultLabelEn":"Estimated duration","decimals":2,"showEquation":true,"noteAr":"النتيجة تقديرية عامة ولا تغني عن استشارة مختص صحي.","noteEn":"This is a general estimate and not a substitute for professional medical advice."}'::jsonb, '[{"key":"target_kg","label":"الوزن المستهدف فقده بالكيلوجرام","type":"number","required":true,"min":0,"step":0.1},{"key":"daily_deficit","label":"العجز اليومي بالسعرات","type":"number","required":true,"min":1,"step":1}]'::jsonb, '[{"key":"target_kg","label":"Target weight loss in kg","type":"number","required":true,"min":0,"step":0.1},{"key":"daily_deficit","label":"Daily calorie deficit","type":"number","required":true,"min":1,"step":1}]'::jsonb, 'احسب المدة', 'Calculate duration', 1307, false),
  ('education-tools', 'course-weighted-score-calculator', 'حاسبة الدرجة الموزونة للمقرر', 'Course Weighted Score Calculator', 'احسب الدرجة الموزونة من درجتين ونسبتيهما.', 'Calculate a weighted course score from two components.', '{"expression":"score_a * weight_a / 100 + score_b * weight_b / 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"الدرجة الموزونة","resultLabelEn":"Weighted score","decimals":2,"showEquation":true}'::jsonb, '[{"key":"score_a","label":"الدرجة الأولى","type":"number","required":true,"min":0,"max":100,"step":0.01},{"key":"weight_a","label":"وزن الدرجة الأولى","type":"number","required":true,"min":0,"max":100,"step":0.01},{"key":"score_b","label":"الدرجة الثانية","type":"number","required":true,"min":0,"max":100,"step":0.01},{"key":"weight_b","label":"وزن الدرجة الثانية","type":"number","required":true,"min":0,"max":100,"step":0.01}]'::jsonb, '[{"key":"score_a","label":"First score","type":"number","required":true,"min":0,"max":100,"step":0.01},{"key":"weight_a","label":"First weight","type":"number","required":true,"min":0,"max":100,"step":0.01},{"key":"score_b","label":"Second score","type":"number","required":true,"min":0,"max":100,"step":0.01},{"key":"weight_b","label":"Second weight","type":"number","required":true,"min":0,"max":100,"step":0.01}]'::jsonb, 'احسب الدرجة', 'Calculate score', 1400, true),
  ('education-tools', 'final-exam-required-score', 'حاسبة الدرجة المطلوبة في النهائي', 'Required Final Exam Score', 'احسب الدرجة اللازمة في الاختبار النهائي للوصول إلى هدف محدد.', 'Calculate the final-exam score needed to reach a target grade.', '{"expression":"(target_grade - current_grade * (1 - final_weight / 100)) / (final_weight / 100)","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"الدرجة المطلوبة في النهائي","resultLabelEn":"Required final score","decimals":2,"showEquation":true}'::jsonb, '[{"key":"current_grade","label":"الدرجة الحالية","type":"number","required":true,"min":0,"max":100,"step":0.01},{"key":"final_weight","label":"وزن الاختبار النهائي","type":"number","required":true,"min":1e-06,"max":100,"step":0.01},{"key":"target_grade","label":"الدرجة المستهدفة","type":"number","required":true,"min":0,"max":100,"step":0.01}]'::jsonb, '[{"key":"current_grade","label":"Current grade","type":"number","required":true,"min":0,"max":100,"step":0.01},{"key":"final_weight","label":"Final exam weight","type":"number","required":true,"min":1e-06,"max":100,"step":0.01},{"key":"target_grade","label":"Target grade","type":"number","required":true,"min":0,"max":100,"step":0.01}]'::jsonb, 'احسب الدرجة المطلوبة', 'Calculate required score', 1401, false),
  ('education-tools', 'attendance-rate-calculator', 'حاسبة نسبة الحضور', 'Attendance Rate Calculator', 'احسب نسبة الحضور من عدد الجلسات الكلي والحضور الفعلي.', 'Calculate attendance rate from total and attended sessions.', '{"expression":"attended / total_sessions * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة الحضور","resultLabelEn":"Attendance rate","decimals":2,"showEquation":true}'::jsonb, '[{"key":"attended","label":"الجلسات التي حضرتها","type":"number","required":true,"min":0,"step":1},{"key":"total_sessions","label":"إجمالي الجلسات","type":"number","required":true,"min":1,"step":1}]'::jsonb, '[{"key":"attended","label":"Attended sessions","type":"number","required":true,"min":0,"step":1},{"key":"total_sessions","label":"Total sessions","type":"number","required":true,"min":1,"step":1}]'::jsonb, 'احسب نسبة الحضور', 'Calculate attendance', 1402, false),
  ('education-tools', 'study-hours-per-subject', 'حاسبة ساعات المذاكرة لكل مادة', 'Study Hours per Subject', 'قسّم إجمالي ساعات المذاكرة بالتساوي على عدد المواد.', 'Split total study hours evenly across subjects.', '{"expression":"total_hours / subjects","outputUnitAr":" ساعة/مادة","outputUnitEn":" hours/subject","resultLabelAr":"ساعات المذاكرة لكل مادة","resultLabelEn":"Study hours per subject","decimals":2,"showEquation":true}'::jsonb, '[{"key":"total_hours","label":"إجمالي ساعات المذاكرة","type":"number","required":true,"min":0,"step":0.25},{"key":"subjects","label":"عدد المواد","type":"number","required":true,"min":1,"step":1}]'::jsonb, '[{"key":"total_hours","label":"Total study hours","type":"number","required":true,"min":0,"step":0.25},{"key":"subjects","label":"Subjects","type":"number","required":true,"min":1,"step":1}]'::jsonb, 'احسب نصيب المادة', 'Calculate per subject', 1403, false),
  ('education-tools', 'assignment-average-calculator', 'حاسبة متوسط الواجبات', 'Assignment Average Calculator', 'احسب متوسط أربع درجات للواجبات.', 'Calculate the average of four assignment scores.', '{"expression":"(score_1 + score_2 + score_3 + score_4) / 4","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"متوسط الواجبات","resultLabelEn":"Assignment average","decimals":2,"showEquation":true}'::jsonb, '[{"key":"score_1","label":"الواجب الأول","type":"number","required":true,"min":0,"max":100,"step":0.01},{"key":"score_2","label":"الواجب الثاني","type":"number","required":true,"min":0,"max":100,"step":0.01},{"key":"score_3","label":"الواجب الثالث","type":"number","required":true,"min":0,"max":100,"step":0.01},{"key":"score_4","label":"الواجب الرابع","type":"number","required":true,"min":0,"max":100,"step":0.01}]'::jsonb, '[{"key":"score_1","label":"Assignment 1","type":"number","required":true,"min":0,"max":100,"step":0.01},{"key":"score_2","label":"Assignment 2","type":"number","required":true,"min":0,"max":100,"step":0.01},{"key":"score_3","label":"Assignment 3","type":"number","required":true,"min":0,"max":100,"step":0.01},{"key":"score_4","label":"Assignment 4","type":"number","required":true,"min":0,"max":100,"step":0.01}]'::jsonb, 'احسب المتوسط', 'Calculate average', 1404, false),
  ('education-tools', 'grade-improvement-rate', 'حاسبة تحسن الدرجة', 'Grade Improvement Rate', 'احسب نسبة التحسن بين درجتين.', 'Calculate percentage improvement between two grades.', '{"expression":"(new_score - old_score) / old_score * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة التحسن","resultLabelEn":"Improvement rate","decimals":2,"showEquation":true}'::jsonb, '[{"key":"old_score","label":"الدرجة السابقة","type":"number","required":true,"min":1e-06,"step":0.01},{"key":"new_score","label":"الدرجة الجديدة","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"old_score","label":"Previous score","type":"number","required":true,"min":1e-06,"step":0.01},{"key":"new_score","label":"New score","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'احسب التحسن', 'Calculate improvement', 1405, false),
  ('education-tools', 'completed-credits-rate', 'حاسبة نسبة الساعات المنجزة', 'Completed Credits Rate', 'احسب نسبة الساعات الأكاديمية المنجزة من إجمالي الخطة.', 'Calculate completed academic credits as a share of the plan.', '{"expression":"completed_credits / total_credits * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة الساعات المنجزة","resultLabelEn":"Completed credits rate","decimals":2,"showEquation":true}'::jsonb, '[{"key":"completed_credits","label":"الساعات المنجزة","type":"number","required":true,"min":0,"step":1},{"key":"total_credits","label":"إجمالي ساعات الخطة","type":"number","required":true,"min":1,"step":1}]'::jsonb, '[{"key":"completed_credits","label":"Completed credits","type":"number","required":true,"min":0,"step":1},{"key":"total_credits","label":"Total plan credits","type":"number","required":true,"min":1,"step":1}]'::jsonb, 'احسب النسبة', 'Calculate rate', 1406, false),
  ('education-tools', 'points-needed-for-target', 'حاسبة النقاط المطلوبة للهدف', 'Points Needed for Target', 'احسب عدد النقاط المتبقية للوصول إلى هدف دراسي.', 'Calculate remaining points needed to reach a study target.', '{"expression":"target_points - current_points","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"النقاط المتبقية","resultLabelEn":"Remaining points","decimals":2,"showEquation":true}'::jsonb, '[{"key":"target_points","label":"النقاط المستهدفة","type":"number","required":true,"min":0,"step":0.01},{"key":"current_points","label":"النقاط الحالية","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"target_points","label":"Target points","type":"number","required":true,"min":0,"step":0.01},{"key":"current_points","label":"Current points","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'احسب المتبقي', 'Calculate remaining', 1407, false),
  ('employment-tools', 'net-salary-after-deductions', 'حاسبة صافي الراتب بعد الخصومات', 'Net Salary after Deductions', 'احسب صافي الراتب بعد طرح الخصومات الشهرية.', 'Calculate net salary after monthly deductions.', '{"expression":"gross_salary - deductions","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"صافي الراتب","resultLabelEn":"Net salary","decimals":2,"showEquation":true}'::jsonb, '[{"key":"gross_salary","label":"الراتب الإجمالي","type":"number","required":true,"min":0,"step":0.01},{"key":"deductions","label":"إجمالي الخصومات","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"gross_salary","label":"Gross salary","type":"number","required":true,"min":0,"step":0.01},{"key":"deductions","label":"Total deductions","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'احسب صافي الراتب', 'Calculate net salary', 1500, true),
  ('employment-tools', 'annual-compensation-calculator', 'حاسبة التعويض السنوي', 'Annual Compensation Calculator', 'احسب التعويض السنوي من الراتب الشهري والمكافآت.', 'Calculate annual compensation from monthly salary and bonuses.', '{"expression":"monthly_salary * 12 + annual_bonus","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"التعويض السنوي","resultLabelEn":"Annual compensation","decimals":2,"showEquation":true}'::jsonb, '[{"key":"monthly_salary","label":"الراتب الشهري","type":"number","required":true,"min":0,"step":0.01},{"key":"annual_bonus","label":"المكافآت السنوية","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"monthly_salary","label":"Monthly salary","type":"number","required":true,"min":0,"step":0.01},{"key":"annual_bonus","label":"Annual bonus","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'احسب التعويض', 'Calculate compensation', 1501, false),
  ('employment-tools', 'employer-payroll-cost', 'حاسبة تكلفة الموظف على المنشأة', 'Employer Payroll Cost', 'احسب تكلفة الموظف الشهرية بإضافة المزايا والتكاليف على الراتب.', 'Calculate monthly employer cost including benefits and overhead.', '{"expression":"salary + benefits + employer_costs","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"التكلفة الشهرية للموظف","resultLabelEn":"Monthly employer cost","decimals":2,"showEquation":true}'::jsonb, '[{"key":"salary","label":"الراتب","type":"number","required":true,"min":0,"step":0.01},{"key":"benefits","label":"المزايا الشهرية","type":"number","required":true,"min":0,"step":0.01},{"key":"employer_costs","label":"تكاليف صاحب العمل","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"salary","label":"Salary","type":"number","required":true,"min":0,"step":0.01},{"key":"benefits","label":"Monthly benefits","type":"number","required":true,"min":0,"step":0.01},{"key":"employer_costs","label":"Employer costs","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'احسب التكلفة', 'Calculate cost', 1502, false),
  ('employment-tools', 'vacation-pay-estimate', 'حاسبة بدل الإجازة', 'Vacation Pay Estimate', 'قدّر قيمة أيام الإجازة من الراتب الشهري وعدد الأيام.', 'Estimate vacation pay from monthly salary and leave days.', '{"expression":"monthly_salary / 30 * vacation_days","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"بدل الإجازة التقديري","resultLabelEn":"Estimated vacation pay","decimals":2,"showEquation":true}'::jsonb, '[{"key":"monthly_salary","label":"الراتب الشهري","type":"number","required":true,"min":0,"step":0.01},{"key":"vacation_days","label":"أيام الإجازة","type":"number","required":true,"min":0,"step":1}]'::jsonb, '[{"key":"monthly_salary","label":"Monthly salary","type":"number","required":true,"min":0,"step":0.01},{"key":"vacation_days","label":"Vacation days","type":"number","required":true,"min":0,"step":1}]'::jsonb, 'احسب بدل الإجازة', 'Calculate vacation pay', 1503, false),
  ('employment-tools', 'bonus-amount-calculator', 'حاسبة مبلغ المكافأة', 'Bonus Amount Calculator', 'احسب مبلغ المكافأة كنسبة من الراتب.', 'Calculate bonus amount as a percentage of salary.', '{"expression":"salary * bonus_rate / 100","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"مبلغ المكافأة","resultLabelEn":"Bonus amount","decimals":2,"showEquation":true}'::jsonb, '[{"key":"salary","label":"الراتب","type":"number","required":true,"min":0,"step":0.01},{"key":"bonus_rate","label":"نسبة المكافأة","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"salary","label":"Salary","type":"number","required":true,"min":0,"step":0.01},{"key":"bonus_rate","label":"Bonus rate","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'احسب المكافأة', 'Calculate bonus', 1504, false),
  ('employment-tools', 'commission-plus-salary', 'حاسبة الراتب مع العمولة', 'Salary plus Commission Calculator', 'احسب الدخل الشهري من الراتب الأساسي وعمولة المبيعات.', 'Calculate monthly income from base salary and sales commission.', '{"expression":"base_salary + sales * commission_rate / 100","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"الدخل الشهري","resultLabelEn":"Monthly income","decimals":2,"showEquation":true}'::jsonb, '[{"key":"base_salary","label":"الراتب الأساسي","type":"number","required":true,"min":0,"step":0.01},{"key":"sales","label":"المبيعات","type":"number","required":true,"min":0,"step":0.01},{"key":"commission_rate","label":"نسبة العمولة","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"base_salary","label":"Base salary","type":"number","required":true,"min":0,"step":0.01},{"key":"sales","label":"Sales","type":"number","required":true,"min":0,"step":0.01},{"key":"commission_rate","label":"Commission rate","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'احسب الدخل', 'Calculate income', 1505, false),
  ('employment-tools', 'unpaid-leave-deduction', 'حاسبة خصم الإجازة بدون راتب', 'Unpaid Leave Deduction', 'احسب قيمة الخصم مقابل أيام الإجازة بدون راتب.', 'Calculate deduction for unpaid leave days.', '{"expression":"monthly_salary / 30 * unpaid_days","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"قيمة الخصم","resultLabelEn":"Deduction amount","decimals":2,"showEquation":true}'::jsonb, '[{"key":"monthly_salary","label":"الراتب الشهري","type":"number","required":true,"min":0,"step":0.01},{"key":"unpaid_days","label":"أيام الإجازة بدون راتب","type":"number","required":true,"min":0,"step":1}]'::jsonb, '[{"key":"monthly_salary","label":"Monthly salary","type":"number","required":true,"min":0,"step":0.01},{"key":"unpaid_days","label":"Unpaid leave days","type":"number","required":true,"min":0,"step":1}]'::jsonb, 'احسب الخصم', 'Calculate deduction', 1506, false),
  ('employment-tools', 'shift-premium-pay', 'حاسبة بدل الوردية', 'Shift Premium Pay', 'احسب بدل الوردية من الأجر بالساعة والساعات ونسبة البدل.', 'Calculate shift premium from hourly rate, hours, and premium rate.', '{"expression":"hourly_rate * shift_hours * premium_rate / 100","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"بدل الوردية","resultLabelEn":"Shift premium","decimals":2,"showEquation":true}'::jsonb, '[{"key":"hourly_rate","label":"الأجر بالساعة","type":"number","required":true,"min":0,"step":0.01},{"key":"shift_hours","label":"ساعات الوردية","type":"number","required":true,"min":0,"step":0.25},{"key":"premium_rate","label":"نسبة بدل الوردية","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"hourly_rate","label":"Hourly rate","type":"number","required":true,"min":0,"step":0.01},{"key":"shift_hours","label":"Shift hours","type":"number","required":true,"min":0,"step":0.25},{"key":"premium_rate","label":"Shift premium rate","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'احسب البدل', 'Calculate premium', 1507, false),
  ('marketing-tools', 'customer-lifetime-value-simple', 'حاسبة القيمة العمرية للعميل', 'Customer Lifetime Value Calculator', 'قدّر القيمة العمرية للعميل من متوسط الطلب وعدد الطلبات والمدة.', 'Estimate customer lifetime value from order value, frequency, and lifetime.', '{"expression":"average_order_value * purchases_per_year * customer_years","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"القيمة العمرية التقديرية","resultLabelEn":"Estimated customer lifetime value","decimals":2,"showEquation":true}'::jsonb, '[{"key":"average_order_value","label":"متوسط قيمة الطلب","type":"number","required":true,"min":0,"step":0.01},{"key":"purchases_per_year","label":"عدد المشتريات سنويًا","type":"number","required":true,"min":0,"step":0.01},{"key":"customer_years","label":"مدة العميل بالسنوات","type":"number","required":true,"min":0,"step":0.1}]'::jsonb, '[{"key":"average_order_value","label":"Average order value","type":"number","required":true,"min":0,"step":0.01},{"key":"purchases_per_year","label":"Purchases per year","type":"number","required":true,"min":0,"step":0.01},{"key":"customer_years","label":"Customer lifetime in years","type":"number","required":true,"min":0,"step":0.1}]'::jsonb, 'احسب القيمة العمرية', 'Calculate CLV', 1600, true),
  ('marketing-tools', 'lead-to-sale-rate', 'حاسبة تحويل العملاء المحتملين إلى مبيعات', 'Lead to Sale Rate', 'احسب نسبة العملاء المحتملين الذين تحولوا إلى مبيعات.', 'Calculate the percentage of leads converted into sales.', '{"expression":"sales / leads * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"معدل التحويل إلى مبيعات","resultLabelEn":"Lead-to-sale rate","decimals":2,"showEquation":true}'::jsonb, '[{"key":"sales","label":"عدد المبيعات","type":"number","required":true,"min":0,"step":1},{"key":"leads","label":"عدد العملاء المحتملين","type":"number","required":true,"min":1,"step":1}]'::jsonb, '[{"key":"sales","label":"Sales","type":"number","required":true,"min":0,"step":1},{"key":"leads","label":"Leads","type":"number","required":true,"min":1,"step":1}]'::jsonb, 'احسب معدل التحويل', 'Calculate conversion', 1601, false),
  ('marketing-tools', 'marketing-efficiency-ratio', 'حاسبة كفاءة الإنفاق التسويقي', 'Marketing Efficiency Ratio', 'احسب نسبة الإيراد إلى الإنفاق التسويقي.', 'Calculate revenue generated per unit of marketing spend.', '{"expression":"revenue / marketing_spend","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"معامل الكفاءة التسويقية","resultLabelEn":"Marketing efficiency ratio","decimals":3,"showEquation":true}'::jsonb, '[{"key":"revenue","label":"الإيراد","type":"number","required":true,"min":0,"step":0.01},{"key":"marketing_spend","label":"الإنفاق التسويقي","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, '[{"key":"revenue","label":"Revenue","type":"number","required":true,"min":0,"step":0.01},{"key":"marketing_spend","label":"Marketing spend","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, 'احسب الكفاءة', 'Calculate efficiency', 1602, false),
  ('marketing-tools', 'ad-frequency-calculator', 'حاسبة تكرار الإعلان', 'Ad Frequency Calculator', 'احسب متوسط عدد مرات ظهور الإعلان لكل مستخدم.', 'Calculate average ad impressions per reached user.', '{"expression":"impressions / reach","outputUnitAr":"","outputUnitEn":"","resultLabelAr":"تكرار الإعلان","resultLabelEn":"Ad frequency","decimals":2,"showEquation":true}'::jsonb, '[{"key":"impressions","label":"مرات الظهور","type":"number","required":true,"min":0,"step":1},{"key":"reach","label":"الوصول","type":"number","required":true,"min":1,"step":1}]'::jsonb, '[{"key":"impressions","label":"Impressions","type":"number","required":true,"min":0,"step":1},{"key":"reach","label":"Reach","type":"number","required":true,"min":1,"step":1}]'::jsonb, 'احسب التكرار', 'Calculate frequency', 1603, false),
  ('marketing-tools', 'landing-page-bounce-rate', 'حاسبة معدل ارتداد صفحة الهبوط', 'Landing Page Bounce Rate', 'احسب نسبة الجلسات التي غادرت دون تفاعل.', 'Calculate the share of sessions that left without interaction.', '{"expression":"bounced_sessions / total_sessions * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"معدل الارتداد","resultLabelEn":"Bounce rate","decimals":2,"showEquation":true}'::jsonb, '[{"key":"bounced_sessions","label":"الجلسات المرتدة","type":"number","required":true,"min":0,"step":1},{"key":"total_sessions","label":"إجمالي الجلسات","type":"number","required":true,"min":1,"step":1}]'::jsonb, '[{"key":"bounced_sessions","label":"Bounced sessions","type":"number","required":true,"min":0,"step":1},{"key":"total_sessions","label":"Total sessions","type":"number","required":true,"min":1,"step":1}]'::jsonb, 'احسب معدل الارتداد', 'Calculate bounce rate', 1604, false),
  ('marketing-tools', 'email-click-to-open-rate', 'حاسبة معدل النقر إلى الفتح', 'Email Click-to-Open Rate', 'احسب نسبة النقرات إلى عدد الرسائل المفتوحة.', 'Calculate clicks as a percentage of opened emails.', '{"expression":"clicks / opens * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"معدل النقر إلى الفتح","resultLabelEn":"Click-to-open rate","decimals":2,"showEquation":true}'::jsonb, '[{"key":"clicks","label":"عدد النقرات","type":"number","required":true,"min":0,"step":1},{"key":"opens","label":"عدد الفتحات","type":"number","required":true,"min":1,"step":1}]'::jsonb, '[{"key":"clicks","label":"Clicks","type":"number","required":true,"min":0,"step":1},{"key":"opens","label":"Opens","type":"number","required":true,"min":1,"step":1}]'::jsonb, 'احسب CTOR', 'Calculate CTOR', 1605, false),
  ('marketing-tools', 'unsubscribe-rate-calculator', 'حاسبة معدل إلغاء الاشتراك', 'Unsubscribe Rate Calculator', 'احسب نسبة إلغاء الاشتراك من الرسائل المستلمة.', 'Calculate unsubscribes as a percentage of delivered emails.', '{"expression":"unsubscribes / delivered * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"معدل إلغاء الاشتراك","resultLabelEn":"Unsubscribe rate","decimals":2,"showEquation":true}'::jsonb, '[{"key":"unsubscribes","label":"إلغاءات الاشتراك","type":"number","required":true,"min":0,"step":1},{"key":"delivered","label":"الرسائل المستلمة","type":"number","required":true,"min":1,"step":1}]'::jsonb, '[{"key":"unsubscribes","label":"Unsubscribes","type":"number","required":true,"min":0,"step":1},{"key":"delivered","label":"Delivered emails","type":"number","required":true,"min":1,"step":1}]'::jsonb, 'احسب المعدل', 'Calculate rate', 1606, false),
  ('marketing-tools', 'repeat-purchase-rate', 'حاسبة معدل الشراء المتكرر', 'Repeat Purchase Rate', 'احسب نسبة العملاء الذين اشتروا أكثر من مرة.', 'Calculate the percentage of customers who purchased more than once.', '{"expression":"repeat_customers / total_customers * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"معدل الشراء المتكرر","resultLabelEn":"Repeat purchase rate","decimals":2,"showEquation":true}'::jsonb, '[{"key":"repeat_customers","label":"العملاء المتكررون","type":"number","required":true,"min":0,"step":1},{"key":"total_customers","label":"إجمالي العملاء","type":"number","required":true,"min":1,"step":1}]'::jsonb, '[{"key":"repeat_customers","label":"Repeat customers","type":"number","required":true,"min":0,"step":1},{"key":"total_customers","label":"Total customers","type":"number","required":true,"min":1,"step":1}]'::jsonb, 'احسب المعدل', 'Calculate rate', 1607, false),
  ('finance-tools', 'personal-savings-rate', 'حاسبة معدل الادخار الشخصي', 'Personal Savings Rate', 'احسب نسبة الادخار من صافي الدخل.', 'Calculate savings as a percentage of net income.', '{"expression":"monthly_savings / net_income * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"معدل الادخار","resultLabelEn":"Savings rate","decimals":2,"showEquation":true}'::jsonb, '[{"key":"monthly_savings","label":"الادخار الشهري","type":"number","required":true,"min":0,"step":0.01},{"key":"net_income","label":"صافي الدخل","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, '[{"key":"monthly_savings","label":"Monthly savings","type":"number","required":true,"min":0,"step":0.01},{"key":"net_income","label":"Net income","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, 'احسب معدل الادخار', 'Calculate savings rate', 1700, true),
  ('finance-tools', 'debt-service-ratio', 'حاسبة نسبة خدمة الدين', 'Debt Service Ratio', 'احسب نسبة أقساط الديون إلى الدخل الشهري.', 'Calculate monthly debt payments as a share of income.', '{"expression":"monthly_debt_payments / monthly_income * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة خدمة الدين","resultLabelEn":"Debt service ratio","decimals":2,"showEquation":true}'::jsonb, '[{"key":"monthly_debt_payments","label":"أقساط الديون الشهرية","type":"number","required":true,"min":0,"step":0.01},{"key":"monthly_income","label":"الدخل الشهري","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, '[{"key":"monthly_debt_payments","label":"Monthly debt payments","type":"number","required":true,"min":0,"step":0.01},{"key":"monthly_income","label":"Monthly income","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, 'احسب النسبة', 'Calculate ratio', 1701, false),
  ('finance-tools', 'emergency-fund-months', 'حاسبة مدة صندوق الطوارئ', 'Emergency Fund Months', 'احسب عدد الأشهر التي يغطيها صندوق الطوارئ.', 'Calculate how many months an emergency fund can cover.', '{"expression":"emergency_fund / monthly_expenses","outputUnitAr":" شهر","outputUnitEn":" months","resultLabelAr":"أشهر التغطية","resultLabelEn":"Months covered","decimals":2,"showEquation":true}'::jsonb, '[{"key":"emergency_fund","label":"رصيد صندوق الطوارئ","type":"number","required":true,"min":0,"step":0.01},{"key":"monthly_expenses","label":"المصروفات الشهرية","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, '[{"key":"emergency_fund","label":"Emergency fund balance","type":"number","required":true,"min":0,"step":0.01},{"key":"monthly_expenses","label":"Monthly expenses","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, 'احسب مدة التغطية', 'Calculate coverage', 1702, false),
  ('finance-tools', 'rule-of-72-calculator', 'حاسبة قاعدة 72', 'Rule of 72 Calculator', 'قدّر عدد السنوات اللازمة لمضاعفة الاستثمار باستخدام قاعدة 72.', 'Estimate years to double an investment using the Rule of 72.', '{"expression":"72 / annual_rate","outputUnitAr":" سنة","outputUnitEn":" years","resultLabelAr":"سنوات المضاعفة التقديرية","resultLabelEn":"Estimated doubling years","decimals":2,"showEquation":true}'::jsonb, '[{"key":"annual_rate","label":"معدل العائد السنوي","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, '[{"key":"annual_rate","label":"Annual return rate","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, 'احسب السنوات', 'Calculate years', 1703, false),
  ('finance-tools', 'monthly-budget-surplus', 'حاسبة فائض الميزانية الشهرية', 'Monthly Budget Surplus', 'احسب الفائض أو العجز بعد طرح المصروفات من الدخل.', 'Calculate monthly surplus or deficit after expenses.', '{"expression":"monthly_income - monthly_expenses","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"الفائض أو العجز","resultLabelEn":"Surplus or deficit","decimals":2,"showEquation":true}'::jsonb, '[{"key":"monthly_income","label":"الدخل الشهري","type":"number","required":true,"min":0,"step":0.01},{"key":"monthly_expenses","label":"المصروفات الشهرية","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"monthly_income","label":"Monthly income","type":"number","required":true,"min":0,"step":0.01},{"key":"monthly_expenses","label":"Monthly expenses","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'احسب الفائض', 'Calculate surplus', 1704, false),
  ('finance-tools', 'annual-expense-projection', 'حاسبة المصروفات السنوية', 'Annual Expense Projection', 'قدّر المصروفات السنوية من المتوسط الشهري.', 'Estimate annual expenses from a monthly average.', '{"expression":"monthly_expenses * 12","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"المصروفات السنوية","resultLabelEn":"Annual expenses","decimals":2,"showEquation":true}'::jsonb, '[{"key":"monthly_expenses","label":"متوسط المصروفات الشهرية","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"monthly_expenses","label":"Average monthly expenses","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'احسب المصروفات السنوية', 'Calculate annual expenses', 1705, false),
  ('finance-tools', 'sinking-fund-contribution', 'حاسبة مساهمة الهدف الادخاري', 'Sinking Fund Contribution', 'احسب المبلغ الشهري المطلوب للوصول إلى هدف خلال مدة محددة.', 'Calculate monthly contribution required to reach a target.', '{"expression":"(target_amount - current_savings) / months","outputUnitAr":" ر.س/شهر","outputUnitEn":" SAR/month","resultLabelAr":"المساهمة الشهرية","resultLabelEn":"Monthly contribution","decimals":2,"showEquation":true}'::jsonb, '[{"key":"target_amount","label":"المبلغ المستهدف","type":"number","required":true,"min":0,"step":0.01},{"key":"current_savings","label":"المدخرات الحالية","type":"number","required":true,"min":0,"step":0.01},{"key":"months","label":"عدد الأشهر","type":"number","required":true,"min":1,"step":1}]'::jsonb, '[{"key":"target_amount","label":"Target amount","type":"number","required":true,"min":0,"step":0.01},{"key":"current_savings","label":"Current savings","type":"number","required":true,"min":0,"step":0.01},{"key":"months","label":"Months","type":"number","required":true,"min":1,"step":1}]'::jsonb, 'احسب المساهمة', 'Calculate contribution', 1706, false),
  ('finance-tools', 'cash-runway-calculator', 'حاسبة مدة السيولة', 'Cash Runway Calculator', 'احسب عدد الأشهر التي يغطيها الرصيد النقدي بمعدل الصرف الحالي.', 'Calculate months of runway from cash balance and monthly burn.', '{"expression":"cash_balance / monthly_burn","outputUnitAr":" شهر","outputUnitEn":" months","resultLabelAr":"مدة السيولة","resultLabelEn":"Cash runway","decimals":2,"showEquation":true}'::jsonb, '[{"key":"cash_balance","label":"الرصيد النقدي","type":"number","required":true,"min":0,"step":0.01},{"key":"monthly_burn","label":"معدل الصرف الشهري","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, '[{"key":"cash_balance","label":"Cash balance","type":"number","required":true,"min":0,"step":0.01},{"key":"monthly_burn","label":"Monthly burn","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, 'احسب مدة السيولة', 'Calculate runway', 1707, false),
  ('general-tools', 'productivity-rate-calculator', 'حاسبة معدل الإنتاجية', 'Productivity Rate Calculator', 'احسب عدد الوحدات المنجزة لكل ساعة.', 'Calculate completed units per hour.', '{"expression":"completed_units / hours","outputUnitAr":" وحدة/ساعة","outputUnitEn":" units/hour","resultLabelAr":"معدل الإنتاجية","resultLabelEn":"Productivity rate","decimals":2,"showEquation":true}'::jsonb, '[{"key":"completed_units","label":"الوحدات المنجزة","type":"number","required":true,"min":0,"step":1},{"key":"hours","label":"الساعات","type":"number","required":true,"min":1e-06,"step":0.25}]'::jsonb, '[{"key":"completed_units","label":"Completed units","type":"number","required":true,"min":0,"step":1},{"key":"hours","label":"Hours","type":"number","required":true,"min":1e-06,"step":0.25}]'::jsonb, 'احسب الإنتاجية', 'Calculate productivity', 1800, true),
  ('general-tools', 'task-completion-rate', 'حاسبة نسبة إنجاز المهام', 'Task Completion Rate', 'احسب نسبة المهام المكتملة من إجمالي المهام.', 'Calculate completed tasks as a percentage of total tasks.', '{"expression":"completed_tasks / total_tasks * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"نسبة الإنجاز","resultLabelEn":"Completion rate","decimals":2,"showEquation":true}'::jsonb, '[{"key":"completed_tasks","label":"المهام المكتملة","type":"number","required":true,"min":0,"step":1},{"key":"total_tasks","label":"إجمالي المهام","type":"number","required":true,"min":1,"step":1}]'::jsonb, '[{"key":"completed_tasks","label":"Completed tasks","type":"number","required":true,"min":0,"step":1},{"key":"total_tasks","label":"Total tasks","type":"number","required":true,"min":1,"step":1}]'::jsonb, 'احسب النسبة', 'Calculate rate', 1801, false),
  ('general-tools', 'fuel-efficiency-calculator', 'حاسبة كفاءة استهلاك الوقود', 'Fuel Efficiency Calculator', 'احسب المسافة المقطوعة لكل لتر وقود.', 'Calculate distance traveled per liter of fuel.', '{"expression":"distance_km / liters","outputUnitAr":" كم/لتر","outputUnitEn":" km/L","resultLabelAr":"كفاءة الوقود","resultLabelEn":"Fuel efficiency","decimals":2,"showEquation":true}'::jsonb, '[{"key":"distance_km","label":"المسافة بالكيلومتر","type":"number","required":true,"min":0,"step":0.01},{"key":"liters","label":"الوقود باللتر","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, '[{"key":"distance_km","label":"Distance in km","type":"number","required":true,"min":0,"step":0.01},{"key":"liters","label":"Fuel in liters","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, 'احسب الكفاءة', 'Calculate efficiency', 1802, false),
  ('general-tools', 'trip-fuel-cost-calculator', 'حاسبة تكلفة وقود الرحلة', 'Trip Fuel Cost Calculator', 'احسب تكلفة الوقود لرحلة من المسافة والكفاءة وسعر اللتر.', 'Calculate trip fuel cost from distance, efficiency, and fuel price.', '{"expression":"distance_km / km_per_liter * price_per_liter","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"تكلفة وقود الرحلة","resultLabelEn":"Trip fuel cost","decimals":2,"showEquation":true}'::jsonb, '[{"key":"distance_km","label":"مسافة الرحلة بالكيلومتر","type":"number","required":true,"min":0,"step":0.01},{"key":"km_per_liter","label":"كفاءة السيارة كم/لتر","type":"number","required":true,"min":1e-06,"step":0.01},{"key":"price_per_liter","label":"سعر اللتر","type":"number","required":true,"min":0,"step":0.001}]'::jsonb, '[{"key":"distance_km","label":"Trip distance in km","type":"number","required":true,"min":0,"step":0.01},{"key":"km_per_liter","label":"Vehicle efficiency km/L","type":"number","required":true,"min":1e-06,"step":0.01},{"key":"price_per_liter","label":"Price per liter","type":"number","required":true,"min":0,"step":0.001}]'::jsonb, 'احسب التكلفة', 'Calculate cost', 1803, false),
  ('general-tools', 'electricity-usage-cost', 'حاسبة تكلفة استهلاك الكهرباء', 'Electricity Usage Cost', 'احسب تكلفة جهاز من القدرة وساعات التشغيل وسعر الكيلوواط.', 'Calculate appliance electricity cost from power, hours, and tariff.', '{"expression":"watts / 1000 * hours * price_per_kwh","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"تكلفة الاستهلاك","resultLabelEn":"Usage cost","decimals":2,"showEquation":true}'::jsonb, '[{"key":"watts","label":"قدرة الجهاز بالواط","type":"number","required":true,"min":0,"step":1},{"key":"hours","label":"ساعات التشغيل","type":"number","required":true,"min":0,"step":0.1},{"key":"price_per_kwh","label":"سعر الكيلوواط ساعة","type":"number","required":true,"min":0,"step":0.001}]'::jsonb, '[{"key":"watts","label":"Appliance power in watts","type":"number","required":true,"min":0,"step":1},{"key":"hours","label":"Operating hours","type":"number","required":true,"min":0,"step":0.1},{"key":"price_per_kwh","label":"Price per kWh","type":"number","required":true,"min":0,"step":0.001}]'::jsonb, 'احسب التكلفة', 'Calculate cost', 1804, false),
  ('general-tools', 'water-consumption-cost', 'حاسبة تكلفة استهلاك المياه', 'Water Consumption Cost', 'احسب تكلفة استهلاك المياه من الحجم وسعر الوحدة.', 'Calculate water consumption cost from volume and unit price.', '{"expression":"cubic_meters * price_per_cubic_meter","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"تكلفة الاستهلاك","resultLabelEn":"Consumption cost","decimals":2,"showEquation":true}'::jsonb, '[{"key":"cubic_meters","label":"الاستهلاك بالمتر المكعب","type":"number","required":true,"min":0,"step":0.01},{"key":"price_per_cubic_meter","label":"سعر المتر المكعب","type":"number","required":true,"min":0,"step":0.001}]'::jsonb, '[{"key":"cubic_meters","label":"Consumption in cubic meters","type":"number","required":true,"min":0,"step":0.01},{"key":"price_per_cubic_meter","label":"Price per cubic meter","type":"number","required":true,"min":0,"step":0.001}]'::jsonb, 'احسب التكلفة', 'Calculate cost', 1805, false),
  ('general-tools', 'unit-price-comparison', 'حاسبة سعر الوحدة', 'Unit Price Calculator', 'احسب سعر الوحدة لمقارنة العبوات أو العروض.', 'Calculate price per unit for product comparison.', '{"expression":"total_price / quantity","outputUnitAr":" ر.س/وحدة","outputUnitEn":" SAR/unit","resultLabelAr":"سعر الوحدة","resultLabelEn":"Unit price","decimals":2,"showEquation":true}'::jsonb, '[{"key":"total_price","label":"السعر الإجمالي","type":"number","required":true,"min":0,"step":0.01},{"key":"quantity","label":"الكمية","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, '[{"key":"total_price","label":"Total price","type":"number","required":true,"min":0,"step":0.01},{"key":"quantity","label":"Quantity","type":"number","required":true,"min":1e-06,"step":0.01}]'::jsonb, 'احسب سعر الوحدة', 'Calculate unit price', 1806, false),
  ('general-tools', 'shared-expense-split', 'حاسبة تقسيم المصروف المشترك', 'Shared Expense Split', 'قسّم مبلغًا مشتركًا بالتساوي على عدد الأشخاص.', 'Split a shared expense equally among people.', '{"expression":"total_amount / people","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"نصيب الفرد","resultLabelEn":"Per-person share","decimals":2,"showEquation":true}'::jsonb, '[{"key":"total_amount","label":"المبلغ الإجمالي","type":"number","required":true,"min":0,"step":0.01},{"key":"people","label":"عدد الأشخاص","type":"number","required":true,"min":1,"step":1}]'::jsonb, '[{"key":"total_amount","label":"Total amount","type":"number","required":true,"min":0,"step":0.01},{"key":"people","label":"People","type":"number","required":true,"min":1,"step":1}]'::jsonb, 'احسب نصيب الفرد', 'Calculate share', 1807, false),
  ('converter-tools', 'millimeter-to-inch-converter', 'محول المليمتر إلى بوصة', 'Millimeter to Inch Converter', 'حوّل المليمتر إلى الوحدة المطلوبة.', 'Convert millimeters to the target unit.', '{"expression":"millimeters / 25.4","outputUnitAr":" بوصة","outputUnitEn":" in","resultLabelAr":"الطول بالبوصة","resultLabelEn":"Length in inches","decimals":2,"showEquation":true}'::jsonb, '[{"key":"millimeters","label":"المليمتر","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"millimeters","label":"Millimeters","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'حوّل القيمة', 'Convert value', 1900, true),
  ('converter-tools', 'inch-to-millimeter-converter', 'محول البوصة إلى مليمتر', 'Inch to Millimeter Converter', 'حوّل البوصة إلى الوحدة المطلوبة.', 'Convert inches to the target unit.', '{"expression":"inches * 25.4","outputUnitAr":" مم","outputUnitEn":" mm","resultLabelAr":"الطول بالمليمتر","resultLabelEn":"Length in millimeters","decimals":2,"showEquation":true}'::jsonb, '[{"key":"inches","label":"البوصة","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"inches","label":"Inches","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'حوّل القيمة', 'Convert value', 1901, false),
  ('converter-tools', 'liter-to-us-gallon-converter', 'محول اللتر إلى جالون أمريكي', 'Liter to US Gallon Converter', 'حوّل اللتر إلى الوحدة المطلوبة.', 'Convert liters to the target unit.', '{"expression":"liters / 3.785411784","outputUnitAr":" جالون","outputUnitEn":" gal","resultLabelAr":"الحجم بالجالون","resultLabelEn":"Volume in gallons","decimals":2,"showEquation":true}'::jsonb, '[{"key":"liters","label":"اللتر","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"liters","label":"Liters","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'حوّل القيمة', 'Convert value', 1902, false),
  ('converter-tools', 'us-gallon-to-liter-converter', 'محول الجالون الأمريكي إلى لتر', 'US Gallon to Liter Converter', 'حوّل الجالون الأمريكي إلى الوحدة المطلوبة.', 'Convert us gallons to the target unit.', '{"expression":"gallons * 3.785411784","outputUnitAr":" لتر","outputUnitEn":" L","resultLabelAr":"الحجم باللتر","resultLabelEn":"Volume in liters","decimals":2,"showEquation":true}'::jsonb, '[{"key":"gallons","label":"الجالون الأمريكي","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"gallons","label":"US gallons","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'حوّل القيمة', 'Convert value', 1903, false),
  ('converter-tools', 'square-meter-to-square-foot', 'محول المتر المربع إلى قدم مربع', 'Square Meter to Square Foot', 'حوّل المتر المربع إلى الوحدة المطلوبة.', 'Convert square meters to the target unit.', '{"expression":"square_meters * 10.7639104167","outputUnitAr":" قدم²","outputUnitEn":" ft²","resultLabelAr":"المساحة بالقدم المربع","resultLabelEn":"Area in square feet","decimals":2,"showEquation":true}'::jsonb, '[{"key":"square_meters","label":"المتر المربع","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"square_meters","label":"Square meters","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'حوّل القيمة', 'Convert value', 1904, false),
  ('converter-tools', 'square-foot-to-square-meter', 'محول القدم المربع إلى متر مربع', 'Square Foot to Square Meter', 'حوّل القدم المربع إلى الوحدة المطلوبة.', 'Convert square feet to the target unit.', '{"expression":"square_feet / 10.7639104167","outputUnitAr":" م²","outputUnitEn":" m²","resultLabelAr":"المساحة بالمتر المربع","resultLabelEn":"Area in square meters","decimals":2,"showEquation":true}'::jsonb, '[{"key":"square_feet","label":"القدم المربع","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"square_feet","label":"Square feet","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'حوّل القيمة', 'Convert value', 1905, false),
  ('converter-tools', 'kilometer-hour-to-mile-hour', 'محول كم/س إلى ميل/س', 'Kilometers per Hour to Miles per Hour', 'حوّل السرعة كم/س إلى الوحدة المطلوبة.', 'Convert speed in km/h to the target unit.', '{"expression":"kmh * 0.6213711922","outputUnitAr":" ميل/س","outputUnitEn":" mph","resultLabelAr":"السرعة بالميل/س","resultLabelEn":"Speed in mph","decimals":2,"showEquation":true}'::jsonb, '[{"key":"kmh","label":"السرعة كم/س","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"kmh","label":"Speed in km/h","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'حوّل القيمة', 'Convert value', 1906, false),
  ('converter-tools', 'mile-hour-to-kilometer-hour', 'محول ميل/س إلى كم/س', 'Miles per Hour to Kilometers per Hour', 'حوّل السرعة ميل/س إلى الوحدة المطلوبة.', 'Convert speed in mph to the target unit.', '{"expression":"mph / 0.6213711922","outputUnitAr":" كم/س","outputUnitEn":" km/h","resultLabelAr":"السرعة بالكيلومتر/س","resultLabelEn":"Speed in km/h","decimals":2,"showEquation":true}'::jsonb, '[{"key":"mph","label":"السرعة ميل/س","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"mph","label":"Speed in mph","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'حوّل القيمة', 'Convert value', 1907, false),
  ('saudi-tools', 'gosi-employee-deduction-estimate', 'حاسبة خصم التأمينات للموظف', 'Employee GOSI Deduction Estimate', 'قدّر خصم التأمينات من الأجر الخاضع للاشتراك ونسبة الخصم.', 'Estimate employee social-insurance deduction from contributory wage and rate.', '{"expression":"contributory_wage * deduction_rate / 100","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"الخصم التقديري","resultLabelEn":"Estimated deduction","decimals":2,"showEquation":true,"noteAr":"النتيجة تقديرية، ويجب مراجعة اللوائح والعقد والجهات الرسمية للحالة الفعلية.","noteEn":"This is an estimate; review the applicable regulations, contract, and official authorities."}'::jsonb, '[{"key":"contributory_wage","label":"الأجر الخاضع للاشتراك","type":"number","required":true,"min":0,"step":0.01},{"key":"deduction_rate","label":"نسبة الخصم","type":"number","required":true,"min":0,"max":100,"step":0.01,"defaultValue":9.75}]'::jsonb, '[{"key":"contributory_wage","label":"Contributory wage","type":"number","required":true,"min":0,"step":0.01},{"key":"deduction_rate","label":"Deduction rate","type":"number","required":true,"min":0,"max":100,"step":0.01,"defaultValue":9.75}]'::jsonb, 'احسب الخصم', 'Calculate deduction', 2000, true),
  ('saudi-tools', 'salary-after-gosi-estimate', 'حاسبة الراتب بعد التأمينات', 'Salary after GOSI Estimate', 'قدّر الراتب بعد خصم نسبة التأمينات من الأجر الخاضع.', 'Estimate salary after social-insurance deduction.', '{"expression":"salary - salary * deduction_rate / 100","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"الراتب بعد الخصم","resultLabelEn":"Salary after deduction","decimals":2,"showEquation":true,"noteAr":"النتيجة تقديرية، ويجب مراجعة اللوائح والعقد والجهات الرسمية للحالة الفعلية.","noteEn":"This is an estimate; review the applicable regulations, contract, and official authorities."}'::jsonb, '[{"key":"salary","label":"الراتب الخاضع","type":"number","required":true,"min":0,"step":0.01},{"key":"deduction_rate","label":"نسبة الخصم","type":"number","required":true,"min":0,"max":100,"step":0.01,"defaultValue":9.75}]'::jsonb, '[{"key":"salary","label":"Contributory salary","type":"number","required":true,"min":0,"step":0.01},{"key":"deduction_rate","label":"Deduction rate","type":"number","required":true,"min":0,"max":100,"step":0.01,"defaultValue":9.75}]'::jsonb, 'احسب صافي الراتب', 'Calculate net salary', 2001, false),
  ('saudi-tools', 'end-of-service-first-five-years', 'حاسبة نهاية الخدمة لأول خمس سنوات', 'End-of-Service First Five Years', 'قدّر مكافأة نهاية الخدمة لأول خمس سنوات على أساس نصف راتب لكل سنة.', 'Estimate end-of-service award for the first five years at half a monthly wage per year.', '{"expression":"monthly_wage * years / 2","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"المكافأة التقديرية","resultLabelEn":"Estimated award","decimals":2,"showEquation":true,"noteAr":"النتيجة تقديرية، ويجب مراجعة اللوائح والعقد والجهات الرسمية للحالة الفعلية.","noteEn":"This is an estimate; review the applicable regulations, contract, and official authorities."}'::jsonb, '[{"key":"monthly_wage","label":"الأجر الشهري","type":"number","required":true,"min":0,"step":0.01},{"key":"years","label":"سنوات الخدمة","type":"number","required":true,"min":0,"max":5,"step":0.01}]'::jsonb, '[{"key":"monthly_wage","label":"Monthly wage","type":"number","required":true,"min":0,"step":0.01},{"key":"years","label":"Years of service","type":"number","required":true,"min":0,"max":5,"step":0.01}]'::jsonb, 'احسب المكافأة', 'Calculate award', 2002, false),
  ('saudi-tools', 'end-of-service-over-five-years', 'حاسبة نهاية الخدمة بعد خمس سنوات', 'End-of-Service over Five Years', 'قدّر مكافأة نهاية الخدمة لمن تجاوزت خدمته خمس سنوات.', 'Estimate end-of-service award for service longer than five years.', '{"expression":"monthly_wage * 2.5 + monthly_wage * (years - 5)","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"المكافأة التقديرية","resultLabelEn":"Estimated award","decimals":2,"showEquation":true,"noteAr":"النتيجة تقديرية، ويجب مراجعة اللوائح والعقد والجهات الرسمية للحالة الفعلية.","noteEn":"This is an estimate; review the applicable regulations, contract, and official authorities."}'::jsonb, '[{"key":"monthly_wage","label":"الأجر الشهري","type":"number","required":true,"min":0,"step":0.01},{"key":"years","label":"سنوات الخدمة","type":"number","required":true,"min":5,"step":0.01}]'::jsonb, '[{"key":"monthly_wage","label":"Monthly wage","type":"number","required":true,"min":0,"step":0.01},{"key":"years","label":"Years of service","type":"number","required":true,"min":5,"step":0.01}]'::jsonb, 'احسب المكافأة', 'Calculate award', 2003, false),
  ('saudi-tools', 'housing-allowance-estimate', 'حاسبة بدل السكن', 'Housing Allowance Estimate', 'احسب بدل السكن كنسبة من الراتب الأساسي.', 'Calculate housing allowance as a percentage of base salary.', '{"expression":"basic_salary * allowance_rate / 100","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"بدل السكن","resultLabelEn":"Housing allowance","decimals":2,"showEquation":true,"noteAr":"النتيجة تقديرية، ويجب مراجعة اللوائح والعقد والجهات الرسمية للحالة الفعلية.","noteEn":"This is an estimate; review the applicable regulations, contract, and official authorities."}'::jsonb, '[{"key":"basic_salary","label":"الراتب الأساسي","type":"number","required":true,"min":0,"step":0.01},{"key":"allowance_rate","label":"نسبة بدل السكن","type":"number","required":true,"min":0,"step":0.01,"defaultValue":25}]'::jsonb, '[{"key":"basic_salary","label":"Base salary","type":"number","required":true,"min":0,"step":0.01},{"key":"allowance_rate","label":"Housing allowance rate","type":"number","required":true,"min":0,"step":0.01,"defaultValue":25}]'::jsonb, 'احسب البدل', 'Calculate allowance', 2004, false),
  ('saudi-tools', 'annual-rent-monthly-equivalent', 'محول الإيجار السنوي إلى شهري', 'Annual Rent Monthly Equivalent', 'حوّل قيمة الإيجار السنوي إلى متوسط شهري.', 'Convert annual rent into a monthly equivalent.', '{"expression":"annual_rent / 12","outputUnitAr":" ر.س/شهر","outputUnitEn":" SAR/month","resultLabelAr":"المتوسط الشهري","resultLabelEn":"Monthly equivalent","decimals":2,"showEquation":true}'::jsonb, '[{"key":"annual_rent","label":"الإيجار السنوي","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"annual_rent","label":"Annual rent","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'احسب الإيجار الشهري', 'Calculate monthly rent', 2005, false),
  ('saudi-tools', 'thirty-day-daily-wage', 'حاسبة الأجر اليومي على أساس 30 يومًا', '30-Day Daily Wage Calculator', 'احسب الأجر اليومي بقسمة الراتب الشهري على 30 يومًا.', 'Calculate daily wage by dividing monthly salary by 30 days.', '{"expression":"monthly_salary / 30","outputUnitAr":" ر.س/يوم","outputUnitEn":" SAR/day","resultLabelAr":"الأجر اليومي","resultLabelEn":"Daily wage","decimals":2,"showEquation":true,"noteAr":"النتيجة تقديرية، ويجب مراجعة اللوائح والعقد والجهات الرسمية للحالة الفعلية.","noteEn":"This is an estimate; review the applicable regulations, contract, and official authorities."}'::jsonb, '[{"key":"monthly_salary","label":"الراتب الشهري","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"monthly_salary","label":"Monthly salary","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'احسب الأجر اليومي', 'Calculate daily wage', 2006, false),
  ('saudi-tools', 'zakat-base-estimate', 'حاسبة تقديرية للزكاة 2.5%', '2.5% Zakat Estimate', 'احسب تقديرًا بسيطًا بنسبة 2.5% من الوعاء المدخل.', 'Calculate a simple 2.5% estimate from the entered base.', '{"expression":"zakat_base * 2.5 / 100","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"الزكاة التقديرية","resultLabelEn":"Estimated zakat","decimals":2,"showEquation":true,"noteAr":"النتيجة تقديرية، ويجب مراجعة اللوائح والعقد والجهات الرسمية للحالة الفعلية.","noteEn":"This is an estimate; review the applicable regulations, contract, and official authorities."}'::jsonb, '[{"key":"zakat_base","label":"الوعاء المدخل","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, '[{"key":"zakat_base","label":"Entered base","type":"number","required":true,"min":0,"step":0.01}]'::jsonb, 'احسب التقدير', 'Calculate estimate', 2007, false);

do $$
declare
  v_seed_count integer;
  v_duplicate_count integer;
begin
  select count(*) into v_seed_count from initial_800_tool_seed;
  select count(*) - count(distinct slug) into v_duplicate_count
  from initial_800_tool_seed;

  if v_seed_count <> 88 then
    raise exception 'INITIAL_800_WAVE_SEED_COUNT_MISMATCH:%', v_seed_count;
  end if;

  if v_duplicate_count <> 0 then
    raise exception 'INITIAL_800_WAVE_DUPLICATE_SLUGS:%', v_duplicate_count;
  end if;
end;
$$;

insert into public.tools(
  slug, title_ar, title_en, short_description, category_id, engine_type,
  input_schema, output_schema, runtime_config, pricing_mode, fixed_points,
  minimum_points, requires_auth, is_featured, is_active, sort_order,
  seo_title, seo_description
)
select
  seed.slug,
  seed.title_ar,
  seed.title_en,
  seed.description_ar,
  category.id,
  'formula',
  jsonb_build_object('submitLabel', seed.submit_ar, 'fields', seed.input_fields),
  jsonb_build_object('type', 'number', 'format', 'runtime'),
  seed.runtime_config,
  'free',
  0,
  0,
  false,
  seed.is_featured,
  true,
  seed.sort_order,
  seed.title_ar || ' مجانًا | أمبراطورية الويب',
  seed.description_ar
from initial_800_tool_seed seed
join public.categories category on category.slug = seed.category_slug
on conflict (slug) do update set
  title_ar = excluded.title_ar,
  title_en = excluded.title_en,
  short_description = excluded.short_description,
  category_id = excluded.category_id,
  engine_type = excluded.engine_type,
  input_schema = excluded.input_schema,
  output_schema = excluded.output_schema,
  runtime_config = excluded.runtime_config,
  pricing_mode = excluded.pricing_mode,
  fixed_points = excluded.fixed_points,
  minimum_points = excluded.minimum_points,
  requires_auth = excluded.requires_auth,
  is_featured = excluded.is_featured,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  updated_at = now();

insert into public.tool_translations(
  tool_id, locale_id, title, short_description, seo_title, seo_description,
  prompt_template_override
)
select
  tool.id,
  locale.id,
  case when locale.code = 'ar' then seed.title_ar else seed.title_en end,
  case when locale.code = 'ar' then seed.description_ar else seed.description_en end,
  case
    when locale.code = 'ar' then seed.title_ar || ' مجانًا | أمبراطورية الويب'
    else seed.title_en || ' Free | Web Empire'
  end,
  case when locale.code = 'ar' then seed.description_ar else seed.description_en end,
  null
from initial_800_tool_seed seed
join public.tools tool on tool.slug = seed.slug
join public.locales locale on locale.code in ('ar', 'en')
on conflict (tool_id, locale_id) do update set
  title = excluded.title,
  short_description = excluded.short_description,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  prompt_template_override = null,
  updated_at = now();

insert into public.tool_field_translations(
  tool_id, locale_id, field_key, label, placeholder, help_text, options
)
select
  tool.id,
  locale.id,
  field.value ->> 'key',
  field.value ->> 'label',
  nullif(field.value ->> 'placeholder', ''),
  nullif(field.value ->> 'helpText', ''),
  field.value -> 'options'
from initial_800_tool_seed seed
join public.tools tool on tool.slug = seed.slug
join public.locales locale on locale.code in ('ar', 'en')
cross join lateral jsonb_array_elements(
  case when locale.code = 'ar' then seed.input_fields else seed.english_fields end
) field(value)
on conflict (tool_id, locale_id, field_key) do update set
  label = excluded.label,
  placeholder = excluded.placeholder,
  help_text = excluded.help_text,
  options = excluded.options,
  updated_at = now();

insert into public.tool_field_translations(
  tool_id, locale_id, field_key, label, placeholder, help_text, options
)
select
  tool.id,
  locale.id,
  '__submit__',
  case when locale.code = 'ar' then seed.submit_ar else seed.submit_en end,
  null,
  null,
  null
from initial_800_tool_seed seed
join public.tools tool on tool.slug = seed.slug
join public.locales locale on locale.code in ('ar', 'en')
on conflict (tool_id, locale_id, field_key) do update set
  label = excluded.label,
  placeholder = null,
  help_text = null,
  options = null,
  updated_at = now();

do $$
declare
  v_ready_count integer;
  v_bad_categories integer;
begin
  select count(*) into v_ready_count
  from public.tools tool
  join initial_800_tool_seed seed on seed.slug = tool.slug
  where tool.is_active = true
    and tool.engine_type = 'formula'
    and tool.pricing_mode = 'free';

  if v_ready_count <> 88 then
    raise exception 'INITIAL_800_WAVE_READY_COUNT_MISMATCH:%', v_ready_count;
  end if;

  select count(*) into v_bad_categories
  from (
    select category.slug, count(tool.id) as active_tool_count
    from public.categories category
    join public.tools tool
      on tool.category_id = category.id
     and tool.is_active = true
    where category.slug in (
      'business-tools', 'math-tools', 'marketing-tools', 'finance-tools', 'general-tools', 'converter-tools', 'date-time-tools', 'health-tools', 'education-tools', 'employment-tools', 'saudi-tools'
    )
    group by category.slug
    having count(tool.id) < 5 or count(tool.id) > 50
  ) invalid;

  if v_bad_categories <> 0 then
    raise exception 'CATEGORY_TOOL_RANGE_VIOLATION:%', v_bad_categories;
  end if;
end;
$$;

commit;

