-- Web Empire — Non-AI catalog growth wave 4 (seo-tools)
-- GitHub staging only. 10 deterministic bilingual formula tools.
begin;
create temporary table w4_seo_tools(
 slug text primary key,title_ar text,title_en text,description_ar text,description_en text,
 runtime_config jsonb,schema_ar jsonb,schema_en jsonb,sort_order integer
) on commit drop;
insert into w4_seo_tools values
('pages-per-crawl-request-calculator','حاسبة الصفحات لكل طلب زحف','Pages per Crawl Request Calculator','احسب متوسط الصفحات المفيدة لكل مجموعة طلبات زحف.','Calculate useful pages per crawl request set.','{"expression":"useful_pages / crawl_requests","outputUnitAr":" صفحة/طلب","outputUnitEn":" pages/request","resultLabelAr":"الصفحات لكل طلب زحف","resultLabelEn":"Pages per Crawl Request","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"useful_pages","label":"الصفحات المفيدة","type":"number","required":true,"step":0.01,"min":0},{"key":"crawl_requests","label":"طلبات الزحف","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"useful_pages","label":"Useful pages","type":"number","required":true,"step":0.01,"min":0},{"key":"crawl_requests","label":"Crawl requests","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10301),
('indexation-gap-calculator','حاسبة فجوة الفهرسة','Indexation Gap Calculator','احسب عدد الصفحات المقدمة التي لم تتم فهرستها.','Calculate submitted pages that are not indexed.','{"expression":"submitted_pages - indexed_pages","outputUnitAr":" صفحة","outputUnitEn":" pages","resultLabelAr":"فجوة الفهرسة","resultLabelEn":"Indexation Gap","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"submitted_pages","label":"الصفحات المقدمة","type":"number","required":true,"step":0.01,"min":0},{"key":"indexed_pages","label":"الصفحات المفهرسة","type":"number","required":true,"step":0.01,"min":0}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"submitted_pages","label":"Submitted pages","type":"number","required":true,"step":0.01,"min":0},{"key":"indexed_pages","label":"Indexed pages","type":"number","required":true,"step":0.01,"min":0}],"submitLabel":"Calculate"}'::jsonb,10302),
('organic-revenue-per-session-calculator','حاسبة الإيراد لكل جلسة عضوية','Organic Revenue per Session Calculator','احسب متوسط الإيراد لكل جلسة عضوية.','Calculate average revenue per organic session.','{"expression":"organic_revenue / organic_sessions","outputUnitAr":" ر.س","outputUnitEn":" SAR","resultLabelAr":"الإيراد لكل جلسة عضوية","resultLabelEn":"Organic Revenue per Session","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"organic_revenue","label":"الإيراد العضوي","type":"number","required":true,"step":0.01,"min":0},{"key":"organic_sessions","label":"الجلسات العضوية","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"organic_revenue","label":"Organic revenue","type":"number","required":true,"step":0.01,"min":0},{"key":"organic_sessions","label":"Organic sessions","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10303),
('branded-query-share-calculator','حاسبة حصة البحث عن العلامة','Branded Query Share Calculator','احسب نسبة الاستعلامات المرتبطة بالعلامة التجارية.','Calculate branded queries as a percentage of all queries.','{"expression":"branded_queries / total_queries * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"حصة البحث عن العلامة","resultLabelEn":"Branded Query Share","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"branded_queries","label":"استعلامات العلامة","type":"number","required":true,"step":0.01,"min":0},{"key":"total_queries","label":"إجمالي الاستعلامات","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"branded_queries","label":"Branded queries","type":"number","required":true,"step":0.01,"min":0},{"key":"total_queries","label":"Total queries","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10304),
('nonbranded-query-share-calculator','حاسبة حصة البحث غير المرتبط بالعلامة','Non-branded Query Share Calculator','احسب نسبة الاستعلامات غير المرتبطة بالعلامة التجارية.','Calculate non-branded queries as a percentage of all queries.','{"expression":"nonbranded_queries / total_queries * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"حصة البحث غير المرتبط بالعلامة","resultLabelEn":"Non-branded Query Share","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"nonbranded_queries","label":"الاستعلامات غير المرتبطة","type":"number","required":true,"step":0.01,"min":0},{"key":"total_queries","label":"إجمالي الاستعلامات","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"nonbranded_queries","label":"Non-branded queries","type":"number","required":true,"step":0.01,"min":0},{"key":"total_queries","label":"Total queries","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10305),
('organic-ctr-lift-calculator','حاسبة تحسن CTR العضوي','Organic CTR Lift Calculator','احسب نسبة تغير معدل النقر العضوي بين فترتين.','Calculate the percentage change in organic CTR between periods.','{"expression":"(current_ctr - previous_ctr) / previous_ctr * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"تحسن CTR العضوي","resultLabelEn":"Organic CTR Lift","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"current_ctr","label":"CTR الحالي","type":"number","required":true,"step":0.01,"min":0},{"key":"previous_ctr","label":"CTR السابق","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"current_ctr","label":"Current CTR","type":"number","required":true,"step":0.01,"min":0},{"key":"previous_ctr","label":"Previous CTR","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10306),
('ranking-position-improvement-calculator','حاسبة تحسن موضع الترتيب','Ranking Position Improvement Calculator','احسب نسبة التحسن عند الانتقال من موضع أعلى رقمًا إلى موضع أفضل.','Calculate ranking position improvement percentage.','{"expression":"(previous_position - current_position) / previous_position * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"تحسن موضع الترتيب","resultLabelEn":"Ranking Position Improvement","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"previous_position","label":"الموضع السابق","type":"number","required":true,"step":0.01,"min":1e-06},{"key":"current_position","label":"الموضع الحالي","type":"number","required":true,"step":0.01,"min":0}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"previous_position","label":"Previous position","type":"number","required":true,"step":0.01,"min":1e-06},{"key":"current_position","label":"Current position","type":"number","required":true,"step":0.01,"min":0}],"submitLabel":"Calculate"}'::jsonb,10307),
('content-refresh-rate-calculator','حاسبة معدل تحديث المحتوى','Content Refresh Rate Calculator','احسب نسبة الصفحات التي تم تحديثها خلال فترة.','Calculate the percentage of pages refreshed in a period.','{"expression":"refreshed_pages / total_pages * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"معدل تحديث المحتوى","resultLabelEn":"Content Refresh Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"refreshed_pages","label":"الصفحات المحدثة","type":"number","required":true,"step":0.01,"min":0},{"key":"total_pages","label":"إجمالي الصفحات","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"refreshed_pages","label":"Refreshed pages","type":"number","required":true,"step":0.01,"min":0},{"key":"total_pages","label":"Total pages","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10308),
('broken-link-rate-calculator','حاسبة معدل الروابط المعطلة','Broken Link Rate Calculator','احسب نسبة الروابط المعطلة من إجمالي الروابط المفحوصة.','Calculate broken links as a percentage of checked links.','{"expression":"broken_links / checked_links * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"معدل الروابط المعطلة","resultLabelEn":"Broken Link Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"broken_links","label":"الروابط المعطلة","type":"number","required":true,"step":0.01,"min":0},{"key":"checked_links","label":"الروابط المفحوصة","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"broken_links","label":"Broken links","type":"number","required":true,"step":0.01,"min":0},{"key":"checked_links","label":"Checked links","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10309),
('duplicate-title-rate-calculator','حاسبة العناوين المكررة','Duplicate Title Rate Calculator','احسب نسبة الصفحات ذات عناوين SEO مكررة.','Calculate the percentage of pages with duplicate SEO titles.','{"expression":"duplicate_title_pages / crawled_pages * 100","outputUnitAr":"%","outputUnitEn":"%","resultLabelAr":"العناوين المكررة","resultLabelEn":"Duplicate Title Rate","decimals":2,"showEquation":true}'::jsonb,'{"fields":[{"key":"duplicate_title_pages","label":"صفحات العناوين المكررة","type":"number","required":true,"step":0.01,"min":0},{"key":"crawled_pages","label":"الصفحات المزحوفة","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"احسب"}'::jsonb,'{"fields":[{"key":"duplicate_title_pages","label":"Duplicate-title pages","type":"number","required":true,"step":0.01,"min":0},{"key":"crawled_pages","label":"Crawled pages","type":"number","required":true,"step":0.01,"min":1e-06}],"submitLabel":"Calculate"}'::jsonb,10310);
insert into public.tools(slug,title_ar,title_en,short_description,category_id,engine_type,input_schema,output_schema,runtime_config,provider_strategy,model_alias,prompt_template,pricing_mode,fixed_points,minimum_points,cost_multiplier,requires_auth,is_featured,is_active,sort_order,seo_title,seo_description)
select s.slug,s.title_ar,s.title_en,s.description_ar,c.id,'formula'::public.tool_engine_type,s.schema_ar,'{}'::jsonb,s.runtime_config,'primary_with_fallback'::public.provider_strategy_type,null,null,'free'::public.pricing_mode_type,0,0,1,false,false,true,s.sort_order,s.title_ar,s.description_ar
from w4_seo_tools s join public.categories c on c.slug='seo-tools'
on conflict(slug) do update set title_ar=excluded.title_ar,title_en=excluded.title_en,short_description=excluded.short_description,category_id=excluded.category_id,engine_type=excluded.engine_type,input_schema=excluded.input_schema,output_schema=excluded.output_schema,runtime_config=excluded.runtime_config,model_alias=null,prompt_template=null,pricing_mode='free'::public.pricing_mode_type,fixed_points=0,minimum_points=0,cost_multiplier=1,requires_auth=false,is_featured=false,is_active=true,sort_order=excluded.sort_order,seo_title=excluded.seo_title,seo_description=excluded.seo_description,updated_at=now();
insert into public.tool_translations(tool_id,locale_id,title,short_description,seo_title,seo_description,prompt_template_override)
select t.id,l.id,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,null
from w4_seo_tools s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id) do update set title=excluded.title,short_description=excluded.short_description,seo_title=excluded.seo_title,seo_description=excluded.seo_description,prompt_template_override=null,updated_at=now();
insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,f->>'key',f->>'label',nullif(f->>'placeholder',''),nullif(f->>'helpText',''),f->'options'
from w4_seo_tools s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
cross join lateral jsonb_array_elements(case when l.code='ar' then s.schema_ar->'fields' else s.schema_en->'fields' end) f
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,placeholder=excluded.placeholder,help_text=excluded.help_text,options=excluded.options,updated_at=now();
insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,'__submit__',case when l.code='ar' then s.schema_ar->>'submitLabel' else s.schema_en->>'submitLabel' end,null,null,null
from w4_seo_tools s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,updated_at=now();
commit;
