-- Web Empire Wave15 — SaaS + Startup (20 tools)
select public._wave15_upsert_formula_tools('saas-tools',$json$[
{"slug":"saas-contraction-mrr-rate-calculator","title_ar":"حاسبة معدل انكماش الإيراد الشهري المتكرر","title_en":"SaaS Contraction MRR Rate Calculator","expression":"contraction_mrr / starting_mrr * 100","fields":[{"key":"contraction_mrr","ar":"الإيراد الشهري المنكمش","en":"Contraction MRR","min":0},{"key":"starting_mrr","ar":"الإيراد الشهري في بداية الفترة","en":"Starting MRR","min":0.000001}],"sort_order":33801},
{"slug":"saas-reactivation-rate-calculator","title_ar":"حاسبة معدل إعادة تنشيط العملاء","title_en":"SaaS Reactivation Rate Calculator","expression":"reactivated_customers / churned_customers * 100","fields":[{"key":"reactivated_customers","ar":"العملاء المعاد تنشيطهم","en":"Reactivated customers","min":0},{"key":"churned_customers","ar":"العملاء المتسربون","en":"Churned customers","min":0.000001}],"sort_order":33802},
{"slug":"saas-downgrade-rate-calculator","title_ar":"حاسبة معدل خفض الخطط","title_en":"SaaS Downgrade Rate Calculator","expression":"downgraded_customers / active_customers * 100","fields":[{"key":"downgraded_customers","ar":"العملاء الذين خفضوا الخطة","en":"Downgraded customers","min":0},{"key":"active_customers","ar":"العملاء النشطون","en":"Active customers","min":0.000001}],"sort_order":33803},
{"slug":"saas-expansion-revenue-per-customer-calculator","title_ar":"حاسبة إيراد التوسع لكل عميل","title_en":"SaaS Expansion Revenue per Customer Calculator","expression":"expansion_revenue / expanded_customers","fields":[{"key":"expansion_revenue","ar":"إيراد التوسع","en":"Expansion revenue","min":0},{"key":"expanded_customers","ar":"العملاء المتوسعون","en":"Expanded customers","min":0.000001}],"sort_order":33804},
{"slug":"saas-trial-to-paid-days-calculator","title_ar":"حاسبة متوسط أيام التحول من التجربة إلى الدفع","title_en":"SaaS Trial-to-Paid Days Calculator","expression":"conversion_days / converted_trials","fields":[{"key":"conversion_days","ar":"إجمالي أيام التحول","en":"Conversion days","min":0},{"key":"converted_trials","ar":"التجارب المتحولة","en":"Converted trials","min":0.000001}],"sort_order":33805},
{"slug":"saas-onboarding-cost-per-customer-calculator","title_ar":"حاسبة تكلفة التهيئة لكل عميل","title_en":"SaaS Onboarding Cost per Customer Calculator","expression":"onboarding_cost / new_customers","fields":[{"key":"onboarding_cost","ar":"تكلفة التهيئة","en":"Onboarding cost","min":0},{"key":"new_customers","ar":"العملاء الجدد","en":"New customers","min":0.000001}],"sort_order":33806},
{"slug":"saas-api-usage-per-customer-calculator","title_ar":"حاسبة استخدام API لكل عميل","title_en":"SaaS API Usage per Customer Calculator","expression":"api_requests / active_customers","fields":[{"key":"api_requests","ar":"طلبات API","en":"API requests","min":0},{"key":"active_customers","ar":"العملاء النشطون","en":"Active customers","min":0.000001}],"sort_order":33807},
{"slug":"saas-storage-cost-per-customer-calculator","title_ar":"حاسبة تكلفة التخزين لكل عميل","title_en":"SaaS Storage Cost per Customer Calculator","expression":"storage_cost / active_customers","fields":[{"key":"storage_cost","ar":"تكلفة التخزين","en":"Storage cost","min":0},{"key":"active_customers","ar":"العملاء النشطون","en":"Active customers","min":0.000001}],"sort_order":33808},
{"slug":"saas-support-hours-per-customer-calculator","title_ar":"حاسبة ساعات الدعم لكل عميل","title_en":"SaaS Support Hours per Customer Calculator","expression":"support_hours / active_customers","fields":[{"key":"support_hours","ar":"ساعات الدعم","en":"Support hours","min":0},{"key":"active_customers","ar":"العملاء النشطون","en":"Active customers","min":0.000001}],"sort_order":33809},
{"slug":"saas-billing-recovery-rate-calculator","title_ar":"حاسبة معدل استرداد المدفوعات الفاشلة","title_en":"SaaS Billing Recovery Rate Calculator","expression":"recovered_failed_payments / failed_payments * 100","fields":[{"key":"recovered_failed_payments","ar":"المدفوعات الفاشلة المستردة","en":"Recovered failed payments","min":0},{"key":"failed_payments","ar":"المدفوعات الفاشلة","en":"Failed payments","min":0.000001}],"sort_order":33810}
]$json$::jsonb);

select public._wave15_upsert_formula_tools('startup-tools',$json$[
{"slug":"startup-revenue-run-rate-calculator","title_ar":"حاسبة معدل الإيراد السنوي التقديري للشركة الناشئة","title_en":"Startup Revenue Run Rate Calculator","expression":"monthly_revenue * 12","fields":[{"key":"monthly_revenue","ar":"الإيراد الشهري","en":"Monthly revenue","min":0}],"sort_order":33901},
{"slug":"startup-cash-efficiency-ratio-calculator","title_ar":"حاسبة كفاءة استخدام النقد للشركة الناشئة","title_en":"Startup Cash Efficiency Ratio Calculator","expression":"revenue_generated / cash_spent","fields":[{"key":"revenue_generated","ar":"الإيراد المتولد","en":"Revenue generated","min":0},{"key":"cash_spent","ar":"النقد المنفق","en":"Cash spent","min":0.000001}],"sort_order":33902},
{"slug":"startup-funding-per-employee-calculator","title_ar":"حاسبة التمويل لكل موظف","title_en":"Startup Funding per Employee Calculator","expression":"funding / employees","fields":[{"key":"funding","ar":"إجمالي التمويل","en":"Funding","min":0},{"key":"employees","ar":"عدد الموظفين","en":"Employees","min":0.000001}],"sort_order":33903},
{"slug":"startup-revenue-per-founder-calculator","title_ar":"حاسبة الإيراد لكل مؤسس","title_en":"Startup Revenue per Founder Calculator","expression":"revenue / founders","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"founders","ar":"عدد المؤسسين","en":"Founders","min":0.000001}],"sort_order":33904},
{"slug":"startup-operating-expense-rate-calculator","title_ar":"حاسبة نسبة المصروفات التشغيلية","title_en":"Startup Operating Expense Rate Calculator","expression":"operating_expenses / revenue * 100","fields":[{"key":"operating_expenses","ar":"المصروفات التشغيلية","en":"Operating expenses","min":0},{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0.000001}],"sort_order":33905},
{"slug":"startup-customer-acquisition-spend-share-calculator","title_ar":"حاسبة حصة إنفاق اكتساب العملاء","title_en":"Startup Customer Acquisition Spend Share Calculator","expression":"acquisition_spend / total_spend * 100","fields":[{"key":"acquisition_spend","ar":"إنفاق اكتساب العملاء","en":"Acquisition spend","min":0},{"key":"total_spend","ar":"إجمالي الإنفاق","en":"Total spend","min":0.000001}],"sort_order":33906},
{"slug":"startup-product-development-spend-share-calculator","title_ar":"حاسبة حصة إنفاق تطوير المنتج","title_en":"Startup Product Development Spend Share Calculator","expression":"product_development_spend / total_spend * 100","fields":[{"key":"product_development_spend","ar":"إنفاق تطوير المنتج","en":"Product development spend","min":0},{"key":"total_spend","ar":"إجمالي الإنفاق","en":"Total spend","min":0.000001}],"sort_order":33907},
{"slug":"startup-sales-efficiency-ratio-calculator","title_ar":"حاسبة كفاءة الإنفاق على المبيعات والتسويق","title_en":"Startup Sales Efficiency Ratio Calculator","expression":"new_revenue / sales_marketing_spend","fields":[{"key":"new_revenue","ar":"الإيراد الجديد","en":"New revenue","min":0},{"key":"sales_marketing_spend","ar":"إنفاق المبيعات والتسويق","en":"Sales and marketing spend","min":0.000001}],"sort_order":33908},
{"slug":"startup-monthly-net-cash-flow-calculator","title_ar":"حاسبة صافي التدفق النقدي الشهري","title_en":"Startup Monthly Net Cash Flow Calculator","expression":"cash_inflows - cash_outflows","fields":[{"key":"cash_inflows","ar":"التدفقات النقدية الداخلة","en":"Cash inflows","min":0},{"key":"cash_outflows","ar":"التدفقات النقدية الخارجة","en":"Cash outflows","min":0}],"sort_order":33909},
{"slug":"startup-cash-buffer-months-calculator","title_ar":"حاسبة أشهر الاحتياطي النقدي","title_en":"Startup Cash Buffer Months Calculator","expression":"cash_reserve / monthly_fixed_costs","fields":[{"key":"cash_reserve","ar":"الاحتياطي النقدي","en":"Cash reserve","min":0},{"key":"monthly_fixed_costs","ar":"التكاليف الشهرية الثابتة","en":"Monthly fixed costs","min":0.000001}],"sort_order":33910}
]$json$::jsonb);
