-- Web Empire wave 11: Salon, Rental, Franchise, SaaS, Startup (50 tools).
-- GitHub staging only; not applied to Supabase.

select public._wave11_upsert_formula_tools('salon-tools',$json$[
{"slug":"salon-membership-revenue-share-calculator","title_ar":"حاسبة حصة إيراد عضويات الصالون","title_en":"Salon Membership Revenue Share Calculator","expression":"membership_revenue / total_revenue * 100","fields":[{"key":"membership_revenue","ar":"إيراد العضويات","en":"Membership revenue","min":0},{"key":"total_revenue","ar":"إجمالي الإيراد","en":"Total revenue","min":0.000001}],"sort_order":31601},
{"slug":"salon-discount-rate-calculator","title_ar":"حاسبة نسبة خصومات الصالون","title_en":"Salon Discount Rate Calculator","expression":"discounts / gross_sales * 100","fields":[{"key":"discounts","ar":"قيمة الخصومات","en":"Discounts","min":0},{"key":"gross_sales","ar":"إجمالي المبيعات","en":"Gross sales","min":0.000001}],"sort_order":31602},
{"slug":"salon-walkin-share-calculator","title_ar":"حاسبة حصة العملاء بدون موعد","title_en":"Salon Walk-in Share Calculator","expression":"walkin_clients / served_clients * 100","fields":[{"key":"walkin_clients","ar":"العملاء بدون موعد","en":"Walk-in clients","min":0},{"key":"served_clients","ar":"العملاء المخدومون","en":"Served clients","min":0.000001}],"sort_order":31603},
{"slug":"salon-appointment-fill-rate-calculator","title_ar":"حاسبة نسبة إشغال مواعيد الصالون","title_en":"Salon Appointment Fill Rate Calculator","expression":"booked_slots / available_slots * 100","fields":[{"key":"booked_slots","ar":"المواعيد المحجوزة","en":"Booked slots","min":0},{"key":"available_slots","ar":"المواعيد المتاحة","en":"Available slots","min":0.000001}],"sort_order":31604},
{"slug":"salon-average-service-time-calculator","title_ar":"حاسبة متوسط وقت الخدمة في الصالون","title_en":"Salon Average Service Time Calculator","expression":"service_minutes / services","fields":[{"key":"service_minutes","ar":"إجمالي دقائق الخدمات","en":"Service minutes","min":0},{"key":"services","ar":"عدد الخدمات","en":"Services","min":0.000001}],"sort_order":31605},
{"slug":"salon-cancellation-rate-calculator","title_ar":"حاسبة إلغاء مواعيد الصالون","title_en":"Salon Cancellation Rate Calculator","expression":"cancelled_appointments / booked_appointments * 100","fields":[{"key":"cancelled_appointments","ar":"المواعيد الملغاة","en":"Cancelled appointments","min":0},{"key":"booked_appointments","ar":"المواعيد المحجوزة","en":"Booked appointments","min":0.000001}],"sort_order":31606},
{"slug":"salon-labor-cost-share-calculator","title_ar":"حاسبة حصة تكلفة العمالة في الصالون","title_en":"Salon Labor Cost Share Calculator","expression":"labor_cost / revenue * 100","fields":[{"key":"labor_cost","ar":"تكلفة العمالة","en":"Labor cost","min":0},{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0.000001}],"sort_order":31607},
{"slug":"salon-revenue-per-staff-hour-calculator","title_ar":"حاسبة إيراد الصالون لكل ساعة موظف","title_en":"Salon Revenue per Staff Hour Calculator","expression":"revenue / staff_hours","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"staff_hours","ar":"ساعات الموظفين","en":"Staff hours","min":0.000001}],"sort_order":31608},
{"slug":"salon-new-client-conversion-calculator","title_ar":"حاسبة تحويل العملاء الجدد للصالون","title_en":"Salon New Client Conversion Calculator","expression":"new_clients / inquiries * 100","fields":[{"key":"new_clients","ar":"العملاء الجدد","en":"New clients","min":0},{"key":"inquiries","ar":"الاستفسارات","en":"Inquiries","min":0.000001}],"sort_order":31609},
{"slug":"salon-client-frequency-calculator","title_ar":"حاسبة تكرار زيارات عميل الصالون","title_en":"Salon Client Visit Frequency Calculator","expression":"appointments / active_clients","fields":[{"key":"appointments","ar":"عدد المواعيد","en":"Appointments","min":0},{"key":"active_clients","ar":"العملاء النشطون","en":"Active clients","min":0.000001}],"sort_order":31610}
]$json$::jsonb);

select public._wave11_upsert_formula_tools('rental-business-tools',$json$[
{"slug":"rental-add-on-revenue-share-calculator","title_ar":"حاسبة حصة إيراد إضافات التأجير","title_en":"Rental Add-on Revenue Share Calculator","expression":"add_on_revenue / total_revenue * 100","fields":[{"key":"add_on_revenue","ar":"إيراد الإضافات","en":"Add-on revenue","min":0},{"key":"total_revenue","ar":"إجمالي الإيراد","en":"Total revenue","min":0.000001}],"sort_order":31701},
{"slug":"rental-maintenance-cost-rate-calculator","title_ar":"حاسبة نسبة تكلفة صيانة التأجير","title_en":"Rental Maintenance Cost Rate Calculator","expression":"maintenance_cost / rental_revenue * 100","fields":[{"key":"maintenance_cost","ar":"تكلفة الصيانة","en":"Maintenance cost","min":0},{"key":"rental_revenue","ar":"إيراد التأجير","en":"Rental revenue","min":0.000001}],"sort_order":31702},
{"slug":"rental-average-rental-duration-calculator","title_ar":"حاسبة متوسط مدة التأجير","title_en":"Average Rental Duration Calculator","expression":"rental_days / bookings","fields":[{"key":"rental_days","ar":"إجمالي أيام التأجير","en":"Rental days","min":0},{"key":"bookings","ar":"عدد الحجوزات","en":"Bookings","min":0.000001}],"sort_order":31703},
{"slug":"rental-extension-rate-calculator","title_ar":"حاسبة نسبة تمديد حجوزات التأجير","title_en":"Rental Extension Rate Calculator","expression":"extended_bookings / total_bookings * 100","fields":[{"key":"extended_bookings","ar":"الحجوزات الممددة","en":"Extended bookings","min":0},{"key":"total_bookings","ar":"إجمالي الحجوزات","en":"Total bookings","min":0.000001}],"sort_order":31704},
{"slug":"rental-deposit-refund-rate-calculator","title_ar":"حاسبة استرداد تأمينات التأجير","title_en":"Rental Deposit Refund Rate Calculator","expression":"refunded_deposits / collected_deposits * 100","fields":[{"key":"refunded_deposits","ar":"التأمينات المستردة","en":"Refunded deposits","min":0},{"key":"collected_deposits","ar":"التأمينات المحصلة","en":"Collected deposits","min":0.000001}],"sort_order":31705},
{"slug":"rental-security-deposit-coverage-calculator","title_ar":"حاسبة تغطية التأمينات للأضرار","title_en":"Rental Deposit Coverage Calculator","expression":"deposit_amount / damage_cost * 100","fields":[{"key":"deposit_amount","ar":"قيمة التأمين","en":"Deposit amount","min":0},{"key":"damage_cost","ar":"تكلفة الأضرار","en":"Damage cost","min":0.000001}],"sort_order":31706},
{"slug":"rental-delivery-cost-per-booking-calculator","title_ar":"حاسبة تكلفة توصيل التأجير لكل حجز","title_en":"Rental Delivery Cost per Booking Calculator","expression":"delivery_cost / bookings","fields":[{"key":"delivery_cost","ar":"تكلفة التوصيل","en":"Delivery cost","min":0},{"key":"bookings","ar":"عدد الحجوزات","en":"Bookings","min":0.000001}],"sort_order":31707},
{"slug":"rental-pickup-delay-rate-calculator","title_ar":"حاسبة تأخر استلام أصول التأجير","title_en":"Rental Pickup Delay Rate Calculator","expression":"delayed_pickups / total_pickups * 100","fields":[{"key":"delayed_pickups","ar":"عمليات الاستلام المتأخرة","en":"Delayed pickups","min":0},{"key":"total_pickups","ar":"إجمالي عمليات الاستلام","en":"Total pickups","min":0.000001}],"sort_order":31708},
{"slug":"rental-net-margin-calculator","title_ar":"حاسبة هامش صافي التأجير","title_en":"Rental Net Margin Calculator","expression":"(rental_revenue - operating_cost) / rental_revenue * 100","fields":[{"key":"rental_revenue","ar":"إيراد التأجير","en":"Rental revenue","min":0.000001},{"key":"operating_cost","ar":"تكلفة التشغيل","en":"Operating cost","min":0}],"sort_order":31709},
{"slug":"rental-repair-cost-per-damaged-rental-calculator","title_ar":"حاسبة إصلاح الأضرار لكل عملية تأجير","title_en":"Repair Cost per Damaged Rental Calculator","expression":"repair_cost / damaged_rentals","fields":[{"key":"repair_cost","ar":"تكلفة الإصلاح","en":"Repair cost","min":0},{"key":"damaged_rentals","ar":"عمليات التأجير المتضررة","en":"Damaged rentals","min":0.000001}],"sort_order":31710}
]$json$::jsonb);

select public._wave11_upsert_formula_tools('franchise-tools',$json$[
{"slug":"franchise-operating-expense-rate-calculator","title_ar":"حاسبة نسبة مصروفات تشغيل الامتياز","title_en":"Franchise Operating Expense Rate Calculator","expression":"operating_expenses / gross_sales * 100","fields":[{"key":"operating_expenses","ar":"المصروفات التشغيلية","en":"Operating expenses","min":0},{"key":"gross_sales","ar":"إجمالي المبيعات","en":"Gross sales","min":0.000001}],"sort_order":31801},
{"slug":"franchise-rent-to-sales-ratio-calculator","title_ar":"حاسبة نسبة الإيجار إلى مبيعات الامتياز","title_en":"Franchise Rent to Sales Ratio Calculator","expression":"rent_cost / gross_sales * 100","fields":[{"key":"rent_cost","ar":"تكلفة الإيجار","en":"Rent cost","min":0},{"key":"gross_sales","ar":"إجمالي المبيعات","en":"Gross sales","min":0.000001}],"sort_order":31802},
{"slug":"franchise-training-cost-per-location-calculator","title_ar":"حاسبة تكلفة التدريب لكل فرع امتياز","title_en":"Franchise Training Cost per Location Calculator","expression":"training_cost / locations","fields":[{"key":"training_cost","ar":"تكلفة التدريب","en":"Training cost","min":0},{"key":"locations","ar":"عدد الفروع","en":"Locations","min":0.000001}],"sort_order":31803},
{"slug":"franchise-support-cost-per-location-calculator","title_ar":"حاسبة تكلفة الدعم لكل فرع امتياز","title_en":"Franchise Support Cost per Location Calculator","expression":"support_cost / locations","fields":[{"key":"support_cost","ar":"تكلفة الدعم","en":"Support cost","min":0},{"key":"locations","ar":"عدد الفروع","en":"Locations","min":0.000001}],"sort_order":31804},
{"slug":"franchise-store-closure-rate-calculator","title_ar":"حاسبة معدل إغلاق فروع الامتياز","title_en":"Franchise Store Closure Rate Calculator","expression":"closed_locations / starting_locations * 100","fields":[{"key":"closed_locations","ar":"الفروع المغلقة","en":"Closed locations","min":0},{"key":"starting_locations","ar":"فروع بداية الفترة","en":"Starting locations","min":0.000001}],"sort_order":31805},
{"slug":"franchise-unit-growth-rate-calculator","title_ar":"حاسبة نمو عدد فروع الامتياز","title_en":"Franchise Unit Growth Rate Calculator","expression":"(ending_locations - starting_locations) / starting_locations * 100","fields":[{"key":"ending_locations","ar":"فروع نهاية الفترة","en":"Ending locations","min":0},{"key":"starting_locations","ar":"فروع بداية الفترة","en":"Starting locations","min":0.000001}],"sort_order":31806},
{"slug":"franchise-sales-per-sqm-calculator","title_ar":"حاسبة مبيعات الامتياز لكل متر مربع","title_en":"Franchise Sales per Square Meter Calculator","expression":"gross_sales / floor_area_sqm","fields":[{"key":"gross_sales","ar":"إجمالي المبيعات","en":"Gross sales","min":0},{"key":"floor_area_sqm","ar":"المساحة بالمتر المربع","en":"Floor area m²","min":0.000001}],"sort_order":31807},
{"slug":"franchise-average-ticket-calculator","title_ar":"حاسبة متوسط فاتورة الامتياز","title_en":"Franchise Average Ticket Calculator","expression":"gross_sales / transactions","fields":[{"key":"gross_sales","ar":"إجمالي المبيعات","en":"Gross sales","min":0},{"key":"transactions","ar":"عدد العمليات","en":"Transactions","min":0.000001}],"sort_order":31808},
{"slug":"franchise-contribution-after-fees-calculator","title_ar":"حاسبة مساهمة الامتياز بعد الرسوم","title_en":"Franchise Contribution after Fees Calculator","expression":"gross_profit - royalty_fee - marketing_fee","fields":[{"key":"gross_profit","ar":"الربح الإجمالي","en":"Gross profit","min":0},{"key":"royalty_fee","ar":"رسوم الامتياز","en":"Royalty fee","min":0},{"key":"marketing_fee","ar":"رسوم التسويق","en":"Marketing fee","min":0}],"sort_order":31809},
{"slug":"franchise-utilities-cost-rate-calculator","title_ar":"حاسبة نسبة تكلفة المرافق للامتياز","title_en":"Franchise Utilities Cost Rate Calculator","expression":"utilities_cost / gross_sales * 100","fields":[{"key":"utilities_cost","ar":"تكلفة المرافق","en":"Utilities cost","min":0},{"key":"gross_sales","ar":"إجمالي المبيعات","en":"Gross sales","min":0.000001}],"sort_order":31810}
]$json$::jsonb);

select public._wave11_upsert_formula_tools('saas-tools',$json$[
{"slug":"saas-support-cost-per-user-calculator","title_ar":"حاسبة تكلفة دعم SaaS لكل مستخدم","title_en":"SaaS Support Cost per User Calculator","expression":"support_cost / active_users","fields":[{"key":"support_cost","ar":"تكلفة الدعم","en":"Support cost","min":0},{"key":"active_users","ar":"المستخدمون النشطون","en":"Active users","min":0.000001}],"sort_order":31901},
{"slug":"saas-revenue-per-seat-calculator","title_ar":"حاسبة إيراد SaaS لكل مقعد","title_en":"SaaS Revenue per Seat Calculator","expression":"monthly_revenue / paid_seats","fields":[{"key":"monthly_revenue","ar":"الإيراد الشهري","en":"Monthly revenue","min":0},{"key":"paid_seats","ar":"المقاعد المدفوعة","en":"Paid seats","min":0.000001}],"sort_order":31902},
{"slug":"saas-monthly-logo-retention-calculator","title_ar":"حاسبة الاحتفاظ الشهري بعملاء SaaS","title_en":"SaaS Monthly Logo Retention Calculator","expression":"ending_customers / starting_customers * 100","fields":[{"key":"ending_customers","ar":"عملاء نهاية الشهر","en":"Ending customers","min":0},{"key":"starting_customers","ar":"عملاء بداية الشهر","en":"Starting customers","min":0.000001}],"sort_order":31903},
{"slug":"saas-onboarding-completion-rate-calculator","title_ar":"حاسبة إكمال تهيئة مستخدمي SaaS","title_en":"SaaS Onboarding Completion Rate Calculator","expression":"completed_onboarding / started_onboarding * 100","fields":[{"key":"completed_onboarding","ar":"التهيئة المكتملة","en":"Completed onboarding","min":0},{"key":"started_onboarding","ar":"التهيئة التي بدأت","en":"Started onboarding","min":0.000001}],"sort_order":31904},
{"slug":"saas-feature-adoption-rate-calculator","title_ar":"حاسبة تبني ميزة SaaS","title_en":"SaaS Feature Adoption Rate Calculator","expression":"feature_users / active_users * 100","fields":[{"key":"feature_users","ar":"مستخدمو الميزة","en":"Feature users","min":0},{"key":"active_users","ar":"المستخدمون النشطون","en":"Active users","min":0.000001}],"sort_order":31905},
{"slug":"saas-annual-prepay-share-calculator","title_ar":"حاسبة حصة الدفع السنوي المسبق في SaaS","title_en":"SaaS Annual Prepay Share Calculator","expression":"annual_prepaid_revenue / total_billings * 100","fields":[{"key":"annual_prepaid_revenue","ar":"إيراد الدفع السنوي المسبق","en":"Annual prepaid revenue","min":0},{"key":"total_billings","ar":"إجمالي الفوترة","en":"Total billings","min":0.000001}],"sort_order":31906},
{"slug":"saas-discount-rate-calculator","title_ar":"حاسبة نسبة خصومات SaaS","title_en":"SaaS Discount Rate Calculator","expression":"discounts / gross_billings * 100","fields":[{"key":"discounts","ar":"قيمة الخصومات","en":"Discounts","min":0},{"key":"gross_billings","ar":"إجمالي الفوترة قبل الخصم","en":"Gross billings","min":0.000001}],"sort_order":31907},
{"slug":"saas-refund-rate-calculator","title_ar":"حاسبة معدل استرداد SaaS","title_en":"SaaS Refund Rate Calculator","expression":"refunds / billings * 100","fields":[{"key":"refunds","ar":"المبالغ المستردة","en":"Refunds","min":0},{"key":"billings","ar":"الفوترة","en":"Billings","min":0.000001}],"sort_order":31908},
{"slug":"saas-payment-failure-rate-calculator","title_ar":"حاسبة فشل مدفوعات SaaS","title_en":"SaaS Payment Failure Rate Calculator","expression":"failed_payments / payment_attempts * 100","fields":[{"key":"failed_payments","ar":"المدفوعات الفاشلة","en":"Failed payments","min":0},{"key":"payment_attempts","ar":"محاولات الدفع","en":"Payment attempts","min":0.000001}],"sort_order":31909},
{"slug":"saas-seat-utilization-rate-calculator","title_ar":"حاسبة استخدام مقاعد SaaS","title_en":"SaaS Seat Utilization Rate Calculator","expression":"active_seats / purchased_seats * 100","fields":[{"key":"active_seats","ar":"المقاعد النشطة","en":"Active seats","min":0},{"key":"purchased_seats","ar":"المقاعد المشتراة","en":"Purchased seats","min":0.000001}],"sort_order":31910}
]$json$::jsonb);

select public._wave11_upsert_formula_tools('startup-tools',$json$[
{"slug":"startup-payroll-share-calculator","title_ar":"حاسبة حصة الرواتب من مصروفات الشركة الناشئة","title_en":"Startup Payroll Share Calculator","expression":"payroll / operating_expenses * 100","fields":[{"key":"payroll","ar":"الرواتب","en":"Payroll","min":0},{"key":"operating_expenses","ar":"المصروفات التشغيلية","en":"Operating expenses","min":0.000001}],"sort_order":32001},
{"slug":"startup-marketing-spend-share-calculator","title_ar":"حاسبة حصة التسويق من مصروفات الشركة الناشئة","title_en":"Startup Marketing Spend Share Calculator","expression":"marketing_spend / operating_expenses * 100","fields":[{"key":"marketing_spend","ar":"الإنفاق التسويقي","en":"Marketing spend","min":0},{"key":"operating_expenses","ar":"المصروفات التشغيلية","en":"Operating expenses","min":0.000001}],"sort_order":32002},
{"slug":"startup-cash-burn-per-employee-calculator","title_ar":"حاسبة الحرق النقدي لكل موظف","title_en":"Startup Cash Burn per Employee Calculator","expression":"monthly_net_burn / employees","fields":[{"key":"monthly_net_burn","ar":"صافي الحرق الشهري","en":"Monthly net burn","min":0},{"key":"employees","ar":"عدد الموظفين","en":"Employees","min":0.000001}],"sort_order":32003},
{"slug":"startup-monthly-revenue-per-customer-calculator","title_ar":"حاسبة الإيراد الشهري لكل عميل ناشئ","title_en":"Startup Monthly Revenue per Customer Calculator","expression":"monthly_revenue / customers","fields":[{"key":"monthly_revenue","ar":"الإيراد الشهري","en":"Monthly revenue","min":0},{"key":"customers","ar":"عدد العملاء","en":"Customers","min":0.000001}],"sort_order":32004},
{"slug":"startup-equity-value-per-percent-calculator","title_ar":"حاسبة قيمة 1% من الشركة الناشئة","title_en":"Startup Equity Value per 1 Percent Calculator","expression":"valuation / 100","fields":[{"key":"valuation","ar":"تقييم الشركة","en":"Valuation","min":0}],"sort_order":32005},
{"slug":"startup-payroll-to-revenue-ratio-calculator","title_ar":"حاسبة نسبة الرواتب إلى إيراد الشركة الناشئة","title_en":"Startup Payroll to Revenue Ratio Calculator","expression":"payroll / revenue * 100","fields":[{"key":"payroll","ar":"الرواتب","en":"Payroll","min":0},{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0.000001}],"sort_order":32006},
{"slug":"startup-revenue-to-burn-ratio-calculator","title_ar":"حاسبة نسبة الإيراد إلى الحرق النقدي","title_en":"Startup Revenue to Burn Ratio Calculator","expression":"revenue / net_burn","fields":[{"key":"revenue","ar":"الإيراد","en":"Revenue","min":0},{"key":"net_burn","ar":"صافي الحرق النقدي","en":"Net burn","min":0.000001}],"sort_order":32007},
{"slug":"startup-funding-gap-calculator","title_ar":"حاسبة فجوة تمويل الشركة الناشئة","title_en":"Startup Funding Gap Calculator","expression":"target_raise - committed_funding","fields":[{"key":"target_raise","ar":"التمويل المستهدف","en":"Target raise","min":0},{"key":"committed_funding","ar":"التمويل الملتزم به","en":"Committed funding","min":0}],"sort_order":32008},
{"slug":"startup-customer-growth-rate-calculator","title_ar":"حاسبة نمو عملاء الشركة الناشئة","title_en":"Startup Customer Growth Rate Calculator","expression":"(ending_customers - starting_customers) / starting_customers * 100","fields":[{"key":"ending_customers","ar":"عملاء نهاية الفترة","en":"Ending customers","min":0},{"key":"starting_customers","ar":"عملاء بداية الفترة","en":"Starting customers","min":0.000001}],"sort_order":32009},
{"slug":"startup-monthly-cash-change-calculator","title_ar":"حاسبة التغير النقدي الشهري للشركة الناشئة","title_en":"Startup Monthly Cash Change Calculator","expression":"cash_inflows - cash_outflows","fields":[{"key":"cash_inflows","ar":"التدفقات النقدية الداخلة","en":"Cash inflows","min":0},{"key":"cash_outflows","ar":"التدفقات النقدية الخارجة","en":"Cash outflows","min":0}],"sort_order":32010}
]$json$::jsonb);
