-- Web Empire — Non-AI catalog growth wave 2 (social-media-tools)
begin;
create temporary table social_media_tools_w2 (slug text primary key,title_ar text not null,title_en text not null,description_ar text not null,description_en text not null,operations jsonb not null,schema_kind text not null check (schema_kind in ('one','aux','case','style')),input_ar text not null,input_en text not null,submit_ar text not null,submit_en text not null,max_length integer not null,aux_key text,aux_ar text,aux_en text,aux_ph_ar text,aux_ph_en text,sort_order integer not null) on commit drop;
insert into social_media_tools_w2 values
('caption-stats','عداد وإحصاءات الكابشن','Caption Stats','احسب الكلمات والأحرف والأسطر في الكابشن قبل النشر.','Count words, characters, and lines in a caption before posting.','[{"type":"stats"}]'::jsonb,'one','الكابشن','Caption','احسب الإحصاءات','Calculate stats',10000,null,null,null,null,null,7301),
('caption-case-converter','محول حالة الكابشن','Caption Case Converter','حوّل حالة الأحرف في الكابشن الإنجليزي بسرعة.','Change English caption letter case quickly.','[{"type":"case","mode_key":"mode"}]'::jsonb,'case','الكابشن','Caption','حوّل الحالة','Convert case',10000,null,null,null,null,null,7302),
('hashtag-list-deduplicator','حذف الهاشتاقات المكررة','Hashtag List Deduplicator','احذف الهاشتاقات المكررة عندما يكون كل هاشتاق في سطر.','Remove duplicate hashtags when each hashtag is on its own line.','[{"type":"unique_lines"}]'::jsonb,'one','الهاشتاقات','Hashtags','احذف التكرار','Remove duplicates',10000,null,null,null,null,null,7303),
('hashtag-list-sorter','ترتيب الهاشتاقات','Hashtag List Sorter','رتب قائمة الهاشتاقات أبجديًا سطرًا بسطر.','Sort a hashtag list alphabetically, one tag per line.','[{"type":"sort_lines","direction":"asc"}]'::jsonb,'one','الهاشتاقات','Hashtags','رتب الهاشتاقات','Sort hashtags',10000,null,null,null,null,null,7304),
('hashtag-prefixer','إضافة علامة # للكلمات','Hashtag Prefixer','أضف علامة # إلى كل كلمة أو عبارة موجودة في سطر مستقل.','Add # to every word or phrase placed on a separate line.','[{"type":"line_prefix","value":"#"}]'::jsonb,'one','الكلمات أو العبارات','Words or phrases','أضف #','Add #',10000,null,null,null,null,null,7305),
('caption-decorator','زخرفة الكابشن','Caption Decorator','أضف زخرفة بسيطة حول الكابشن أو العنوان.','Add simple decorative styling around a caption or title.','[{"type":"trim"},{"type":"decorate","style_key":"style"}]'::jsonb,'style','الكابشن أو العنوان','Caption or title','زخرف الكابشن','Decorate caption',10000,null,null,null,null,null,7306),
('social-keyword-cleaner','منظف كلمات السوشيال','Social Keyword Cleaner','نظف قائمة كلمات المحتوى من التكرار ورتبها.','Remove duplicate content keywords and sort them.','[{"type":"unique_lines"},{"type":"sort_lines","direction":"asc"}]'::jsonb,'one','الكلمات','Keywords','نظف الكلمات','Clean keywords',10000,null,null,null,null,null,7307),
('social-list-reverser','عكس قائمة محتوى السوشيال','Social List Reverser','اعكس ترتيب قائمة أفكار أو عناوين أو منشورات قصيرة.','Reverse a list of social ideas, titles, or short posts.','[{"type":"reverse","mode":"lines"}]'::jsonb,'one','القائمة','List','اعكس القائمة','Reverse list',10000,null,null,null,null,null,7308),
('social-post-bullet-formatter','تنسيق نقاط لمنشور اجتماعي','Social Post Bullet Formatter','حوّل كل سطر إلى نقطة مرتبة مناسبة للمنشورات.','Turn each line into a bullet suitable for social posts.','[{"type":"line_prefix","value":"• "}]'::jsonb,'one','النقاط أو الأسطر','Lines or points','نسق المنشور','Format post',10000,null,null,null,null,null,7309),
('social-text-arabic-normalizer','تطبيع النص العربي للسوشيال','Social Arabic Text Normalizer','وحّد أشال الحروف العربية وأزل التشكيل الزائد قبل النشر.','Normalize Arabic letter forms and remove extra diacritics before posting.','[{"type":"normalize_arabic"}]'::jsonb,'one','النص العربي','Arabic text','طبّع النص','Normalize text',10000,null,null,null,null,null,7310);
create temporary table social_media_tools_w2_ready as select seed.*,
jsonb_build_object('fields',case seed.schema_kind when 'one' then jsonb_build_array(jsonb_build_object('key','text','label',seed.input_ar,'type','textarea','required',true,'placeholder','أدخل النص هنا...','maxLength',seed.max_length)) when 'case' then jsonb_build_array(jsonb_build_object('key','text','label',seed.input_ar,'type','textarea','required',true,'placeholder','أدخل النص هنا...','maxLength',seed.max_length),jsonb_build_object('key','mode','label','الحالة','type','select','required',true,'defaultValue','lowercase','options','[{"value":"uppercase","label":"أحرف كبيرة"},{"value":"lowercase","label":"أحرف صغيرة"},{"value":"title","label":"حالة العنوان"},{"value":"sentence","label":"حالة الجملة"}]'::jsonb)) else jsonb_build_array(jsonb_build_object('key','text','label',seed.input_ar,'type','textarea','required',true,'placeholder','أدخل النص هنا...','maxLength',seed.max_length),jsonb_build_object('key','style','label','النمط','type','select','required',true,'defaultValue','sparkles','options','[{"value":"stars","label":"نجوم"},{"value":"sparkles","label":"لمعان"},{"value":"hearts","label":"قلوب"},{"value":"brackets","label":"أقواس"},{"value":"quotes","label":"اقتباس"},{"value":"arrows","label":"أسهم"}]'::jsonb)) end,'submitLabel',seed.submit_ar) schema_ar,
jsonb_build_object('fields',case seed.schema_kind when 'one' then jsonb_build_array(jsonb_build_object('key','text','label',seed.input_en,'type','textarea','required',true,'placeholder','Enter text here...','maxLength',seed.max_length)) when 'case' then jsonb_build_array(jsonb_build_object('key','text','label',seed.input_en,'type','textarea','required',true,'placeholder','Enter text here...','maxLength',seed.max_length),jsonb_build_object('key','mode','label','Case','type','select','required',true,'defaultValue','lowercase','options','[{"value":"uppercase","label":"UPPERCASE"},{"value":"lowercase","label":"lowercase"},{"value":"title","label":"Title Case"},{"value":"sentence","label":"Sentence case"}]'::jsonb)) else jsonb_build_array(jsonb_build_object('key','text','label',seed.input_en,'type','textarea','required',true,'placeholder','Enter text here...','maxLength',seed.max_length),jsonb_build_object('key','style','label','Style','type','select','required',true,'defaultValue','sparkles','options','[{"value":"stars","label":"Stars"},{"value":"sparkles","label":"Sparkles"},{"value":"hearts","label":"Hearts"},{"value":"brackets","label":"Brackets"},{"value":"quotes","label":"Quotes"},{"value":"arrows","label":"Arrows"}]'::jsonb)) end,'submitLabel',seed.submit_en) schema_en from social_media_tools_w2 seed;
insert into public.tools(slug,title_ar,title_en,short_description,category_id,engine_type,input_schema,output_schema,runtime_config,provider_strategy,model_alias,prompt_template,pricing_mode,fixed_points,minimum_points,cost_multiplier,requires_auth,is_featured,is_active,sort_order,seo_title,seo_description)
select s.slug,s.title_ar,s.title_en,s.description_ar,c.id,'text_transform'::public.tool_engine_type,s.schema_ar,'{}'::jsonb,jsonb_build_object('input_key','text','operations',s.operations),'primary_with_fallback'::public.provider_strategy_type,null,null,'free'::public.pricing_mode_type,0,0,1,false,false,true,s.sort_order,s.title_ar,s.description_ar from social_media_tools_w2_ready s join public.categories c on c.slug='social-media-tools'
on conflict(slug) do update set title_ar=excluded.title_ar,title_en=excluded.title_en,short_description=excluded.short_description,category_id=excluded.category_id,engine_type=excluded.engine_type,input_schema=excluded.input_schema,output_schema=excluded.output_schema,runtime_config=excluded.runtime_config,model_alias=null,prompt_template=null,pricing_mode='free'::public.pricing_mode_type,fixed_points=0,minimum_points=0,cost_multiplier=1,requires_auth=false,is_featured=false,is_active=true,sort_order=excluded.sort_order,seo_title=excluded.seo_title,seo_description=excluded.seo_description,updated_at=now();
insert into public.tool_translations(tool_id,locale_id,title,short_description,seo_title,seo_description,prompt_template_override) select t.id,l.id,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,null from social_media_tools_w2_ready s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en') on conflict(tool_id,locale_id) do update set title=excluded.title,short_description=excluded.short_description,seo_title=excluded.seo_title,seo_description=excluded.seo_description,prompt_template_override=null,updated_at=now();
insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options) select t.id,l.id,f->>'key',f->>'label',nullif(f->>'placeholder',''),nullif(f->>'helpText',''),f->'options' from social_media_tools_w2_ready s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en') cross join lateral jsonb_array_elements(case when l.code='ar' then s.schema_ar->'fields' else s.schema_en->'fields' end) f on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,placeholder=excluded.placeholder,help_text=excluded.help_text,options=excluded.options,updated_at=now();
insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options) select t.id,l.id,'__submit__',case when l.code='ar' then s.submit_ar else s.submit_en end,null,null,null from social_media_tools_w2_ready s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en') on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,updated_at=now();
commit;