-- Web Empire release fix — Wave 10 cross-wave collisions.
-- Restores 8 earlier tools overwritten by Wave 10 slug reuse and adds 8 unique replacements.

begin;

create temporary table wave10_collision_fix_seed(
  category_slug text not null, slug text primary key, title_ar text not null, title_en text not null,
  description_ar text not null, description_en text not null, expression text not null,
  input_fields jsonb not null, english_fields jsonb not null, sort_order integer not null
) on commit drop;

insert into wave10_collision_fix_seed values
('bakery-tools','bakery-revenue-per-item-calculator','حاسبة الإيراد لكل قطعة مخبوزات','Bakery Revenue per Item Calculator','احسب متوسط الإيراد لكل قطعة مباعة.','Calculate average revenue per sold bakery item.','revenue / items_sold','[{"key":"revenue","label":"الإيراد","type":"number","required":true,"min":0},{"key":"items_sold","label":"القطع المباعة","type":"number","required":true,"min":1}]','[{"key":"revenue","label":"Revenue","type":"number","required":true,"min":0},{"key":"items_sold","label":"Items sold","type":"number","required":true,"min":1}]',11306),
('cybersecurity-tools','security-training-failure-rate-calculator','حاسبة فشل اختبار التوعية الأمنية','Security Training Failure Rate Calculator','احسب نسبة المستخدمين الذين فشلوا اختبار التوعية الأمنية.','Calculate users failing security awareness testing as a percentage of tested users.','failed_users / tested_users * 100','[{"key":"failed_users","label":"المستخدمون الذين فشلوا","type":"number","required":true,"min":0},{"key":"tested_users","label":"المستخدمون المختبرون","type":"number","required":true,"min":1}]','[{"key":"failed_users","label":"Failed users","type":"number","required":true,"min":0},{"key":"tested_users","label":"Tested users","type":"number","required":true,"min":1}]',11708),
('event-tools','event-ticket-revenue-calculator','حاسبة إيراد تذاكر الفعالية','Event Ticket Revenue Calculator','احسب إيراد التذاكر من العدد المباع وسعر التذكرة.','Calculate ticket revenue from tickets sold and ticket price.','tickets_sold * ticket_price','[{"key":"tickets_sold","label":"التذاكر المباعة","type":"number","required":true,"min":0},{"key":"ticket_price","label":"سعر التذكرة","type":"number","required":true,"min":0}]','[{"key":"tickets_sold","label":"Tickets sold","type":"number","required":true,"min":0},{"key":"ticket_price","label":"Ticket price","type":"number","required":true,"min":0}]',12001),
('event-tools','event-revenue-per-attendee-calculator','حاسبة إيراد الفعالية لكل حاضر','Event Revenue per Attendee Calculator','احسب متوسط إيراد الفعالية لكل حاضر.','Calculate average event revenue per attendee.','total_revenue / attendees','[{"key":"total_revenue","label":"إجمالي الإيراد","type":"number","required":true,"min":0},{"key":"attendees","label":"عدد الحضور","type":"number","required":true,"min":1}]','[{"key":"total_revenue","label":"Total revenue","type":"number","required":true,"min":0},{"key":"attendees","label":"Attendees","type":"number","required":true,"min":1}]',12004),
('event-tools','event-marketing-cost-per-registration-calculator','حاسبة تكلفة التسويق لكل تسجيل','Event Marketing Cost per Registration Calculator','احسب متوسط تكلفة التسويق لكل تسجيل في الفعالية.','Calculate average event marketing cost per registration.','marketing_cost / registrations','[{"key":"marketing_cost","label":"تكلفة التسويق","type":"number","required":true,"min":0},{"key":"registrations","label":"التسجيلات","type":"number","required":true,"min":1}]','[{"key":"marketing_cost","label":"Marketing cost","type":"number","required":true,"min":0},{"key":"registrations","label":"Registrations","type":"number","required":true,"min":1}]',12005),
('procurement-tools','procurement-cost-per-order-calculator','حاسبة تكلفة المشتريات لكل أمر','Procurement Cost per Order Calculator','احسب متوسط التكلفة الإدارية لكل أمر شراء.','Calculate average procurement cost per purchase order.','procurement_cost / purchase_orders','[{"key":"procurement_cost","label":"تكلفة إدارة المشتريات","type":"number","required":true,"min":0},{"key":"purchase_orders","label":"أوامر الشراء","type":"number","required":true,"min":1}]','[{"key":"procurement_cost","label":"Procurement cost","type":"number","required":true,"min":0},{"key":"purchase_orders","label":"Purchase orders","type":"number","required":true,"min":1}]',12303),
('procurement-tools','supplier-fill-rate-calculator','حاسبة معدل تلبية المورد','Supplier Fill Rate Calculator','احسب نسبة الكمية المسلمة من الكمية المطلوبة.','Calculate delivered quantity as a percentage of ordered quantity.','delivered_quantity / ordered_quantity * 100','[{"key":"delivered_quantity","label":"الكمية المسلمة","type":"number","required":true,"min":0},{"key":"ordered_quantity","label":"الكمية المطلوبة","type":"number","required":true,"min":0.000001}]','[{"key":"delivered_quantity","label":"Delivered quantity","type":"number","required":true,"min":0},{"key":"ordered_quantity","label":"Ordered quantity","type":"number","required":true,"min":0.000001}]',12301),
('quality-tools','inspection-cost-per-unit-calculator','حاسبة تكلفة الفحص لكل وحدة','Inspection Cost per Unit Calculator','احسب متوسط تكلفة الفحص لكل وحدة.','Calculate average inspection cost per unit.','inspection_cost / inspected_units','[{"key":"inspection_cost","label":"تكلفة الفحص","type":"number","required":true,"min":0},{"key":"inspected_units","label":"الوحدات المفحوصة","type":"number","required":true,"min":1}]','[{"key":"inspection_cost","label":"Inspection cost","type":"number","required":true,"min":0},{"key":"inspected_units","label":"Inspected units","type":"number","required":true,"min":1}]',12403),

('bakery-tools','bakery-average-basket-value-calculator','حاسبة متوسط سلة مشتريات المخبز','Bakery Average Basket Value Calculator','احسب متوسط قيمة كل عملية شراء في المخبز.','Calculate average bakery revenue per transaction.','revenue / transactions','[{"key":"revenue","label":"الإيراد","type":"number","required":true,"min":0},{"key":"transactions","label":"عدد المعاملات","type":"number","required":true,"min":1}]','[{"key":"revenue","label":"Revenue","type":"number","required":true,"min":0},{"key":"transactions","label":"Transactions","type":"number","required":true,"min":1}]',31001),
('cybersecurity-tools','phishing-reporting-rate-calculator','حاسبة معدل الإبلاغ عن التصيد','Phishing Reporting Rate Calculator','احسب نسبة محاولات التصيد الاختبارية التي أبلغ عنها المستخدمون.','Calculate reported phishing simulations as a percentage of phishing tests.','reported_phishing / phishing_tests * 100','[{"key":"reported_phishing","label":"محاولات التصيد المبلغ عنها","type":"number","required":true,"min":0},{"key":"phishing_tests","label":"اختبارات التصيد","type":"number","required":true,"min":1}]','[{"key":"reported_phishing","label":"Reported phishing tests","type":"number","required":true,"min":0},{"key":"phishing_tests","label":"Phishing tests","type":"number","required":true,"min":1}]',31002),
('event-tools','event-merchandise-revenue-share-calculator','حاسبة حصة مبيعات المنتجات من إيراد الفعالية','Event Merchandise Revenue Share Calculator','احسب نسبة إيراد منتجات الفعالية من إجمالي الإيراد.','Calculate merchandise revenue as a percentage of total event revenue.','merchandise_revenue / total_revenue * 100','[{"key":"merchandise_revenue","label":"إيراد المنتجات","type":"number","required":true,"min":0},{"key":"total_revenue","label":"إجمالي الإيراد","type":"number","required":true,"min":0.000001}]','[{"key":"merchandise_revenue","label":"Merchandise revenue","type":"number","required":true,"min":0},{"key":"total_revenue","label":"Total revenue","type":"number","required":true,"min":0.000001}]',31003),
('event-tools','event-sponsor-revenue-per-attendee-calculator','حاسبة إيراد الرعايات لكل حاضر','Sponsor Revenue per Attendee Calculator','احسب متوسط إيراد الرعايات لكل حاضر.','Calculate average sponsorship revenue per attendee.','sponsorship_revenue / attendees','[{"key":"sponsorship_revenue","label":"إيراد الرعايات","type":"number","required":true,"min":0},{"key":"attendees","label":"عدد الحضور","type":"number","required":true,"min":1}]','[{"key":"sponsorship_revenue","label":"Sponsorship revenue","type":"number","required":true,"min":0},{"key":"attendees","label":"Attendees","type":"number","required":true,"min":1}]',31004),
('event-tools','event-paid-upgrade-rate-calculator','حاسبة معدل الترقيات المدفوعة في الفعالية','Event Paid Upgrade Rate Calculator','احسب نسبة الحضور الذين اشتروا ترقية مدفوعة.','Calculate attendees purchasing a paid upgrade as a percentage of attendees.','paid_upgrades / attendees * 100','[{"key":"paid_upgrades","label":"الترقيات المدفوعة","type":"number","required":true,"min":0},{"key":"attendees","label":"عدد الحضور","type":"number","required":true,"min":1}]','[{"key":"paid_upgrades","label":"Paid upgrades","type":"number","required":true,"min":0},{"key":"attendees","label":"Attendees","type":"number","required":true,"min":1}]',31005),
('procurement-tools','procurement-cost-per-supplier-calculator','حاسبة تكلفة إدارة المشتريات لكل مورد','Procurement Cost per Supplier Calculator','احسب متوسط تكلفة إدارة المشتريات لكل مورد نشط.','Calculate average procurement administration cost per active supplier.','procurement_cost / suppliers','[{"key":"procurement_cost","label":"تكلفة إدارة المشتريات","type":"number","required":true,"min":0},{"key":"suppliers","label":"الموردون النشطون","type":"number","required":true,"min":1}]','[{"key":"procurement_cost","label":"Procurement cost","type":"number","required":true,"min":0},{"key":"suppliers","label":"Active suppliers","type":"number","required":true,"min":1}]',31006),
('procurement-tools','supplier-shortfall-rate-calculator','حاسبة معدل عجز توريد المورد','Supplier Shortfall Rate Calculator','احسب نسبة الكمية غير المسلمة من إجمالي الكمية المطلوبة.','Calculate undelivered quantity as a percentage of ordered quantity.','(ordered_quantity - delivered_quantity) / ordered_quantity * 100','[{"key":"ordered_quantity","label":"الكمية المطلوبة","type":"number","required":true,"min":0.000001},{"key":"delivered_quantity","label":"الكمية المسلمة","type":"number","required":true,"min":0}]','[{"key":"ordered_quantity","label":"Ordered quantity","type":"number","required":true,"min":0.000001},{"key":"delivered_quantity","label":"Delivered quantity","type":"number","required":true,"min":0}]',31007),
('quality-tools','quality-rework-cost-per-defect-calculator','حاسبة تكلفة إعادة العمل لكل عيب','Rework Cost per Defect Calculator','احسب متوسط تكلفة إعادة العمل لكل عيب مكتشف.','Calculate average rework cost per detected defect.','rework_cost / defects','[{"key":"rework_cost","label":"تكلفة إعادة العمل","type":"number","required":true,"min":0},{"key":"defects","label":"عدد العيوب","type":"number","required":true,"min":1}]','[{"key":"rework_cost","label":"Rework cost","type":"number","required":true,"min":0},{"key":"defects","label":"Defects","type":"number","required":true,"min":1}]',31008);

insert into public.tools(slug,title_ar,title_en,short_description,category_id,engine_type,input_schema,output_schema,runtime_config,pricing_mode,fixed_points,minimum_points,requires_auth,is_featured,is_active,sort_order,seo_title,seo_description)
select s.slug,s.title_ar,s.title_en,s.description_ar,c.id,'formula',jsonb_build_object('submitLabel','احسب','fields',s.input_fields),jsonb_build_object('type','number','format','auto'),jsonb_build_object('expression',s.expression),'free',0,0,false,false,true,s.sort_order,s.title_ar,s.description_ar
from wave10_collision_fix_seed s join public.categories c on c.slug=s.category_slug
on conflict(slug) do update set title_ar=excluded.title_ar,title_en=excluded.title_en,short_description=excluded.short_description,category_id=excluded.category_id,engine_type=excluded.engine_type,input_schema=excluded.input_schema,output_schema=excluded.output_schema,runtime_config=excluded.runtime_config,pricing_mode='free',fixed_points=0,minimum_points=0,requires_auth=false,is_featured=false,is_active=true,sort_order=excluded.sort_order,seo_title=excluded.seo_title,seo_description=excluded.seo_description,updated_at=now();

insert into public.tool_translations(tool_id,locale_id,title,short_description,seo_title,seo_description,prompt_template_override)
select t.id,l.id,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,case when l.code='ar' then s.title_ar else s.title_en end,case when l.code='ar' then s.description_ar else s.description_en end,null
from wave10_collision_fix_seed s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id) do update set title=excluded.title,short_description=excluded.short_description,seo_title=excluded.seo_title,seo_description=excluded.seo_description,prompt_template_override=null,updated_at=now();

insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,f.value->>'key',f.value->>'label',null,null,f.value->'options'
from wave10_collision_fix_seed s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
cross join lateral jsonb_array_elements(case when l.code='ar' then s.input_fields else s.english_fields end) f(value)
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,placeholder=null,help_text=null,options=excluded.options,updated_at=now();

insert into public.tool_field_translations(tool_id,locale_id,field_key,label,placeholder,help_text,options)
select t.id,l.id,'__submit__',case when l.code='ar' then 'احسب' else 'Calculate' end,null,null,null
from wave10_collision_fix_seed s join public.tools t on t.slug=s.slug join public.locales l on l.code in('ar','en')
on conflict(tool_id,locale_id,field_key) do update set label=excluded.label,placeholder=null,help_text=null,options=null,updated_at=now();

commit;
